\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring
\import Algebra.Ring.Localization.Properties
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Algebra.Ring.Ideal
\import Algebra.Ring.Localization
\import Algebra.Semiring
\import Arith.Nat
\import Category
\import Category.Functor
\import Category.Limit
\import Category.Slice
\import Category.Topos.Sheaf
\import Category.Topos.Sheaf.Site
\import Data.Array
\import Data.Bool
\import Data.Maybe
\import Equiv
\import Equiv.Fiber
\import Equiv.Path
\import Equiv.Sigma
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.SetCategory
\import Topology.Locale
\open Monoid
\open CompleteLattice(SJoin)
\open Ideal

\func SpecPres (R : CRing) : FramePres R \cowith
  | conj => *
  | BasicCover => FramePres.Indexing {Maybe (\Sigma R R)} {R} (\case __ \with {  | just (a, b) => (Bool, a + b, if __ a b)  | nothing => (Empty, 0, absurd)})
  \where {
    \lemma cover_ideal {R : CRing} {x : R} {J : \Set} {g : J -> R} (c : Cover {SpecPres R} x g) : radical {closure g} x => {?hidden_proof}

    \lemma ideal_cover {R : CRing} {x : R} {J : \Set} {g : J -> R} (p : radical {closure g} x) : Cover {SpecPres R} x g => {?hidden_proof}

    \lemma cover_ide {R : CRing} {x : R} : Cover1 {SpecPres R} x 1 => {?hidden_proof}

    \lemma cover_pow {R : CRing} {x : R} (n : Nat) : Cover1 {SpecPres R} x (pow x n) => {?hidden_proof}

    \lemma cover_bigSum {R : CRing} {l : Array R} : Cover {SpecPres R} (AddMonoid.BigSum l) l => {?hidden_proof}
  }


\func Spec (R : CRing) : Locale => PresentedFrame (SpecPres R)

\class RingedLocale {
  | L : Locale
  | R : VSheaf CRingCat L
}
  \where {
    \use \coerce fromSheaf {L : Locale} (S : VSheaf CRingCat L) => \new (RingedLocale L S)

    \func equality1 (L L' : RingedLocale) : Equiv {L = L'} {\Sigma (p : L.L = L'.L) (transport (VSheaf CRingCat) p L.R = L'.R)} => pathEquiv _ $ later
      (\lam {L : RingedLocale} {L' : RingedLocale} => \new Retraction {  | f => fromPath  | sec => \lam s => toPath s.1 s.2
      | f_sec => \lam s => from-to {L} {L'.L} {L'.R} s.1 s.2})
      \where {
        \func fromPath {L L' : RingedLocale} (p : L = L') : \Sigma (p : L.L = L'.L) (transport (VSheaf CRingCat) p L.R = L'.R) \elim p
          | idp => (idp, idp)

        \func toPath {L L' : RingedLocale} (p : L.L = L'.L) (q : transport (VSheaf CRingCat) p L.R = L'.R) : L = L' => ext (p, q)

        \func from-to {LR : RingedLocale} {L' : Locale} {R' : VSheaf CRingCat L'} (p : LR.L = L') (q : transport (VSheaf CRingCat) p LR.R = R') :
          fromPath (toPath {LR} {\new (RingedLocale L' R')} p q) = (p, q) \elim p, q
          | idp, idp => idp
      }


    \func equality2 (L L' : RingedLocale) : Equiv {L = L'} {\Sigma (p : L.L = L'.L) (VSheaf.direct_image_locale (Iso.f {Precat.idtoiso p}) L.R = L'.R)} 
      => transEquiv (equality1 L L') $ sigma-right (\lam p => pathConcatEquiv (VSheaf.transport_direct_image p L.R))

    \func equality3 (L L' : RingedLocale) : Equiv {L = L'} {\Sigma (e : Iso {LocaleCat} {L.L} {L'.L}) (Iso {_} {VSheaf.direct_image_locale e.f L.R} {L'.R})} 
      => equality2 L L' `transEquiv` sigma-left univalence `transEquiv` sigma-right (later (\lam e => univalence))
  }


\class RingedLocaleHom {
  | Dom : RingedLocale
  | Cod : RingedLocale
  | f : FrameHom Cod Dom
  | f# : NatTrans \levels (\suc \lp) _ Cod.R (VSheaf.direct_image_locale f Dom.R)
}
  \where {
    \func fromHomEq {L M : Locale} {f g : FrameHom M L} (p : f = g) (a : M) : f a <= g a => transport (\lam (h : FrameHom M L) => f a <= h a) p <=-refl

    \lemma ext {L M : RingedLocale} (f g : RingedLocaleHom L M) (p : f.f = g.f) (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g.f# a x) = f.f# a x) : f = g 
      => {?hidden_proof}
      \where {
        \lemma aux {L M : RingedLocale} {f g : FrameHom M L} (f# : NatTrans \levels (\suc \lp) _ M.R (VSheaf.direct_image_locale f L.R)) 
        (g# : NatTrans \levels (\suc \lp) _ M.R (VSheaf.direct_image_locale g L.R)) (p : f = g) 
        (q : \Pi (a : M) (x : M.R a) -> L.R.F.Func (fromHomEq p a) (g# a x) = f# a x) : \new (RingedLocaleHom L M f f#) = (\new (RingedLocaleHom L M g g#)) => {?hidden_proof}
      }

  }


\func RingedLocalePrecat : Precat RingedLocale \cowith
  | Hom => RingedLocaleHom
  | id => id
  | o => o
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  \where {
    \func forget : Functor RingedLocalePrecat LocaleCat \cowith
      | F => \lam L => L
      | Func => \lam f => f
      | Func-id => idp
      | Func-o => idp

    \func homMap {L M : RingedLocale} {f g : RingedLocaleHom M L} (p : f = g) (a : L) : RingHom (M.R (f a)) (M.R (g a)) 
      => M.R.F.Func (=_<= (inv (path (\lam i => p i a))))

    \lemma homMap-lem {L M : RingedLocale} {f g : RingedLocaleHom M L} (p : f = g) (a : L) :
      transport (\lam (h : RingedLocaleHom M L) => RingHom (M.R (f a)) (M.R (h a))) p RingHom.id = homMap p a => {?hidden_proof}

    \lemma homMap-lem2 {L M : RingedLocale} {f g : RingedLocaleHom M L} (p : f = g) (a : L) : homMap p a Cat.∘ homMap (inv p) a = RingHom.id {M.R (g a)} => {?hidden_proof}

    \func homMap-natural {L M : RingedLocale} {f g : RingedLocaleHom M L} (p : f = g) : NatTrans (Comp M.R f.f.functor.op) (Comp M.R g.f.functor.op) \cowith
      | trans => homMap p
      | natural => \lam h => inv M.R.F.Func-o *> pmap M.R.F.Func prop-pi *> M.R.F.Func-o

    \func natTrans-inv {L M : RingedLocale} {e : Iso {RingedLocalePrecat} {L} {M}} 
    (f : NatTrans \levels (\suc \lp) _ L.R (Comp M.R (Functor.op {FrameHom.functor {e.hinv}}))) :
      NatTrans (Comp L.R (Functor.op {FrameHom.functor {e.f}})) M.R \cowith
      | trans => \lam x => homMap e.f_hinv x Cat.∘ f (e.f x)
      | natural => \lam {a} {b} h => (
        \let t : homMap e.f_hinv b Cat.∘ M.R.F.Func (Func {Functor.op {FrameHom.functor {e.hinv}}} (e.f.func-<= h)) = M.R.F.Func h Cat.∘ homMap e.f_hinv a =>
               pmap (_ Cat.∘ M.R.F.Func __) prop-pi *> natural {homMap-natural e.f_hinv} h *> pmap (Cat.∘ _) (pmap M.R.F.Func prop-pi)
        \in unfold Func $ rewrite (prop-isProp (Func {Functor.op {FrameHom.functor {e.f}}} h) (e.f.func-<= h)) $ o-assoc *> rewrite (f.natural (e.f.func-<= h)) 
              (inv o-assoc *> path (\lam i => t i Cat.∘ f (e.f a)) *> o-assoc))

    \lemma homMap_o {L L' : RingedLocale} (f : RingedLocaleHom L L') (g : RingedLocaleHom L' L) (p : f RingedLocalePrecat.∘ g = id L') (a : L') :
      g.f# (f a) Cat.∘ f.f# a = homMap (inv p) a => {?hidden_proof}

    \lemma homMap_o-right {L L' : RingedLocale} (f : RingedLocaleHom L L') (g : RingedLocaleHom L' L) (p : f RingedLocalePrecat.∘ g = id L') 
    (q : g RingedLocalePrecat.∘ f = id L) (a : L') : f.f# a Cat.∘ homMap p a Cat.∘ g.f# (f a) = RingHom.id {L.R (f a)} => {?hidden_proof}

    \lemma homMap_o-left {L L' : RingedLocale} (f : RingedLocaleHom L L') (g : RingedLocaleHom L' L) (p : f RingedLocalePrecat.∘ g = id L') (a : L') :
      homMap p a Cat.∘ g.f# (f a) Cat.∘ f.f# a = RingHom.id {L'.R a} => {?hidden_proof}

    \func fromIso {L L' : RingedLocale} (e : Iso {RingedLocalePrecat} {L} {L'}) : Iso {VSheafCat CRingCat L'.L} {VSheaf.direct_image_locale e.f L.R} {L'.R} \cowith
      | f => natTrans-inv (RingedLocaleHom.f# {e.hinv})
      | hinv => RingedLocaleHom.f# {e.f}
      | hinv_f => exts (homMap_o-right e.f e.hinv e.f_hinv e.hinv_f)
      | f_hinv => exts (homMap_o-left e.f e.hinv e.f_hinv)

    \func isotoid (e : Iso {RingedLocalePrecat}) : e.dom = e.cod => ext (Cat.isotoid (RingedLocalePrecat.forget.Func-iso e), 
      VSheaf.transport_direct_image-iso _ (RingedLocale.R {e.dom}) *> Cat.isotoid (RingedLocalePrecat.fromIso e))
  }


\class LocallyRingedLocale \extends RingedLocale {
  | isNonTrivial (a : L) : 0 = {R.F a} 1 -> a <= bottom
  | isLocallyRinged (a : L) (x : R.F a) : a <= SJoin (\lam b => \Sigma (p : b <= a) (EitherInv \this p x))
}
  \where {
    \func EitherInv (L : RingedLocale) {a b : L} (p : b <= a) (x : L.R.F a) => Inv (L.R.F.Func p x) || Inv (L.R.F.Func p x + 1)
  }


\class RingedFramePres {
  | P : FramePres
  | R : VSheaf CRingCat (framePresSite P)
}

\class LocallyRingedFramePres \extends RingedFramePres {
  | isNonTrivialPres (a : P) : 0 = {R.F a} 1 -> Cover a absurd
  | isLocallyRingedPres (a : P) (x : R.F a) : FramePres.SCover a (\lam b => \Sigma (p : Cover1 b a) (Inv (R.F.Func p x) || Inv (R.F.Func p x + 1)))
}
  \where {
    \func EitherInv (P : RingedFramePres) {a b : P} (p : Cover1 b a) (x : P.R.F a) => Inv (P.R.F.Func p x) || Inv (P.R.F.Func p x + 1)

    \open sheafOnPresentedFrame
    \open PresentedFrame

    \lemma limInv {P : FramePres} (F : VSheaf CRingBicat (framePresSite P)) (b : P) {y : extend.lim (embed b)} (yi : Inv (y.1 (b, <=-refl))) : Inv y => {?hidden_proof}
      \where {
        \lemma element-lem (j : \Sigma (x : P) (embed x <= embed b)) : y.1 j = F.F.Func (embed_Cover j.2) (y.1 (b, <=-refl)) => {?hidden_proof}
      }


    \func toPresented {P : RingedFramePres} {a b : P} (p : Cover1 b a) (U : PresentedFrame P) (Ua : U.1 a) (x : extend.lim {P} {CRingBicat} {P.R} U) 
    (e : EitherInv P p (x.1 (a, \lam {z} c => U.2 z $ Cover.cover-trans1 c $ cover-inj (a, Ua) idp))) :
      LocallyRingedLocale.EitherInv (ringedLocaleFromPres P) {U} {embed b} (\lam {z} c => U.2 z $ Cover.cover-trans1 c $ Cover.cover-trans1 p $ cover-inj (a, Ua) idp) x 
    \elim e
      | byLeft i => byLeft $ limInv P.R b $ transport Inv (x.2 p) i
      | byRight i => byRight $ limInv P.R b $ transport Inv (pmap (+ 1) (x.2 p)) i
  }


\func ringedLocaleFromPres (P : RingedFramePres) : RingedLocale \cowith
  | L => PresentedFrame P
  | R => sheafOnPresentedFrame {P} {CRingBicat} P.R

\func locallyRingedLocaleFromPres (P : LocallyRingedFramePres) : LocallyRingedLocale \cowith
  | RingedLocale => ringedLocaleFromPres P
  | isNonTrivial => \lam U t {x} Ux => cover-trans (isNonTrivialPres x $ pmap (__.1 (x, \lam {y} c => U.2 y $ Cover.cover-trans1 c $ cover-inj (x, Ux) idp)) t) (\case __ \with {})
  | isLocallyRinged => \lam U x {a} Ua => cover-trans (isLocallyRingedPres a (x.1 (a, \lam {z} c => U.2 z $ Cover.cover-trans1 c $ cover-inj (a, Ua) idp)))
    (\lam t => cover-inj ((PresentedFrame.embed t.1, 
    (\lam {z} c => U.2 z $ Cover.cover-trans1 c $ Cover.cover-trans1 t.2.1 $ cover-inj (a, Ua) idp, LocallyRingedFramePres.toPresented t.2.1 U Ua x t.2.2)
    ), t.1, cover-inj () idp) idp)

\func affineRingedPres (R : CRing) : LocallyRingedFramePres (SpecPres R) \cowith
  | R => R
  | isNonTrivialPres => \lam a => \lam p => SpecPres.ideal_cover (\case LocRing.unequals p \with {  | inP (c, inP (n, a^n=c), zro=c) => inP (n, inP (nil, equation))})
  | isLocallyRingedPres => \lam a in~ (y, c, inP (n, a^n=c)) => cover-trans1 (SpecPres.cover_pow (suc n)) $ transport (Cover __ _) (equation : a * negative y + a * (y + pow a n) = pow a (suc n)) $ cover-trans 
    (cover-basic $ FramePres.indexing-make $ just (a * negative y, a * (y + pow a n))) $ later
      (\case \elim __ \with {  | true => cover-inj (_,  (cover-proj1 idp () idp,
        byLeft $ transportInv Inv (functorial-lem-div (\new LDiv {  | inv => negative y  | inv-right => idp}) n a^n=c) $ Inv.lmake 
        (inl~ (negative $ pow a (suc n), a * negative y, later $ inP (1, ide-left))) $ LocRing.equals1 $ later $ rewrite CMonoid.pow_*-comm equation)) idp
      | false => cover-inj (_,  (cover-proj1 idp () idp,
        byRight $ transportInv (\lam x => Inv (x + 1)) (functorial-lem-div (\new LDiv {  | inv => y + pow a n  | inv-right => idp}) n a^n=c) $ Inv.lmake 
        (inl~ (pow a (suc n), a * (y + pow a n), later $ inP (1, ide-left))) $ LocRing.equals1 $ later $ rewrite CMonoid.pow_*-comm equation)) idp})
  \where {
    \open localization
    \open SubMonoid(powers)
    \open sheafOnSiteWithBasis
    \open Cover

    \func functor (R : CRing) => \new (Functor (Precat.op {framePresSite (SpecPres R)}) CRingBicat) {
      | F => \lam a => LocRing (powers a)
      | Func => \lam c => (functorial (SpecPres.cover_ideal c)).1
      | Func-id => \lam {a} => locMap-epi {_} {_} {LocRing (powers a)} $ (functorial (SpecPres.cover_ideal (id {framePresSite $ SpecPres R} a))).2 *> inv id-left
      | Func-o => \lam {a} {b} {c} {g} {f} => locMap-epi {_} {_} {LocRing (powers c)} $ (functorial (SpecPres.cover_ideal (f ∘ {framePresSite $ SpecPres R} g))).2 *> inv 
        (o-assoc *> pmap (_ RingHom.∘) (functorial (SpecPres.cover_ideal f)).2 *> (functorial (SpecPres.cover_ideal g)).2)
    }

    \lemma functorial {R : CRing} {a b : R} (r : radical {closure1 a} b) :
      \level (\Sigma (f : RingHom (LocRing (powers a)) (LocRing (powers b))) (f ∘ locMap = locMap)) (\lam p q => ext (locMap-epi {_} {_} {LocRing (powers b)} (p.2 *> inv q.2))) 
      => {?hidden_proof}

    \lemma functorial-lem {R : CRing} {a b : R} {r : radical {closure1 a} b} {x : LocRing.SType (powers a)} (m : Nat) (p : pow a m = x.2) {n : Nat} {c : R} 
    (q : pow b n = a * c) : (functorial r).1 (in~ x) = in~ (x.1 * pow c m, pow b (n * m), inP (n * m, idp)) => {?hidden_proof}

    \lemma functorial-lem-div {R : CRing} {a b : R} (d : LDiv a b) {r : radical {closure1 a} b} {x : LocRing.SType (powers a)} (m : Nat) (p : pow a m = x.2) :
      (functorial r).1 (in~ x) = in~ (x.1 * pow d.inv m, pow b m, inP (m, idp)) => {?hidden_proof}

    \lemma emptyMatchingFamily {C : SiteWithBasis} {F : Functor C.op SetCat} {x : C} {g : Empty -> SlicePrecat x} : Contr (MatchingFamily {C} {F} x g) => {?hidden_proof}

    \lemma common-denom {R : CRing} {a b : R} (e1 : LocRing (powers a)) (e2 : LocRing (powers b)) :
      ∃ (x y : R) (m : Nat) (e1 = in~ (x, pow a m, inP (m, idp))) (e2 = in~ (y, pow b m, inP (m, idp))) => {?hidden_proof}

    \lemma pow-lin-comb {R : CRing} {a b c d e : R} {k : Nat} (p : pow e k = a * c + b * d) (n m : Nat) : ∃ (t s : R) (l : Nat) (pow e l = t * pow a n + s * pow b m) => {?hidden_proof}

    \lemma localization-lem {R : CRing} {e : R} {c d : R} (g : Bool -> SlicePrecat {framePresSite (SpecPres R)} e) {n : Nat} (p : pow e n = (g true).1 * c + (g false).1 * d) :
      Equiv {_} {MatchingFamily _ _} (matchingFamily {_} {Comp CRingCat.forget (functor R)} e g) => {?hidden_proof}
  }


\func affineRingedLocale (R : CRing) => locallyRingedLocaleFromPres (affineRingedPres R)

\class Scheme \extends LocallyRingedLocale {
  | isScheme : L.top <= SJoin (\lam U => ∃ (R' : CRing) (VSheaf.restrict U R = {RingedLocale} affineRingedLocale R'))
  | isNonTrivial => \lam a p => meet-univ L.top-univ <=-refl <=∘ L.meet-monotone isScheme <=-refl <=∘ L.Join-rdistr>= <=∘ Join-univ
    (\lam (b, inP (R', q)) => (
    \let t => transportInv (\lam (x : RingedLocale) => \Pi (a : x.L) -> 0 = {x.R.F a} 1 -> a <= bottom) q (isNonTrivial {affineRingedLocale R'})
    \in t (b ∧ a, meet-left) (inv func-zro *> pmap (R.F.Func (meet-right {_} {b})) p *> func-ide) <=∘ Join-univ (\case __ \with {})))
  | isLocallyRinged => \lam a x => meet-univ L.top-univ <=-refl <=∘ L.meet-monotone isScheme <=-refl <=∘ L.Join-rdistr>= <=∘ Join-univ
    (\lam (b, inP (R', q)) => (
    \let t => transportInv (\lam (x : RingedLocale) => \Pi (a : x.L) (y : x.R.F a) -> a <= SJoin (\lam b => \Sigma (p : b <= a) (LocallyRingedLocale.EitherInv _ p y))) q 
             (isLocallyRinged {affineRingedLocale R'})  \in t (b ∧ a, meet-left) (R.F.Func meet-right x) <=∘ Join-univ
          (\lam ((c, c<=b), (c<=ba, e)) => Join-cond $ later  (c,  (c<=ba <=∘ meet-right,
          ||.map (transportInv (\lam (f : RingHom (R a) (R c)) => Inv (f x)) R.F.Func-o) (transportInv (\lam (f : RingHom (R a) (R c)) => Inv (f x + 1)) R.F.Func-o) e
                )))))
}

\func affineScheme (R : CRing) : Scheme \cowith
  | RingedLocale => affineRingedLocale R
  | isScheme => \lam {x} _ =>
    cover-inj (((\lam _ => \Sigma, \lam _ _ => ()), inP (R, RingedLocalePrecat.isotoid $ restrict_iso (RingedLocale.R {affineRingedLocale R}))), x, ()) idp
  \where {
    \func locale_iso {L : Locale} : Iso {LocaleCat} {L.restrict L.top} {L} \cowith
      | f => Locale.restrict.map
      | hinv => \new FrameHom {
        | func => \lam x => x.1
        | func-top => idp
        | func-meet => idp
        | func-Join => idp
      }
      | hinv_f => exts (\lam p => ext L.top-right)
      | f_hinv => exts (\lam x => L.top-right)

    \func restrict_map {L : Locale} (a : L) (S : VSheaf CRingCat L) : RingedLocaleHom (\new (RingedLocale (L.restrict a) (VSheaf.restrict a S))) (\new (RingedLocale L S)) \cowith
      | f => Locale.restrict.map
      | f# => \new NatTrans {
        | trans => \lam b => S.F.Func meet-left
        | natural => \lam h => inv S.F.Func-o *> pmap S.F.Func prop-pi *> S.F.Func-o
      }

    \func restrict_iso {L : Locale} (S : VSheaf CRingCat L) : Iso {RingedLocalePrecat} {VSheaf.restrict L.top S} {S} \cowith
      | f => restrict_map L.top S
      | hinv => hinv
      | hinv_f => RingedLocaleHom.ext (hinv RingedLocalePrecat.∘ restrict_map L.top S) _ locale_iso.hinv_f (\lam p x => pmap (S.F.Func __ x) prop-pi)
      | f_hinv => RingedLocaleHom.ext (restrict_map L.top S RingedLocalePrecat.∘ hinv) _ locale_iso.f_hinv (\lam a x => pmap (S.F.Func __ x) prop-pi)
  }
