\import Algebra.Domain.GCD(GCDDomain)
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Ideal
\import Algebra.Ring.Reduced
\import Algebra.Semiring
\import Data.Array
\import Data.Fin(fsuc/=)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set
\import Set.Countable
\open Monoid(LDiv)

\class BezoutRing \extends CRing, GCDMonoid {
  | isBezout : IsBezout
  | isGCD => \lam a b => TruncP.map (isBezout a b)
    (\lam (s, t, d1, d2) => \new (GCD a b (s * a + t * b)) {  | res|val1 => d1  | res|val2 => d2
    | res-univ => \lam g (x, p) (y, q) => LDiv.make (s * x + t * y) (equation.cRing {(p, q)})})
  | gcd-ldistr => \lam c {a} {b} {z} (g : GCD a b z) => TruncP.map (isBezout a b)
    (\lam (s, t, d1, d2) => \new (GCD (c * a) (c * b) (c * z)) {  | res|val1 => LDiv.product-left c g.res|val1
    | res|val2 => LDiv.product-left c g.res|val2  | res-univ => \lam d (x, p) (y, q) =>
    LDiv.trans (later $ rewrite ldistr $ LDiv_+ (LDiv.make (s * x) (equation.cMonoid {p})) (LDiv.make (t * y) (equation.cMonoid {q}))) $ LDiv.product-left c 
        (g.res-univ _ d1 d2)})
}
  \where {
    \lemma bezoutArray_coprime {R : CRing} {n : Nat} (s : Array R n) {u : Array R n} (p : R.BigSum (\lam j => s j * u j) = 1) : IsCoprimeArray u => {?hidden_proof}

    \lemma bezoutArrayInv_coprime {R : CRing} {n : Nat} (s : Array R n) {u : Array R n} (p : Monoid.Inv (R.BigSum (\lam j => s j * u j))) : IsCoprimeArray u => {?hidden_proof}

    \lemma bezout_coprime {R : CRing} {s t a b : R} (p : s * a + t * b = 1) : IsCoprime a b => {?hidden_proof}

    \lemma bezoutInv_coprime {R : CRing} {s t a b : R} (p : Monoid.Inv (s * a + t * b)) : IsCoprime a b => {?hidden_proof}
  }


\class StrictBezoutRing \extends BezoutRing {
  | isStrictBezout : IsStrictBezout
  | isBezout => \lam a b => TruncP.map (isStrictBezout a b)
    (\lam (s, t, u, v, p, q) => (t, s, \new LDiv {  | inv => v  | inv-right => equation.cRing {(inv p, q)}},
    \new LDiv {  | inv => u  | inv-right => equation.cRing {(p, q)}}))
}

\class BezoutDomain \extends GCDDomain, BezoutRing {
  | isGCDDomain => \lam x y _ _ => TruncP.map (isBezout x y) (\lam p => bezoutGCD p.3 p.4)
}
  \where {
\class Dec \extends StrictBezoutDomain, GCDDomain.Dec {
      | isStrictBezout => PPRing.bezout->strictBezout isBezout
    }
  }


\class StrictBezoutDomain \extends BezoutDomain, StrictBezoutRing