\import Algebra.Domain
\import Algebra.Domain.Bezout
\import Algebra.Domain.GCD
\import Algebra.Domain.PID
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Semiring
\import Arith.Int
\import Arith.Nat
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set \hiding (#)
\import Set.Fin
\open Monoid (LDiv, Inv)

\class EuclideanSemiringData \extends CSemiring, DecSet {
  | euclideanMap : E -> Nat
  | divMod : E -> E -> \Sigma E E
  | isDivMod (x y : E) : y * (divMod x y).1 + (divMod x y).2 = x
  | isEuclideanMap (x y : E) : y /= 0 -> (divMod x y).2 /= 0 -> euclideanMap (divMod x y).2 < euclideanMap y
  | summandDiv {x y z d : E} (d/=0 : d /= 0) (p : d * x + y = d * z) : LDiv d y

  \func gcd (a b : E) => gcd-fueled (suc' (euclideanMap b)) a b

  \func gcd-fueled (s : Nat) (a b : E) : E \elim s
    | 0 => a
    | suc s => \case decideEq b 0 \with {
      | yes _ => a
      | no _ => gcd-fueled s b (divMod a b).2
    }

  \lemma fueled_zro (s : Nat) (a : E) : gcd-fueled s a 0 = a => {?hidden_proof}

  \func reduce-fueled (s : Nat) (a b : E) : \Sigma E E \elim s
    | 0 => (1, 0)
    | suc s => \case decideEq b 0 \with {
      | yes _ => (1, 0)
      | no _ => 
        \let! | (d, m) => divMod a b
              | (a', b') => reduce-fueled s b m
        \in (a' * d + b', a')
    }

  \func reduce (a b : E) => reduce-fueled (suc' (euclideanMap b)) a b

  \lemma reduce_zro (s : Nat) (a : E) : reduce-fueled s a 0 = (1, 0) => {?hidden_proof}

  \lemma reduce*fueled-left (s : Nat) (a b : E) (b<=s : euclideanMap b < s) : (reduce-fueled s a b).1 * gcd-fueled s a b = a => {?hidden_proof}

  \lemma reduce*fueled-right (s : Nat) (a b : E) (b<=s : euclideanMap b < s) : (reduce-fueled s a b).2 * gcd-fueled s a b = b => {?hidden_proof}

  \lemma reduce*gcd-right (a b : E) : (reduce a b).2 * gcd a b = b => {?hidden_proof}

  \func gcd-isGCD-fueled (s : Nat) {a b g : E} (g|a : LDiv g a) (g|b : LDiv g b) : LDiv g (gcd-fueled s a b) \elim s
    | 0 => g|a
    | suc s => mcases

  \func gcd-isGCD (a b : E) : GCD a b \cowith
    | res => gcd a b
    | res|val1 => \new LDiv {
      | inv => (reduce a b).1
      | inv-right => *-comm *> reduce*fueled-left (suc' (euclideanMap b)) a b (rewrite suc'=suc id<suc)
    }
    | res|val2 => \new LDiv {
      | inv => (reduce a b).2
      | inv-right => *-comm *> reduce*gcd-right a b
    }
    | res-univ => \lam g g|a g|b => gcd-isGCD-fueled (suc' (euclideanMap b)) g|a g|b

  \lemma gcd_0 {x : E} : gcd x 0 = x => {?hidden_proof}
    \where {
      \lemma aux {s : Nat} {x : E} : gcd-fueled s x 0 = x => {?hidden_proof}
    }


  \func isPseudonorm {a b : E} (a/=0 : a /= 0) (b|a : LDiv b a) => aux b a/=0 b|a id<suc
    \where {
      \func aux {a : E} (b : E) (a/=0 : a /= 0) (b|a : LDiv b a) {n : Nat} (p : euclideanMap a < n) :
        Or (LDiv a b) (\Sigma (b' : E) (LDiv b b') (LDiv b' b) (euclideanMap b' < euclideanMap a)) \elim n
        | 0 => \case p \with {}
        | suc n => \case decideEq (divMod b a).2 0 \with {
          | yes e => inl (\new LDiv {  | inv => (divMod b a).1  | inv-right => later (rewrite e $ inv zro-right) *> isDivMod b a})
          | no q => inr (  \have b|m : LDiv b (divMod b a).2 =>
                    summandDiv {_} {b|a.inv * (divMod b a).1} (ldiv/=0 a/=0 b|a) $ pmap (+ _) (inv *-assoc *> later (rewrite b|a.inv-right idp)) *> isDivMod b a *> inv ide-right
            \in \case aux b q b|m (isEuclideanMap b a a/=0 q <∘l <_suc_<= p) \with {        | inl m|b => ((divMod b a).2, b|m, m|b, isEuclideanMap b a a/=0 q)
                  | inr (b', b'|b, b|b', s) => (b', b'|b, b|b', s <∘ isEuclideanMap b a a/=0 q)      })
        }
    }


  \lemma unit-dec (a : E) (f : \Pi {b : E} -> Inv a -> b /= 0 -> euclideanMap a <= euclideanMap b) : Dec (Inv a) => {?hidden_proof}
}
  \where {
    \func suc' (n : Nat) : Nat 
      | 0 => 1
      | suc n => suc (suc n)

    \lemma suc'=suc (n : Nat) : suc' n = suc n => {?hidden_proof}
  }


\open EuclideanSemiringData

\class EuclideanRingData \extends EuclideanSemiringData, CRing {
  | summandDiv => \lam {x} {y} {z} {d} _ p => \new LDiv {
    | inv => z - x
    | inv-right => ldistr *> +-comm *> pmap (+ _) (inv p) *> simplify
  }

  \func bezout-fueled (s : Nat) (a b : E) : \Sigma E E \elim s
    | 0 => (1, 0)
    | suc s => \case decideEq b 0 \with {
      | yes _ => (1, 0)
      | no _ => 
        \let! | (d, m) => divMod a b
              | (u, v) => bezout-fueled s b m
        \in (v, u - d * v)
    }

  \func bezout (a b : E) => bezout-fueled (suc' (euclideanMap b)) a b

  \lemma bezoutIdentity-fueled (s : Nat) (a b : E) : (bezout-fueled s a b).1 * a + (bezout-fueled s a b).2 * b = gcd-fueled s a b => {?hidden_proof}

  \lemma bezoutIdentity (a b : E) : (bezout a b).1 * a + (bezout a b).2 * b = gcd a b => {?hidden_proof}
}

\class EuclideanDomain \extends PID {
  | isEuclidean : TruncP (EuclideanRingData {  | CRing => \this  | decideEq => decideEq})
  | isBezout => \lam a b => TruncP.map isEuclidean
    (\lam (d : EuclideanRingData {  | CRing => \this}) => ((d.bezout a b).1, (d.bezout a b).2, rewrite d.bezoutIdentity (GCD.res|val1 {d.gcd-isGCD a b}), 
    rewrite d.bezoutIdentity (GCD.res|val2 {d.gcd-isGCD a b})))
  | divChain => \lam a c => (\case isEuclidean \with {
    | inP d => cases (a 0 arg addPath)
  })
}
  \where {
    \open DivQuotient

    \lemma aux {R : EuclideanRingData} (n : Nat) (a : Fin (suc n) -> \Sigma (x : R) (x /= 0)) (c : \Pi (i : Fin n) -> TruncP (LDiv (a (suc i)).1 (a i).1)) (b : R) 
    (a0|b : LDiv (a 0).1 b) (b|a0 : LDiv b (a 0).1) (p : euclideanMap b < n) : ∃ (i : Fin n) (LDiv (a i).1 (a (suc i)).1) => {?hidden_proof}
  }


\instance NatEuclidean : EuclideanSemiringData 
  | CSemiring => NatSemiring
  | euclideanMap => \lam n => n
  | divMod => divMod
  | isDivMod => {?hidden_proof}
  | isEuclideanMap => {?hidden_proof}
  | decideEq => {?hidden_proof}
  | summandDiv {x y z d : Nat} (d/=0 : d /= 0) (dx+y=dz : d * x + y = d * z) : Monoid.LDiv d y \elim d
    | 0 => absurd (d/=0 idp)
    | suc _ \as d => \new Monoid.LDiv {
      | inv => div y d
      | inv-right => pmap (d * y div d +)
        (mod-unique {d} {z} {0} {x + y div d} {y mod d} NatOrder.zero<suc (fin_< (y mod d)) (inv (pmap (+ _) ldistr *> +-assoc *> pmap (_ +) (divModProp y d) *> dx+y=dz))) 
      *> divModProp y d
    }
  \where {
    \open Nat

    \lemma gcd0_ {x : Nat} : NatEuclidean.gcd 0 x = x => {?hidden_proof}
  }


\instance IntEuclidean : EuclideanRingData 
  | CRing => IntRing
  | decideEq => {?hidden_proof}
  | euclideanMap => iabs
  | divMod => \lam x y => (
    \let! (d, m) => Nat.divMod (iabs x) (iabs y)
    \in (pos d * signum y * signum x, pos m * signum x))
  | isDivMod (x y : Int) : y * (pos (iabs x Nat.div iabs y) * signum y * signum x) + pos (iabs x Nat.mod iabs y) * signum x = x => {?hidden_proof}
  | isEuclideanMap => {?hidden_proof}
  \where {
    \func modToNat (m : Int) (p : \Sigma Int Int) : \Sigma Int Nat \elim p
      | (q, pos n) => (q, n)
      | (q, neg suc n) => (q - signum m, iabs (iabs m Nat.- suc n))

    \func natDivMod (x y : Int) : \Sigma Int Nat => modToNat y (IntEuclidean.divMod x y)

    \func \infixl 8 div (x y : Int) : Int => (natDivMod x y).1

    \func \infixl 8 mod (x y : Int) : Nat => (natDivMod x y).2

    \lemma intMod<right (x : Int) (n : Nat) : iabs (IntEuclidean.divMod x (suc n)).2 < suc n => {?hidden_proof}

    \lemma natMod<right (x : Int) (n : Nat) : x mod suc n < suc n => {?hidden_proof}

    \lemma divModProp (x y : Int) (y/=0 : y /= 0) : y * x div y + x mod y = x => {?hidden_proof}

    \lemma natDivModProp (x : Int) (n : Nat) : pos (suc n) * x div suc n + x mod suc n = x => {?hidden_proof}

    \lemma mod-unique {q q' : Int} {n r r' : Nat} (r<n : r < n) (r'<n : r' < n) (p : pos n * q + r = pos n * q' + r') : r = r' => {?hidden_proof}
      \where {
        \lemma aux (x y x' y' : Int) (p : x + y = negative x' + y') : (x' + x) + y = y' => {?hidden_proof}
      }


    \lemma natMod=mod' (x n : Nat) : (IntEuclidean.divMod x n).2 = x Nat.mod n => {?hidden_proof}

    \lemma natMod=mod (x n : Nat) : x mod n = x Nat.mod n => {?hidden_proof}
  }


\instance IntDomain : EuclideanDomain 
  | CRing => IntRing
  | zro#ide => {?hidden_proof}
  | #0-* {x y : Int} (x/=0 : x /= 0) (y/=0 : y /= 0) : x * y /= 0 => {?hidden_proof}
  | decideEq => {?hidden_proof}
  | isEuclidean => {?hidden_proof}

\lemma ldiv_nat_int (d : LDiv {NatSemiring}) : LDiv (pos d.val) (pos d.elem) (pos d.inv) => {?hidden_proof}

\lemma ldiv_int_nat (d : LDiv {IntRing}) : LDiv (iabs d.val) (iabs d.elem) (iabs d.inv) => {?hidden_proof}

\lemma inv_nat_int (d : Inv {NatSemiring}) : Inv (pos d.val) (pos d.inv) => {?hidden_proof}

\lemma inv_int_nat (d : Inv {IntRing}) : Inv (iabs d.val) (iabs d.inv) => {?hidden_proof}

\lemma inv_abs {x : Int} (d : Inv (iabs x)) : Inv x => {?hidden_proof}

\func gcd_nat_int (g : GCD {NatSemiring}) : GCD (pos g.val1) (pos g.val2) (pos g) \cowith
  | res|val1 => ldiv_nat_int g.res|val1
  | res|val2 => ldiv_nat_int g.res|val2
  | res-univ => \lam g' g'|a g'|b => (
    \have abs_g'|g : LDiv (iabs g') g => g.res-univ (iabs g') (ldiv_int_nat g'|a) (ldiv_int_nat g'|b)
    \in \new LDiv {
          | inv => signum g' * abs_g'|g.inv
          | inv-right => inv *-assoc *> pmap (* _) (inv iabs.signum_*) *> pmap pos abs_g'|g.inv-right
        })

\func gcd_int_nat (g : GCD {IntRing}) : GCD (iabs g.val1) (iabs g.val2) (iabs g) \cowith
  | res|val1 => ldiv_int_nat g.res|val1
  | res|val2 => ldiv_int_nat g.res|val2
  | res-univ => \lam g' (g'|a : LDiv) (g'|b : LDiv) => (
    \have pos_g'|g : LDiv (pos g') g =>
          g.res-univ (pos g') (\new LDiv {  | inv => pos g'|a.inv * signum g.val1  | inv-right => inv *-assoc *> pmap (pos __ * _) g'|a.inv-right *> iabs.*_signum})
            (\new LDiv {  | inv => pos g'|b.inv * signum g.val2  | inv-right => inv *-assoc *> pmap (pos __ * _) g'|b.inv-right *> iabs.*_signum})
    \in \new LDiv {
          | inv => iabs pos_g'|g.inv
          | inv-right => inv iabs_* *> pmap iabs pos_g'|g.inv-right
        })

\lemma nat_gcd-isUnique {n m : Nat} (g g' : GCD n m) : g.res = g'.res => {?hidden_proof}

\lemma int_gcd-isUnique {x y : Int} (g g' : GCD x y) : iabs g = iabs g' => {?hidden_proof}

\lemma int_gcd_pos {n m : Nat} : gcd (pos n) (pos m) = pos (gcd n m) => {?hidden_proof}
  \where {
    \lemma aux (s : Nat) {n m : Nat} : gcd-fueled s (pos n) (pos m) = iabs (gcd-fueled s (pos n) (pos m)) => {?hidden_proof}
  }


\lemma nat_gcd_sum (a b d : Nat) : gcd (a + b * d) b = gcd a b => {?hidden_proof}

\func nat_gcd_*_div {a b c : Nat} (a|bc : LDiv a (b * c)) (a_b : gcd a b = 1) : LDiv a c 
=> ldiv_int_nat $ Domain.Dec.LDiv_TruncP $ IntDomain.coprime_*_div {pos a} {pos b} {pos c} (ldiv_nat_int a|bc) $ IsCoprime.<=gcd $ gcd_nat_int $ transport 
  (GCD a b __) a_b (gcd-isGCD a b)

\lemma nat_gcd-comm {a b : Nat} : gcd a b = gcd b a => {?hidden_proof}