\import Algebra.Monoid
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Ring.RingHom
\import Algebra.Ring.Solver
\import Algebra.Semiring
\import Arith.Nat
\import Arith.Rat
\import Data.Array
\import Data.Bool
\import Function.Meta
\import Logic
\import Logic.Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\open LinearlyOrderedAbMonoid

\data Operation 
  | Less
  | LessOrEquals
  | Equals

\class LinearData \extends AlgData {
  \override R : LinearlyOrderedSemiring

  \func Equation  => \Sigma (RingTerm C V) Operation (RingTerm C V)

  \func interpretEq (e : Equation) : \Prop \elim e
    | (t1, Less, t2) => interpret t1 < interpret t2
    | (t1, LessOrEquals, t2) => interpret t1 <= interpret t2
    | (t1, Equals, t2) => interpret t1 = interpret t2

  \lemma interpretEq_<= (e : Equation) (h : interpretEq e) : interpret e.1 <= interpret e.3 => {?hidden_proof}

  \func Problem  => Array Equation

  \func isConst (t : RingTerm C V) : Bool \elim t
    | coef c => true
    | var v => false
    | :zro => true
    | :ide => true
    | :negative t => isConst t
    | t :+ t1 => isConst t and isConst t1
    | t :* t1 => isConst t and isConst t1

  \func Cert (n : Nat) => Array Nat n

  \func certSum (l : Array (RingTerm C V)) (c : Cert l.len) => R.BigSum (\lam j => R.natCoef (c j) * interpret (l j))

  \func cert-toTerm (l : Array (RingTerm C V)) (c : Cert l.len) : RingTerm C V \elim l, c
    | nil, nil => :zro
    | t :: l, k :: c => coef (natCoef k) :* t :+ cert-toTerm l c

  \func interpretCert (l : Array (RingTerm C V)) (c : Cert l.len) => interpretRingNF (normalize (cert-toTerm l c))

  \lemma cert-toRingTerm-correct (l : Array (RingTerm C V)) (c : Cert l.len) : AlgData.interpret (cert-toTerm l c) = certSum l c => {?hidden_proof}

  \lemma interpretCert_certSum (l : Array (RingTerm C V)) {c : Cert l.len} : interpretCert l c = certSum l c => {?hidden_proof}

  \func isLess (o : Operation) : Bool 
    | Less => true
    | _ => false
    \where {
      \lemma correct {o : Operation} (p : isLess o = true) : o = Less => {?hidden_proof}
    }


  \func isSuc (n : Nat) : Bool 
    | suc _ => true
    | 0 => false
    \where {
      \lemma correct {n : Nat} (p : isSuc n = true) : 0 < n => {?hidden_proof}
    }


  \func hasNegative (p : Problem) (c : Cert p.len) : Bool \elim p, c
    | nil, nil => false
    | e :: p, k :: c => isLess e.2 and isSuc k or hasNegative p c

  \func hasNegative-correct (p : Problem) (c : Cert p.len) (q : hasNegative p c = true) : ∃ (j : Fin p.len) (0 < c j) ((p j).2 = Less) \elim p, c
    | nil, nil => \case q \with {}
    | e :: p, k :: c => \case or.toOr q \with {
      | byLeft s => inP (0, isSuc.correct (and.toSigma s).2, isLess.correct (and.toSigma s).1)
      | byRight q' => 
        \have inP t => hasNegative-correct p c q'
        \in inP (suc t.1, t.2, t.3)
    }

  \func CorrectCert (p : Problem) => \Sigma (c : Cert p.len) (f : Nat) (interpretCert (map __.1 p) c = interpretCert (:ide :: map __.3 p) (f :: c)) (hasNegative p c or isSuc f = true)

  \lemma certToLeq (p : Problem) (c : CorrectCert p) : certSum (map __.3 p) c.1 <= certSum (map __.1 p) c.1 => {?hidden_proof}
    \where {
      \lemma aux  => {?hidden_proof}
    }


  \lemma certToLess (p : Problem) (c : CorrectCert p) (q : isSuc c.2 = true) : certSum (map __.3 p) c.1 < certSum (map __.1 p) c.1 => {?hidden_proof}

  \lemma solveContrProblem (p : Problem) (c : CorrectCert p) (h : DArray (\lam j => interpretEq (p j))) : Empty => {?hidden_proof}
    \where {
      \lemma aux_<= (p : Problem) (c : Cert p.len) (h : ∀ (e : p) (interpretEq e)) : certSum (map __.1 p) c <= certSum (map __.3 p) c => {?hidden_proof}

      \lemma aux (p : Problem) (c : Cert p.len) (cc : ∃ (j : Fin p.len) (0 < c j) ((p j).2 = Less)) (h : ∀ (e : p) (interpretEq e)) :
        certSum (map __.1 p) c < certSum (map __.3 p) c => {?hidden_proof}
    }


  \lemma solve<=Problem (p : Problem) (t1 t2 : RingTerm C V) (c : CorrectCert (toContr p t1 t2)) (h : DArray (\lam j => interpretEq (p j))) : interpret t1 <= interpret t2 => {?hidden_proof}
    \where {
      \func toContr (p : Problem) (t1 t2 : RingTerm C V) : Problem => (t2, Less, t1) :: p
    }


  \lemma solve=Problem (p : Problem) (t1 t2 : RingTerm C V) (c1 : CorrectCert (toContr1 p t1 t2)) (c2 : CorrectCert (toContr2 p t1 t2)) 
  (h : DArray (\lam j => interpretEq (p j))) : interpret t1 = interpret t2 => {?hidden_proof}
    \where {
      \func toContr1 (p : Problem) (t1 t2 : RingTerm C V) : Problem => (t1, Less, t2) :: p

      \func toContr2 (p : Problem) (t1 t2 : RingTerm C V) : Problem => (t2, Less, t1) :: p
    }


  \lemma solve<Problem (p : Problem) (t1 t2 : RingTerm C V) (c : CorrectCert (toContr p t1 t2)) (h : DArray (\lam j => interpretEq (p j))) : interpret t1 < interpret t2 => {?hidden_proof}
    \where {
      \func toContr (p : Problem) (t1 t2 : RingTerm C V) : Problem => (t2, LessOrEquals, t1) :: p
    }

}
  \where {
    \open PosetSemiring
    \open LinearlyOrderedSemiring
  }


\class LinearSemiringData \extends LinearData, SemiringData

\class LinearRingData \extends LinearData, RingData {
  \override R : OrderedRing
}

\class LinearRatData \extends LinearData, RatData {
  \override R : OrderedRing
}

\class LinearRatAlgebraData \extends RatAlgebraData, LinearData {
  \override R : OrderedAAlgebra RatField
}