\import Algebra.Meta
\import Category
\import Category.Factorization
\import Category.Meta
\import Category.Subcat
\import Equiv
\import Function(IsSurj)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.SetHom
\import Topology.Locale
\open CompleteLattice(SJoin)
\open Locale
\open Nucleus
\open MeetSemilattice
\open FrameHom \hiding (isClosed, functor)

\func star {L : Locale} (x : L) (U : L -> \Prop) => SJoin (\lam y => \Sigma (U y) (IsPositive (x ∧ y)))
  \where {
    \lemma star_<= {L : Locale} {x y : L} (x<=y : x <= y) (U : L -> \Prop) : star x U <= star y U => {?hidden_proof}

    \lemma star-refl {L : PreuniformLocale} {x : L} {U : L -> \Prop} (uU : isUniform U) : x <= star x U => {?hidden_proof}
  }


\func nucleus-star {L : Locale} (j : Nucleus {L}) (U : L -> \Prop) => SJoin (\lam y => \Sigma (U y) (j.locale.IsPositive (j y, nucleus-join>=)))
  \where {
    \lemma star_open {L : Locale} (a : L) (U : L -> \Prop) : nucleus-star (open a) U = star a U => {?hidden_proof}
  }


\class PreuniformLocale \extends Locale {
  | uniform-overt : IsOvert
  | isUniform : (E -> \Prop) -> \Prop
  | isCovering {U : E -> \Prop} : isUniform U -> top <= SJoin U
  | isDownset {U : E -> \Prop} {x y : E} : isUniform U -> U y -> x <= y -> U x
  | top-uniform : isUniform (\lam _ => \Sigma)
  | meet-uniform {U V : E -> \Prop} : isUniform U -> isUniform V -> isUniform (\lam x => \Sigma (U x) (V x))
  | <=-uniform {U V : E -> \Prop} : isUniform U -> (\Pi {x : E} -> U x -> V x) -> (\Pi {x y : E} -> V y -> x <= y -> V x) -> isUniform V
  | star-uniform {U : E -> \Prop} : isUniform U -> ∃ (V : isUniform) ∀ x (V x -> U (star x V))
}
  \where {
    \lemma dClosure {L M : Preorder} {f : L -> M} {U : L -> \Prop} {x y : M} (p : ∃ (z : L) (U z) (y <= f z)) (x<=y : x <= y) : ∃ (z : L) (U z) (x <= f z) => {?hidden_proof}
  }


\open PreuniformLocale(dClosure)

\class UniformHom \extends FrameHom {
  \override Dom : PreuniformLocale
  \override Cod : PreuniformLocale
  | func-uniform {U : Dom -> \Prop} : isUniform U -> isUniform (\lam y => ∃ (x : Dom) (U x) (y <= func x))
}

\class UniformEmbedding \extends UniformHom {
  | isEmbedding : IsSurj func
  | isUniformEmbedding {U : Cod -> \Prop} : isUniform U -> ∃ (V : isUniform) ∀ {x} (V x -> U (func x))
}
  \where {
    \func comp {L M K : PreuniformLocale} (g : UniformEmbedding M K) (f : UniformEmbedding L M) : UniformEmbedding L K \cowith
      | UniformHom => g PreuniformCat.∘ f
      | isEmbedding => {?hidden_proof}
      | isUniformEmbedding => {?hidden_proof}
  }


\func \infix 4 <=u {L : PreuniformLocale} (a b : L) => ∃ (U : (L -> \Prop)) (isUniform U) (star a U <= b)
  \where {
    \lemma func-<=u (f : UniformHom) {a b : f.Dom} (p : a <=u b) : f a <=u f b => {?hidden_proof}

    \lemma adjoint (f : UniformHom) {a : f.Dom} {b : f.Cod} (p : a <=u f.direct b) : f a <=u b => {?hidden_proof}

    \lemma dense {L : PreuniformLocale} {a c : L} (p : a <=u c) : ∃ (b : L) (a <=u b) (b <=u c) => {?hidden_proof}
      \where {
        \lemma meet_star-comm {L : Locale} (o : L.IsOvert) {a b : L} {U : L -> \Prop} (p : IsPositive (a ∧ star b U)) : IsPositive (b ∧ star a U) => {?hidden_proof}
      }


    \lemma uniform-refine {L : PreuniformLocale} {U : L -> \Prop} (uU : isUniform U) : isUniform (\lam b => ∃ (a : L) (U a) (b <=u a)) => {?hidden_proof}
  }


\lemma <=u-trans-left {L : PreuniformLocale} (a : L) {b c : L} (p : a <=u b) (b<=c : b <= c) : a <=u c => {?hidden_proof}

\lemma <=u-trans-right {L : PreuniformLocale} {a b c : L} (a<=b : a <= b) (p : b <=u c) : a <=u c => {?hidden_proof}

\lemma <=u_meet {L : PreuniformLocale} {a a' b b' : L} (p : a <=u a') (q : b <=u b') : a ∧ b <=u a' ∧ b' => {?hidden_proof}

\lemma <=u_<= {L : PreuniformLocale} {a b : L} (p : a <=u b) : a <= b => {?hidden_proof}

\class UniformLocale \extends PreuniformLocale {
  | isAdmissible (b : E) : b <= SJoin (<=u b)
}
  \where {
    \open NucleusFrame

    \lemma star_wclosure {L : PreuniformLocale} {j : Nucleus {L}} {U : L -> \Prop} (uU : isUniform U) : nucleus-star j.map.wclosed-image U = nucleus-star j U => {?hidden_proof}

    \lemma top>=star {L : PreuniformLocale} {j : Nucleus {L}} (o : j.locale.IsOvert) {U : L -> \Prop} (uU : isUniform U) : open (nucleus-star j U) <= j => {?hidden_proof}

    \lemma wclosure>=nucleus-star {L : PreuniformLocale} {j : Nucleus {L}} (o : j.locale.IsOvert) {U : L -> \Prop} (uU : isUniform U) : open (nucleus-star j U) <= j.map.wclosed-image => {?hidden_proof}

    \lemma wclosure>=star {L : PreuniformLocale} {a : L} {U : L -> \Prop} (uU : isUniform U) : open (star a U) <= wclosed-image {Nucleus.map {open a}} => {?hidden_proof}
  }


\lemma uniform=>wregular {L : UniformLocale} : L.IsWeaklyRegularLocale => {?hidden_proof}

\func PreuniformCat : Cat PreuniformLocale \cowith
  | Hom => UniformHom
  | id => \lam L => \new UniformHom {
    | FrameHom => FrameCat.id L
    | func-uniform => <=-uniform __ (\lam {x} Ux => inP (x, Ux, <=-refl)) dClosure
  }
  | o => \lam g f => \new UniformHom {
    | FrameHom => g FrameCat.∘ f
    | func-uniform => \lam uU => <=-uniform (func-uniform {g} (func-uniform {f} uU)) (\lam {x} inP (y, inP (z, Uz, y<=fz), x<=gy) => inP (z, Uz, x<=gy <=∘ func-<= y<=fz)) dClosure
  }
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  | univalence => {?hidden_proof}
  \where {
    \lemma uniform-lem {L : PreuniformLocale} {U : L -> \Prop} (u : isUniform (\lam y => ∃ (x : L) (U x) (y <= x))) (d : \Pi {x y : L} -> U y -> x <= y -> U x) : isUniform U => {?hidden_proof}
  }


\func UniformCat : Cat UniformLocale => subCat {PreuniformCat}
  (\new Embedding {  | f => \lam L => L  | isEmb => \lam (L M : UniformLocale) => \new Retraction {
    | sec => \lam p => path (\lam i => \new UniformLocale {  | PreuniformLocale => p i
      | isAdmissible => prop-dpi (\Pi (b : p __) -> b <= SJoin (<=u b)) L.isAdmissible M.isAdmissible i})    | f_sec => idpe  }})

\func CompletionPres (L : UniformLocale) : FramePres L \cowith
  | conj => meet
  | BasicCover => FramePres.Indexing {\Sigma (j : Fin 4) ((L :: L :: (\Sigma (U : L -> \Prop) (isUniform U)) :: L.E :: nil) j)}
    (\case __ \with {  | (0, a) => (\Sigma, a, \lam _ => top)  | (1, a) => (IsPositive a, a, \lam _ => a)
    | (2, U) => (\Sigma (x : L) (U.1 x), top, __.1)  | (3, a) => (\Sigma (b : L) (b <=u a), a, __.1)})
  \where {
    \lemma <=_cover {L : UniformLocale} {a b : L} (a<=b : a <= b) : Cover1 {CompletionPres L} a b => {?hidden_proof}
  }


\open CompletionPres
\open PresentedFrame \hiding (<=)

\func CompletionLocale (L : UniformLocale) => PresentedFrame (CompletionPres L)

\func completionLocale {L : UniformLocale} : LocaleCat.Hom L (CompletionLocale L) => FrameReflectiveSubcat.adjointMap completionLocale.presentation
  \where {
    \func presentation {L : UniformLocale} : FramePresHom (CompletionPres L) (FrameUnitalSubcat.F L) \cowith
      | func => \lam x => x
      | func-conj => {?hidden_proof}
      | func-basicCover => {?hidden_proof}
      | func-image => {?hidden_proof}

    \lemma sdense {L : UniformLocale} : isStronglyDense {completionLocale {L}} => {?hidden_proof}

    \lemma completion_embed {L : UniformLocale} {a : L} : completionLocale (embed a) = a => {?hidden_proof}
  }


\func Completion (L : UniformLocale) : UniformLocale \cowith
  | Locale => CompletionLocale L
  | uniform-overt => {?hidden_proof}
  | isUniform => isUniform
  | isCovering => {?hidden_proof}
  | isDownset => {?hidden_proof}
  | top-uniform => {?hidden_proof}
  | meet-uniform => {?hidden_proof}
  | <=-uniform => {?hidden_proof}
  | star-uniform => {?hidden_proof}
  | isAdmissible => {?hidden_proof}
  \where {
    \open FramePres(indexing-make)

    \func make-covering {L : UniformLocale} (U : L -> \Prop) (uU : L.isUniform U) :
      \Sigma (V : CompletionLocale L -> \Prop) (isUniform V) (\Pi (a : L) -> star (embed a) V <= embed (star a U)) 
    => (\lam s => ∃ (x : L) (U x) (s <= embed x), inP (U, uU, \lam {a} Ua => inP (a, Ua, <=-refl), dClosure),
      \lam a => Join-univ (\lam (t, (inP (y, V'y, t<=y), xt>0)) => t<=y <=∘ Cover_embed  (<=_cover $ Join-cond $ later  (y,  (V'y,
      transport IsPositive completionLocale.completion_embed $ sdense_positive {completionLocale} completionLocale.sdense $ transport IsPositive embed_meet $ 
                positive_<= xt>0 $ MeetSemilattice.meet-monotone (<=-refl {_} {embed a}) t<=y))))
    )
  }


\func completion {L : UniformLocale} : UniformEmbedding (Completion L) L \cowith
  | FrameHom => completionLocale
  | func-uniform => {?hidden_proof}
  | isEmbedding => {?hidden_proof}
  | isUniformEmbedding => {?hidden_proof}
  \where {
    \lemma isMono {L M : UniformLocale} {f g : UniformHom M (Completion L)} (p : completion PreuniformCat.∘ f = completion PreuniformCat.∘ g) : f = g => {?hidden_proof}
  }


completion-factor {L M : UniformLocale} (f : UniformEmbedding M L) (sd : f.isStronglyDense) : \Sigma (g : UniformHom (Completion L) M) (f UniformCat.∘ g = completion) => 
  \have g => \new (UniformHom (Completion L) M) {
          | FrameHom => FrameReflectiveSubcat.adjointMap (presentation f sd)
          | func-uniform => \lam inP (V, uV, V<=U, Ud) => <=-uniform (f.direct-uniform uV) (\lam inP (y, Vy, x<=f_y) => inP (embed y, V<=U Vy, x<=f_y <=∘ Join-cond (later (y, cover-inj () idp)))) 
            (\lam inP (z, Uz, p) x<=y => inP (z, Uz, x<=y <=∘ p))
        }
  \in (g,
        exts $ func-equality (g LocaleCat.∘ f) completionLocale (\lam x => func-Join *> path (\lam i => Join (\lam p => surjective-split f.isEmbedding p.1 i)))
)
  \where {
    \func presentation {L M : UniformLocale} (f : UniformEmbedding M L) (sd : f.isStronglyDense) : FramePresHom (CompletionPres L) (FrameUnitalSubcat.F M) \cowith
      | func => direct
      | func-conj => {?hidden_proof}
      | func-basicCover => {?hidden_proof}
      | func-image => {?hidden_proof}
  }


\lemma completion-isComplete (L : UniformLocale) : UniformLocale.isComplete {Completion L} => {?hidden_proof}

\func completion-functor {L M : UniformLocale} (f : UniformHom M L) : UniformHom (Completion M) (Completion L) \cowith
  | FrameHom => FrameReflectiveSubcat.adjointMap (presentation f)
  | func-uniform => {?hidden_proof}
  \where {
    \open Cover

    \func presentation {L M : UniformLocale} (f : UniformHom M L) : FramePresHom (CompletionPres M) (FrameUnitalSubcat.F (Completion L)) \cowith
      | func => \lam a => closure (\lam (t : \Sigma (b : M) (b <=u a)) => f t.1)
      | func-conj => {?hidden_proof}
      | func-basicCover => {?hidden_proof}
      | func-image => {?hidden_proof}
  }


\lemma completion-natural {L M : UniformLocale} (f : UniformHom M L) : completion UniformCat.∘ completion-functor f = f UniformCat.∘ completion => {?hidden_proof}

\lemma completion-isReflector {L M : UniformLocale} (Mc : M.isComplete) : Equiv {UniformHom M (Completion L)} {UniformHom M L} (\lam g => completion UniformCat.∘ g) => {?hidden_proof}