\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Semiring
\import Function.Meta
\import Meta
\import Order.BooleanAlgebra
\import Order.HeytingAlgebra
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta

\class BooleanRing \extends PseudoCRing, BottomDistributiveLattice {
  | isBooleanRing {x : E} : x * x = x
  | <= => BooleanRing.<=
  | <=-refl => isBooleanRing
  | <=-transitive => \lam xy=x yz=y => pmap (* _) (inv xy=x) *> *-assoc *> pmap (_ *) yz=y *> xy=x
  | <=-antisymmetric => \lam xy=x yx=y => inv xy=x *> *-comm *> yx=y
  | meet => *
  | meet-left => *-comm *> inv *-assoc *> pmap (* _) isBooleanRing
  | meet-right => *-assoc *> pmap (_ *) isBooleanRing
  | meet-univ => \lam zx=z zy=z => inv *-assoc *> pmap (* _) zx=z *> zy=z
  | join => \lam x y => x + y + x * y
  | join-left => ldistr *> pmap2 + ldistr (inv *-assoc) *> +-assoc *> pmap2 + isBooleanRing (pmap (_ + __ * _) isBooleanRing *> sum2 isBooleanRing) *> zro-right
  | join-right => ldistr *> pmap2 (__ + _ * __) ldistr *-comm *> +-comm *> inv +-assoc *> pmap2 + (pmap (+ _) (inv *-assoc *> pmap (* _) isBooleanRing) *> sum2 isBooleanRing) 
    isBooleanRing *> zro-left
  | join-univ => \lam xz=x yz=y => rdistr *> pmap2 + (rdistr *> pmap2 + xz=x yz=y) (*-assoc *> pmap (_ *) yz=y)
  | bottom => 0
  | bottom-univ => zro_*-left
  | ldistr>= => pmap (_ *)
    (inv $ ldistr *> pmap2 + ldistr (pmap (* _) (inv isBooleanRing) *> *-assoc *> pmap (_ *) (inv *-assoc *> pmap (* _) *-comm *> *-assoc) *> inv *-assoc)) 
  *> isBooleanRing
  | *-comm => \lam {x} {y} => inv zro-left *> pmap (+ _)
    (cancel-right y $ zro-left *> cancel-left x 
    (inv isBooleanRing *> ldistr *> pmap2 + rdistr rdistr *> pmap2 (__ + _ + (_ + __)) isBooleanRing isBooleanRing *> +-assoc) *> inv +-assoc) *> 
  +-assoc *> pmap (_ +) (sum2 isBooleanRing) *> zro-right
}
  \where {
    \lemma sum2 {R : PseudoRing} (br : \Pi {x : R} -> x * x = x) {x : R} : x + x = 0 => {?hidden_proof}

    \type \infix 4 <= {R : Semigroup} (x y : R) => x * y = x
  }


\class UnitalBooleanRing \extends BooleanRing, CRing, BooleanAlgebra {
  | top => 1
  | top-univ => ide-right
  | compl => \lam a => a + 1
  | compl-meet => zro_*-right *> inv (ldistr *> pmap2 + isBooleanRing ide-right *> double=0)
  | compl-join => unfold $ ide-left *> pmap2 + (inv +-assoc *> pmap (+ 1) double=0 *> zro-left) (ldistr *> pmap2 + isBooleanRing ide-right *> double=0) *> zro-right
}
  \where {
    \open MeetSemilattice
    \open JoinSemilattice

    \use \coerce fromBooleanAlgebra (R : BooleanAlgebra) : UnitalBooleanRing R \cowith
      | zro => R.bottom
      | + => \lam a b => a ∧ compl b ∨ b ∧ compl a
      | zro-left => <=-antisymmetric (join-univ (meet-left <=∘ bottom-univ) meet-left) $ meet-univ <=-refl (top-univ <=∘ compl-join <=∘ join-univ bottom-univ <=-refl) <=∘ join-right
      | +-assoc => rewrite (R.compl_symm-diff, R.compl_symm-diff, R.meet-ldistr, R.meet-rdistr, R.meet-ldistr, R.meet-rdistr) $ <=-antisymmetric
        (join-univ (join-univ (meet-assoc =<= join-right <=∘ join-left) ((meet-assoc *> pmap (_ ∧) meet-comm *> inv meet-assoc) =<= join-left <=∘ join-right)) 
        (join-univ (meet-comm =<= meet-assoc =<= join-left <=∘ join-left) ((pmap (_ ∧) meet-comm *> inv meet-assoc) =<= join-right <=∘ join-right)))
        (join-univ (join-univ ((inv meet-assoc *> meet-comm) =<= join-left <=∘ join-right) (inv meet-assoc =<= join-left <=∘ join-left))
        (join-univ ((meet-assoc *> pmap (_ ∧) meet-comm *> inv meet-assoc) =<= join-right <=∘ join-left) 
        ((meet-assoc *> pmap (_ ∧) meet-comm) =<= join-right <=∘ join-right)))
      | +-comm => join-comm
      | * => ∧
      | *-assoc => meet-assoc
      | ldistr => R.meet-ldistr *> pmap2 ∨
        (later $ rewrite R.compl_meet $ inv $ R.meet-ldistr *> pmap2 ∨ (<=-antisymmetric (meet-monotone meet-left <=-refl <=∘ compl-meet) bottom-univ) meet-assoc *> 
          R.bottom-left)
        (later $ rewrite R.compl_meet $ inv $ R.meet-ldistr *> pmap2 ∨ (<=-antisymmetric (meet-monotone meet-left <=-refl <=∘ compl-meet) bottom-univ) meet-assoc *> 
          R.bottom-left)
      | negative => \lam x => x
      | negative-left => unfold $ <=-antisymmetric (join-univ compl-meet compl-meet) bottom-univ
      | ide => top
      | ide-left => R.top-left
      | *-comm => meet-comm
      | isBooleanRing => meet-idemp
  }


\instance HeytingBooleanRing (R : HeytingAlebra) : UnitalBooleanRing (NegatedElem R) => UnitalBooleanRing.fromBooleanAlgebra (HeytingBooleanAlgebra R)