\import Algebra.Domain.Bezout
\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Prime
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.Sub
\import Algebra.Ring
\import Algebra.Ring.Ideal
\import Algebra.Ring.RingHom
\import Algebra.Semiring
\import Function.Meta
\import Logic
\import Meta
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\open Monoid

\instance FactorRing (I : Ideal) : CRing 
  | E => Type I
  | zro => inF 0
  | + => +
  | zro-left => \lam {x} => (\case \elim x \with {
    | in~ a => fequiv (simplify contains_zro)
  })
  | +-assoc => \lam {x} {y} {z} => (\case \elim x, \elim y, \elim z \with {
    | in~ a, in~ b, in~ c => fequiv (simplify contains_zro)
  })
  | +-comm => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ a, in~ b => fequiv (simplify contains_zro)
  })
  | ide => inF 1
  | * => *
  | ide-left => \lam {x} => (\case \elim x \with {
    | in~ a => fequiv (simplify contains_zro)
  })
  | *-assoc => \lam {x} {y} {z} => (\case \elim x, \elim y, \elim z \with {
    | in~ a, in~ b, in~ c => fequiv (transportInv I (AddGroup.toZero *-assoc) contains_zro)
  })
  | ldistr => \lam {x} {y} {z} => (\case \elim x, \elim y, \elim z \with {
    | in~ a, in~ b, in~ c => fequiv (transportInv I (AddGroup.toZero ldistr) contains_zro)
  })
  | natCoef => \lam n => inF (natCoef n)
  | natCoefZero => fequiv $ simplify (transportInv I natCoefZero contains_zro)
  | natCoefSuc => \lam n => fequiv $ later $ rewrite natCoefSuc (simplify contains_zro)
  | negative => negative
  | negative-left => \lam {x} => (\case \elim x \with {
    | in~ a => fequiv (simplify contains_zro)
  })
  | *-comm => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ a, in~ b => fequiv (transportInv I (AddGroup.toZero *-comm) contains_zro)
  })
  \where {
    \type Type (I : Ideal) => Quotient {I.S} (\lam a b => I (a - b))

    \func inF {I : Ideal} (a : I.S) : Type I => in~ a

    \lemma fequiv {I : Ideal} {a b : I.S} (p : I (a - b)) : inF a = inF b => {?hidden_proof}

    \lemma fequiv0 {I : Ideal} {a : I.S} (p : I a) : inF a = inF 0 => {?hidden_proof}

    \lemma unfequiv {I : Ideal} {a b : I.S} (p : inF a = inF b) : I (a - b) => {?hidden_proof}

    \lemma unfequiv0 {I : Ideal} {a : I.S} (p : inF a = inF 0) : I a => {?hidden_proof}
  }


\func factorHom {I : Ideal} : RingHom I.S (FactorRing I) \cowith
  | func => FactorRing.inF
  | func-+ => idp
  | func-ide => idp
  | func-* => idp

\func factor-lift {I : Ideal} {R : Ring} (f : RingHom I.S R) (p : \Pi {a : I.S} -> I a -> f a = 0) : RingHom (FactorRing I) R \cowith
  | func => func
  | func-+ => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ a, in~ b => f.func-+
  })
  | func-ide => f.func-ide
  | func-* => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ a, in~ b => f.func-*
  })

\instance FactorField {I : Ideal} (Im : I.IsMaximal) : DiscreteField 
  | CRing => FactorRing I
  | zro/=ide => \lam p => Im.1 $ unfequiv0 (inv p)
  | eitherZeroOrInv => \case \elim __ \with {
    | in~ a => \case Im.2 a \with {
      | byLeft r => byLeft $ fequiv0 r
      | byRight s => byRight $ Inv.lmake (inF s.1) $ inv $ later $ fequiv s.2
    }
  }
  \where {
    \open FactorRing

    \lemma conv {I : Ideal} (p : 0 /= {FactorRing I} 1) (q : \Pi (x : FactorRing I) -> (x = 0) || Inv x) : I.IsMaximal => {?hidden_proof}
  }


\instance FactorIrrField (R : BezoutRing) (p : Irr {R}) : DiscreteField 
  | CRing => FactorRing (Ideal.closure1 p)
  | zro/=ide => \lam q => p.notInv (trivial_Inv.1 q)
  | eitherZeroOrInv => zeroOrInv-char.2 (\lam a => (\case isBezout p a \with {  | inP (s, t, d|p : Monoid.LDiv, d|a : Monoid.LDiv) => \case p.isIrr (inv d|p.inv-right) \with {
      | byLeft c : Inv => byRight (t * c.inv, s * c.inv, equation.cRing {c.inv-right})
      | byRight c : Inv => byLeft (\new Monoid.LDiv {  | inv => c.inv * d|a.inv  | inv-right => equation.monoid {(inv d|p.inv-right, c.inv-right, d|a.inv-right)}})
    }}))
  \where {
    \open FactorRing \hiding (+, *, negative)

    \lemma trivial_Inv {R : CRing} {p : R} : (0 = {FactorRing (Ideal.closure1 p)} 1) <-> Inv p => {?hidden_proof}

    \lemma zeroOrInv-char {R : CRing} {p : R} : (\Pi (a : FactorRing (Ideal.closure1 p)) -> (a = 0) || Inv a) <-> (\Pi (a : R) -> Monoid.LDiv p a || (\Sigma (s t : R) (s * a + t * p = 1))) 
      => {?hidden_proof}

    \lemma conv {R : CRing} {p : R} (c : \Pi {x y : R} -> p * x = p * y -> x = y) (d : DiscreteField {  | CRing => FactorRing (Ideal.closure1 p)}) : Prime p => {?hidden_proof}
  }
