\import Algebra.Algebra
\import Algebra.Domain
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Poly
\import Algebra.Ring.RingHom
\import Arith.Nat
\import Data.Or
\import Equiv
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set.Fin
\open AddGroup

\type FSeries (R : \Set) => Nat -> R

\lemma fseries-apply {R : \Set} {x y : FSeries R} (p : x = y) {n : Nat} : x n = y n => {?hidden_proof}

\instance FSeriesRing (R : Ring) : Ring (FSeries R) 
  | zro => \lam _ => 0
  | + => \lam f g n => f n + g n
  | zro-left => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | negative => \lam f n => negative (f n)
  | negative-left => {?hidden_proof}
  | ide => coef 1
  | * => \lam f g n => R.FinSum {PairsFinSet n} (\lam s => f s.1 * g s.2)
  | *-assoc => {?hidden_proof}
  | ldistr => {?hidden_proof}
  | rdistr => {?hidden_proof}
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  | natCoef => \lam n => coef (R.natCoef n)
  | natCoefZero => {?hidden_proof}
  | natCoefSuc => {?hidden_proof}
  \where {
    \func coef (a : R) (n : Nat) : R \elim n
      | 0 => a
      | suc _ => 0

    \lemma coef_/=0 {a : R} {n : Nat} (n/=0 : n /= 0) : coef a n = 0 => {?hidden_proof}

    \lemma PairsFinSet (n : Nat) : FinSet (\Sigma (i j : Nat) (\property (i + j = n))) (suc n) => {?hidden_proof}

    \lemma PairsFinSet-ext1 {n : Nat} {x y : \Sigma (s : PairsFinSet n) (PairsFinSet s.1)} (p1 : x.1.1 = y.1.1) (p2 : x.1.2 = y.1.2) (p3 : x.2.1 = y.2.1) (p4 : x.2.2 = y.2.2) : x = y 
      => {?hidden_proof}

    \lemma PairsFinSet-ext2 {n : Nat} {x y : \Sigma (s : PairsFinSet n) (PairsFinSet s.2)} (p1 : x.1.1 = y.1.1) (p2 : x.1.2 = y.1.2) (p3 : x.2.1 = y.2.1) (p4 : x.2.2 = y.2.2) : x = y 
      => {?hidden_proof}

    \lemma Pairs_zero {f : PairsFinSet 0 -> R} : R.FinSum f = f (0, 0, idp) => {?hidden_proof}

    \lemma Pairs_suc-left {n : Nat} {f : PairsFinSet (suc n) -> R} : R.FinSum f = f (0, suc n, idp) + R.FinSum (\lam (s : PairsFinSet n) => f (suc s.1, s.2, pmap suc s.3)) => {?hidden_proof}
  }


\instance FSeriesAlgebra (R : CRing) : CAlgebra R 
  | Ring => FSeriesRing R
  | *c => \lam c x n => c * x n
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  | *c-comm-left => {?hidden_proof}
  | coefMap => \lam a => FSeriesRing.coef a
  | coefMap_*c => {?hidden_proof}
  | *-comm => {?hidden_proof}

\instance FSeriesRingWith# (R : Ring.With#) : Ring.With# 
  | Ring => FSeriesRing R
  | #0 => \lam x => ∃ (n : Nat) (#0 (x n))
  | #0-zro => {?hidden_proof}
  | #0-+ => {?hidden_proof}
  | #0-tight => {?hidden_proof}
  | #0-*-left => {?hidden_proof}
  | #0-*-right => {?hidden_proof}

\instance FSeriesCRingWith# (R : CRing.With#) : CRing.With# 
  | Ring.With# => FSeriesRingWith# R
  | *-comm => {?hidden_proof}

\instance FSeriesDomain (R : Domain) : Domain 
  | Ring.With# => FSeriesRingWith# R
  | zro#ide => {?hidden_proof}
  | #0-* => {?hidden_proof}
  \where {
    \protected \lemma aux {k n m : Nat} (n+m<k : n + m < k) {x y : FSeries R} (xn#0 : #0 (x n)) (ym#0 : #0 (y m)) : ∃ (k : Nat) (#0 ((x * y) k)) => {?hidden_proof}
  }


\instance FSeriesIntegralDomain (R : IntegralDomain) : IntegralDomain 
  | Domain => FSeriesDomain R
  | *-comm => {?hidden_proof}

\func poly-FSeries {R : Ring} : RingHom (PolyRing R) (FSeriesRing R) (polyCoef __) \cowith
  | func-+ => {?hidden_proof}
  | func-ide => {?hidden_proof}
  | func-* => {?hidden_proof}
  \where {
    \lemma *-lem {p q : Poly R} {n : Nat} : polyCoef (p * q) n = (polyCoef p * {FSeriesRing R} polyCoef q) n => {?hidden_proof}
  }


\lemma geometric-FSeries {R : Ring} : Monoid.Inv {FSeriesRing R} (\lam _ => 1) (polyCoef (padd (padd pzero -1) 1)) => {?hidden_proof}