\import Algebra.Meta
\import Algebra.Monoid.MonoidLocalization
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Semiring
\import Function.Meta
\import Paths
\import Relation.Equivalence

\instance GrothendieckRing (R : Semiring) : Ring 
  | AbGroup => GrothendieckAbGroup R
  | * => *
  | ide => inl~ (1, 0, ())
  | *-assoc => {?hidden_proof}
  | ldistr => {?hidden_proof}
  | rdistr => {?hidden_proof}
  | zro_*-left => {?hidden_proof}
  | zro_*-right => {?hidden_proof}
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  \where {
    \open LocAbType
  }


\instance GrothendieckCRing (R : CSemiring) : CRing 
  | Ring => GrothendieckRing R
  | *-comm => {?hidden_proof}