\import Algebra.Group
\import Algebra.Group.Sub
\import Algebra.Module
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.Sub
\import Algebra.Ring
\import Algebra.Semiring
\import Arith.Int
\import Arith.Nat
\import Combinatorics.Binom
\import Data.Array
\import Data.Bool
\import Data.Or
\import Equiv
\import Function.Meta ($)
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\import Set.Countable
\import Set.Fin
\open AddMonoid
\open AbMonoid

\record LIdeal \extends SubAddGroup {
  \override S : Ring
  | ideal-left {r a : S} : contains a -> contains (r * a)
  | contains_negative => \lam c => transport contains (Ring.negative_*-left *> pmap negative ide-left) (ideal-left c)
}

\record RIdeal \extends SubAddGroup {
  \override S : Ring
  | ideal-right {r a : S} : contains a -> contains (a * r)
  | contains_negative => \lam c => transport contains (Ring.negative_*-right *> pmap negative ide-right) (ideal-right c)

  \lemma ldiv {a b : S} (a|b : Monoid.LDiv a b) (Ia : contains a) : contains b => {?hidden_proof}
}

\record TIdeal \extends LIdeal, RIdeal

\record Ideal \extends TIdeal {
  \override S : CRing
  | ideal-right => \lam s => transport contains *-comm (ideal-left s)

  \func radical : Ideal S \cowith
    | contains => \lam a => ∃ (n : Nat) (contains (Monoid.pow a n))
    | contains_zro => {?hidden_proof}
    | contains_+ => {?hidden_proof}
    | ideal-left => {?hidden_proof}

  \func module : LModule S \cowith
    | AbGroup => SubAddGroup.abStruct \this
    | *c => \lam a s => (a * s.1, ideal-left s.2)
    | *c-assoc => {?hidden_proof}
    | *c-ldistr => {?hidden_proof}
    | *c-rdistr => {?hidden_proof}
    | ide_*c => {?hidden_proof}
    \where {
      \lemma finitelyGenerated (p : IsFinitelyGenerated) : module.IsFinitelyGenerated => {?hidden_proof}
    }


  \lemma radical-superset {x : S} (s : contains x) : radical x => {?hidden_proof}

  \lemma radical_pow {x : S} {n : Nat} (s : radical (Monoid.pow x n)) : radical x => {?hidden_proof}

  \lemma radical-univ {I : Ideal S} (p : \Pi {x : S} -> I x -> radical x) {x : S} (s : I.radical x) : radical x => {?hidden_proof}

  \lemma bigSum (l : Array S) (p : \Pi (i : Fin l.len) -> contains (l i)) : contains (BigSum l) => {?hidden_proof}

  \lemma finSum {J : FinSet} {a : J -> S} (p : \Pi (j : J) -> contains (a j)) : contains (FinSum a) => {?hidden_proof}

  \func IsGeneratedBy (l : Array S) => \Sigma (∀ (a : l) (contains a)) (\Pi {a : S} -> contains a -> ∃ (l' : Array S l.len) (a = BigSum (\lam j => l' j * l j)))

  \protected \func IsFinitelyGenerated  => ∃ (l : Array S) (IsGeneratedBy l)

  \func IsGeneratedBy1 (a : S) => \Sigma (contains a) (\Pi {b : S} -> contains b -> TruncP (Monoid.LDiv a b))

  \func IsPrincipal  => ∃ (a : S) (IsGeneratedBy1 a)

  \lemma principal->finitelyGenerated (p : IsPrincipal) : IsFinitelyGenerated => {?hidden_proof}

  \func IsMaximal  => \Sigma (Not (contains 1)) (\Pi (x : S) -> contains x || (\Sigma (y : S) (contains (1 - y * x))))
}
  \where {
    \open Ideal

    \func closure {R : CRing} {J : \Set} (g : J -> R) : Ideal R \cowith
      | contains => \lam e => ∃ (l : Array (\Sigma R J)) (e = BigSum (map (\lam p => p.1 * g p.2) l))
      | contains_zro => {?hidden_proof}
      | contains_+ => {?hidden_proof}
      | ideal-left => {?hidden_proof}

    \func sclosure {R : CRing} (U : R -> \Prop) => closure (\lam (p : \Sigma (x : R) (U x)) => p.1)

    \lemma closure-superset {R : CRing} {J : \Set} {g : J -> R} (j : J) : closure g (g j) => {?hidden_proof}

    \lemma sclosure-superset {R : CRing} {U : R -> \Prop} {x : R} (Ux : U x) : sclosure U x => {?hidden_proof}

    \lemma closure-univ {R : CRing} {J : \Set} {g : J -> R} {I : Ideal R} (c : \Pi (j : J) -> I (g j)) {x : R} (d : closure g x) : I x => {?hidden_proof}

    \lemma sclosure-univ {R : CRing} {U : R -> \Prop} {I : Ideal R} (c : \Pi (x : R) -> U x -> I x) {x : R} (d : sclosure U x) : I x => {?hidden_proof}

    \func closure1 {R : CRing} (a : R) : Ideal R => closure (\lam (_ : \Sigma) => a)

    \lemma closure1-lem {R : CRing} {a b : R} : closure1 a b <-> ∃ (c : R) (b = a * c) => {?hidden_proof}

    \lemma closure1_LDiv {R : CRing} {a b : R} : closure1 a b <-> TruncP (Monoid.LDiv a b) => {?hidden_proof}

    \lemma closure1-principal {R : CRing} {a : R} : IsPrincipal {closure1 a} => {?hidden_proof}
      \where {
        \lemma generated {R : CRing} {a : R} : IsGeneratedBy1 {closure1 a} a => {?hidden_proof}
      }


    \lemma closure2-lem {R : CRing} {a : R} (f : Bool -> R) : closure f a <-> ∃ (c d : R) (a = f true * c + f false * d) => {?hidden_proof}

    \lemma fin-closure-lem {D : FinSet} {R : CRing} {a : R} (f : D -> R) : closure f a <-> ∃ (c : (D -> R)) (a = FinSum (\lam i => c i * f i)) => {?hidden_proof}

    \lemma closureN-lem {R : CRing} {a : R} {B : Array R} : closure B a <-> ∃ (c : Array R B.len) (a = BigSum (\lam i => c i * B i)) => {?hidden_proof}
      \where {
        \lemma singleton-lem {R : Semiring} (a : R) (n : Nat) (i : Fin n) : BigSum (\lam (j : Fin n) => if (i NatSemiring.== j) a 0) = a => {?hidden_proof}

        \lemma suc-eq {a b : Nat} : suc a == suc b = a == b => {?hidden_proof}
      }


    \lemma closure-generated {R : CRing} {l : Array R} : IsGeneratedBy {closure l} l => {?hidden_proof}

    \lemma closure-finGenerated {R : CRing} {l : Array R} : Ideal.IsFinitelyGenerated {closure l} => {?hidden_proof}

    \func ChainCondition {R : CRing} (I : Nat -> Ideal R) => (\Pi (n : Nat) {a : R} -> I n a -> I (suc n) a) -> ∃ (n : Nat) ∀ {a} (I (suc n) a -> I n a)

    \lemma fromMonoidChainCondition {R : CRing} (cc : CMonoid.DivChain {DivQuotient.DivQuotientMonoid R}) (I : Nat -> Ideal R) (p : \Pi (n : Nat) -> Ideal.IsPrincipal {I n}) : ChainCondition I 
      => {?hidden_proof}

    \func union {R : CRing} (I : Nat -> Ideal R) (\property inc : \Pi {n : Nat} {a : R} -> I n a -> I (suc n) a) : Ideal R \cowith
      | contains => \lam a => ∃ (n : Nat) (I n a)
      | contains_zro => {?hidden_proof}
      | contains_+ => {?hidden_proof}
      | ideal-left => {?hidden_proof}
      \where {
        \lemma include {n m : Nat} {a : R} (Ia : I n a) : I (n + m) a => {?hidden_proof}
      }


    \func countable-maximal {R : CRing} (c : Countable R) (Id : \Pi (I : Ideal R) -> I.IsFinitelyGenerated -> \Pi (x : R) -> Dec (I x)) {I : Ideal R} (Ig : I.IsFinitelyGenerated) 
    (Ip : Not (I 1)) : \Sigma (M : Ideal R) M.IsMaximal (\Pi {a : R} -> I a -> M a) => (union (\lam n => (ideal n).1) (\lam {_} {a} c => mcases),
      (\lam inP c => ideal-proper c.1 c.2,
      \lam a => (\case pointed-countable-surj R.zro c a \with {  | inP (n, fn=a) => \case Id (next n (ideal n)) (next-fg n (ideal n)) 1 \with {
        | yes inP (x, y, Ix, p) => byRight (y, inP (n, transport (ideal n).1 equation Ix))
        | no r => byLeft $ inP (suc n, rewrite (dec_no_reduce r) $ inP (0, 1, contains_zro, equation))  }})), \lam c => inP (0, c)
    )
      \where {
        \func next (n : Nat) (I : \Sigma (I : Ideal R) I.IsFinitelyGenerated) : Ideal R \cowith
          | contains => \lam z => ∃ (x y : R) (I.1 x) (z = x + y * pointed-countable R.zro c n)
          | contains_zro => {?hidden_proof}
          | contains_+ => {?hidden_proof}
          | ideal-left => {?hidden_proof}

        \lemma next-fg (n : Nat) (I : \Sigma (I : Ideal R) I.IsFinitelyGenerated) : Ideal.IsFinitelyGenerated {next n I} => {?hidden_proof}

        \func ideal (n : Nat) : \Sigma (I : Ideal R) I.IsFinitelyGenerated \elim n
          | 0 => (I, Ig)
          | suc n => \case Id (next n (ideal n)) (next-fg n (ideal n)) 1 \with {
            | yes r => ideal n
            | no r => (next n (ideal n), next-fg n (ideal n))
          }

        \lemma ideal-proper (n : Nat) (c : (ideal n).1 1) : Empty => {?hidden_proof}
      }

  }


\instance IdealLattice {R : CRing} : BoundedLattice (Ideal R) 
  | <= => \lam I J => \Pi {a : R} -> I a -> J a
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | meet (I J : Ideal R) : Ideal R 
    | contains => \lam x => \Sigma (I x) (J x)
    | contains_zro => (contains_zro, contains_zro)
    | contains_+ => \lam s t => (contains_+ s.1 t.1, contains_+ s.2 t.2)
    | ideal-left => \lam s => (ideal-left s.1, ideal-left s.2)
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | top : Ideal R 
    | contains => \lam _ => \Sigma
    | contains_zro => ()
    | contains_+ => \lam _ _ => ()
    | ideal-left => \lam _ => ()
  | top-univ => {?hidden_proof}
  | join => \lam I J => Ideal.closure {R} {Or (\Sigma (a : R) (I a)) (\Sigma (a : R) (J a))} (Or.rec __.1 __.1)
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  | bottom : Ideal R 
    | contains => \lam a => a = 0
    | contains_zro => idp
    | contains_+ => \lam p q => rewrite (p, q) zro-left
    | ideal-left => \lam p => rewrite p zro_*-right
  | bottom-univ => {?hidden_proof}

\instance IdealMonoid {R : CRing} : CMonoid (Ideal R) 
  | ide => IdealLattice.top
  | * => product
  | ide-left => {?hidden_proof}
  | *-assoc => {?hidden_proof}
  | *-comm => {?hidden_proof}
  \where {
    \func func {R : CRing} (I J : Ideal R) => \lam (s : \Sigma (a b : R) (I a) (J b)) => s.1 * s.2

    \func product {R : CRing} (I J : Ideal R) => Ideal.closure (func I J)

    \lemma product-left {R : CRing} {I J : Ideal R} : product I J <= I => {?hidden_proof}

    \lemma product-right {R : CRing} {I J : Ideal R} : product I J <= J => {?hidden_proof}

    \lemma product_meet {R : CRing} {I J : Ideal R} : product I J <= I ∧ J => {?hidden_proof}
  }
