\import Algebra.Domain
\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.Sub
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Function (IsInj, IsSurj)
\import Function.Meta
\import Logic.Meta
\import Logic.Unique
\import Logic
\import Meta
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set \hiding (#)
\open Monoid (Inv)
\open RingHom

\instance SubsetPoset {M : Monoid} : Poset (SubSet M) 
  | <= => \lam (S S' : SubSet M) => \Pi (x : M) -> S x -> S' x
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}

\class Localization (R : CRing) (S : SubSet R) (R' : CRing) {
  | inL : RingHom R R'
  | local (x : R) : S x -> Inv (inL x)
  | local-univ {R'' : CRing} (f : RingHom R R'') (l : \Pi (x : R) -> S x -> Inv (f x)) : Contr (\Sigma (g : RingHom R' R'') (\Pi (x : R) -> g (inL x) = f x))

  \func lift {R'' : CRing} (f : RingHom R R'') (l : \Pi (x : R) -> S x -> Inv (f x)) : RingHom R' R'' => (Contr.center {local-univ f l}).1

  \lemma lift-prop {R'' : CRing} (f : RingHom R R'') (l : \Pi (x : R) -> S x -> Inv (f x)) : lift f l ∘ inL = f => {?hidden_proof}

  \lemma lift-prop-func {R'' : CRing} (f : RingHom R R'') (l : \Pi (x : R) -> S x -> Inv (f x)) (x : R) : lift f l (inL x) = f x => {?hidden_proof}

  \lemma remove_inL {R'' : CRing} (f g : RingHom R' R'') (p : \Pi (x : R) -> f (inL x) = g (inL x)) : f = g => {?hidden_proof}
}

\instance LocRing {R : CRing} (S : SubMonoid R) : CRing 
  | E => Type
  | zro => in~ (zro, ide, contains_ide)
  | + => ++
  | zro-left => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | ide => in~ (ide, ide, contains_ide)
  | * => **
  | ide-left => {?hidden_proof}
  | *-assoc => {?hidden_proof}
  | ldistr => {?hidden_proof}
  | negative => neg
  | negative-left => {?hidden_proof}
  | *-comm => {?hidden_proof}
  | natCoef => \lam n => in~ (R.natCoef n, 1, contains_ide)
  | natCoefZero => {?hidden_proof}
  | natCoefSuc => {?hidden_proof}
  \where {
    \func SType (S : SubMonoid R) => \Sigma (x y : R) (S y)

    \func Type  => Quotient {SType S} (\lam a b => a.1 * b.2 = b.1 * a.2)

    \lemma inl-surj : IsSurj (inl~ {R} {S}) => {?hidden_proof}

    \lemma equals-lem {a b : SType S} (c : R) (s : S c) (p : a.1 * b.2 * c = b.1 * a.2 * c) : inl~ a = inl~ b => {?hidden_proof}

    \lemma equals1 {a b : SType S} (p : a.1 * b.2 = b.1 * a.2) : inl~ a = inl~ b => {?hidden_proof}

    \lemma unequals {a b : SType S} (p : inl~ a = inl~ b) : ∃ (c : R) (S c) (a.1 * b.2 * c = b.1 * a.2 * c) => {?hidden_proof}

    \lemma equality {a b : SType S} : (inl~ a = inl~ b) = ∃ (c : R) (S c) (a.1 * b.2 * c = b.1 * a.2 * c) => {?hidden_proof}

    \lemma swap {R : CMonoid} {r1 r2 s1 s2 : R} : (r1 * r2) * (s1 * s2) = (r1 * s1) * (r2 * s2) => {?hidden_proof}

    \func neg (a : Type) : Type \elim a
      | in~ (r, s, p) => in~ (negative r, s, p)
      | ~-equiv x y p => ~-pequiv (equation.cRing {p})

    \func ++ (a b : Type) : Type \elim a, b
      | in~ (r1, s1, p1), in~ (r2, s2, p2) => in~ (r1 * s2 + r2 * s1, s1 * s2, contains_* p1 p2)
      | ~-equiv x y p, in~ z => ~-pequiv (equation.cRing {p})
      | in~ x, ~-equiv y z p => ~-pequiv (equation.cRing {p})

    \func ** (a b : Type) : Type \elim a, b
      | in~ (r1, s1, p1), in~ (r2, s2, p2) => in~ (r1 * r2, s1 * s2, contains_* p1 p2)
      | ~-equiv x y p, in~ z => ~-pequiv (equation.cMonoid {p})
      | in~ x, ~-equiv y z p => ~-pequiv (equation.cMonoid {p})

    \lemma trivial {x : R} (n : R.IsNilpotent x) (s : S x) : Contr (LocRing S) => {?hidden_proof}
  }


\func inl~ {R : CRing} {S : SubMonoid R} (x : LocRing.SType S) : LocRing.Type => in~ x

\lemma loc_unequals_domain {D : IntegralDomain} (S : SubMonoid D) (nz : \Pi (x : D) -> S x -> x /= 0) {a b : LocRing.SType S} (p : inl~ a = inl~ b) : a.1 * b.2 = b.1 * a.2 => {?hidden_proof}

\func locMap {R : CRing} {S : SubMonoid R} : RingHom R (LocRing S) \cowith
  | func => \lam x => in~ (x, ide, contains_ide)
  | func-ide => {?hidden_proof}
  | func-+ => {?hidden_proof}
  | func-* => {?hidden_proof}

\lemma locMap-inj {R : CRing} {S : SubMonoid R} (p : \Pi {a : R} -> S a -> \Pi {x y : R} -> x * a = y * a -> x = y) : IsInj (locMap {R} {S}) => {?hidden_proof}

\func localization {R : CRing} (S : SubMonoid R) : Localization R S \cowith
  | R' => LocRing S
  | inL => locMap
  | local => {?hidden_proof}
  | local-univ => {?hidden_proof}
  \where {
    \open LocRing

    \func elem-inv (s : R) (p : S s) => \new (Inv {LocRing S}) {
      | val => in~ (s, ide, contains_ide)
      | inv => in~ (ide, s, p)
      | inv-left => equals1 (*-comm *> pmap (ide *) *-comm)
      | inv-right => equals1 (*-comm *> pmap (ide *) *-comm)
    }

    \lemma locMap-epiMap {Q : CRing} (g h : RingHom (LocRing S) Q) (d : \Pi (a : R) -> g (locMap a) = h (locMap a)) (x : LocRing S) : g x = h x => {?hidden_proof}

    \func lift {R' : CRing} (f : RingHom R R') (l : \Pi (x : R) -> S x -> Inv (f x)) (a : Type {R} {S}) : R' \elim a
      | in~ (r, s, p) => f r * Inv.inv {l s p}
      | ~-equiv (r, s, p) (r', s', p') rs~rs' =>
        equation.cMonoid {(1 inv (l s' p').inv-right, inv (f.func-* {r} {s'}), pmap f rs~rs', f.func-* {r'} {s}, (l s p).inv-right)}

    \func liftHom {R' : CRing} (f : RingHom R R') (l : \Pi (x : R) -> S x -> Inv (f x)) : RingHom (LocRing S) R' \cowith
      | func => lift f l
      | func-ide => {?hidden_proof}
      | func-+ => {?hidden_proof}
      | func-* => {?hidden_proof}
      \where {
        \lemma func-inv {s1 s2 : R} {p1 : S s1} {p2 : S s2} : Inv.inv {l (s1 * s2) (contains_* p1 p2)} = Inv.inv {l s2 p2} * Inv.inv {l s1 p1} => {?hidden_proof}
      }


    \lemma liftHom-loc {R' : CRing} (f : RingHom R R') (l : \Pi (x : R) -> S x -> Inv (f x)) (x : R) : liftHom f l (locMap x) = f x => {?hidden_proof}

    \open SubMonoid (powers)
    \open Monoid

    \func pow-map (b : R) (n : Nat) : RingHom (LocRing (powers (pow b n))) (LocRing (powers b)) \cowith
      | func => \case __ \with {
        | in~ (x, y, c) => in~ (x, y, TruncP.map c (\lam p => (n Nat.* p.1, rewrite pow_* p.2)))
        | ~-equiv x y r => ~-pequiv r
      }
    | func-+ => {?hidden_proof}
    | func-ide => {?hidden_proof}
    | func-* => {?hidden_proof}

    \lemma pow-map_loc (b : R) (n : Nat) : pow-map b n ∘ locMap = locMap => {?hidden_proof}

    \lemma div-map_loc {a b : R} (a|b : LDiv a b) : div-map a|b ∘ locMap = locMap => {?hidden_proof}

    \func div-map {a b : R} (a|b : LDiv a b) : RingHom (LocRing (powers a)) (LocRing (powers b)) \cowith
      | func => aux-func a|b
      | func-+ => {?hidden_proof}
      | func-ide => {?hidden_proof}
      | func-* => {?hidden_proof}
      \where {
        \lemma aux {a b : R} (a|b : LDiv a b) (x : SType (powers a)) => {?hidden_proof}

        \func aux-func {a b : R} (a|b : LDiv a b) (x : LocRing (powers a)) : LocRing (powers b) => \case \elim x \with {
          | in~ x => (aux a|b x).1
          | ~-equiv x y r => \case (aux a|b x).2, (aux a|b y).2 \with {
            | inP ((n, a^n=x2), p), inP ((m, a^m=y2), q) => inv p *> ~-pequiv equation *> q
          }
        }
      }


    \lemma map-lemma {R S : CRing} {M : SubMonoid R} (f : RingHom (LocRing M) S) {x : LocRing.SType M} (i : Inv (f (inl~ (x.2, 1, contains_ide)))) :
      f (inl~ x) = f (inl~ (x.1, 1, contains_ide)) * i.inv => {?hidden_proof}

    \lemma powers-inv {R S : CRing} (f : RingHom R S) {a : R} (p : Inv (f a)) (x : R) (c : powers a x) : Inv (f x) => {?hidden_proof}
  }


\lemma div_loc {R : CRing} {S : SubMonoid R} {a b : R} {Sb : S b} (a|b : Monoid.LDiv b a) : inl~ (a, b, Sb) = locMap a|b.inv => {?hidden_proof}

\open localization

\func loc_change-of-base1 {R S : CRing} (f : RingHom R S) {a : R} : RingHom (LocRing (SubMonoid.powers a)) (LocRing (SubMonoid.powers (f a))) 
  => liftHom (locMap ∘ f) $ powers-inv (locMap ∘ f) $ elem-inv {_} {SubMonoid.powers (f a)} (f a) (inP (1, ide-left))

\lemma loc_change-of-base1-loc {R S : CRing} (f : RingHom R S) {a : R} : loc_change-of-base1 f {a} ∘ locMap = locMap ∘ f => {?hidden_proof}

\instance FieldOfQuotients (D : IntegralDomain.Dec) : DiscreteField 
  | CRing => LocRing D.subMonoid
  | zro/=ide => {?hidden_proof}
  | eitherZeroOrInv => {?hidden_proof}