\import Algebra.Algebra
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Module
\import Algebra.Monoid
\import Algebra.Monoid.MonoidCategory
\import Algebra.Monoid.MonoidHom
\import Algebra.Monoid.PermSet
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Algebra.Ring.MonoidRing
\import Algebra.Ring.Poly
\import Algebra.Semiring
\import Arith.Nat
\import Data.Array
\import Data.Array.EPerm
\import Data.Array.Pairs
\import Data.Fin
\import Equiv
\import Function(IsSurj)
\import Function.Meta($)
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.LinearOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\import Set.Fin
\open MonoidSet \hiding (~)
\open Monoid(pow)
\open RingHom \hiding (equals)

\func MPoly (J : \Set) (R : CRing) => MonoidAlgebra (PermSetMonoid J) R

\func mPolyHom {J : \Set} {R : CRing} : RingHom R (MPoly J R) => monoidRingHom

\func mPoly-map {J : \Set} {R S : CRing} (f : AddMonoidHom R S) (p : MPoly J R) : MPoly J S => monoidSet-map (\lam x => x) f p

\lemma mPoly-map-comp {J : \Set} {R E S : CRing} {f : AddMonoidHom R E} {g : AddMonoidHom E S} {p : MPoly J R} :
  mPoly-map (g AddMonoidCat.∘ f) p = mPoly-map g (mPoly-map f p) => {?hidden_proof}

\func mPoly-mapHom {J : \Set} {R S : CRing} (f : RingHom R S) : RingHom (MPoly J R) (MPoly J S) (mPoly-map f) => monoidSet-ringHom MonoidHom.id f

\lemma mPoly-map_permSet-univ {I J : \Set} {R S : CRing} (f : RingHom R S) (g : I -> MPoly J R) {a : PermSet I} :
  mPoly-map f (permSet-univ {I} {MPoly J R} g a) = permSet-univ {I} {MPoly J S} (\lam i => mPoly-map f (g i)) a => {?hidden_proof}

\func mPolyEval {J : \Set} {R : CRing} (f : J -> R) : RingHom (MPoly J R) R => evalMSRingHom (permSet-univ {J} {R} f)

\func mPolyMapEval {J : \Set} {R S : CRing} (f : AddMonoidHom R S) (p : MPoly J R) (a : J -> S) : S => mPolyEval a (mPoly-map f p)

\func mPolyMapEvalRingHom {J : \Set} {R S : CRing} (f : RingHom R S) (a : J -> S) : RingHom (MPoly J R) S => mPolyEval a ∘ mPoly-mapHom f

\func mVar {J : \Set} {R : CRing} (j : J) : MPoly J R => msMonomial 1 $ PermSet.inPS (j :: nil)

\lemma mVar_pow {J : \Set} {R : CRing} {j : J} {n : Nat} : pow (mVar j) n = msMonomial R.ide (pow (PermSet.inPS (j :: nil)) n) => {?hidden_proof}

\func mConst {J : \Set} {R : CRing} (a : R) : MPoly J R => msMonomial a ide

\lemma msCoef_mVar=0 {J : DecSet} {R : CRing} {j : J} {n m : Nat} {p : MPoly J R} (q : n < m) : msCoef (pow (mVar j) m * p) (pow (PermSet.inPS (j :: nil)) n) = 0 => {?hidden_proof}

\lemma msCoef_mMap {J : DecSet} {R E : CRing} {g : AddMonoidHom R E} {p : MPoly J R} {m : PermSet J} : msCoef (mPoly-map g p) m = g (msCoef p m) => {?hidden_proof}

\lemma mPolyMapEval-var {J : \Set} {R S : CRing} (f : RingHom R S) (a : J -> S) (j : J) : mPolyMapEvalRingHom f a (mVar j) = a j => {?hidden_proof}

\lemma mPolyRingHom-unique {J : \Set} {R S : CRing} (f g : RingHom (MPoly J R) S) (p : \Pi (r : R) -> f (mConst r) = g (mConst r)) (q : \Pi (j : J) -> f (mVar j) = g (mVar j)) 
(x : MPoly J R) : f x = g x => {?hidden_proof}

\func mLastCoef {J : \Set} {R : CRing} (p : MPoly J R) => monoidSet-coefs permSet-zro-dec p

\func MPoly_Empty {J : \Set} {R : CRing} (e : J -> Empty) : QEquiv {MPoly J R} {R} mLastCoef \cowith
  | ret => \lam a => in~ $ (a, in~ nil) :: nil
  | ret_f => \case \elim __ \with {
    | in~ l => 
      \have t j : (l j).2 = ide => cases (l j).2
      \in unfold mLastCoef $ rewrite (keep-all t) $ inv $ fromClosure $ unique-sum (PermSet.inPS nil) t
  }
| f_sec => \lam a => zro-right

\func MPoly_Fin-suc {n : Nat} {R : CRing} : QEquiv {MPoly (Fin (suc n)) R} {Poly (MPoly (Fin n) R)} \cowith
  | f => f
  | ret => ret
  | ret_f => \case \elim __ \with {
    | in~ l => retHom.func-BigSum *> pmap AddMonoid.BigSum (exts (\lam j => unfold $ unfold m-func $ cases (l j).2)) *> msMonomial_BigSum-split
  }
| f_sec => f_sec
  \where {
    \open MonoidSet

    \func var-func (j : Fin (suc n)) : Poly (MPoly (Fin n) R) 
      | 0 => padd 1 0
      | suc j => padd 0 (mVar j)

    \func f-monomial (x : PermSet (Fin (suc n))) : Poly (MPoly (Fin n) R) 
      | in~ l => Monoid.BigProd (map var-func l)
      | ~-equiv l l' r => CMonoid.BigProd_EPerm (EPerm.EPerm_map var-func r)

    \lemma f-monomial_+ {x y : PermSet (Fin (suc n))} : f-monomial (x * y) = f-monomial x * f-monomial y => {?hidden_proof}

    \func m-func (s : \Sigma R (PermSet (Fin (suc n)))) => msMonomial s.1 ide *c f-monomial s.2

    \func m-func-coh {l l' : Array (\Sigma R (PermSet (Fin (suc n))))} (e : l ~ l') : AddMonoid.BigSum (map m-func l) = AddMonoid.BigSum (map m-func l') \elim e
      | ~-perm e => AbMonoid.BigSum_EPerm (EPerm.EPerm_map m-func e)
      | ~-sym e => inv (m-func-coh e)
      | ~-zro {m} idp => pmap (+ _) $ pmap (*c _) (monoidSet-ext $ ~-pequiv (~-zro idp)) *> LModule.*c_zro-left
      | ~-+ m idp idp => pmap (+ _) (pmap (*c _) (later msMonomial_+) *> *c-rdistr) *> +-assoc

    \func fHom : RingHom (MPoly (Fin (suc n)) R) (PolyRing (MPoly (Fin n) R)) f \cowith
      | func-+ => \lam {x} {y} => (\case \elim x, \elim y \with {
        | in~ l, in~ l' => pmap AddMonoid.BigSum (map_++ m-func) *> AddMonoid.BigSum_++
      })
      | func-ide => simplify
      | func-* => \lam {x} {y} => (\case \elim x, \elim y \with {
        | in~ l, in~ l' =>
          pairs.pairs-distr m-func (\lam {a} {b} => pmap2 *c msMonomial_* f-monomial_+ *> *c-assoc {_} {msMonomial a.1 ide} *> pmap (_ *c) *c-comm-right *> *c-comm-left)
      })

    \lemma ret-aux {p : Poly (MPoly (Fin n) R)} {e : MPoly (Fin n) R} : ret (e *c p) = monoidSet-map (permSet-map fsuc) id e * ret p => {?hidden_proof}

    \func retHom : RingHom (PolyRing (MPoly (Fin n) R)) (MPoly (Fin (suc n)) R) ret \cowith
      | func-zro => idp
      | func-+ => func-+
      | func-ide => idp
      | func-* => func-*

    \lemma ret_eval (p : Poly (MPoly (Fin n) R)) {a : R} (l : Array R n) : mPolyEval l (polyEval p (msMonomial a ide)) = mPolyEval (a :: l) (ret p) => {?hidden_proof}

    \lemma f_eval (p : MPoly (Fin (suc n)) R) {a : R} (l : Array R n) : mPolyEval l (polyEval (f p) (msMonomial a ide)) = mPolyEval (a :: l) p => {?hidden_proof}

    \lemma f_polyMap {S : CRing} {p : MPoly (Fin (suc n)) R} {g : RingHom (MPoly (Fin n) R) (MPoly (Fin n) S)} (h : AddMonoidHom R S) 
    (g-var : \Pi (j : Fin n) -> g (mVar j) = mVar j) (g-const : \Pi (a : R) -> g (msMonomial a ide) = msMonomial (h a) ide) :
      polyMap g (f p) = f (mPoly-map h p) => {?hidden_proof}
  }


\lemma MPoly-surj {J : \Set} {R S : CRing} (f : AddMonoidHom R S) (fs : IsSurj f) : IsSurj (mPoly-map {J} f) => {?hidden_proof}

\func MPoly_Fin-suc' {n : Nat} {R : CRing} : QEquiv {MPoly (Fin (suc n)) R} {MPoly (Fin n) (PolyAlgebra R)} \cowith
  | f => fHom
  | ret => retHom
  | ret_f => mPolyRingHom-unique (retHom ∘ fHom) id (\lam r => simplify)
    (\case \elim __ \with {  | 0 => simplify $ monoidSet-ext $ ~-pequiv (~-perm $ later $ eperm-swap idp idp idp) *> ~-pequiv (~-zro idp)
    | suc j => simplify})
  | f_sec => mPolyRingHom-unique (fHom ∘ retHom) id (polyMapEval-unique (fHom ∘ retHom ∘ mPolyHom) mPolyHom (\lam r => simplify) (pmap fHom retHom_mConst *> fHom_mVar)) 
    (\lam j => simplify)
  \where {
    \func fHom {R : CRing} : RingHom (MPoly (Fin (suc n)) R) (MPoly (Fin n) (PolyAlgebra R)) 
      => mPolyMapEvalRingHom (mPolyHom ∘ polyHom) $ later (mConst (padd 1 0) :: mkArray (\lam j => mVar j))

    \func retHom {R : CRing} : RingHom (MPoly (Fin n) (PolyAlgebra R)) (MPoly (Fin (suc n)) R) 
      => mPolyMapEvalRingHom (polyMapEvalRingHom mPolyHom (mVar (0 : Fin (suc n)))) (\lam j => mVar (fsuc j))

    \lemma retHom_mConst : retHom (mConst (padd 1 R.zro)) = mVar (0 : Fin (suc n)) => {?hidden_proof}

    \lemma fHom_mVar : fHom (mVar (0 : Fin (suc n))) = mConst (padd 1 R.zro) => {?hidden_proof}

    \lemma map-comm {R S : CRing} (f : RingHom R S) {p : MPoly (Fin n) (PolyAlgebra R)} : mPoly-map f (retHom p) = retHom (mPoly-map (polyMapRingHom f) p) => {?hidden_proof}

    \lemma eval-comm {R : CRing} {p : MPoly (Fin n) (PolyAlgebra R)} {a : R} {l : Array R n} : mPolyEval (a :: l) (retHom p) = mPolyEval l (mPoly-map (polyEvalRingHom a) p) 
      => {?hidden_proof}

    \lemma mapEval-comm {R S : CRing} (f : RingHom R S) {p : MPoly (Fin (suc n)) R} {a : S} {l : Array (Poly R) n} :
      polyMapEval f (mPolyEval l (fHom p)) a = mPolyMapEval f p (a :: map (polyMapEval f __ a) l) => {?hidden_proof}
  }


\func mdegree< {J : \Set} {R : CRing} (p : MPoly J R) (d : Nat) : \Prop \elim p
  | in~ l : Array => ∃ (l' : Array (\Sigma R (PermSetMonoid J))) (inMS~ l = inMS~ l') ∀ (s : l') (permSet-length s.2 < d)
  | ~-equiv l l' r => ext (TruncP.map __ (\lam s => (s.1, inv (~-pequiv r) *> s.2, s.3)), TruncP.map __ (\lam s => (s.1, ~-pequiv r *> s.2, s.3)))

\lemma mdegree<_map {J : \Set} {R E : CRing} {f : AddMonoidHom R E} {p : MPoly J R} {d : Nat} (pd : mdegree< p d) : mdegree< (mPoly-map f p) d => {?hidden_proof}

\lemma mdegree<-exists {J : \Set} {R : CRing} (p : MPoly J R) : ∃ (d : Nat) (mdegree< p d) => {?hidden_proof}

\lemma mdegree<0 {J : \Set} {R : CRing} {p : MPoly J R} (d : mdegree< p 0) : p = zro => {?hidden_proof}

\func decMdegree {J : DecSet} {R : CRing.Dec} (p : DecMonoidSet (PermSet J) R) : Nat \elim p
  | in~ s => Big ∨ 0 (map (\lam t => permSet-length t.2) s.1)
  | ~-equiv x y r => AbMonoid.BigSum_EPerm {BottomJoinSemilattice.toMonoid NatBSemilattice} $ EPerm.EPerm_map (\lam t => permSet-length t.2) r

\func mdegree {J : DecSet} {R : CRing.Dec} (p : MPoly J R) : Nat => decMdegree (monoidSetDec-equiv.ret p)

\lemma mdegree_mdegree< {J : DecSet} {R : CRing.Dec} {p : MPoly J R} : mdegree< p (suc (mdegree p)) => {?hidden_proof}