\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ring
\import Algebra.Ring.Ideal
\import Algebra.Ring.RingHom
\import Arith.Nat
\import Function
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.LinearOrder
\import Paths
\import Paths.Meta
\open Monoid(LDiv, Inv)
\open equation(cRing)

\class ReducedRing \extends Ring {
  | isReduced {a : E} : a * a = 0 -> a = 0
}

\class ReducedCRing \extends ReducedRing, CRing

\class PPRing \extends ReducedCRing {
  | isPPRing (a : E) : ∃ (u : E) (a = u * a) ∀ {x} (a * x = 0 -> u * x = 0)
  | isReduced => \lam {a} aa=0 => (\case isPPRing a \with {
    | inP s => s.2 *> s.3 aa=0
  })
}

\class ImpotentRing \extends ReducedRing, NonZeroRing {
  | isImpotent {a : E} : a * a = a -> (a = 0) || (a = 1)
}
  \where {
    \func subring {R : Ring} {E : ImpotentRing} (f : RingHom R E) (inj : IsInj f) : ImpotentRing {
      | Ring => R
    } \cowith
      | zro/=ide => \lam p => E.zro/=ide $ inv f.func-zro *> pmap f p *> f.func-ide
      | isReduced => \lam aa=0 => inj $ isReduced (inv f.func-* *> pmap f aa=0 *> f.func-zro) *> inv f.func-zro
      | isImpotent => \lam aa=a => (\case isImpotent (inv f.func-* *> pmap f aa=a) \with {
        | byLeft fa=0 => byLeft $ inj (fa=0 *> inv f.func-zro)
        | byRight fa=1 => byRight $ inj (fa=1 *> inv f.func-ide)
      })
  }


\class ImpotentCRing \extends ImpotentRing, ReducedCRing, NonZeroCRing
  \where {
    \func subring {R : CRing} {E : ImpotentRing} (f : RingHom R E) (inj : IsInj f) : ImpotentCRing {
      | CRing => R
    } \cowith
      | ImpotentRing => ImpotentRing.subring f inj
  }
