\import Algebra.Field
\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Ideal
\import Algebra.Ring.MPoly
\import Algebra.Ring.Poly ()
\import Algebra.Ring.Sub
\import Algebra.Semiring
\import Arith.Int
\import Arith.Nat
\import Category
\import Function (IsInj, IsSurj)
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Paths
\import Paths.Meta

\lemma *-addMonoidHom-left {R : PseudoSemiring} {a : R} : AddMonoidHom R R (a *) => {?hidden_proof}

\lemma *-addMonoidHom-right {R : PseudoSemiring} {a : R} : AddMonoidHom R R (* a) => {?hidden_proof}

\record SemiringHom \extends AddMonoidHom, MonoidHom {
  \override Dom : Semiring
  \override Cod : Semiring

  \lemma func-natCoef {n : Nat} : func (natCoef n) = natCoef n => {?hidden_proof}
}

\lemma *-addGroupHom-left {R : PseudoRing} {a : R} : AddGroupHom R R (a *) => {?hidden_proof}

\lemma *-addGroupHom-right {R : PseudoRing} {a : R} : AddGroupHom R R (* a) => {?hidden_proof}

\record RingHom \extends SemiringHom, AddGroupHom {
  \override Dom : Ring
  \override Cod : Ring

  \protected \func Kernel : TIdeal Dom \cowith
    | SubAddGroup => AddGroupHom.Kernel
    | ideal-left => {?hidden_proof}
    | ideal-right => {?hidden_proof}

  \protected \func Image : SubRing Cod \cowith
    | SubRing => ringHomImage _

  \protected \func image : RingHom (SubRing.IRing {Image}) Cod \cowith
    | func => \lam x => x.1
    | func-+ => {?hidden_proof}
    | func-ide => {?hidden_proof}
    | func-* => {?hidden_proof}
    \where {
      \lemma isInj : IsInj image => {?hidden_proof}

      \lemma isSurj (s : IsSurj func) : IsSurj image => {?hidden_proof}
    }

}
  \where {
    \func equals {R S : Ring} {f g : RingHom R S} (p : \Pi (x : R) -> f x = g x) : f = g => exts p

    \func id {R : Ring} : RingHom R R \cowith
      | func => \lam x => x
      | func-ide => {?hidden_proof}
      | func-+ => {?hidden_proof}
      | func-* => {?hidden_proof}

    \func \fixl 8 compose \alias \infixl 8 ∘ {R S T : Ring} (g : RingHom S T) (f : RingHom R S) : RingHom R T \cowith
      | func => \lam x => g (f x)
      | func-ide => {?hidden_proof}
      | func-+ => {?hidden_proof}
      | func-* => {?hidden_proof}

    \lemma contr-isTerm {R S : Ring} (c : Contr S) : Contr (RingHom R S) => {?hidden_proof}

    \lemma field-isInj {K : Field} {R : NonZeroRing} {f : RingHom K R} : IsInj f => {?hidden_proof}

    \type isAlgebraGenerated {R E : CRing} (f : RingHom R E) (l : Array E) : \Prop => \Pi (x : E) -> ∃ (p : MPoly (Fin l.len) R) (x = mPolyEval l (mPoly-map f p))

    \type isFiniteAlgebra {R E : CRing} (f : RingHom R E) : \Prop => ∃ (l : Array E) (isAlgebraGenerated f l)

    \open Algebra.Ring.Poly

    \lemma isAlgebraGenerated-comp {R E S : CRing} {f : RingHom R E} {g : RingHom E S} {a : E} {l : Array S} (fg : \Pi (x : E) -> ∃ (p : Poly R) (polyMapEval f p a = x)) 
    (gg : isAlgebraGenerated g l) : isAlgebraGenerated (g ∘ f) (g a :: l) => {?hidden_proof}

    \lemma isAlgebraGenerated-poly {R E : CRing} {f : RingHom R E} {a : E} (fg : \Pi (x : E) -> ∃ (p : Poly R) (polyMapEval f p a = x)) : isAlgebraGenerated f (a :: nil) => {?hidden_proof}

    \func KernelC {R : CRing} {S : Ring} (f : RingHom R S) : Ideal R \cowith
      | TIdeal => f.Kernel

    \func ImageC {R : Ring} {S : CRing} (f : RingHom R S) : CSubRing S \cowith
      | SubRing => ringHomImage f
  }


\func natMap {R : Semiring} : SemiringHom NatSemiring R \cowith
  | func => natCoef
  | func-+ {n m : Nat} : R.natCoef (n + m) = natCoef n + natCoef m => {?hidden_proof}
  | func-zro => {?hidden_proof}
  | func-ide => {?hidden_proof}
  | func-* {n m : Nat} : R.natCoef (n * m) = natCoef n * natCoef m => {?hidden_proof}

\lemma natComm {R : Semiring} (n : Nat) (x : R) : natMap n * x = x * natMap n => {?hidden_proof}

\func intMap {R : Ring} : RingHom IntRing R \cowith
  | func => intCoef
  | func-+ {x y : Int} : R.intCoef (x + y) = intCoef x + intCoef y => {?hidden_proof}
  | func-ide => {?hidden_proof}
  | func-* {x y : Int} : R.intCoef (x * y) = intCoef x * intCoef y => {?hidden_proof}
  \where {
    \open AddGroup (negative_zro, negative_+)
    \open Ring

    \lemma intCoef_diff {R : Ring} (n m : Nat) : R.intCoef (n Nat.- m) = intCoef n - intCoef m => {?hidden_proof}
  }


\lemma intComm {R : Ring} (n : Int) (x : R) : intMap n * x = x * intMap n => {?hidden_proof}