\import Algebra.Group
\import Algebra.Group.Sub
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Algebra.Semiring.Sub
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Paths
\import Paths.Meta

\class SubPseudoRing \extends SubPseudoSemiring, SubAddGroup {
  \override S : PseudoRing
}
  \where {
    \func cStruct {R : PseudoCRing} (S : SubPseudoRing R) : PseudoCRing \cowith
      | PseudoRing => S.IPseudoRing
      | *-comm => ext *-comm
  }


\class SubRing \extends SubPseudoRing, SubSemiring {
  \override S : Ring
}
  \where {
    \func cStruct {R : CRing} (S : SubRing R) : CRing \cowith
      | Ring => S.IRing
      | PseudoCRing => SubPseudoRing.cStruct S

    \func max {R : Ring} : SubRing \cowith
      | SubSemiring => SubSemiring.max {R}
      | SubAddGroup => SubAddGroup.max

    \lemma isContr {R : Ring} {S : SubRing R} (c : Contr R) : Contr S.IRing => {?hidden_proof}

    \lemma comm-isContr {R : CRing} {S : SubRing R} (c : Contr R) : Contr (cStruct S) => {?hidden_proof}
  }


\class CSubRing \extends SubRing {
  \override S : CRing
}

\func ringHomImage (f : RingHom) : SubRing f.Cod \cowith
  | contains => \lam y => ∃ (x : f.Dom) (f x = y)
  | contains_zro => inP (0, f.func-zro)
  | contains_+ => \lam inP (x1, p1) inP (x2, p2) => inP (x1 + x2, f.func-+ *> pmap2 + p1 p2)
  | contains_ide => inP (1, f.func-ide)
  | contains_* => \lam inP (x1, p1) inP (x2, p2) => inP (x1 * x2, f.func-* *> pmap2 * p1 p2)
  | contains_negative => \lam inP (x, p) => inP (negative x, f.func-negative *> pmap negative p)