\import Algebra.Group
\import Algebra.Group.Sub
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Algebra.Semiring.Sub
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Paths
\import Paths.Meta

\class SubPseudoRing \extends SubPseudoSemiring, SubAddGroup {
  \override S : PseudoRing

  \func IPseudoRing : PseudoRing \cowith
    | PseudoSemiring => IPseudoSemiring
    | AbGroup => SubAddGroup.abStruct \this
}
  \where {
    \func cStruct {R : PseudoCRing} (S : SubPseudoRing R) : PseudoCRing \cowith
      | PseudoRing => S.IPseudoRing
      | *-comm => {?hidden_proof}
  }


\class SubRing \extends SubPseudoRing, SubSemiring {
  \override S : Ring

  \func IRing : Ring \cowith
    | Semiring => ISemiring
    | AbGroup => SubAddGroup.abStruct \this

  \func corestrict {R : Ring} (f : RingHom R S) (p : \Pi (x : R) -> contains (f x)) : RingHom R IRing \cowith
    | func => \lam x => (f x, p x)
    | func-+ => {?hidden_proof}
    | func-ide => {?hidden_proof}
    | func-* => {?hidden_proof}

  \func embed : RingHom IRing S \cowith
    | func => __.1
    | func-+ => {?hidden_proof}
    | func-ide => {?hidden_proof}
    | func-* => {?hidden_proof}
}
  \where {
    \func cStruct {R : CRing} (S : SubRing R) : CRing \cowith
      | Ring => S.IRing
      | PseudoCRing => SubPseudoRing.cStruct S

    \func max {R : Ring} : SubRing \cowith
      | SubSemiring => SubSemiring.max {R}
      | SubAddGroup => SubAddGroup.max

    \lemma isContr {R : Ring} {S : SubRing R} (c : Contr R) : Contr S.IRing => {?hidden_proof}

    \lemma comm-isContr {R : CRing} {S : SubRing R} (c : Contr R) : Contr (cStruct S) => {?hidden_proof}
  }


\class CSubRing \extends SubRing {
  \override S : CRing

  \func ICRing : CRing \cowith
    | Ring => SubRing.IRing
    | *-comm => {?hidden_proof}
}

\func ringHomImage (f : RingHom) : SubRing f.Cod \cowith
  | contains => \lam y => ∃ (x : f.Dom) (f x = y)
  | contains_zro => {?hidden_proof}
  | contains_+ => {?hidden_proof}
  | contains_ide => {?hidden_proof}
  | contains_* => {?hidden_proof}
  | contains_negative => {?hidden_proof}