\import Algebra.Algebra
\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Module
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Function.Meta
\import Paths
\import Paths.Meta

\instance UnitAlgebra (R : CRing) (A : PseudoAlgebra R) : AAlgebra R (\Sigma R A) 
  | zro => (0, 0)
  | + => \lam s t => (s.1 + t.1, s.2 + t.2)
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | * => \lam (a, x) (b, y) => (a * b, a *c y + b *c x + x * y)
  | *-assoc => {?hidden_proof}
  | ldistr => {?hidden_proof}
  | rdistr => {?hidden_proof}
  | negative => \lam (a, x) => (negative a, negative x)
  | negative-left => {?hidden_proof}
  | *c => \lam a (b, x) => (a * b, a *c x)
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  | *c-comm-left => {?hidden_proof}
  | *c-comm-right => {?hidden_proof}
  | ide => (1, 0)
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  | coefMap => \lam a => (a, 0)
  | coefMap_*c => {?hidden_proof}
  \where {
    \lemma *n-comm {a : R} {x : A} {n : Nat} : n AddMonoid.*n {UnitAlgebra R A} (a, x) = (n R.*n a, n A.*n x) => {?hidden_proof}

    \lemma *n-comm1 {a : R} {x : A} {n : Nat} : (n AddMonoid.*n {UnitAlgebra R A} (a, x)).1 = n R.*n a => {?hidden_proof}

    \lemma *n-comm2 {a : R} {x : A} {n : Nat} : (n AddMonoid.*n {UnitAlgebra R A} (a, x)).2 = n A.*n x => {?hidden_proof}
  }


\func unit-algebra {R : CRing} {A : PseudoAlgebra R} : AddGroupHom A (UnitAlgebra R A) \cowith
  | func => \lam x => (0, x)
  | func-+ => {?hidden_proof}

\instance UnitCAlgebra (R : CRing) (A : PseudoCAlgebra R) : CAlgebra R 
  | AAlgebra => UnitAlgebra R A
  | *-comm => {?hidden_proof}