dist: trusty

language: java

sudo: false

jdk:
  - oraclejdk11

branches:
  only:
    - master
    - dev
    - travis

install:
  - git clone https://github.com/JetBrains/Arend.git ../Arend

script: ./gradlew check --no-daemon --info --stacktrace -Pkotlin.incremental=false -Dkotlin.daemon.jvm.options=-Xmx1024m

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/jars-3/
  - rm -fr $HOME/.gradle/caches/6.3/
  - rm -fr $HOME/.gradle/caches/journal-1/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
