\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Operations
\import Order.Directed
\import Order.Lattice
\import Order.PartialOrder
\import Paths.Meta
\import Set.Subset
\import Topology.TopSpace

\instance TopSpaceHasProduct : HasProduct TopSpace 
  | Product => ProductTopSpace

\instance ProductTopSpace (X Y : TopSpace) : TopSpace (\Sigma X Y) 
  | isOpen => \lam W => ∀ {s : W} ∃ (U : X.isOpen) (U s.1) (V : Y.isOpen) (V s.2) ∀ {x : U} {y : V} (W (x, y))
  | open-top => \lam _ => inP (top, open-top, (), top, open-top, (), \lam _ _ => ())
  | open-inter => \lam {W} {W'} f g (Ws, W's) => (\case f Ws, g W's \with {
    | inP (U, Uo, Ux, V, Vo, Vy, h), inP (U', U'o, U'x, V', V'o, V'y, h') =>
      inP (U ∧ U', open-inter Uo U'o, (Ux, U'x), V ∧ V', open-inter Vo V'o, (Vy, V'y), \lam (Ux, U'x) (Vy, V'y) => (h Ux Vy, h' U'x V'y))
  })
  | open-Union => \lam So inP (W, SW, Ws) => (\case So SW Ws \with {
    | inP (U, Uo, Ux, V, Vo, Vy, h) => inP (U, Uo, Ux, V, Vo, Vy, \lam Ux Vy => inP (W, SW, h Ux Vy))
  })
  \where {
    \open ContMap

    \func proj1 {X Y : TopSpace} : ContMap (X ⨯ Y) X \cowith
      | func => \lam s => s.1
      | func-cont => \lam Uo => \lam Ux => inP (_, Uo, Ux, top, open-top, (), \lam Ux _ => Ux)

    \func proj2 {X Y : TopSpace} : ContMap (X ⨯ Y) Y \cowith
      | func => \lam s => s.2
      | func-cont => \lam Uo => \lam Uy => inP (top, open-top, (), _, Uo, Uy, \lam _ Uy => Uy)

    \func tuple {X Y Z : TopSpace} (f : ContMap X Y) (g : ContMap X Z) : ContMap X (Y ⨯ Z) \cowith
      | func => \lam x => (f x, g x)
      | func-cont => \lam {W} Wo => X.cover-open (\lam w => (\case Wo w \with {
        | inP (U, Uo, Ufx, V, Vo, Vgx, h) => inP (_, open-inter (f.func-cont Uo) (g.func-cont Vo), (Ufx, Vgx), \lam (Ufx, Vgx) => h Ufx Vgx)}))

    \func prod {X X' Y Y' : TopSpace} (f : ContMap X Y) (f' : ContMap X' Y') : ContMap (X ⨯ X') (Y ⨯ Y') => tuple (f ∘ proj1) (f' ∘ proj2)
      \where {
        \lemma isDense {X X' Y Y' : TopSpace} {f : ContMap X Y} {g : ContMap X' Y'} (fd : f.IsDense) (gd : g.IsDense) : ContMap.IsDense {prod f g} => {?hidden_proof}

        \lemma isWeaklyDense {X X' Y Y' : TopSpace} {f : ContMap X Y} {g : ContMap X' Y'} (fd : f.IsWeaklyDense) (gd : g.IsWeaklyDense) : ContMap.IsWeaklyDense {prod f g} => {?hidden_proof}

        \lemma isEmbedding {X X' Y Y' : TopSpace} {f : ContMap X Y} {g : ContMap X' Y'} (fd : f.IsTopEmbedding) (gd : g.IsTopEmbedding) : ContMap.IsTopEmbedding {prod f g} => {?hidden_proof}

        \lemma isDenseEmbedding {X X' Y Y' : TopSpace} {f : ContMap X Y} {g : ContMap X' Y'} (fd : f.IsDenseTopEmbedding) (gd : g.IsDenseTopEmbedding) :
          ContMap.IsDenseTopEmbedding {prod f g} => {?hidden_proof}
      }

  }


\lemma Prod-open {X Y : TopSpace} {U : Set X} (Uo : isOpen U) {V : Set Y} (Vo : isOpen V) : isOpen (Set.Prod U V) => {?hidden_proof}

\lemma contAt-tuple {X Y Z : TopSpace} {f : X -> Y} {g : X -> Z} {x : X} (fc : IsContAt f x) (gc : IsContAt g x) : IsContAt (\lam x => (f x, g x)) x => {?hidden_proof}

\lemma limit-tuple {I : DirectedSet} {X Y : TopSpace} {f : I -> X} {x : X} (fl : X.IsLimit f x) {g : I -> Y} {y : Y} (gl : Y.IsLimit g y) :
  TopSpace.IsLimit (\lam n => (f n, g n)) (x, y) => {?hidden_proof}

\lemma cont2-limit {I : DirectedSet} {X Y Z : TopSpace} {f : I -> X} {g : I -> Y} {lx : X} {ly : Y} (px : X.IsLimit f lx) (py : Y.IsLimit g ly) (h : ContMap (X ⨯ Y) Z) :
  Z.IsLimit (\lam n => h (f n, g n)) (h (lx, ly)) => {?hidden_proof}

\lemma denseSet_<= {X : TopSpace} {Y : HausdorffTopSpace} {P : JoinSemilattice Y} (jc : ContMap (Y ⨯ Y) Y (\lam s => s.1 ∨ s.2)) {S : Set X} (Sd : IsDenseSet S) 
(f g : ContMap X Y) (p : \Pi {x : X} -> S x -> f x <= g x) {x : X} : f x <= g x => {?hidden_proof}

\lemma dense_<= {X Y : TopSpace} {Z : HausdorffTopSpace} {P : JoinSemilattice Z} (jc : ContMap (Z ⨯ Z) Z (\lam s => s.1 ∨ s.2)) (f : ContMap X Y) (fd : f.IsDense) 
(g h : ContMap Y Z) (p : \Pi (x : X) -> g (f x) <= h (f x)) (y : Y) : g y <= h y => {?hidden_proof}

\lemma weaklyDenseSet_<= {X : TopSpace} {Y : StronglyHausdorffTopSpace} {P : JoinSemilattice Y} (jc : ContMap (Y ⨯ Y) Y (\lam s => s.1 ∨ s.2)) {S : Set X} 
(Sd : IsWeaklyDenseSet S) (f g : ContMap X Y) (p : \Pi {x : X} -> S x -> f x <= g x) {x : X} : f x <= g x => {?hidden_proof}

\lemma weaklyDense_<= {X Y : TopSpace} {Z : StronglyHausdorffTopSpace} {P : JoinSemilattice Z} (jc : ContMap (Z ⨯ Z) Z (\lam s => s.1 ∨ s.2)) (f : ContMap X Y) 
(fd : f.IsWeaklyDense) (g h : ContMap Y Z) (p : \Pi (x : X) -> g (f x) <= h (f x)) (y : Y) : g y <= h y => {?hidden_proof}

\lemma hausdorff-char {X : TopSpace} : (\Pi {x y : X} -> ∀ {U V : isOpen} (U x) (V y) ∃ (U ∧ V) -> x = y) <-> (ProductTopSpace X X).IsClosed (\lam s => s.1 = s.2) => {?hidden_proof}