\import Equiv
\import Function.Meta
\import InfCat.Objects
\import Paths
\import Paths.Meta

\data CatPushout {A B C : \Cat} (f : A ->⁺ B) (g : A ->⁺ C)
  | cinl (b :⁺ B)
  | cinr (c :⁺ C)
  | cglue (a :⁺ A) : cinl (f a) = cinr (g a)
  \where {
    \protected \func rec {Z : \Cat} (lm : B ->⁺ Z) (rm : C ->⁺ Z) (gm : \Pi (a :⁺ A) -> lm (f a) = rm (g a)) (x :⁺ CatPushout f g) : Z \elim x
      | cinl b => lm b
      | cinr c => rm c
      | cglue a => gm a

    \protected \func elim {Z :⁺ CatPushout f g ->⁺ \Cat}
                          (lm :⁺ \Pi (b :⁺ B) -> Z (cinl b)) (rm :⁺ \Pi (c :⁺ C) -> Z (cinr c))
                          (gm :⁺ \Pi (a :⁺ A) -> Path (\lam i => Z (cglue a i)) (lm (f a)) (rm (g a)))
                          (x :⁺ CatPushout f g) : Z x \elim x
      | cinl b => lm b
      | cinr c => rm c
      | cglue a => gm a

    \protected \func elim-equiv {D : CatPushout f g ->⁺ \Cat}
      : QEquiv {Ob (\Pi (w :⁺ CatPushout f g) -> D w)}
               {\Sigma (u : \Pi (y :⁺ B) -> D (cinl y))
                       (v : \Pi (z :⁺ C) -> D (cinr z))
                       (\Pi (x :⁺ A) -> Path (\lam i => D (cglue x i)) (u (f x)) (v (g x)))}
      \cowith
      | f h => (\lam y => unob h (cinl y), \lam z => unob h (cinr z), \lam x => path \lam i => unob h (cglue x i))
      | ret s => ob (elim s.1 s.2 s.3)
      | ret_f (ob h) => pmap ob $ ext \case \elim __ \with {
        | cinl y => idp
        | cinr z => idp
        | cglue x i => idp
      }
      | f_sec s => idp
  }
