\import Equiv
\import Function.Meta
\import InfCat.Basics
\import InfCat.Equiv
\import InfCat.FullyFaithful
\import InfCat.Objects
\import InfCat.Paths
\import InfCat.Rezk
\import Logic
\import Meta

\func IsGroupoid (C : \Cat) : \Prop
  => \Pi {x y : C} (f : x ~> y) -> IsIso f

\lemma groupoid-char {C : \Cat} : IsGroupoid C <-> (\Pi (x y : C) -> IsEquiv {x = y} =_~>)
  => (\lam cg x y => IsEquiv.fromEmbSurj (=_~>-embedding x y) \lam f => IsIso-char.1 (cg f),
      \lam cg {x} {y} f => IsIso-char.2 $ inP (IsEquiv.ret (cg x y) f, IsEquiv.f_ret (cg x y)))

\lemma type-groupoid {X : \Type} : IsGroupoid X
  => \lam f => inP (=_~> $ inv (~>_= f),
                    pmap (comp _) (inv ~>_=_~>) *> =_~>_comp *> pmap =_~> inv_*>,
                    pmap (comp __ _) (inv ~>_=_~>) *> =_~>_comp *> pmap =_~> *>_inv)

\func type_ob {X : \Type} : QEquiv {X} {Ob X} \cowith
  | f => ob
  | ret => unob
  | ret_f x => idp
  | f_sec y => idp

\lemma cat_ob {C : \Cat} (Cg : IsGroupoid C) : IsHEquiv {Ob C} {C} unob
  => ff-surj-equiv.1 (\lam x y => later $ propExt.dir (IsEquiv.parallelEquiv {x = y} (inP =_~>-equiv) (groupoid-char.1 Cg x.1 y.1) \case \elim y, \elim __ \with {
    | _, idp => idp
  }) (inP unob_=), \lam y => inP (ob y, idp))