\import Equiv
\import Paths

\data Ob (C : \Cat)
  | ob C

\func unob {C : \Cat} (x :⁺ Ob C) : C \elim x
  | ob x => x

\func ob_unob {C : \Cat} (x : Ob C) : ob (unob x) = x \elim x
  | ob x => idp

\sfunc pmap_ob_unob {C : \Cat} {x y : Ob C} (p : x = y) : pmap ob (pmap unob p) = ob_unob x *> p *> inv (ob_unob y) \elim p
  | idp => inv (pmap (_ *>) idp_*> *> *>_inv)

\func unob_= {C : \Cat} {x y : Ob C} : QEquiv {x = y} {unob x = unob y} \elim x, y
  | ob x, ob y => \new QEquiv {
    | f => pmap unob
    | ret => pmap ob
    | ret_f p => pmap_ob_unob p *> idp_*>
    | f_sec => idpe
  }