\import Equiv
\import Function.Meta
\import InfCat.Fibration.Straightening
\import InfCat.Functor.Equiv
\import InfCat.Functor.FullyFaithful
\import InfCat.Paths
\import InfCat.Resizing
\import InfCat.SubCat.Full
\import InfCat.Yoneda.CovariantYoneda
\import Logic
\import Logic.Meta
\import Paths
\import Paths.Meta

\type Op.{u} (C : \Cat u) : \Cat u
  => ResizeFromObjects {OpLarge C} OpLargeOb-equiv OpLarge-hom
  \where {
    \private \func OpLarge.{u} (C : \Cat u)
      => FullSubCat {C ->⁺ \Type u} \lam F => ∃ (x : C) (F = ReprFunctor x)

    \private \func OpLargeOb.{u} {C : \Cat u} (x : C) : OpLarge C
      => FullSubCat.make (ReprFunctor x) $ inP (x,idp)

    \private \sfunc OpLargeOb-equiv.{u} {C : \Cat u} : QEquiv (OpLargeOb {C})
      => IsEquiv.toQEquiv $ IsEquiv.fromEmbSurj
          (leftEmbedding (IsFFMap.isObEmbedding FullSubCat.inc-ff) ReprFunctor-embedding)
          \lam y => \case FullSubCat.inc-con {_} {_} {y} \with {
            | inP (x,p) => inP (x, ((IsFFMap.isObEmbedding FullSubCat.inc-ff).isEmb (OpLargeOb x) y).sec (inv p))
          }

    \private \sfunc OpLarge-hom.{u} {C : \Cat u} (x y : C) : QEquiv {y ~> x} {OpLargeOb x ~> OpLargeOb y}
      => yonedaEmbCov `transQEquiv` symQEquiv (IsEquiv.toQEquiv (FullSubCat.inc-ff _ _))

    \private \lemma OpLarge-equiv.{u} {C : \Cat u} : IsHEquiv {OpLarge C} {Op C} (\lam x => resizeCat x)
      => inP \new HQEquiv {
        | finv (resizeCat x) => x
        | finv_f x => idp
        | f_finv (resizeCat x) => idp
      }

    \sfunc Hom.{u} {C : \Cat u} (x :⁺ Op C) (y :⁺ C) : \Type u
      => FullSubCat.inc (IsHEquiv.ret OpLarge-equiv x) y

    \lemma Hom-ff.{u} {C : \Cat u} : IsFFMap (Hom {C})
      => transportInv IsFFMap (ext \lam x y => \peval Hom x y) $
          ffMap-comp (ff-surj-equiv.2 (IsHEquiv.ret-equiv OpLarge-equiv)).1 FullSubCat.inc-ff

    \sfunc OpOb.{u} {C : \Cat u} (x : C) : Op C
      => resizeCat (OpLargeOb x)

    \lemma OpOb-equiv.{u} {C : \Cat u} : IsEquiv (OpOb {C})
      => transportInv IsEquiv (ext \lam x => \peval OpOb x) $
          IsEquiv.trans (inP OpLargeOb-equiv) (IsHEquiv.toIsEquiv OpLarge-equiv)

    \sfunc Hom-char.{u} {C : \Cat u} {x : C} : Hom (OpOb x) = ReprFunctor x
      => ext \lam y => (\peval Hom _ y)
          *> pmap+ (FullSubCat.inc {C ->⁺ \Type u} __ y)
                   (pmap (IsHEquiv.ret OpLarge-equiv __) (\peval OpOb x) *> IsHEquiv.ret_f OpLarge-equiv)
  }