\import Equiv
\import Function.Meta
\import InfCat.Fibration.LeftKanType
\import InfCat.Fibration.Straightening
\import InfCat.Functor.Equiv
\import InfCat.Functor.FullyFaithful
\import InfCat.Paths
\import InfCat.Resizing
\import InfCat.SubCat.Full
\import InfCat.Yoneda.CovariantYoneda
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta

\type Op.{u} (C : \Cat u) : \Cat u
  => ResizeFromObjects {OpLarge C} OpLargeOb-equiv OpLarge-hom
  \where {
    \private \func OpLarge.{u} (C : \Cat u)
      => FullSubCat {C ->⁺ \Type u} \lam F => ∃ (x : C) (F = ReprFunctor x)

    \private \func OpLargeOb.{u} {C : \Cat u} (x : C) : OpLarge C
      => FullSubCat.make (ReprFunctor x) $ inP (x,idp)

    \private \sfunc OpLargeOb-equiv.{u} {C : \Cat u} : QEquiv (OpLargeOb {C})
      => IsEquiv.toQEquiv $ IsEquiv.fromEmbSurj
          (leftEmbedding (IsFFMap.isObEmbedding FullSubCat.inc-ff) ReprFunctor-embedding)
          \lam y => \case FullSubCat.inc-con {_} {_} {y} \with {
            | inP (x,p) => inP (x, ((IsFFMap.isObEmbedding FullSubCat.inc-ff).isEmb (OpLargeOb x) y).sec (inv p))
          }

    \private \sfunc OpLarge-hom.{u} {C : \Cat u} (x y : C) : QEquiv {y ~> x} {OpLargeOb x ~> OpLargeOb y}
      => symQEquiv $ IsEquiv.toQEquiv $ IsEquiv.trans (FullSubCat.inc-ff _ _) yonedaEmbCov

    \private \lemma OpLarge-equiv.{u} {C : \Cat u} : IsHEquiv {OpLarge C} {Op C} (\lam x => resizeCat x)
      => inP \new HQEquiv {
        | finv (resizeCat x) => x
        | finv_f x => idp
        | f_finv (resizeCat x) => idp
      }

    \func toLarge.{u} {C : \Cat u} (x :⁺ Op C) : OpLarge C \elim x
      | resizeCat x => x

    \func Hom.{u} {C : \Cat u} (x :⁺ Op C) (y :⁺ C) : \Type u
      => FullSubCat.inc (toLarge x) y

    \lemma Hom-ff.{u} {C : \Cat u} : IsFFMap (Hom {C})
      => ffMap-comp (ff-surj-equiv.2 $ inP $ later \new HQEquiv {
        | finv x => resizeCat x
        | finv_f (resizeCat x) => idp
        | f_finv => idpe
      }).1 FullSubCat.inc-ff

    \func toOp.{u} {C : \Cat u} (x : C) : Op C
      => resizeCat (OpLargeOb x)

    \lemma toOp-equiv.{u} {C : \Cat u} : IsEquiv (toOp {C})
      => IsEquiv.trans (inP OpLargeOb-equiv) (IsHEquiv.toIsEquiv OpLarge-equiv)

    -- | The identity of {x} as an element of `Hom (toOp x) x`.
    \func Hom-idd.{u} {C : \Cat u} (x : C) : Hom (toOp x) x
      => Straight.toStraight idd
  }

\sfunc OpFunc.{u} {C : \Cat u} {D : \Cat u} (f : C ->⁺ D) (x :⁺ Op C) : Op D
  => pair.1 x
  \where {
    \private \sfunc pair
      => ffMap-lift Op.Hom-ff (\lam x => LeftKanExtType f (Op.Hom x))
          \lam x' => \case IsEquiv.isSurj Op.toOp-equiv x' \with {
            | inP (x,p) => inP (Op.toOp (f x), ext (\lam b => inv LeftKanExtType_ReprFunctor) *> pmap (LeftKanExtType f) (pmap Op.Hom p))
          }

    \protected \sfunc char : Op.Hom (OpFunc f x) = LeftKanExtType f (Op.Hom x)
      => pmap+ Op.Hom (\peval OpFunc f x) *> pair.2 x
  }