\import Algebra.Monoid
\import Algebra.Pointed.PointedHom
\import Logic
\import Paths
\import Paths.Meta
\import Set.Fin

\record MonoidHom \extends PointedHom {
  \override Dom : Monoid
  \override Cod : Monoid
  | func-* {x y : Dom} : func (x * y) = func x * func y

  \lemma func-pow {x : Dom} {n : Nat} : func (Monoid.pow x n) = Monoid.pow (func x) n => {?hidden_proof}

  \lemma func-BigProd {l : Array Dom} : func (Monoid.BigProd l) = Monoid.BigProd (\lam j => func (l j)) => {?hidden_proof}

  \lemma func-LDiv {a b : Dom} (d : Monoid.LDiv a b) : Monoid.LDiv (func a) (func b) (func d.inv) => {?hidden_proof}

  \lemma func-Inv {a : Dom} (d : Monoid.Inv a) : Monoid.Inv (func a) (func d.inv) => {?hidden_proof}
}
  \where {
    \func equals {M N : Monoid} {f g : MonoidHom M N} (p : \Pi (x : M) -> f x = g x) : f = g => exts p

    \func id {M : Monoid} : MonoidHom M M \cowith
      | func => \lam x => x
      | func-ide => {?hidden_proof}
      | func-* => {?hidden_proof}

    \open Monoid (Inv)

    \func presInv (h : MonoidHom) (e : Inv {h.Dom}) : Inv (h e) \cowith
      | inv => h e.inv
      | inv-left => {?hidden_proof}
      | inv-right => {?hidden_proof}

    \lemma presInvElem (h : MonoidHom) (e : Inv {h.Dom}) (e' : Inv (h e)) : h e.inv = e'.inv => {?hidden_proof}
  }


\record AddMonoidHom \extends AddPointedHom {
  \override Dom : AddMonoid
  \override Cod : AddMonoid
  | func-+ {x y : Dom} : func (x + y) = func x + func y

  \lemma func-BigSum {l : Array Dom} : func (AddMonoid.BigSum l) = AddMonoid.BigSum (\lam j => func (l j)) => {?hidden_proof}

  \lemma func-*n {n : Nat} {x : Dom} : func (n AddMonoid.*n x) = n AddMonoid.*n func x => {?hidden_proof}
}
  \where {
    \use \coerce toMonoidHom (f : AddMonoidHom) : MonoidHom \cowith
      | Dom => f.Dom
      | Cod => f.Cod
      | func => f
      | func-* => {?hidden_proof}
      | func-ide => {?hidden_proof}

    \func id {M : AddMonoid} : AddMonoidHom M M \cowith
      | func => \lam x => x
      | func-zro => {?hidden_proof}
      | func-+ => {?hidden_proof}

    \lemma func-FinSum {A B : AbMonoid} (f : AddMonoidHom A B) {J : FinSet} {a : J -> A} : f (A.FinSum a) = B.FinSum (\lam j => f (a j)) => {?hidden_proof}
  }
