\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed.PointedCategory
\import Algebra.Pointed.PointedHom
\import Category
\import Category.Adjoint
\import Category.Functor
\import Category.Limit
\import Category.Meta
\import Logic
\import Logic.FirstOrder.Algebraic
\import Logic.FirstOrder.Algebraic.Category
\import Logic.FirstOrder.Term
\import Paths
\import Paths.Meta
\import Set.SetCategory
\import Set.Fin
\import Set.Fin.Instances

\instance MonoidCat : Cat Monoid 
  | Hom => \lam M N => MonoidHom M N
  | id => \lam _ => MonoidHom.id
  | o => \lam {x y z : Monoid} (g : MonoidHom y z) (f : MonoidHom x y) => \new MonoidHom {
    | func => \lam x => g (f x)
    | func-ide => pmap g f.func-ide *> g.func-ide
    | func-* => pmap g f.func-* *> g.func-*
  }
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  | univalence => {?hidden_proof}
  \where {
    \func forget : Functor MonoidCat SetCat \cowith
      | F => \lam R => R
      | Func => \lam f => f
      | Func-id => {?hidden_proof}
      | Func-o => {?hidden_proof}
  }


\instance MonoidBicat : BicompleteCat 
  | Cat => MonoidCat
  | limit => CompletePrecat.applyEquiv catEquiv
  | colimit => CocompletePrecat.applyEquiv catEquiv
  \where {
    \instance theory : Theory 
      | Sort => \Sigma
      | Symb => \lam _ => Fin 2
      | domain => \case __ \with {
        | 0 => nil
        | 1 => () :: () :: nil
      }
    | PredSymb => Empty
    | predDomain => absurd
    | axioms => arraySubset {Sequent {\this}}
      ((\lam _ => \Sigma, finSet, nil, equality (apply 1 (apply 0 nil :: var () :: nil)) (var ()))
    :: (\lam _ => \Sigma, finSet, nil, equality (apply 1 (var () :: apply 0 nil :: nil)) (var ())) ::  (\lam _ => Fin 3, finSet, nil, 
    equality (apply 1 (apply 1 (var 0 :: var 1 :: nil) :: var 2 :: nil)) (apply 1 (var 0 :: apply 1 (var 1 :: var 2 :: nil) :: nil))) :: nil)

    \func catEquiv : CatEquiv (ModelCat theory) MonoidCat modToMonoid \cowith
      | Func => \lam (f : ModelHom) => \new MonoidHom {
        | func => f.funcs
        | func-ide => f.func-op 0 nil
        | func-* => \lam {x} {y} => f.func-op 1 (x :: y :: nil)
      }
      | Func-id => {?hidden_proof}
      | Func-o => {?hidden_proof}
      | LAdj => monoidToMod.functor
      | eta {
        | trans => \lam M => id M
        | natural => \lam f => idp
      }
      | eta-iso => {?hidden_proof}
      | epsilon {
        | trans => \lam M => \new ModelHom {
          | funcs => \lam x => x
          | func-op => \case \elim __ \with {
            | 0 => \lam d => idp
            | 1 => \lam d => idp
          }
        | func-rel => \case __ \with {}
        }
        | natural => \lam f => idp
      }
      | eta_epsilon-left => {?hidden_proof}
      | eta_epsilon-right => {?hidden_proof}
      | epsilon-iso => {?hidden_proof}

    \func modToMonoid (M : Model theory) : Monoid (M ()) \cowith
      | ide => operation 0 nil
      | * => \lam x y => operation 1 (x :: y :: nil)
      | ide-left => {?hidden_proof}
      | ide-right => {?hidden_proof}
      | *-assoc => {?hidden_proof}

    \func monoidToMod (M : Monoid) : Model theory (\lam _ => M) \cowith
      | operation => \case \elim __ \with {
        | 0 => \lam _ => M.ide
        | 1 => \lam l => l 0 * l 1
      }
    | relation => \case __ \with {}
    | isModel => {?hidden_proof}
      \where {
        \func functor : Functor MonoidCat (ModelCat theory) monoidToMod \cowith
          | Func => \lam (f : MonoidHom) => \new ModelHom {
            | funcs => f
            | func-op => \case \elim __ \with {
              | 0 => \lam _ => f.func-ide
              | 1 => \lam d => f.func-*
            }
          | func-rel => \case __ \with {}
          }
          | Func-id => {?hidden_proof}
          | Func-o => {?hidden_proof}
      }

  }


\instance AddMonoidCat : Cat AddMonoid 
  | Hom => \lam M N => AddMonoidHom M N
  | id => \lam _ => AddMonoidHom.id
  | o => \lam g f => \new AddMonoidHom {
    | func => \lam x => g (f x)
    | func-zro => pmap g func-zro *> func-zro
    | func-+ => pmap g func-+ *> func-+
  }
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  | univalence => {?hidden_proof}
  \where {
    \func forget : Functor AddMonoidCat SetCat \cowith
      | F => \lam R => R
      | Func => \lam f => f
      | Func-id => {?hidden_proof}
      | Func-o => {?hidden_proof}
  }


\instance KerAddMonoid (f : AddMonoidHom) : AddMonoid 
  | AddPointed => KerAddPointed f
  | + => \lam a b => (a.1 + b.1, func-+ *> pmap2 + a.2 b.2 *> zro-left)
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}

\func KerMonoidHom (f : AddMonoidHom) : AddMonoidHom (KerAddMonoid f) f.Dom \cowith
  | AddPointedHom => KerPointedHom f
  | func-+ => {?hidden_proof}

\instance KerAbMonoid {A : AbMonoid} (f : AddMonoidHom A) : AbMonoid (Kernel f) 
  | AddMonoid => KerAddMonoid f
  | +-comm => {?hidden_proof}

\instance ImageAddMonoid (f : AddMonoidHom) : AddMonoid 
  | AddPointed => ImageAddPointed f
  | + => \lam a b => (a.1 + b.1, \case a.2, b.2 \with {  | inP t, inP s => inP (t.1 + s.1, func-+ *> pmap2 + t.2 s.2)})
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}

\instance ImageMonoid (f : MonoidHom) : Monoid 
  | Pointed => ImagePointed f
  | * => \lam a b => (a.1 * b.1, \case a.2, b.2 \with {  | inP t, inP s => inP (t.1 * s.1, func-* *> pmap2 * t.2 s.2)})
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  | *-assoc => {?hidden_proof}

\func ImageMonoidLeftHom (f : MonoidHom) : MonoidHom f.Dom (ImageMonoid f) \cowith
  | PointedHom => ImagePointedLeftHom f
  | func-* => {?hidden_proof}

\func ImageMonoidRightHom (f : MonoidHom) : MonoidHom (ImageMonoid f) f.Cod \cowith
  | PointedHom => ImagePointedRightHom f
  | func-* => {?hidden_proof}

\func ImageAddMonoidLeftHom (f : AddMonoidHom) : AddMonoidHom f.Dom (ImageAddMonoid f) \cowith
  | AddPointedHom => ImageAddPointedLeftHom f
  | func-+ => {?hidden_proof}

\func ImageAddMonoidRightHom (f : AddMonoidHom) : AddMonoidHom (ImageAddMonoid f) f.Cod \cowith
  | AddPointedHom => ImageAddPointedRightHom f
  | func-+ => {?hidden_proof}

\instance ImageAbMonoid {A : AddMonoid} {B : AbMonoid} (f : AddMonoidHom A B) : AbMonoid 
  | AddMonoid => ImageAddMonoid f
  | +-comm => {?hidden_proof}