\import Algebra.Monoid
\import Algebra.Pointed
\import Arith.Fin.Order
\import Data.List
\import Function.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set \hiding (#)

\data MonoidTerm (V : \Type) 
  | var V
  | :ide
  | \infixl 7 :* (t s : MonoidTerm V)

\protected \func normalize {V : \Type} (t : MonoidTerm V) => aux t nil
  \where {
    \func aux {V : \Type} (t : MonoidTerm V) (acc : List V) : List V \elim t
      | var v => v :: acc
      | :ide => acc
      | :* t s => aux t (aux s acc)
  }


\class MonoidData {M : Monoid} (vars : Array M) {
\meta V => Fin vars.len

  \protected \func interpret (t : MonoidTerm V) : M \elim t
    | var x => vars x
    | :ide => ide
    | :* t s => interpret t * interpret s

  \func interpretNF (l : List V) : M \elim l
    | nil => ide
    | :: x nil => vars x
    | :: x l => vars x * interpretNF l
    \where {
      \lemma cons (x : V) (l : List V) : interpretNF (x :: l) = vars x * interpretNF l => {?hidden_proof}
    }


  \protected \lemma normalize-consistent (t : MonoidTerm V) : interpret t = interpretNF (normalize t) => {?hidden_proof}
    \where {
      \lemma aux (t : MonoidTerm V) (acc : List V) : interpret t * interpretNF acc = interpretNF (normalize.aux t acc) => {?hidden_proof}
    }


  \protected \lemma terms-equality (t s : MonoidTerm V) (p : interpretNF (normalize t) = interpretNF (normalize s)) : interpret t = interpret s => {?hidden_proof}

  \lemma terms-equality-conv (t s : MonoidTerm V) (p : interpret t = interpret s) : interpretNF (normalize t) = interpretNF (normalize s) => {?hidden_proof}

  \protected \lemma interpretNF_++ (l1 l2 : List V) : interpretNF (l1 ++ l2) = interpretNF l1 * interpretNF l2 => {?hidden_proof}

  \protected \lemma replace-consistent (l : List V) (i s : Nat) (r : List V) (p : interpretNF (slice l i s) = interpretNF r) : interpretNF l = interpretNF (replace l i s r) => {?hidden_proof}
}

\class CMonoidData \extends MonoidData {
  \override M : CMonoid

  \lemma sort-consistent (l : List V) : interpretNF l = interpretNF (sort l) => {?hidden_proof}

  \protected \lemma perm-consistent {l l' : List V} (p : Perm l l') : interpretNF l = interpretNF l' => {?hidden_proof}

  \protected \lemma normalize-consistent (t : MonoidTerm V) : interpret t = interpretNF (sort (normalize t)) => {?hidden_proof}

  \protected \lemma terms-equality (t s : MonoidTerm V) (p : interpretNF (sort (normalize t)) = interpretNF (sort (normalize s))) : interpret t = interpret s => {?hidden_proof}

  \lemma terms-equality-conv (t s : MonoidTerm V) (p : interpret t = interpret s) : interpretNF (sort (normalize t)) = interpretNF (sort (normalize s)) => {?hidden_proof}

  \protected \lemma replace-consistent (l : List V) (is : List Nat) (r : List V) (p : interpretNF (indices is l) = interpretNF r) : interpretNF l = interpretNF (r ++ removeIndices is l) => {?hidden_proof}

  \protected \lemma replace-consistent-lem (is : List Nat) (l : List V) : interpretNF l = interpretNF (indices is l ++ removeIndices is l) => {?hidden_proof}
}
  \where {
    \open MonoidData
    \open Sort
    \open Sort.RedBlack

    \func indices {A : \Type} (is : List Nat) (l : List A) : List A \elim is, l
      | nil, _ => nil
      | :: _ _, nil => nil
      | :: 0 is, :: a l => a :: indices is l
      | :: suc n is, :: _ l => indices (n :: is) l

    \func removeIndices {A : \Type} (is : List Nat) (l : List A) : List A \elim is, l
      | nil, l => l
      | :: _ _, nil => nil
      | :: 0 is, :: a l => removeIndices is l
      | :: suc n is, :: a l => a :: removeIndices (n :: is) l
  }


\class LData \extends CMonoidData {L : TopMeetSemilattice} {
  | M => L

  \func removeDuplicates (l : List V) : List V \elim l
    | nil => nil
    | :: a nil => a :: nil
    | :: a :: a' _ \as l => \case decideEq a a' \with {
      | yes _ => removeDuplicates l
      | no _ => a :: removeDuplicates l
    }

  \lemma removeDuplicates-consistent (l : List V) : interpretNF l = interpretNF (removeDuplicates l) => {?hidden_proof}

  \protected \lemma normalize-consistent (t : MonoidTerm V) : interpret t = interpretNF (removeDuplicates (RedBlack.sort (normalize t))) => {?hidden_proof}

  \protected \lemma terms-equality (t s : MonoidTerm V) (p : interpretNF (removeDuplicates (RedBlack.sort (normalize t))) = interpretNF (removeDuplicates (RedBlack.sort (normalize s)))) : interpret t = interpret s 
    => {?hidden_proof}

  \lemma terms-equality-conv (t s : MonoidTerm V) (p : interpret t = interpret s) :
    interpretNF (removeDuplicates (RedBlack.sort (normalize t))) = interpretNF (removeDuplicates (RedBlack.sort (normalize s))) => {?hidden_proof}
}
  \where {
    \open MonoidData
    \open Sort
  }
