\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Algebra.Pointed.Sub
\import Algebra.Ring.Localization ()
\import Arith.Nat
\import Data.Array
\import Function.Iterate
\import Logic
\import Logic.Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set

\class SubSemigroup \extends SubSet {
  \override S : Semigroup
  | contains_* {x y : S} : contains x -> contains y -> contains (x * y)

  \func ISemigroup : Semigroup \cowith
    | BaseSet => ISet
    | * => \lam x y => (x.1 * y.1, contains_* x.2 y.2)
    | *-assoc => {?hidden_proof}
}
  \where {
    \func cStruct {A : CSemigroup} (S : SubSemigroup A) : CSemigroup \cowith
      | Semigroup => S.ISemigroup
      | *-comm => {?hidden_proof}
  }


\class SubMonoid \extends SubPointed, SubSemigroup {
  \override S : Monoid

  \func IMonoid : Monoid \cowith
    | Pointed => IPointed
    | Semigroup => ISemigroup
    | ide-left => {?hidden_proof}
    | ide-right => {?hidden_proof}

  \lemma contains_pow {x : S} (s : contains x) {n : Nat} : contains (Monoid.pow x n) => {?hidden_proof}

  \lemma sub-pow {x : IMonoid} {n : Nat} : (IMonoid.pow x n).1 = Monoid.pow x.1 n => {?hidden_proof}

  \func embedMonoid : MonoidHom IMonoid S \cowith
    | func => __.1
    | func-ide => {?hidden_proof}
    | func-* => {?hidden_proof}
}
  \where {
    \func cStruct {A : CMonoid} (S : SubMonoid A) : CMonoid \cowith
      | Monoid => S.IMonoid
      | CSemigroup => SubSemigroup.cStruct S

    \func max {A : Monoid} : SubMonoid \cowith
      | SubPointed => SubPointed.max {A}
      | contains_* => {?hidden_proof}

    \func closure {M : Monoid} (S : SubSet M) : SubMonoid M \cowith
      | contains => \lam x => ∃ (n : Nat) (iterr apl n S x)
      | contains_ide => {?hidden_proof}
      | contains_* => {?hidden_proof}
      \where {
        \open Algebra.Ring.Localization

        \lemma ext {M : Monoid} (S : SubSet M) : S <= closure S => {?hidden_proof}

        \lemma univ (S' : SubMonoid M) (p : S <= S') (x : M) (q : closure S x) : S' x => {?hidden_proof}

        \func apl {M : Monoid} (S : SubSet M) : SubSet M \cowith
          | contains => \lam x => S x || (x = 1) || (\Sigma (y z : M) (S y) (S z) (x = y * z))

        \lemma apl-inc {n m : Nat} (q : n <= m) (x : M) (p : iterr apl n S x) : iterr apl m S x => {?hidden_proof}
          \where {
            \lemma alt (n m : Nat) (x : M) (p : iterr apl n S x) : iterr apl (n + m) S x => {?hidden_proof}
          }

      }


    \func powers {M : Monoid} (a : M) : SubMonoid M \cowith
      | contains => \lam x => ∃ (n : Nat) (M.pow a n = x)
      | contains_ide => {?hidden_proof}
      | contains_* => {?hidden_proof}
  }


\class DecSubMonoid \extends SubMonoid, DecSubPointed {
  \override S : Monoid
}

\class SubAddMonoid \extends SubAddPointed {
  \override S : AddMonoid
  | contains_+ {x y : S} : contains x -> contains y -> contains (x + y)

  \func IAddMonoid : AddMonoid \cowith
    | AddPointed => IAddPointed
    | + => \lam x y => (x.1 + y.1, contains_+ x.2 y.2)
    | zro-left => {?hidden_proof}
    | zro-right => {?hidden_proof}
    | +-assoc => {?hidden_proof}

  \lemma sub-BigSum {l : Array IAddMonoid} : (IAddMonoid.BigSum l).1 = AddMonoid.BigSum (map __.1 l) => {?hidden_proof}
}
  \where {
    \func abStruct {A : AbMonoid} (S : SubAddMonoid A) : AbMonoid \cowith
      | AddMonoid => S.IAddMonoid
      | +-comm => {?hidden_proof}

    \func max {A : AddMonoid} : SubAddMonoid \cowith
      | SubAddPointed => SubAddPointed.max {A}
      | contains_+ => {?hidden_proof}
  }
