\import Algebra.Meta
\import Category
\import Category.Functor
\import Paths
\import Paths.Meta

\func commaPrecat {C D E : Precat} (F : Functor C E) (G : Functor D E) : Precat \cowith
  | Ob => \Sigma (x : C) (y : D) (Hom (F x) (G y))
  | Hom => \lam (x, y, a) (x', y', a') => \Sigma (f : Hom x x') (g : Hom y y') (a' ∘ F.Func f = G.Func g ∘ a)
  | id => \lam (x, y, a) => (id x, id y, pmap (a ∘) Func-id *> id-right *> inv (pmap (∘ a) Func-id *> id-left))
  | o => \lam (f, g, p) (f', g', p') => (f ∘ f', g ∘ g', pmap (_ ∘) Func-o *> inv o-assoc *> pmap (∘ _) p *> o-assoc *> pmap (_ ∘) p' *> inv o-assoc *> pmap (∘ _) (inv Func-o))
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  \where {
    \lemma leftForget {C D E : Precat} (F : Functor C E) (G : Functor D E) : Functor (commaPrecat F G) C __.1 __.1 => {?hidden_proof}

    \lemma rightForget {C D E : Precat} (F : Functor C E) (G : Functor D E) : Functor (commaPrecat F G) D __.2 __.2 => {?hidden_proof}

    \func functor {C D E : Precat} (F F' : Functor C E) (G G' : Functor D E) (a : NatTrans F' F) (b : NatTrans G G') : Functor (commaPrecat F G) (commaPrecat F' G') \cowith
      | F => \lam (x, y, s) => (x, y, b y ∘ s ∘ a x)
      | Func => \lam (f, g, c) => (f, g, rewriteEq (inv (b.natural g), inv c, a.natural f) equation)
      | Func-id => {?hidden_proof}
      | Func-o => {?hidden_proof}
  }


\func commaCat {C D : Cat} {E : Precat} (F : Functor C E) (G : Functor D E) : Cat \cowith
  | Precat => commaPrecat F G
  | univalence => {?hidden_proof}