\import Category
\import Category.Comma
\import Category.Functor
\import Category.Limit
\import Function.Meta
\import Meta
\import Paths
\import Paths.Meta

\func LeftKanExt {C C' : SmallPrecat} {D : CocompletePrecat} (p : Functor C C') (F : Functor C D) : Functor C' D => Functor.op {RightKanExt D.op p.op F.op}

\func RightKanExt {C C' : SmallPrecat} (D : CompletePrecat) (p : Functor C C') (F : Functor C D) : Functor C' D \cowith
  | F => \lam c' => lim F c'
  | Func => \lam {x} {y} f => limMap {lim F y} (Cone.premap (commaFunctor f) (lim F x))
  | Func-id => {?hidden_proof}
  | Func-o => {?hidden_proof}
  \where {
    \open Limit

    \func lim {C C' : SmallPrecat} {D : CompletePrecat} {p : Functor C C'} (F : Functor C D) (b : C') 
      => D.limit (Comp F (commaPrecat.rightForget (Const {TrivialCat} b) p))

    \func commaFunctor {C C' : SmallPrecat} {p : Functor C C'} {x y : C'} (f : Hom y x) => commaPrecat.functor (Const {TrivialCat} x) (Const y) p p (Const.natTrans f) (id p)

\class DoubleLimit {
      | J : SmallPrecat
      | C : SmallPrecat
      | C' : SmallPrecat
      | D : CompletePrecat
      | p : Functor C C'
      | F : Functor C D
      | G : Functor J C'
    }
  }
