\import Category
\import Category.Functor
\import Paths
\import Paths.Meta

\type ObOver {C : Precat} (x : C) => \Sigma (y : C) (Hom y x)

\instance SlicePrecat {C : Precat} (x : C) : Precat (ObOver x) 
  | Hom => \lam (y, f) (z, g) => \Sigma (h : Hom y z) (g ∘ h = f)
  | id => \lam (y, f) => (id y, id-right)
  | o => \lam (h1, p1) (h2, p2) => (h1 ∘ h2, inv o-assoc *> pmap (∘ h2) p1 *> p2)
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  \where {
    \lemma forget {C : Precat} (x : C) : FaithfulFunctor (SlicePrecat x) C __.1 __.1 => {?hidden_proof}
  }


\instance SliceCat {C : Cat} (x : C) : Cat 
  | Precat => SlicePrecat x
  | univalence => {?hidden_proof}