\import Category
\import Function.Meta
\import Paths
\import Paths.Meta

\data CatTerm {V : \Type} (a b : V) (H : V -> V -> \Type) 
  | var (H a b)
  | :id (a = b)
  | :o (c : V) (CatTerm c b H) (CatTerm a c H)

\data CatNF {V : \Type} (a b : V) (H : V -> V -> \Type) 
  | :nil (a = b)
  | \infixl 7 :cons {c : V} (H c b) (CatNF a c H)

\func normalize {V : \Type} {a b : V} {H : V -> V -> \Type} (t : CatTerm a b H) : CatNF a b H => aux t (:nil idp)
  \where {
    \func aux {V : \Type} {a b c : V} {H : V -> V -> \Type} (t : CatTerm b c H) (acc : CatNF a b H) : CatNF a c H \elim t
      | var h => h :cons acc
      | :id idp => acc
      | :o _ t s => aux t (aux s acc)
  }


\class HData {
  | C : Precat
  | V : \Set
  | f : V -> C
  | H : V -> V -> \Set
  | g : \Pi {x y : V} -> H x y -> Hom (f x) (f y)
}