\import Category
\import Category.Adjoint
\import Category.Functor
\import Category.Limit
\import Equiv
\import Function.Meta
\import Homotopy.Fibration
\import Meta
\import Paths
\import Paths.Meta

\func subPrecat {C : Precat} {X : \hType obj} (f : X -> C) : Precat X \cowith
  | Hom => \lam x y => Hom (f x) (f y)
  | id => \lam x => id (f x)
  | o => \lam h g => o h g
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  \where {
    \func embedding {C : Precat} {X : \hType obj} (f : X -> C) : FullyFaithfulFunctor (subPrecat f) C f \cowith
      | Func => \lam h => h
      | Func-id => {?hidden_proof}
      | Func-o => {?hidden_proof}
      | isFullyFaithful => {?hidden_proof}

    \func pred {C : Precat} (P : C -> \Prop) => subPrecat (Total.proj P)
      \where {
        \func embedding {C : Precat} (P : C -> \Prop) => subPrecat.embedding (Total.proj P)
      }


    \func funcLift {C D : Precat} {X : \hType} (f : X -> D) (g : C -> X) (G : Functor C D) (p : \Pi {a : C} -> Iso {D} {f (g a)} {G a}) : Functor C (subPrecat f) g \cowith
      | Func => \lam h => p.hinv ∘ G.Func h ∘ p.f
      | Func-id => {?hidden_proof}
      | Func-o => {?hidden_proof}
  }


\func subCat {C : Cat} {X : \hType obj} (e : Embedding {X} {C}) : Cat \cowith
  | Precat => subPrecat e
  | univalence => {?hidden_proof}

\lemma subCat-iso {C : Precat} {X : \hType obj} {f : X -> C} (e : Iso {subPrecat f}) : Iso {C} {f e.dom} {f e.cod} e => {?hidden_proof}
  \where {
    \protected \lemma conv {C : Precat} {X : \hType obj} {f : X -> C} {x x' : X} (e : Iso {C} {f x} {f x'}) : Iso {subPrecat f} {x} {x'} e => {?hidden_proof}
  }


\class ReflectiveSubPrecat \extends FullyFaithfulFunctor, RightAdjointUnit {
  | reflector : D -> C
  | reflectorMap (X : D) : Hom X (F (reflector X))
  \field isReflective {X : D} {Y : C} : Equiv {Hom (reflector X) Y} {Hom X (F Y)} (Func __ ∘ reflectorMap X)
  | LAdj {
    | F => reflector
    | Func => \lam {X} {Y} h => isReflective.ret (reflectorMap Y ∘ h)
    | Func-id => rewrite id-right (unfold (rewrite (Func-id, id-left) idp) *> isReflective.ret_f (id _))
    | Func-o => run {(isReflective.isInj, unfold, rewrite (isReflective.f_ret, Func-o, o-assoc, isReflective.f_ret), rewriteI {2} o-assoc, rewrite isReflective.f_ret, 
      inv o-assoc)}
  }
  | eta {
    | trans => reflectorMap
    | natural => \lam h => inv (isReflective.f_ret _)
  }
  | eta-adjoint => isReflective
}
  \where {
    \func fromRightAdjoint (F : RightAdjoint) {ff : FullyFaithfulFunctor {  | Functor => F}} : ReflectiveSubPrecat \cowith
      | FullyFaithfulFunctor => ff
      | reflector => F.LAdj
      | reflectorMap => F.eta
      | isReflective => {?hidden_proof}
  }


\func reflectiveSubPrecatColimit {J : Precat} (I : ReflectiveSubPrecat) (F : Functor J I.C) (c : Colimit (Comp I F)) : Limit F.op \cowith
  | apex => I.reflector c.apex
  | coneMap => \lam j => I.inverse (reflectorMap _ ∘ c.coneMap j)
  | coneCoh => {?hidden_proof}
  | limMap => \lam {z} c' => I.isReflective.ret (c.limMap (Cone.map I.op {J.op} c'))
  | limBeta => {?hidden_proof}
  | limUnique => {?hidden_proof}