\import Algebra.Domain
\import Algebra.Field
\import Algebra.Field.Splitting
\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.LatticeColimit
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Algebra.Ring.Integral
\import Algebra.Ring.Poly
\import Algebra.Semiring
\import Arith.Nat
\import Category
\import Data.Array
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.TFAE
\import Meta
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\import Set.SetCategory
\import Set.SetHom
\import Set.Countable

\type IsAlgebraicallyClosed (K : Ring) => \Pi {p : Poly K} -> ∃ (n : Nat) (n /= 0) (degree<= p n) (polyCoef p n = 1) -> ∃ (a : K) (polyEval p a = 0)

\lemma algebraicallyClosed<->split {K : CRing} : TFAE (IsAlgebraicallyClosed K, \Pi {p : Poly K} -> isMonic p -> ∃ (l : Array K) (p = Monoid.BigProd (map (\lam a => padd 1 (negative a)) l)), 
  \Pi {p : Poly K} (n : Nat) -> degree<= p n -> polyCoef p n = 1 -> ∃ (l : Array K n) (p = Monoid.BigProd (map (\lam a => padd 1 (negative a)) l))) => {?hidden_proof}
  \where {
    \lemma aux {K : CRing} (ac : IsAlgebraicallyClosed K) {p : Poly K} {n : Nat} (pd : degree<= p n) (pc : polyCoef p n = 1) :
      ∃ (l : Array K n) (p = Monoid.BigProd (map (\lam a => padd 1 (negative a)) l)) => {?hidden_proof}
  }


\lemma algebraicallyClosed-integrallyClosed {K : CRing} (ac : IsAlgebraicallyClosed K) {E : StrictIntegralDomain} (f : RingHom K E) : isIntegrallyClosed f => {?hidden_proof}

\type IsAlgebraicClosure (f : RingHom) => \Sigma (IsAlgebraicallyClosed f.Cod) (isIntegralExt f)

\lemma algebraicClosure-split {K : CRing} {E : StrictIntegralDomain} (f : RingHom K E) (fi : isIntegralExt f) 
(c : \Pi {p : Poly K} -> isMonic p -> ∃ (l : Array E) (polyMap f p = Monoid.BigProd (map (\lam a => padd 1 (negative a)) l))) : IsAlgebraicClosure f => {?hidden_proof}

\sfunc countableAlgebraicClosure {k : DiscreteField} (c : Countable k) : \Sigma (K : DiscreteField) (f : RingHom k K) (IsAlgebraicClosure f) => 
  \let | ps n => pointed-countable zro (Poly.poly-countable c) n
       | S => sequence c ps
       | sf n => countableSplittingField (S n).2 {polyMap (S n).3 (ps n)}
       | F => NatFunctor (\lam n => (S n).1) (\lam {n} => (sf n).3)
       | E => DiscreteFieldLatticeColimit {NatBSemilattice} F (\lam n => (S n).1)
       | h n => RingLatticeColimit.inMap {_} {F} n
  \in (E, h 0,
        algebraicClosure-split {_} {E} _  (later (\lam in~ (n, a) => (  \let t => integral_image-comp (RingLatticeColimit.inMap {_} {F} n) ((S n).4 a)
  \in transportInv {RingHom k E} (isIntegral __ _) 
        (later $ exts (\lam a => SetColimit.~-cequiv zero<=_ $ pmap (NatFunctor.natHom {CRingCat} __ _) (NatFunctor.sigma-isProp _ _) *> sequence3)) t)))
  (\lam {p} pm => (\case pointed-countable-surj zro (Poly.poly-countable c) p \with {
  | inP (n, q) => \case splitting-monic {_} {_} {polyMap (S n).3 (ps n)} (rewrite q $ polyMap_isMonic pm) (sf n).4 \with {
    | inP (l, _, lq) => inP (map (h (suc n)) l,  later rewrite q  (pmap {RingHom (F 0) (CRingLatticeColimit F)} (polyMap __ p) {h 0} {h (suc n) ∘ ((sf n).3 ∘ (S n).3)} 
                (exts (\lam a => SetColimit.~-cequiv zero<=_ $ pmap (sf n).3 $ pmap (NatFunctor.natHom {CRingCat} __ a) (NatFunctor.sigma-isProp _ _) *> sequence3)) 
      *> inv (polyMap-comp (_ RingHom.∘ _) (h _)) *> pmap (polyMap _) (inv (later $ polyMap-comp _ _))) *> pmap (polyMapRingHom _) lq *> 
    (polyMapRingHom (h (suc n))).func-BigProd *> pmap Monoid.BigProd 
    (exts (\lam j => pmap2 (\lam x y => padd (padd pzero x) y) func-ide AddGroupHom.func-negative)))  }}))
)
  \where {
    \func sequence {k : DiscreteField} (kc : Countable k) (f : Nat -> Poly k) (n : Nat) : \Sigma (K : DiscreteField) (Countable K) (g : RingHom k K) (isIntegralExt g) \elim n
      | 0 => (k, kc, id k, integralExt_id)
      | suc n => 
        \let | (K, Kc, g, gi) => sequence kc f n
             | t => countableSplittingField Kc {polyMap g (f n)}
        \in (t.1, t.2, t.3 RingCat.∘ g, integralExt-comp _ _ gi $ splitting-integral (countableSplittingField Kc).4)

    \lemma sequence3 {k : DiscreteField} {kc : Countable k} {f : Nat -> Poly k} {n : Nat} {a : k} :
    NatFunctor.natHom {CRingCat} {_} {\lam {n} => (countableSplittingField (sequence kc f n).2 {polyMap (sequence kc f n).3 (f n)}).3} {0} (n, idp) a = (sequence kc f n).3 
      a => {?hidden_proof}
  }
