\import Algebra.Field
\import Algebra.Field.Algebraic
\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring.Integral
\import Algebra.Ring.RingHom
\import Algebra.Ring.Factor
\import Algebra.Ring.MPoly
\import Algebra.Ring.Poly
\import Algebra.Ring.Poly.Euclidean
\import Algebra.Semiring
\import Arith.Nat
\import Category
\import Data.Array
\import Function.Meta($)
\import Logic
\import Logic.Meta
\import Meta
\import Order.LinearOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\import Set.Countable
\open Monoid

\type IsSplittingField {k K : DiscreteField} (p : Poly k) (f : RingHom k K) 
  => ∃ (l : Array K) (c : K) (RingHom.isAlgebraGenerated f l) (polyMap f p = c PolyRing.*c Monoid.BigProd (map (\lam a => padd 1 (negative a)) l))

\lemma splitting-integral {k K : DiscreteField} {p : Poly k} {f : RingHom k K} (s : IsSplittingField p f) : isIntegralExt f => {?hidden_proof}

\lemma splitting-monic {k K : DiscreteField} {p : Poly k} (pm : isMonic p) {f : RingHom k K} (s : IsSplittingField p f) :
  ∃ (l : Array K) (RingHom.isAlgebraGenerated f l) (polyMap f p = Monoid.BigProd (map (\lam a => padd 1 (negative a)) l)) => {?hidden_proof}

countableSplittingField {k : DiscreteField} (c : Countable k) {p : Poly k} : \Sigma (K : DiscreteField) (Countable K) (f : RingHom k K) (IsSplittingField p f) 
  => CountableSplittingFieldData.makeSplittingField c ()
  \where {
\class RootFieldData {
      | P : DiscreteField -> \Set
      | k : DiscreteField
      | p : Poly k
      | RootField : DiscreteField
      | RootFieldP : P RootField
      | rootFieldHom : RingHom k RootField
      | root : RootField
      | isRoot : polyMapEval rootFieldHom p root = 0
      | RootField-gen (x : RootField) : ∃ (q : Poly k) (polyMapEval rootFieldHom q root = x)
    }

\class SplittingFieldData {
      | P : DiscreteField -> \Set
      | S : \Pi {K : DiscreteField} -> Poly K -> \Prop
      | S-hom : \Pi {K K' : DiscreteField} (f : RingHom K K') {p : Poly K} -> S p -> S (polyMap f p)
      | S-factor : \Pi {K : DiscreteField} {p q : Poly K} -> S (p * q) -> S p
      | nextField : \Pi {K : DiscreteField} {p : Poly K} -> P K -> p /= 0 -> Not (Inv p) -> RootFieldData P K p
    }

    \func CountableSplittingFieldData : SplittingFieldData \cowith
      | P => \lam K => Countable K
      | S => \lam _ => \Sigma
      | S-hom => {?hidden_proof}
      | S-factor => {?hidden_proof}
      | nextField => \lam {k} {p} c p/=0 pc => \new RootFieldData {
        | RootField => FactorField {(poly-maximal-ideal c p pc).1} (poly-maximal-ideal c p pc).2
        | RootFieldP => factor-countable (Poly.poly-countable c)
        | rootFieldHom => factorHom RingHom.∘ polyHom
        | root => in~ (padd 1 0)
        | isRoot => pmap (polyEval __ _) (inv (polyMap-comp polyHom factorHom)) *> polyEval_polyMap *> FactorRing.fequiv0 
          (transportInv (poly-maximal-ideal c p pc).1 poly-eval (poly-maximal-ideal c p pc).3)
        | RootField-gen => \lam in~ q => inP (q, pmap (polyEval __ _) (inv (later $ polyMap-comp _ _)) *> polyEval_polyMap *> pmap FactorRing.inF poly-eval)
      }

    \lemma poly-eval {K : DiscreteField} {p : Poly K} : polyMapEval polyHom p (padd 1 0) = p => {?hidden_proof}
  }
