\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Arith.Real.UpperReal
\import Function()
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Operations
\import Order.Biordered
\import Order.Lattice
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.CoverSpace.CompletionTools
\import Topology.CoverSpace.Product
\import Topology.CoverSpace.StronglyComplete
\import Topology.MetricSpace
\import Topology.NormedAbGroup.Real
\import Topology.NormedAbGroup.Real.Functions
\import Topology.TopAbGroup.Product
\import Topology.TopSpace
\import Topology.TopSpace.Product
\import Topology.UniformSpace
\import Topology.UniformSpace.StronglyComplete

\func dense-metric-lift {X Y : PseudoMetricSpace} {Z : CompleteMetricSpace} (f : IsometricMap X Y) (fd : f.IsWeaklyDenseUniformEmbedding) (g : MetricMap X Z) : MetricMap Y Z \cowith
  | UniformMap => weaklyDense-uniform-lift f fd g
  | func-dist => {?hidden_proof}
  \where {
    \open ProductTopSpace
    \open ContMap
  }


\instance MetricCompletion (X : PseudoMetricSpace) : CompleteMetricSpace 
  | StronglyCompleteUniformSpace => UniformStrongCompletion X
  | dist => \lam x y => dist-cover (x, y)
  | dist-refl => {?hidden_proof}
  | dist-symm => {?hidden_proof}
  | dist-triang => {?hidden_proof}
  | dist-uniform => {?hidden_proof}
  \where {
    \open ProductCoverSpace
    \open CoverMap

    dist-cover : CoverMap (StrongCompletion X ⨯ StrongCompletion X) RealNormed 
    => weaklyDense-lift {_} {ProductStronglyRegularCoverSpace (StrongCompletion X) (StrongCompletion X)} (prod strongCompletion strongCompletion) 
      (prod.isWeaklyDenseEmbedding strongCompletion.isDenseEmbedding strongCompletion.isDenseEmbedding) ldist-uniform-map

    \lemma dist-char {x y : X} : dist-cover (pointSCF x, pointSCF y) = ldist x y => {?hidden_proof}

    \lemma dist-refl-lem {F : StronglyRegularCauchyFilter X} : dist-cover (F, F) = 0 => {?hidden_proof}

    \lemma filter-dist-triang (x y z : StronglyRegularCauchyFilter X) : dist-cover (x, z) <= dist-cover (x, y) + dist-cover (y, z) => {?hidden_proof}

    \lemma dist-neighborhood (F G : StronglyRegularCauchyFilter X) {eps : Rat} (eps>0 : 0 < eps) {x : X} (Fx : F (OBall (RatField.half (RatField.half eps)) x)) 
    (Gx : G (OBall (RatField.half (RatField.half eps)) x)) : (dist-cover (F, G)).U eps => {?hidden_proof}
  }
