\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Arith.Rat
\import Arith.Real.UpperReal
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.MetricSpace
\import Topology.NormedAbGroup.Real.Functions
\import Topology.TopSpace
\import Topology.TopSpace.Product
\import Topology.UniformSpace.Complete

\func dense-metric-lift {X Y : ExPseudoMetricSpace} {Z : CompleteExMetricSpace} (f : IsometricMap X Y) (fd : f.IsDense) (g : MetricMap X Z) : MetricMap Y Z \cowith
  | UniformMap => dense-uniform-lift f (f.dense->uniformEmbedding fd) g
  | func-dist => {?hidden_proof}
  \where {
    \open ProductTopSpace
    \open ContMap
  }


\instance ExMetricCompletion (X : ExPseudoMetricSpace) : CompleteExMetricSpace 
  | CompleteUniformSpace => UniformCompletion X
  | dist (F G : RegularCauchyFilter X) : ExUpperReal 
    | U => \lam q => ∃ (r : < q) (U : F.F) (V : G.F) ∀ {x : U} {y : V} ((X.dist x y).U r)
    | U-closed => \lam inP (r, r<q, U, FU, V, GV, h) q<q' => inP (r, r<q <∘ q<q', U, FU, V, GV, h)
    | U-rounded => \lam {q} inP (r, r<q, U, FU, V, GV, h) => inP (RatField.mid r q, inP (r, RatField.mid>left r<q, U, FU, V, GV, h), RatField.mid<right r<q)
  | dist-refl => {?hidden_proof}
  | dist-symm => {?hidden_proof}
  | dist-triang => {?hidden_proof}
  | dist-uniform => {?hidden_proof}

\func completion-ex-isometry {X : ExPseudoMetricSpace} : IsometricMap X (ExMetricCompletion X) \cowith
  | UniformMap => uniform-completion
  | func-isometry => {?hidden_proof}