\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Arith.Rat
\import Arith.Real.UpperReal
\import Function.Meta
\import Logic
\import Logic.Meta
\import Order.Biordered
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace.Complete
\import Topology.MetricSpace
\import Topology.TopAbGroup
\import Topology.UniformSpace

\instance ExUpperRealMetric : CompleteExMetricSpace ExUpperReal 
  | dist => dist
  | dist-refl => {?hidden_proof}
  | dist-symm => {?hidden_proof}
  | dist-triang => {?hidden_proof}
  | dist-ext => {?hidden_proof}
  | isCompleteMetric => {?hidden_proof}
  \where {
    \open ExUpperRealAbMonoid(<-rat, <_+)

    \lemma dist-left {x y : ExUpperReal} {a : Rat} (xy<a : (dist x y).U a) : x <= y + a => {?hidden_proof}

    \lemma dist-right {x y : ExUpperReal} {a : Rat} (xy<a : (dist x y).U a) : y <= x + a => {?hidden_proof}

    \func cfPoint (F : Set ExUpperReal -> \Prop) : ExUpperReal \cowith
      | U => \lam q => ∃ (a : < q) (U : F) ∀ {x : U} (x < a)
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}
  }


\instance UpperRealMetric : CompleteExMetricSpace UpperReal 
  | dist => \lam x y => ExUpperRealMetric.dist x y
  | dist-refl => {?hidden_proof}
  | dist-symm => {?hidden_proof}
  | dist-triang => {?hidden_proof}
  | dist-ext => {?hidden_proof}
  | isCompleteMetric => {?hidden_proof}

\func upper-ex-isometry : IsometricMap UpperRealMetric ExUpperRealMetric (\lam x => x) \cowith
  | func-isometry => {?hidden_proof}