\import Algebra.Meta
\import Equiv
\import Equiv.Path
\import Function.Meta($)
\import Logic
\import Meta
\import Paths
\import Paths.Meta
\import Set

\plevels obj >= hom

\class Precat {
  | Ob : \hType obj
  | Hom : Ob -> Ob -> \Set hom
  | id (X : Ob) : Hom X X
  | \infixl 8 o \alias \infixl 8 ∘ {X Y Z : Ob} : Hom Y Z -> Hom X Y -> Hom X Z
  | id-left {X Y : Ob} {f : Hom X Y} : id Y ∘ f = f
  | id-right {X Y : Ob} {f : Hom X Y} : f ∘ id X = f
  | o-assoc {X Y Z W : Ob} {h : Hom Z W} {g : Hom Y Z} {f : Hom X Y} : (h ∘ g) ∘ f = h ∘ (g ∘ f)
}

\meta SmallPrecat => Precat \levels \lp _

\open Precat(>>)

\class Map {
  | C : Precat
  | dom : C
  | cod : C
  | f : Hom dom cod
}

\class Mono \extends Map {
  | isMono {x : C} {g h : Hom x dom} : f ∘ g = f ∘ h -> g = h
}
  \where {
    \func comp {C : Precat} {x y z : C} (g : Mono {C} {y} {z}) (f : Mono {C} {x} {y}) : Mono {C} {x} {z} (g.f ∘ f) \cowith
      | isMono => \lam p => f.isMono (g.isMono (inv o-assoc *> p *> o-assoc))
  }


\func isEpi {C : Precat} {x y : C} (f : Hom x y) => \Pi {z : C} {g h : Hom y z} -> g ∘ f = h ∘ f -> g = h

\class SplitMono \extends Mono {
  | hinv : Hom cod dom
  | hinv_f : hinv ∘ f = id dom
  | isMono => \lam {_} {g} {h} gf=hf => qed (g ==< inv id-left >== g >> id dom ==< pmap (g >>) (inv hinv_f) >== g >> (f >> hinv) ==< o-assoc >== (g >> f) >> hinv ==< pmap (o hinv) gf=hf >== 
    (h >> f) >> hinv ==< inv o-assoc >== h >> (f >> hinv) ==< pmap (h >>) hinv_f >== h >> id dom ==< id-left >== h)
}

\class Iso \extends SplitMono {
  | f_hinv : f ∘ hinv = id cod
}
  \where {
    \func equals {C : Precat} {x y : C} (e e' : Iso {C} {x} {y}) (p : e.f = e'.f) : e = e' 
      => ext (p, isMono {e} (e.f_hinv *> inv e'.f_hinv *> inv (pmap (e'.hinv >>) p)))

    \use \level levelProp {C : Precat} {x y : C} (f : Hom x y) (e e' : Iso f) => equals e e' idp

    \lemma hinv-unique {C : Precat} {x y : C} (e : SplitMono {C} {x} {y}) (e' : Iso {C} {x} {y}) (p : e.f = e'.f) : e.hinv = e'.hinv => {?hidden_proof}

    \lemma rightFactor {C : Precat} {x y z : C} (f : Hom x y) (e2 : Mono {C} {y} {z}) (e3 : Iso (e2.f ∘ f)) : Iso f => {?hidden_proof}

    \lemma leftFactor {C : Precat} {x y z : C} {f : Hom x y} (e : isEpi f) (g : Hom y z) (e3 : Iso (g ∘ f)) : Iso g => {?hidden_proof}

    \lemma composite {C : Precat} {x y z : C} (f : Iso {C} {x} {y}) (g : Iso {C} {y} {z}) : Iso (g.f ∘ f.f) => {?hidden_proof}
  }


\func idIso {C : Precat} {x : C} : Iso (id x) \cowith
  | hinv => id x
  | f_hinv => id-left
  | hinv_f => id-right

\func oIso {C : Precat} {x y z : C} (e : Iso {C} {x} {y}) (f : Iso {C} {y} {z}) : Iso {C} {x} {z} \cowith
  | f => f.f ∘ e.f
  | hinv => e.hinv ∘ f.hinv
  | f_hinv => o-assoc *> pmap (_ ∘) (inv o-assoc *> pmap (∘ _) e.f_hinv *> id-left) *> f.f_hinv
  | hinv_f => o-assoc *> pmap (_ ∘) (inv o-assoc *> pmap (∘ _) f.hinv_f *> id-left) *> e.hinv_f

\class Cat \extends Precat {
  | univalence {a b : Ob} : Equiv (idtoiso {_} {a} {b})
}
  \where {
    \lemma univalenceFromEquiv {C : Precat} (e : \Pi {a b : C} -> Equiv {a = b} {Iso {C} {a} {b}}) (i : \Pi {a : C} -> Iso.f {e (idpe a)} = id a) {a b : C} : Equiv (C.idtoiso {a} {b}) 
      => {?hidden_proof}

    \lemma makeUnivalence {C : Precat} (c : \Pi (e : Iso {C}) -> \Sigma (p : e.dom = e.cod) (transport (Hom e.dom) p (id e.dom) = e)) {a b : C} : Equiv (C.idtoiso {a} {b}) => {?hidden_proof}
  }


\meta SmallCat => Cat \levels \lp _

\func DiscretePrecat (X : \Type) : Precat X \cowith
  | Hom => \lam x y => Trunc0 (x = y)
  | id => \lam x => in0 idp
  | o => o
  | id-left => \lam {_} {_} {p} => cases p idp
  | id-right => \lam {_} {_} {p} => cases p (pmap in0 (idp_*> _))
  | o-assoc => \lam {_} {_} {_} {_} {p} {q} {r} => cases (p, q, r) (pmap in0 (inv (*>-assoc _ _ _)))
  \where {
    \func map {X : \Type} {D : Precat} (f : X -> D) {x y : X} (h : Hom {DiscretePrecat X} x y) : Hom (f x) (f y) \elim h
      | in0 idp => id _
  }


SIP (C : Cat) (Str : C -> \hType (\suc \lp)) (isHom : \Pi {x y : C} -> Str x -> Str y -> Hom x y -> \hType (\suc \lp)) 
(st : \Pi {X : C} {S1 S2 : Str X} -> isHom S1 S2 (id X) -> isHom S2 S1 (id X) -> S1 = S2) {X Y : C} (e : Iso {C} {X} {Y}) (S1 : Str X) (S2 : Str Y) 
(p : isHom S1 S2 e) (q : isHom S2 S1 e.hinv) : \Sigma (p : X = Y) (Path (\lam i => Str (p @ i)) S1 S2) (transport (Hom X) p (id X) = e) 
=> \case \elim Y, \elim e, \elim S2, p, q, Cat.univalenceToTransport e \with {
  | Y, e : Iso, S2, p, q, (idp, s) => (idp, st (transportInv (isHom S1 S2) s p) (transport (isHom S2 S1) (inv id-right *> pmap (∘ e.hinv) s *> e.hinv_f) q), s)
}

\class Graph {
  | V : \Set
  | E : V -> V -> \Set
}

\func TrivialCat : Cat => Graph.FreeCat {\new (Graph (\Sigma) (\lam _ _ => Empty))}