\import Algebra.Meta
\import Data.Or
\import Function.Meta
\import Logic.Unique
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta

\data Empty 

\func absurd {A : \Type} (x : Empty) : A 

\func Not (A : \Type) => A -> Empty

\func \infix 1 /= {A : \Type} (a a' : A) => Not (a = a')

\lemma /=-sym {A : \Type} {a a' : A} (p : a /= a') : a' /= a => {?hidden_proof}

\data TruncP (A : \Type) 
  | inP A
  | truncP (a a' : TruncP A) : a = a'
  \where {
    \use \level levelProp {A : \Type} (a a' : TruncP A) : a = a' => path (truncP a a')

    \lemma remove {A : \Type} (p : isProp A) (t : TruncP A) : \level A p => {?hidden_proof}

    \lemma remove' {A : \Prop} (t : TruncP A) : A => {?hidden_proof}

    \lemma rec {A B : \Type} (p : isProp B) (t : TruncP A) (f : A -> B) : \level B p => {?hidden_proof}

    \lemma rec-eval {A B : \Type} {p : isProp B} {a : A} {f : A -> B} : \level (rec p (inP a) f = f a) (isProp.=>isSet p _ _) => {?hidden_proof}

    \lemma rec-set {A : \Type} {B : \Set} (t : TruncP A) (f : A -> B) (p : \Pi (a a' : A) -> f a = f a') : \level (\Sigma (b : B) (∃ (a : A) (f a = b))) (level p) => {?hidden_proof}
      \where {
        \lemma level (p : \Pi (a a' : A) -> f a = f a') : isProp (\Sigma (b : B) (∃ (a : A) (f a = b))) => {?hidden_proof}
      }


    \func map {A B : \Type} (t : TruncP A) (f : A -> B) : TruncP B \elim t
      | inP a => inP (f a)
  }


\lemma prop-pi {A : \Prop} {a a' : A} : a = a' => {?hidden_proof}

\lemma prop-isProp {A : \Prop} : isProp A => {?hidden_proof}

\lemma set-pi {A : \Set} {a b : A} {p q : a = b} : p = q => {?hidden_proof}

\lemma prop-dpi (A : I -> \Prop) (a : A left) (a' : A right) : Path A a a' => {?hidden_proof}

\data ToProp (A : \Type) (p : isProp A) 
  | toProp A
  \where {
    \lemma fromProp {A : \Type} {p : isProp A} (t : ToProp A p) : \level A p => {?hidden_proof}

    \use \level levelProp {A : \Type} {p : isProp A} (x y : ToProp A p) : x = y \elim x, y
      | toProp a, toProp a' => pmap toProp (p a a')
  }


\data \infixr 2 || (A B : \Type) : \Prop 
  | byLeft A
  | byRight B
  \where {
    \lemma rec {A B C : \Type} (p : isProp C) (f : A -> C) (g : B -> C) (t : A || B) : \level C p => {?hidden_proof}

    \lemma rec' {A B : \Type} {C : \Prop} (f : A -> C) (g : B -> C) (t : A || B) : C => {?hidden_proof}

    \func map {A B C D : \Type} (f : A -> C) (g : B -> D) (t : A || B) : C || D \elim t
      | byLeft a => byLeft (f a)
      | byRight b => byRight (g b)

    \lemma fromOr {A B : \Type} (p : Or A B) : A || B => {?hidden_proof}

    \lemma toOr {A B : \Type} (p : A || B) : TruncP (Or A B) => {?hidden_proof}

    \lemma flip {A B : \Type} (e : A || B) : B || A => {?hidden_proof}
  }


\func \infix 0 <-> (P Q : \Prop) => \Sigma (P -> Q) (Q -> P)

\lemma <->_= {P Q : \Prop} : (P <-> Q) <-> (P = Q) => {?hidden_proof}

\lemma <->refl {P : \Prop} : P <-> P => {?hidden_proof}

\lemma <->trans {P Q S : \Prop} (f : P <-> Q) (g : Q <-> S) : P <-> S => {?hidden_proof}

\lemma <->sym {P Q : \Prop} (f : P <-> Q) : Q <-> P => {?hidden_proof}

\func OneOf (l : Array \Type) => ∃ (P : l) P

\func ElemOf (l : Array \Type) => Given (P : l) P

\type arraySubset {X : \Type} (l : Array X) (x : X) => ∃ (y : l) (y = x)

\lemma propExt {A B : \Prop} (f : A -> B) (g : B -> A) : A = B => {?hidden_proof}
  \where {
    \lemma dir {A B : \Prop} (p : A = B) (a : A) : B => {?hidden_proof}

    \lemma conv {A B : \Prop} (p : A = B) (b : B) : A => {?hidden_proof}
  }


\meta isProp-prover => \lam x y => cases (x, y) (cong prop-pi <|> contradiction)

\class NegatedProp {
  | P : \Prop
  | isNegated : Not (Not P) -> P
}

\instance EmptyNegated : NegatedProp Empty 
  | isNegated => {?hidden_proof}