\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Group.GSet
\import Algebra.Meta
\import Algebra.Monoid
\import Logic
\import Paths
\import Paths.Meta
\import Set

\func TranslationAction (G : Group) : TransitiveGroupAction G \cowith
  | E => G
  | ** => G.*
  | **-assoc => {?hidden_proof}
  | id-action => {?hidden_proof}
  | isTransAction => {?hidden_proof}

\func TranslationActionOnSubsets (G : Group) : GroupAction G \cowith
  | E => SubSet G
  | ** => \lam (g : G) (p : SubSet G) => \new (SubSet G) {
    | contains => \lam h => p.contains (inverse g G.* h)
  }
  | **-assoc => {?hidden_proof}
  | id-action => {?hidden_proof}

\func conjAction (G : Group) : GroupAction G \cowith
  | E => G
  | ** => \lam (g : G) => conjugate g
  | **-assoc {m : G} {n : G} {e : G} : conjugate m (conjugate n e) = conjugate (m * n) e => {?hidden_proof}
  | id-action {e : G} : conjugate G.ide e = e => {?hidden_proof}

\func trivialAction (G : Group) (E : BaseSet) : GroupAction G E \cowith
  | ** => \lam _ e => e
  | **-assoc => {?hidden_proof}
  | id-action => {?hidden_proof}

\func conjugate-subset {G : Group} (g : G) (S : SubSet G) : SubSet G \cowith
  | contains => \lam h => S.contains (conjugate (inverse g) h)