\import Algebra.Group
\import Algebra.Group.SubGroup
\import Algebra.Monoid
\import Algebra.Pointed
\import Logic
\import Logic.Meta
\import Paths
\import Relation.Equivalence
\import Set

\class GSet (G : Group) \extends BaseSet {
  | \infixl 8 ** : G -> E -> E -- priority should be bigger than priority of "+" in LModule (=7)
  | **_ide {e : E} : ide ** e = e
  | **-assoc {m n : G} {e : E} : (m * n) ** e = m ** (n ** e)

  \func Stabilizer (s : E) : SubGroup G \cowith
    | contains m => m ** s = s
    | contains_* {m n : G} (p : m ** s = s) (q : n ** s = s)  =>
      (m * n) ** s  ==< **-assoc >==
      m ** (n ** s) ==< pmap (\lam x => m ** x) q >==
      m ** s  ==< p >==
      s `qed

    | contains_ide => **_ide

    | contains_inverse {m : G} (p : m ** s = s) =>
      inverse m ** s ==< pmap (\lam x => inverse m ** x) (inv p) >==
      inverse m ** (m ** s) ==< inv **-assoc >==
      (inverse m * m) ** s ==< pmap (\lam x => x ** s) inverse-left >==
      ide ** s ==< **_ide >==
      s `qed

  \func choosePoint (e : E) => ActionBySubgroup (Stabilizer e)
}

\class TransitiveGroupAction \extends GSet
  | isTransAction : \Pi (v v' : E) -> ∃ (g : G) (g ** v = v')

\func ActionBySubgroup {G : Group} (H : SubGroup G) : GSet G \cowith
  | E => H.Cosets
  | ** (g : G) (e : H.Cosets) : H.Cosets \with {
    | g, in~ a => in~ (g * a)
    | g, ~-equiv x y r => in~ (g * x) ==< H.~-pequiv-left (H.contains_~.1 r) >==
    in~ (g * x * (inverse x * y)) ==< pmap in~ (trivialRelation g x y ) >== in~ (g * y) `qed
    }
  | **-assoc {_} {_} {e} => \case \elim e \with{
      | in~ a => pmap in~ *-assoc
    }
  | **_ide {e} => \case \elim e \with{
    | in~ a => pmap in~ ide-left
  }
  \where \lemma trivialRelation (g x y : G) : g * x * (inverse x * y) = g * y =>
    g * x * (inverse x * y)   ==< *-assoc >==
    g * (x * (inverse x * y)) ==< pmap (g *) (inv *-assoc) >==
    g * ((x * inverse x) * y) ==< pmap (\lam z => g *( z * y)) inverse-right >==
    g * (ide * y)             ==< pmap (g *) ide-left >==
    g * y `qed


\instance TransitiveActionBySubgroup {G : Group} (H : SubGroup G) : TransitiveGroupAction G
   | GSet => ActionBySubgroup H
   | isTransAction (v v' : H.Cosets) : ∃ (g : G) (g ActionBySubgroup.** v = v') => \case \elim v, \elim v'\with{
      | in~ a, in~ a1 => inP(a1 * inverse a ,
                              in~ (a1 * inverse a * a) ==< pmap in~ *-assoc >==
                              in~ (a1 * (inverse a * a)) ==< pmap (\lam z => in~ (a1 * z)) inverse-left >==
                              in~ (a1 * ide) ==< pmap in~ ide-right >==
                              in~ a1 `qed
                           )
   }
