\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Group.SubGroup
\import Function
\import Function.Meta
\import Meta
\import Relation.Equivalence

\func \infix 7 // (G : Group) (H : NormalSubGroup G) : Group
  => H.Quot

\func kerQuotHom {G H : Group} (f : GroupHom G H) : GroupHom (G // KernelGroup f) H
  => NormalSubGroup.quot-univ {KernelGroup f} f \lam _ c => c

\lemma FirstIsoTheorem {G H : Group} (f : GroupHom G H) (p : IsSurj f) : (kerQuotHom f).IsIsomorphism
  => (Kernel-trivial-char.1 $ later \lam {in~ a} q => NormalSubGroup.quotHom_=1 {KernelGroup f} q,
      IsSurj.factor {G} {_} {H} {NormalSubGroup.quotHom} p)