\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.RatherBelow
\import Topology.UniformSpace
\open ClosurePrecoverSpace
\open Completion

\class CompleteUniformSpace \extends UniformSpace, CompleteCoverSpace

\func dense-uniform-lift {X Y : UniformSpace} {Z : CompleteUniformSpace} (f : UniformMap X Y) (fd : f.IsDenseUniformEmbedding) (g : UniformMap X Z) : UniformMap Y Z \cowith
  | CoverMap => dense-lift f (fd.1, f.embedding->coverEmbedding fd.2) g
  | func-uniform => {?hidden_proof}

\instance UniformCompletion (X : UniformSpace) : CompleteUniformSpace 
  | CompleteCoverSpace => Completion X
  | isUniform => \lam D => ∃ (C : isUniform) (∀ {U : C} ∃ (V : D) (mkSet U ⊆ V))
  | uniform-cover => {?hidden_proof}
  | uniform-top => {?hidden_proof}
  | uniform-refine => {?hidden_proof}
  | uniform-inter => {?hidden_proof}
  | uniform-star => {?hidden_proof}
  | uniform-cauchy => {?hidden_proof}
  \where {
    \lemma properUniform (Xp : X.IsProperUniform) : (UniformCompletion X).IsProperUniform => {?hidden_proof}

    \lemma makeUniform {C : Set (Set X)} (Cu : isUniform C) : isUniform {UniformCompletion X} (\lam V => ∃ (U : C) (V = mkSet U)) => {?hidden_proof}
  }


\lemma mkSet_<=* {X : UniformSpace} {V U : Set X} (p : V <=* U) : mkSet V <=* mkSet U => {?hidden_proof}

\func uniform-completion {X : UniformSpace} : UniformMap X (UniformCompletion X) \cowith
  | CoverMap => completion
  | func-uniform => {?hidden_proof}
  \where {
    \lemma isDenseEmbedding : UniformMap.IsDenseUniformEmbedding {uniform-completion {X}} => {?hidden_proof}
  }


\lemma cauchyFilter-uniform-char {X : UniformSpace} {F : SetFilter X} : IsCauchyFilter F <-> ∀ {C : isUniform} ∃ (U : C) (F U) => {?hidden_proof}

\lemma regularFilter-uniform-char {X : UniformSpace} {F : CauchyFilter X} : ∀ {U : F.F} ∃ (V : Set X) (V <=< U) (F V) <-> ∀ {U : F.F} ∃ (V : Set X) (V <=* U) (F V) => {?hidden_proof}