\import Data.Bool
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Operations
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Product
\import Topology.TopSpace.Product
\import Topology.UniformSpace
\open ClosurePrecoverSpace
\open Set
\open UniformMap

\instance RegularPreuniformSpaceHasProduct : HasProduct RegularPreuniformSpace 
  | Operations.HasProduct.Product => ProductRegularPreuniformSpace

\instance ProductRegularPreuniformSpace (X Y : RegularPreuniformSpace) : RegularPreuniformSpace (\Sigma X Y) 
  | CoverSpace => ProductCoverSpace X Y
  | isUniform => \lam E => ∃ (C : X.isUniform) (D : Y.isUniform) (Refines (\lam W => ∃ (U : C) (V : D) (W = Prod U V)) E)
  | uniform-cover => {?hidden_proof}
  | uniform-top => {?hidden_proof}
  | uniform-refine => {?hidden_proof}
  | uniform-inter => {?hidden_proof}
  | uniform-cauchy => {?hidden_proof}
  | uniform-regular => {?hidden_proof}

\instance UniformSpaceHasProduct : HasProduct UniformSpace 
  | Operations.HasProduct.Product => ProductUniformSpace

\instance ProductUniformSpace (X Y : UniformSpace) : UniformSpace (\Sigma X Y) 
  | RegularPreuniformSpace => ProductRegularPreuniformSpace X Y
  | uniform-star => {?hidden_proof}
  \where {
    \lemma properUniform (Xp : X.IsProperUniform) (Yp : Y.IsProperUniform) : PreuniformSpace.IsProperUniform {X ⨯ Y} => {?hidden_proof}

    \func proj1 {X Y : UniformSpace} : UniformMap (X ⨯ Y) X \cowith
      | func => \lam s => s.1
      | func-uniform => {?hidden_proof}

    \func proj2 {X Y : UniformSpace} : UniformMap (X ⨯ Y) Y \cowith
      | func => \lam s => s.2
      | func-uniform => {?hidden_proof}

    \func tuple {X Y Z : UniformSpace} (f : UniformMap Z X) (g : UniformMap Z Y) : UniformMap Z (X ⨯ Y) \cowith
      | func => \lam z => (f z, g z)
      | func-uniform => {?hidden_proof}

    \func prod {X X' Y Y' : UniformSpace} (f : UniformMap X Y) (f' : UniformMap X' Y') : UniformMap (X ⨯ X') (Y ⨯ Y') => tuple (f ∘ proj1) (f' ∘ proj2)

    \lemma prodCover {X Y : UniformSpace} {C : Set (Set X)} (Cu : X.isUniform C) {D : Set (Set Y)} (Du : Y.isUniform D) :
      isUniform {X ⨯ Y} (\lam W => ∃ (U : C) (V : D) (W = (\lam s => \Sigma (U s.1) (V s.2)))) => {?hidden_proof}
  }
