\import Paths
\import Paths.Meta
\import Relation.Truncated

\class AbstractReductionSystem {
  | A : \Set
  | \infix 4 ~> : Rel A
  | \infix 5 |--| : Rel A
  | |--|_symmetric (a b : A) (a~b : a |--| b) : b |--| a
}

\class SimpleARS \extends AbstractReductionSystem {
  | |--| => \lam a b => a = b
  | |--|_symmetric => \lam (a b : A) (p : a |--| b) => inv p
}

\func \infix 4 ~>_0 {A : ARS} : Rel A => =

\func \infix 4 ~>_1 {A : ARS} : Rel A => A.~>

\func \infix 4 ~>_= {A : ARS} : Rel A => reflexive-closure ~>

\func \infix 4 ~>_+ {A : ARS} : Rel A => transitive-closure ~>

\func \infix 4 ~>_* {A : ARS} : Rel A => transitive-refl-closure ~>

\func \infix 4 <~ {A : ARS} : Rel A => \lam a b => b ~> a

\func \infix 4 <~> {A : ARS} : Rel A => symmetric-closure ~>

\func <~>-reverse {A : ARS} {a b : A} (a<~>b : a <~> b) : b <~> a \elim a<~>b
  | sc-left a~>b => sc-right a~>b
  | sc-right a<~b => sc-left a<~b

\func \infix 4 <~>* {A : ARS} : A -> A -> \Prop => transitive-refl-closure <~>

\lemma <~>*-compose {A : ARS} {a c : A} (b : A) (a<~>*b : a <~>* b) (b<~>*c : b <~>* c) : a <~>* c => {?hidden_proof}

\lemma <~>*-reverse {A : ARS} {a b : A} (a<~>*b : a <~>* b) : b <~>* a => {?hidden_proof}

\lemma ~>=><~>* {A : ARS} {a b : A} (red : a ~> b) : a <~>* b => {?hidden_proof}

\lemma ~>*=><~>* {A : ARS} {a b : A} (red : a ~>_* b) : a <~>* b => {?hidden_proof}

\lemma ~>*-concat {A : ARS} {a b c : A} (a~>*b : a ~>_* b) (b~>*c : b ~>_* c) : a ~>_* c => {?hidden_proof}

\lemma ~>_=-append {A : ARS} {a b c : A} (a~>_=b : a ~>_= b) (b~>*c : b ~>_* c) : a ~>_* c => {?hidden_proof}

\data Join {A : ARS} (a b : A) : \Prop 
  | join (c : A) (a ~>_* c) (b ~>_* c)
  \where {
    \lemma append-left {A : ARS} {a b c : A} (c~>*a : c ~>_* a) (j : Join a b) : Join c b => {?hidden_proof}

    \lemma append-right {A : ARS} {a b c : A} (c~>*b : c ~>_* b) (j : Join a b) : Join a c => {?hidden_proof}
  }


\func \infix 5 ~ {A : ARS} : Rel A => transitive-refl-closure |--|

\data \infix 5 |==| {A : ARS} (a b : A) : \Prop 
  | red-to (a ~> b)
  | red-from (a <~ b)
  | eq (a ~ b)

\func Conversion~ {A : ARS} : Rel A => transitive-refl-closure |==|

\data Join~ {A : ARS} (a b : A) : \Prop 
  | join~ (c d : A) (a ~>_* c) (c ~ d) (b ~>_* d)

\data \infix 4 ~>~ {A : ARS} (a b : A) : \Prop 
  | red~ (c d : A) (a ~ c) (c ~> d) (d ~ b)