\import Data.Array
\import Order.Lattice
\import Order.PartialOrder
\import Order.StrictOrder

\class BiorderedSet \extends StrictPoset, Poset {
  | <-transitive-right \alias \infixr 9 <∘r {a1 a2 a3 : E} : a1 <= a2 -> a2 < a3 -> a1 < a3
  | <-transitive-left \alias \infixl 8 <∘l {a1 a2 a3 : E} : a1 < a2 -> a2 <= a3 -> a1 < a3
  | <=-less {a1 a2 : E} : a1 < a2 -> a1 <= a2

  \protected \func op : BiorderedSet \cowith
    | StrictPoset => StrictPoset.op
    | Poset => Poset.op
    | <-transitive-right => {?hidden_proof}
    | <-transitive-left => {?hidden_proof}
    | <=-less => {?hidden_proof}
}

\class BiorderedLattice \extends BiorderedSet, Lattice {
  | <_meet-univ {x y z : E} : x < y -> x < z -> x < y ∧ z
  | <_join-univ {x y z : E} : x < z -> y < z -> x ∨ y < z

  \lemma <_meet-monotone {x x' y y' : E} (p : x < y) (q : x' < y') : x ∧ x' < y ∧ y' => {?hidden_proof}

  \lemma Big_<_meet-univ {l : Array E} {x y : E} (p : y < x) (f : \Pi (i : Fin l.len) -> y < l i) : y < Big ∧ x l => {?hidden_proof}

  \lemma <_join-monotone {x x' y y' : E} (p : x < y) (q : x' < y') : x ∨ x' < y ∨ y' => {?hidden_proof}

  \lemma Big_<_join-univ {l : Array E} {x y : E} (p : x < y) (f : \Pi (i : Fin l.len) -> l i < y) : Big ∨ x l < y => {?hidden_proof}
}