\import Function.Meta
\import Order.HeytingAlgebra
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Subset

\class BooleanAlgebra \extends BoundedDistributiveLattice, HeytingAlebra {
  | compl : E -> E
  | compl-meet {a : E} : a ∧ compl a <= bottom
  | compl-join {a : E} : top <= a ∨ compl a
  | implies => \lam a b => compl a ∨ b
  | exponent-left => \lam xa<=b => meet-univ <=-refl top-univ <=∘ meet-monotone <=-refl compl-join <=∘ ldistr>= <=∘ join-comm =<= join-monotone meet-right xa<=b
  | exponent-right => \lam x<=a-->b => meet-monotone x<=a-->b <=-refl <=∘ rdistr>= <=∘ join-univ (meet-comm =<= compl-meet <=∘ bottom-univ) meet-left

  \lemma compl-adj {a b : E} (ab : a ∧ b <= bottom) : a <= compl b => {?hidden_proof}

  \lemma compl-mono {a b : E} (a<=b : a <= b) : compl b <= compl a => {?hidden_proof}

  \lemma compl_meet {a b : E} : compl (a ∧ b) = compl a ∨ compl b => {?hidden_proof}

  \lemma compl_join {a b : E} : compl (a ∨ b) = compl a ∧ compl b => {?hidden_proof}

  \lemma compl-inv {a : E} : compl (compl a) = a => {?hidden_proof}

  \func symm-diff (a b : E) => a ∧ compl b ∨ b ∧ compl a

  \lemma compl_symm-diff {a b : E} : compl (symm-diff a b) = a ∧ b ∨ compl a ∧ compl b => {?hidden_proof}
}

\type NegatedElem (R : HeytingAlebra) => Set.Total R.IsNegated

\instance HeytingBooleanAlgebra (R : HeytingAlebra) : BooleanAlgebra (NegatedElem R) 
  | <= => \lam a b => a.1 <= b.1
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | meet => \lam a b => (a.1 ∧ b.1, meet-negated a.2 b.2)
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | join => \lam a b => (neg $ neg $ a.1 ∨ b.1, neg-negated)
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  | top => (R.top, R.top-univ)
  | top-univ => {?hidden_proof}
  | bottom => (R.bottom, R.bottom-negated)
  | bottom-univ => {?hidden_proof}
  | ldistr>= => {?hidden_proof}
  | compl => \lam a => (neg a.1, neg-negated)
  | compl-meet => {?hidden_proof}
  | compl-join => {?hidden_proof}
  \where {
    \open HeytingAlebra
  }
