\import Data.List
\import Logic
\import Order.LinearOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\open LinearOrder

\instance LexicographicalProduct (A B : Dec) : Dec (\Sigma A B) 
  | < => \lam a b => a.1 < b.1 || (\Sigma (a.1 = b.1) (a.2 < b.2))
  | <-irreflexive => {?hidden_proof}
  | <-transitive => {?hidden_proof}
  | trichotomy => {?hidden_proof}

\instance LexicographicalList (A : Dec) : Dec (List A) 
  | < => <L
  | <-irreflexive {l : List A} (p : l <L l) : Empty => {?hidden_proof}
  | <-transitive {as bs cs : List A} (as<bs : as <L bs) (bs<cs : bs <L cs) : as <L cs => {?hidden_proof}
  | trichotomy (as bs : List A) : Tri {\new (StrictPoset (List A) <L <-irreflexive <-transitive)} as bs => {?hidden_proof}
  \where {
\data \infix 4 <L {A : Dec} (l1 l2 : List A) : \Prop \elim l1, l2
      | nil, :: _ _ => nil<::
      | :: a as, :: b bs => <head (a < b) <tail (a = b) (as <L bs)
  }
