\import Category
\import Logic
\import Paths.Meta
\import Relation.Equivalence
\import Set

\class Preorder \extends BaseSet, Precat (\lp, \lp) {
  | \infix 4 <= : E -> E -> \Prop
  | <=-refl {x : E} : x <= x
  | <=-transitive \alias \infixr 9 <=∘ {x y z : E} : x <= y -> y <= z -> x <= z
  | Ob => E
  | Hom => <=
  | id => \lam _ => <=-refl
  | o => \lam f g => g <=∘ f
  | id-left => prop-pi
  | id-right => prop-pi
  | o-assoc => prop-pi
  | \infix 4 >= : E -> E -> \Prop
  | >= => \lam x y => y <= x
}

\lemma =_<= {P : Preorder} {x y : P} (p : x = y) : x <= y => {?hidden_proof}

\class Poset \extends Preorder, Cat (\lp, \lp) {
  | <=-antisymmetric {x y : E} : x <= y -> y <= x -> x = y
  | univalence => Cat.makeUnivalence (\lam (e : Iso) => (<=-antisymmetric e.f e.hinv, prop-pi))
}

\instance ProductPreorder (P Q : Preorder) : Preorder (\Sigma P Q) 
  | <= => \lam (x, y) (x', y') => \Sigma (x <= x') (y <= y')
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}

\instance ProductPoset (P Q : Poset) : Poset (\Sigma P Q) 
  | Preorder => ProductPreorder P Q
  | <=-antisymmetric => {?hidden_proof}

\func subPoset {P : Poset} (S : P -> \Prop) : Poset (\Sigma (x : P) (S x)) \cowith
  | <= => \lam x y => x.1 <= y.1
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}