\import Algebra.Module
\import Algebra.Module.ModuleCategory
\import Algebra.Module.LinearMap
\import Algebra.Ring
\import Category.Functor
\import Paths.Meta
\import Set.SetCategory

\instance PowerLModule {R : Ring} (J : \Set) (M : LModule R) : LModule R (J -> M) 
  | zro => \lam _ => M.zro
  | + => \lam f g j => f j M.+ g j
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | negative => \lam f j => M.negative (f j)
  | negative-left => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | *c => \lam r f j => r *c f j
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}

\func FunctorPowerLMod {R : Ring} : Functor SetCat.op (LModuleCat R) \cowith
  | F => \lam I => PowerLModule I (RingLModule R)
  | Func => \lam f => \new LinearMap {
    | func => \lam r j => r (f j)
    | func-+ => idp
    | func-*c => idp
  }
  | Func-id => {?hidden_proof}
  | Func-o => {?hidden_proof}