\import Algebra.Group
\import Algebra.Group.Sub
\import Algebra.Module
\import Algebra.Monoid
\import Algebra.Monoid.Sub
\import Algebra.Pointed
\import Algebra.Pointed.Sub
\import Algebra.Ring
\import Algebra.Ring.Ideal
\import Data.Array
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Paths
\import Paths.Meta

\class SubLModule \extends SubAddGroup {
  | R : Ring
  \override S : LModule R
  | contains_*c {a : R} {b : S} : contains b -> contains (a *c b)
}

\func topSubLModule {R : Ring} (M : LModule R) : SubLModule {
  | R => R
  | S => M
} \cowith
  | contains => \lam _ => \Sigma
  | contains_zro => {?hidden_proof}
  | contains_+ => {?hidden_proof}
  | contains_negative => {?hidden_proof}
  | contains_*c => {?hidden_proof}

\instance SubLModuleSemilattice (R : Ring) (M : LModule R) : TopMeetSemilattice (SubLModule {  | R => R  | S => M}) 
  | <= => \lam U V => \Pi {a : M} -> U a -> V a
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | meet => meet
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | top => topSubLModule M
  | top-univ => {?hidden_proof}

\func \infixl 7 *m {R : Ring} (I : LIdeal R) {M : LModule R} (S : SubLModule {  | R => R  | S => M}) : SubLModule {
  | R => R
  | S => M
} \cowith
  | contains => \lam a => ∃ (l : Array (\Sigma (x : R) (I x) M)) (a = M.BigSum (map (\lam s => s.1 *c s.3) l))
  | contains_zro => {?hidden_proof}
  | contains_+ => {?hidden_proof}
  | contains_negative => {?hidden_proof}
  | contains_*c => {?hidden_proof}

\func OneDimSubmod {R : Ring} {L : LModule R} (v : L) : SubLModule R L \cowith
  | contains => \lam u => ∃ (r : R) (r *c v = u)
  | contains_zro => {?hidden_proof}
  | contains_+ => {?hidden_proof}
  | contains_negative => {?hidden_proof}
  | contains_*c => {?hidden_proof}