\import Homotopy.Pushout
\import Homotopy.Space
\import Homotopy.Suspension
\import Logic
\import Paths

\class Connected0 \extends InhSpace {
  | isConn0 (x y : E) : TruncP (x = y)
}

\instance UnitConnected0 : Connected0 (\Sigma) 
  | isInh => {?hidden_proof}
  | isConn0 => {?hidden_proof}

\instance PushoutConnected0 {A : InhSpace} {B C : Connected0} {f : A -> B} {g : A -> C} : Connected0 (PushoutData f g) 
  | isInh => {?hidden_proof}
  | isConn0 => {?hidden_proof}