\import Equiv
\import Paths

\record Square (U : \Type) (V : \Type) (X : \Type) (Y : \Type) (ux : U -> X) (vy : V -> Y) (uv : U -> V) (xy : X -> Y) (sqcomm : \Pi (u : U) -> vy (uv u) = xy (ux u))
  \where {
    \func pull (s : Square) {U' : \Type} (f : U' -> s.U) : Square => \new s {
      | U => U'
      | ux => \lam u' => s.ux (f u')
      | uv => \lam u' => s.uv (f u')
      | sqcomm => \lam z => s.sqcomm (f z)
    }

    \func push (s : Square) {Y' : \Type} (f : s.Y -> Y') : Square => \new s {
      | Y => Y'
      | vy => \lam v => f (s.vy v)
      | xy => \lam x => f (s.xy x)
      | sqcomm => \lam u => pmap f (s.sqcomm u)
    }
  }


\open Square (pull, push)

\class Pullback (square : Square) {
  | pullback-univ {Z : \Type} : Equiv {Z -> square.U} {Square {  | U => Z  | V => square.V  | X => square.X  | Y => square.Y  | vy => square.vy  | xy => square.xy}} (pull square)
}

\func sigmaPullback {V X Y : \Type} (vy : V -> Y) (xy : X -> Y) : Pullback \cowith
  | square {
    | U => \Sigma (v : V) (x : X) (p : vy v = xy x)
    | V => V
    | X => X
    | Y => Y
    | ux => \lam p => p.2
    | vy => vy
    | uv => \lam p => p.1
    | xy => xy
    | sqcomm => \lam p => p.3
  }
  | pullback-univ => {?hidden_proof}

\func productPullback (A B : \Type) : Pullback \cowith
  | square {
    | U => \Sigma A B
    | V => A
    | X => B
    | Y => \Sigma
    | ux => \lam p => p.2
    | vy => \lam _ => ()
    | uv => \lam p => p.1
    | xy => \lam _ => ()
    | sqcomm => \lam _ => idp
  }
  | pullback-univ => {?hidden_proof}

\func pathPullback {A : \Type} (x y : A) : Pullback \cowith
  | square {
    | U => x = y
    | V => \Sigma
    | X => \Sigma
    | Y => A
    | ux => \lam _ => ()
    | vy => \lam _ => x
    | uv => \lam _ => ()
    | xy => \lam _ => y
    | sqcomm => \lam p => p
  }
  | pullback-univ => {?hidden_proof}