\import Algebra.Meta
\import Category
\import Category.Functor
\import Category.Limit
\import Data.Array
\import Data.Or
\import Equiv(Equiv, QEquiv)
\import Function.Meta
\import Logic
\import Logic.Classical
\import Logic.FirstOrder.Algebraic
\import Logic.FirstOrder.Term
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set \hiding (#)
\import Set.SetCategory
\import Set.Fin

\class ModelHom {
  | T : Theory
  | Dom : Model T
  | Cod : Model T
  | funcs {s : Sort} : Dom s -> Cod s
  | func-op {r : Sort} (h : Symb r) (d : DArray (\lam j => Dom (domain h j))) : funcs (operation h d) = operation h (\lam j => funcs (d j))
  | func-rel (P : PredSymb) (d : DArray (\lam j => Dom (predDomain P j))) : relation P d -> relation P (\lam j => funcs (d j))
}

\instance ModelCat (T : Theory) : BicompleteCat (Model T) 
  | Precat => ModelPrecat T
  | univalence => {?hidden_proof}
  | limit => \lam {J} (G : Functor) => \new Limit {
    | apex => \new Model {
      | Structure => limitStructure T G
      | isModel => \lam S a rho h => propExt.conv (limitStructureTruth S.4) (\lam j => isModel S a (\lam v => (rho v).1 j) (\lam k => propExt.dir (limitStructureTruth (S.3 k)) (h k) j))
    }
    | coneMap => \lam j => \new ModelHom {
      | funcs => \lam P => P.1 j
      | func-op => \lam _ _ => idp
      | func-rel => \lam P d h => h j
    }
    | coneCoh => \lam f => exts (\lam P => P.2 f)
    | limMap => \lam (c : Cone) => \new ModelHom {
      | funcs => \lam x => (\lam j => c.coneMap j x, \lam f => (c.coneCoh f @ __) x)
      | func-op => \lam h d => ext $ ext (\lam j => func-op h d)
      | func-rel => \lam P d x j => func-rel P d x
    }
    | limBeta => \lam c j => idp
    | limUnique => \lam p => exts (\lam e => exts (\lam j i => funcs {p j i} e))
  }
  | colimit => \lam G => (
    \let data => \new (ColimitData G)
    \in \new Limit {
          | apex => Colimit
          | coneMap => colimitMap
          | coneCoh => colimitCone.coneCoh
          | isLimit => isColimit
        })
  \where {
    \open Structure
    \open Theory
    \open ColimitData \hiding (T, thExt, ColimitStr)

    \func emptyFin {S : \Set} : FinSet (\Sigma S Empty) \cowith
      | finCard => 0
      | finEq => {?hidden_proof}

    \instance ModelPrecat (T : Theory) : Precat (Model T) 
      | Hom => \lam M N => ModelHom M N
      | id => \lam M => \new ModelHom {
        | funcs => \lam x => x
        | func-op => \lam _ _ => idp
        | func-rel => \lam _ _ p => p
      }
      | o => \lam g f => \new ModelHom {
        | funcs => \lam x => g (f x)
        | func-op => \lam h d => rewrite (func-op {f} h d) (func-op {g} h _)
        | func-rel => \lam P d x => func-rel P (\lam j => f (d j)) (func-rel P d x)
      }
      | id-left => {?hidden_proof}
      | id-right => {?hidden_proof}
      | o-assoc => {?hidden_proof}

\class ColimitData {
      | J : SmallPrecat
      | T : Theory
      | G : Functor J (ModelPrecat T)
    }

    \func limitStructure (T : Theory) {J : SmallPrecat} (G : Functor J (ModelPrecat T)) : Structure T \cowith
      | E => \lam s => \Sigma (P : \Pi (j : J) -> G j s) (\Pi {j j' : J} (h : Hom j j') -> G.Func h (P j) = P j')
      | operation => \lam h d => (\lam j => operation h (\lam k => (d k).1 j), \lam {j} {j'} f => func-op {G.Func f} h (\lam k => (d k).1 j) *> cong (ext (\lam k => (d k).2 f)))
      | relation => \lam P d => \Pi (j : J) -> relation P (\lam k => (d k).1 j)

    \lemma limitStructureInterp {T : Theory} {J : SmallPrecat} {G : Functor J (ModelPrecat T)} {V : Sort -> \Set} {rho : Env {limitStructure T G} V} {s : Sort} (t : Term V s) {j : J} :
      (interpret rho t).1 j = interpret (\lam v => (rho v).1 j) t => {?hidden_proof}

    \lemma limitStructureTruth {T : Theory} {J : SmallPrecat} {G : Functor J (ModelPrecat T)} {V : Sort -> \Set} {rho : Env {limitStructure T G} V} (phi : Formula V) :
      isFormulaTrue rho phi = (\Pi (j : J) -> isFormulaTrue (\lam v => (rho v).1 j) phi) => {?hidden_proof}
  }
