\import Data.Bool
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.LinearOrder

\instance BoolLattice : BoundedDistributiveLattice Bool 
  | <= => <=
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | meet => and
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | join => or
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  | top => true
  | top-univ => {?hidden_proof}
  | bottom => false
  | bottom-univ => {?hidden_proof}
  | ldistr>= => {?hidden_proof}
  \where {
\data \infix 4 <= (x y : Bool) \with
      | false, _ => false<=_
      | true, true => true<=true
  }


\instance BoolPoset : Dec Bool 
  | < => <
  | <-irreflexive => {?hidden_proof}
  | <-transitive => {?hidden_proof}
  | trichotomy => {?hidden_proof}
  \where {
    \open LinearOrder

\data \infix 4 < (x y : Bool) \with
      | false, true => false<true
  }
