\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ordered
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Local
\import Algebra.Semiring
\import Arith.Real
\import Function.Meta
\import Logic
\import Meta
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Arith.Real.Field

\record Complex (re : Real) (im : Real)

\instance ComplexField : Field Complex 
  | zro => \new (Complex 0 0)
  | + => \lam (x y : Complex) => \new (Complex (x.re + y.re) (x.im + y.im))
  | zro-left => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | CMonoid => ComplexMonoid
  | ldistr => {?hidden_proof}
  | negative => \lam (x : Complex) => \new (Complex (negative x.re) (negative x.im))
  | negative-left => {?hidden_proof}
  | zro/=ide => {?hidden_proof}
  | locality => {?hidden_proof}
  | #0-tight => {?hidden_proof}
  \where {
    \open Monoid (Inv)

    \instance ComplexMonoid : CMonoid Complex 
      | ide => \new (Complex 1 0)
      | * => \lam (x y : Complex) => \new (Complex (x.re * y.re - x.im * y.im) (x.re * y.im + x.im * y.re))
      | ide-left => {?hidden_proof}
      | *-assoc => {?hidden_proof}
      | *-comm => {?hidden_proof}

    \lemma inv-char {x : Complex} : Inv x <-> Inv x.re || Inv x.im => {?hidden_proof}
  }
