\import Algebra.Domain.Euclidean
\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Monoid.Prime
\import Algebra.Ring
\import Algebra.Semiring
\import Arith.Int
\import Arith.Nat
\import Data.Or
\import Function
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set \hiding (#)
\open Nat(div, mod, divModProp)
\open AddMonoid

\lemma int_n*_+_mod_n {n r : Nat} {q : Int} (r<=n : r < suc n) : (pos (suc n) * q + r) mod suc n = r => {?hidden_proof}
  \where {
    \open IntEuclidean
  }


\lemma int_n*_+_mod_n=mod {n : Nat} {q r : Int} : (pos (suc n) * q + r) mod suc n = r mod suc n => {?hidden_proof}
  \where {
    \open IntEuclidean
  }


\lemma int_mod_*-left {n : Nat} {a b : Int} : (pos (a mod suc n) * b) mod suc n = (a * b) mod suc n => {?hidden_proof}
  \where {
    \open IntEuclidean
  }


\lemma int_mod_*-right {n : Nat} {a b : Int} : (a * b mod suc n) mod suc n = (a * b) mod suc n => {?hidden_proof}
  \where {
    \open IntEuclidean
  }


\lemma div_suc-lem {n m : Nat} (m/=0 : m /= 0) : (n + m) div m = suc (n div m) => {?hidden_proof}

\lemma n*_+_div_n=div {m q r : Nat} (m/=0 : m /= 0) : (m * q + r) div m = q + r div m => {?hidden_proof}

\lemma *_div=id {m q : Nat} (m/=0 : m /= 0) : (q * m) div m = q => {?hidden_proof}

\lemma div-monotone {n k m : Nat} (p : n <= k) : n div m <= k div m => {?hidden_proof}
  \where {
    \lemma aux (c : Nat) {n k m : Nat} (q : n <= c) (p : n <= k) : n div m <= k div m => {?hidden_proof}
  }


\func base-digit (n b j : Nat) : Nat \elim j
  | 0 => n mod b
  | suc j => base-digit (n div b) b j

\lemma base-digit-sum {l : Array Nat} {b : Nat} (p : \Pi (j : Fin l.len) -> l j < b) {j : Fin l.len} : l j = base-digit (BigSum (\lam j => l j * Monoid.pow b j)) b j => {?hidden_proof}

\instance FinRing {n : Nat} : CRing.Dec (Fin (suc n)) 
  | zro => 0
  | + => \lam x y => x + y : Nat
  | zro-left => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | ide => Fin.fromNat 1
  | * => \lam x y => x * y : Nat
  | ide-left => {?hidden_proof}
  | *-assoc => {?hidden_proof}
  | ldistr => {?hidden_proof}
  | negative => \lam x => iabs (suc n Nat.- x)
  | negative-left => {?hidden_proof}
  | decideEq => {?hidden_proof}
  | *-comm => {?hidden_proof}
  | natCoef => Fin.fromNat
  | natCoefZero => {?hidden_proof}
  | natCoefSuc => {?hidden_proof}
  \where {
    \open IntEuclidean

    \lemma mod-mod (a : Int) (n : Nat) : a mod pos (suc n) Nat.mod suc n = {Nat} a mod pos (suc n) => {?hidden_proof}

    \lemma ldiv-modEq (x y : Int) (n : Nat) (p : ∃ (Monoid.LDiv {IntEuclidean} (suc n) (x - y))) : x mod suc n = y mod suc n => {?hidden_proof}

    modEq-ldiv (x y : Int) (n : Nat) (p : x mod suc n = y mod suc n) : Monoid.LDiv {IntEuclidean} (suc n) (x - y) => 
      \have A x => divModProp x (suc n) (\case __ \with {})
      \in rewriteI (A x, A y, p) (\new Monoid.LDiv {  | inv => x div pos (suc n) - y div pos (suc n)  | inv-right => rewrite AbGroup.sum-cancel-right Ring.ldistr_-})

    \lemma finEq-modeq {x y n : Nat} (p : x = {Fin (suc n)} y) : x Nat.mod suc n = {Nat} y Nat.mod suc n => {?hidden_proof}

    \lemma ldiv-finEq {x y n : Nat} (p : ∃ (Monoid.LDiv {IntEuclidean} (suc n) (x Nat.- y))) : x = {Fin (suc n)} y => {?hidden_proof}

    \lemma intCoef-char (n : Nat) (k : Int) : (FinRing {n}).intCoef k = k mod suc n => {?hidden_proof}

    \lemma intCoef_pos-char {n : Nat} (k : Nat) : (FinRing {n}).intCoef (pos k) = k => {?hidden_proof}

    \lemma intCoef-surj {n : Nat} : IsSurj (FinRing {n}).intCoef => {?hidden_proof}
      \where {
        \lemma aux {n : Nat} (k : Fin (suc n)) : (FinRing {n}).natCoef k = k => {?hidden_proof}
      }

  }


\instance FinEuclidean {n : Nat} : EuclideanRingData (Fin (suc n)) 
  | CRing => FinRing {n}
  | decideEq => {?hidden_proof}
  | euclideanMap => \lam x => x
  | divMod => \lam x y => (
    \let! (d, m) => Nat.divMod x y
    \in (d `mod` suc n, m `mod` suc n))
  | isDivMod => {?hidden_proof}
  | isEuclideanMap => {?hidden_proof}

\instance FinField {n : Nat} {p : Prime (suc n)} : DiscreteField (Fin (suc n)) 
  | CRing => FinRing {n}
  | zro/=ide => {?hidden_proof}
  | finv => \lam x => (IntEuclidean.natDivMod (bezout (pos (suc n)) (pos x)).2 (suc n)).2 mod suc n
  | finv_zro => {?hidden_proof}
  | finv-right => {?hidden_proof}
  | decideEq => {?hidden_proof}
  \where {
    \open EuclideanSemiringData
    \open EuclideanRingData
    \open Monoid(Inv)

    \lemma gcd=1 (p : Prime {NatSemiring}) {x : Nat} (x/=0 : Not (x = 0)) (x<p : x < p) : gcd p x = 1 => {?hidden_proof}
  }
