\import Algebra.Domain.Euclidean
\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Monoid.Sub
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Ring
\import Algebra.Ring.Localization
\import Algebra.Ring.Localization.Field
\import Algebra.Semiring
\import Arith.Fin
\import Arith.Int
\import Arith.Nat
\import Data.Bool
\import Data.Or
\import Function.Meta($)
\import Logic
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\open EuclideanSemiringData
\open Monoid(LDiv)

\data Rat 
  | rat (nom : Int) (denom : Nat) (\property denom/=0 : denom /= 0) (\property reduced : gcd (iabs nom) denom = 1)
  \where {
    \use \coerce fromInt (x : Int) => rat x 1 (\case __ \with {}) (natUnit (reduce*gcd-right (iabs x) 1))

    \func AltRat : CRing => LocRing subset
      \where {
        \func subset : SubMonoid => localization-isOrderedField.positiveSubset IntRing
      }


    \lemma eta {x : Rat} : x = rat (ratNom x) (ratDenom x) ratDenom/=0 (ratReduced x) => {?hidden_proof}

    \lemma ext {x y : Rat} (p : ratNom x = ratNom y) (q : ratDenom x = ratDenom y) : x = y => {?hidden_proof}
  }


\func ratNom (x : Rat) : Int 
  | rat n _ _ _ => n

\func ratDenom (x : Rat) : Nat 
  | rat _ d _ _ => d

\lemma ratDenom/=0 {x : Rat} : ratDenom x /= 0 => {?hidden_proof}

\func ratReduced (x : Rat) : gcd (iabs (ratNom x)) (ratDenom x) = 1 
  | rat _ _ _ p => p

\open Rat(AltRat)

\func makeRat (nom : Int) (denom : Nat) (denom/=0 : denom /= 0) : Rat \elim denom
  | 1 => nom
  | denom => makeRat' nom denom denom/=0
  \where {
    \func makeRat' (nom : Int) (denom : Nat) (denom/=0 : denom /= 0) : Rat \elim nom
      | 0 => rat 0 1 (\case __ \with {}) idp
      | pos suc _ \as nom => 
        \let! (a, b) => reduce nom denom
        \in rat a b (reduce2/=0 nom denom denom/=0) (gcd_reduced nom denom denom/=0)
      | neg suc _ \as nom => 
        \let! (a, b) => reduce nom denom
        \in rat (neg a) b (reduce2/=0 nom denom denom/=0) (gcd_reduced nom denom denom/=0)

    \lemma simp {nom : Int} {denom : Nat} {denom/=0 : denom /= 0} : makeRat nom denom denom/=0 = makeRat' nom denom denom/=0 => {?hidden_proof}

    \lemma reduce1/=0 {a b : Nat} : Not ((reduce (suc a) b).1 = 0) => {?hidden_proof}

    \lemma reduce2/=0 (a b : Nat) (b/=0 : Not (b = 0)) : Not ((reduce a b).2 = 0) => {?hidden_proof}

    \lemma div0 {x : Nat} (a|b : LDiv 0 x) : x = 0 => {?hidden_proof}

    \lemma gcd_reduced (a b : Nat) (b/=0 : Not (b = 0)) : gcd (reduce a b).1 (reduce a b).2 = 1 => {?hidden_proof}

    \lemma signum_nom {nom : Int} {denom : Nat} {denom/=0 : Not (denom = 0)} : signum (ratNom (makeRat nom denom denom/=0)) = signum nom => {?hidden_proof}

    \lemma eta {x : Rat} : makeRat (ratNom x) (ratDenom x) ratDenom/=0 = x => {?hidden_proof}
  }


\func rat_alt (x : Rat) : AltRat => in~ (ratNom x, ratDenom x, signum.signum_pos ratDenom/=0)

\lemma rat_alt-inj {x y : Rat} (p : rat_alt x = rat_alt y) : x = y => {?hidden_proof}

\lemma rat_alt_makeRat {nom : Int} {denom : Nat} {denom/=0 : Not (denom = 0)} {p : signum (pos denom) = 1} : rat_alt (makeRat nom denom denom/=0) = in~ (nom, denom, p) => {?hidden_proof}
  \where {
    \lemma aux {a : Int} {b : Nat} {b/=0 : Not (b = 0)} : ratNom (makeRat a b b/=0) * b = a * ratDenom (makeRat a b b/=0) => {?hidden_proof}

    \lemma aux2 {a b : Nat} (b/=0 : Not (b = 0)) : (reduce a b).1 * b = a * (reduce a b).2 => {?hidden_proof}

    \lemma alt : rat_alt (makeRat nom denom denom/=0) = in~ (nom, denom, signum.signum_pos denom/=0) => {?hidden_proof}
  }


\instance RatField : DiscreteOrderedField Rat 
  | zro => rat 0 1 (\case __ \with {}) idp
  | + => +
  | zro-left => \lam {x} => rat_alt-inj $ +_alt *> AltRat.zro-left {rat_alt x}
  | +-assoc => \lam {x} {y} {z} =>
    rat_alt-inj $ +_alt *> pmap (AltRat.+ rat_alt z) +_alt *> AltRat.+-assoc {rat_alt x} {rat_alt y} {rat_alt z} *> inv (+_alt *> pmap (rat_alt x AltRat.+) +_alt)
  | +-comm => \lam {x} {y} => rat_alt-inj $ +_alt *> AltRat.+-comm {rat_alt x} {rat_alt y} *> inv +_alt
  | ide => rat 1 1 (\case __ \with {}) idp
  | * => *
  | ide-left => \lam {x} => rat_alt-inj $ *_alt *> AltRat.ide-left {rat_alt x}
  | *-assoc => \lam {x} {y} {z} =>
    rat_alt-inj $ *_alt *> pmap (__ AltRat.* rat_alt z) *_alt *> AltRat.*-assoc {rat_alt x} {rat_alt y} {rat_alt z} *> inv (*_alt *> pmap (rat_alt x AltRat.*) *_alt)
  | ldistr => \lam {x} {y} {z} =>
    rat_alt-inj $ *_alt *> pmap (rat_alt x AltRat.*) +_alt *> AltRat.ldistr {rat_alt x} {rat_alt y} {rat_alt z} *> inv (+_alt *> pmap2 AltRat.+ *_alt *_alt)
  | negative => negative
  | negative-left => \lam {x} => rat_alt-inj $ +_alt *> pmap (AltRat.+ rat_alt x) negative_alt *> AltRat.negative-left {rat_alt x} *> LocRing.equals1 idp
  | *-comm => \lam {x} {y} => rat_alt-inj $ *_alt *> AltRat.*-comm {rat_alt x} {rat_alt y} *> inv *_alt
  | isPos => \lam x => isPos (ratNom x)
  | zro/>0 => \case __ \with {}
| positive_+ => mcases {+}
| ide>zro => idp
| positive_* => \lam {x} {y} => cases (x, y) (makeRat.signum_nom *> IntRing.positive_* __ __)
| finv => finv
| finv_zro => idp
| finv-right => \lam {x} x/=0 => (
  \have t : ratNom x IntRing.* ratNom (finv x) = ratDenom x Nat.* ratDenom (finv x) => \case \elim x, \elim x/=0 \with {
          | rat 0 b _ r, x/=0 => absurd (x/=0 (rat_alt-inj (LocRing.equals1 (later simplify))))
          | rat pos suc n b b/=0 reduced, _ => pmap pos *-comm
          | rat neg suc n b b/=0 reduced, _ => pmap pos *-comm
        }
  \in rat_alt-inj $ *_alt *> LocRing.equals1 (ide-right *> t *> inv ide-left))
| decideEq => \lam x y => (\case decideEq (ratNom x) (ratNom y), decideEq (ratDenom x) (ratDenom y) \with {
  | yes p, yes q => yes (Rat.ext p q)
  | no p, _ => no (\lam x=y => p $ pmap ratNom x=y)
  | _, no q => no (\lam x=y => q $ pmap ratDenom x=y)
})
| #0=>eitherPosOrNeg => \lam {x} xInv => (\case \elim x, \elim xInv \with {
  | rat n1 d1 d1/=0 r1, (rat n2 d2 d2/=0 r2, il, _) =>
    IntRing.#0=>eitherPosOrNeg {n1} (\lam n1=0 => (\case inv makeRat.simp *> (rewrite (n1=0, IntRing.zro_*-right) in il) \with {}))
})
| natCoef => \lam n => rat n 1 (\case __ \with {}) idp
| natCoefZero => idp
| natCoefSuc => \lam n => idp
| meet => meet
| meet-left => \lam {x} {y} => (\case \elim x, \elim y \with {
  | rat n1 d1 _ r1, rat n2 d2 _ _ => mcases
})
| meet-right => \lam {x} {y} => (\case \elim x, \elim y \with {
  | rat n1 d1 _ _, rat n2 d2 _ _ => mcases
})
| meet-univ => \lam {x} {y} {z} => (\case \elim x, \elim y, \elim z \with {
  | rat n1 d1 _ _, rat n2 d2 _ _, rat n3 d3 _ _ => \lam p q => mcases
})
| join => join
| join-left => \lam {x} {y} => (\case \elim x, \elim y \with {
  | rat n1 d1 _ _, rat n2 d2 _ r2 => mcases
})
| join-right => \lam {x} {y} => (\case \elim x, \elim y \with {
  | rat n1 d1 _ _, rat n2 d2 _ _ => mcases
})
| join-univ => \lam {x} {y} {z} => (\case \elim x, \elim y, \elim z \with {
  | rat n1 d1 _ _, rat n2 d2 _ _, rat n3 d3 _ _ => \lam p q => mcases
})
  \where {
    \lemma productNonZero {n m : Nat} (n/=0 : Not (n = 0)) (m/=0 : Not (m = 0)) : Not (n Nat.* m = 0) => {?hidden_proof}

    \func \infixl 6 +' (x y : Rat) : Rat 
      | rat xNom xDenom xDenom/=0 _, rat yNom yDenom yDenom/=0 _ =>
        makeRat (xNom IntRing.* yDenom IntRing.+ yNom IntRing.* xDenom) (xDenom Nat.* yDenom) (productNonZero xDenom/=0 yDenom/=0)

    \lemma +=+' {x y : Rat} : x + y = x +' y => {?hidden_proof}

    \lemma +_alt {x y : Rat} : rat_alt (x + y) = rat_alt x AltRat.+ rat_alt y => {?hidden_proof}

    \lemma *_alt {x y : Rat} : rat_alt (x * y) = rat_alt x AltRat.* rat_alt y => {?hidden_proof}

    \lemma negative_alt {x : Rat} : rat_alt (negative x) = AltRat.negative (rat_alt x) => {?hidden_proof}

    \lemma ratNom=0 {x : Rat} (p : ratNom x = 0) : x = rat 0 1 (\case __ \with {}) idp => {?hidden_proof}

    \lemma <-char {q r : Rat} (p : ratNom q IntRing.* ratDenom r < ratNom r IntRing.* ratDenom q) : q RatField.< r => {?hidden_proof}

    \lemma <-char-conv-aux {n1 n2 : Int} {d1 d2 : Nat} {d1/=0 : d1 /= 0} {d2/=0 : d2 /= 0} (r1 : gcd (iabs n1) d1 = 1) {r2 : gcd (iabs n2) d2 = 1} 
    (p : signum (ratNom (rat n2 d2 d2/=0 r2 + negative (rat n1 d1 d1/=0 r1))) = 1) : n1 IntRing.* d2 < n2 IntRing.* d1 => {?hidden_proof}

    \lemma <-char-conv {q r : Rat} (q<r : q RatField.< r) : ratNom q IntRing.* ratDenom r < ratNom r IntRing.* ratDenom q => {?hidden_proof}

    \lemma <=-char {q r : Rat} (p : ratNom q IntRing.* ratDenom r <= ratNom r IntRing.* ratDenom q) : q RatField.<= r => {?hidden_proof}

    \lemma <=-char-conv {q r : Rat} (q<=r : q RatField.<= r) : ratNom q IntRing.* ratDenom r <= ratNom r IntRing.* ratDenom q => {?hidden_proof}

    \lemma suc-inv {n : Nat} : Monoid.Inv {RatField} (suc n) (finv (suc n)) => {?hidden_proof}

    \func mid (a b : Rat) => (a + b) * ratio 1 2

    \lemma mid>left {a b : Rat} (p : a RatField.< b) : a RatField.< mid a b => {?hidden_proof}

    \lemma mid<right {a b : Rat} (p : a RatField.< b) : mid a b RatField.< b => {?hidden_proof}

    \lemma mid-between {a b : Rat} (p : a RatField.< b) : \Sigma (a RatField.< mid a b) (mid a b RatField.< b) => {?hidden_proof}

    \func half (a : Rat) => a * ratio 1 2

    \lemma half>0 {a : Rat} (a>0 : 0 RatField.< a) : 0 RatField.< half a => {?hidden_proof}

    \lemma half<id {a : Rat} (a>0 : 0 RatField.< a) : half a RatField.< a => {?hidden_proof}
  }


\lemma fromInt_<= {x y : Int} (p : x <= y) : x RatField.<= y => {?hidden_proof}
  \where {
    \lemma conv {x y : Int} (p : x RatField.<= y) : x <= y => {?hidden_proof}
  }


\lemma fromInt_< {x y : Int} (p : x < y) : x RatField.< y => {?hidden_proof}
  \where {
    \lemma conv {x y : Int} (p : x RatField.< y) : x < y => {?hidden_proof}
  }


\lemma fromNat_>=0 {n : Nat} : 0 RatField.<= n => {?hidden_proof}

\lemma <=_ratNom {x : Rat} (p : 0 IntRing.<= ratNom x) : 0 RatField.<= x => {?hidden_proof}
  \where {
    \lemma conv {x : Rat} (x>=0 : 0 RatField.<= x) : 0 IntRing.<= ratNom x => {?hidden_proof}
  }


\lemma intRat/=0 {x : Int} (x/=0 : x /= 0) : Rat.fromInt x /= 0 => {?hidden_proof}

\lemma natRat/=0 {n : Nat} (n/=0 : n /= 0) : Rat.fromInt n /= 0 => {?hidden_proof}

\lemma rat*denom-right {q : Rat} : q * ratDenom q = ratNom q => {?hidden_proof}

\lemma rat*denom-left {q : Rat} : ratDenom q RatField.* q = ratNom q => {?hidden_proof}

\lemma rat-split {q : Rat} : q = ratNom q RatField.* RatField.finv (ratDenom q) => {?hidden_proof}

\func ratio (nom : Int) (denom : Nat) : Rat \elim denom
  | 0 => 0
  | suc d \as denom => makeRat nom denom (\case __ \with {})

\instance RatDenseOrder : UnboundedDenseLinearOrder.Dec 
  | LinearOrder.Dec => RatField
  | UnboundedDenseLinearOrder => RatField.denseOrder RatField.suc-inv

\func rat_floor (r : Rat) : Int 
  | rat pos n d _ _ => n Nat.div d
  | rat neg suc _ \as n d _ _ => \case n Nat.mod d \with {
    | 0 => neg (n Nat.div d)
    | suc _ => neg (n Nat.div d) - 1
  }

\lemma rat_floor<=id {r : Rat} : Rat.fromInt (rat_floor r) <= r => {?hidden_proof}

\lemma rat_floor-univ {r : Rat} {x : Int} (x<=r : Rat.fromInt x <= r) : x <= rat_floor r => {?hidden_proof}

\lemma rat_floor>id-1 {r : Rat} : r - 1 < rat_floor r => {?hidden_proof}

\func rat_ceiling (r : Rat) : Int => negative (rat_floor (negative r))

\lemma rat_ceiling>=id {r : Rat} : r <= rat_ceiling r => {?hidden_proof}

\lemma rat_ceiling-univ {r : Rat} {x : Int} (r<=x : r <= x) : rat_ceiling r <= x => {?hidden_proof}

rat_round (r : Rat) : Int => \case LinearOrder.dec<_<= (r - rat_floor r) (ratio 1 2) \with {
  | inl a => rat_floor r
  | inr b => rat_floor r + 1
}

\lemma rat_round-dist {r : Rat} : RatField.abs (Rat.fromInt (rat_round r) - r) <= ratio 1 2 => {?hidden_proof}

\lemma rat_<=-dec {r q : Rat} {so : So (rat_<=_Bool r q)} : r <= q => {?hidden_proof}
  \where {
    \func rat_<=_Bool (r q : Rat) : Bool => int_<=-dec.int_<=_Bool (ratNom r * ratDenom q) (ratNom q * ratDenom r)
  }


\lemma rat_<-dec {r q : Rat} {so : So (rat_<_Bool r q)} : r < q => {?hidden_proof}
  \where {
    \func rat_<_Bool (r q : Rat) : Bool => int_<=-dec.int_<=_Bool (isuc (ratNom r * ratDenom q)) (ratNom q * ratDenom r)
  }


rat_natBound (q : Rat) : \Sigma (n : Nat) (q < n) 
  => (iabs $ rat_ceiling (q + 1), rewrite iabs=abs $ (linarith : q < q + 1) <∘l rat_ceiling>=id <=∘ fromInt_<= LinearlyOrderedAbGroup.abs>=id)

rat_>1_pow-bound {q : Rat} (q>1 : 1 RatField.< q) (B : Rat) : \Sigma (n : Nat) (B < RatField.pow q n) => 
  \have | R => rat_natBound $ B * RatField.finv (q - 1)
        | q-1>0 : 0 RatField.< q - 1 => linarith
        | t => rewrite (linarith : 1 RatField.+ (q - 1) = q) $ aux (<=-less q-1>0) {R.1}
        | s => transport (< _) (*-assoc *> pmap (B *) (RatField.finv-left $ RatField.>_/= q-1>0) *> ide-right) $ <_*_positive-left R.2 q-1>0
  \in (R.1, linarith)
  \where {
    \lemma aux {eps : Rat} (eps>=0 : 0 RatField.<= eps) {n : Nat} : 1 RatField.+ n RatField.* eps <= RatField.pow (1 RatField.+ eps) n => {?hidden_proof}
  }


rat_<1_pow-bound {q : Rat} (q<1 : q < 1) {eps : Rat} (eps>0 : 0 RatField.< eps) : \Sigma (n : Nat) (RatField.pow q n < eps) 
=> \case LinearOrder.dec<_<= (0 : Rat) q \with {
  | inl q>0 => 
    \have R => rat_>1_pow-bound (RatField.finv>1 q>0 q<1) (RatField.finv eps)
    \in (R.1, RatField.finv_<-conv eps>0 $ transportInv (_ <) RatField.finv_pow R.2)
  | inr q<=0 => (1, transportInv (<= _) ide-left q<=0 <∘r eps>0)
}