\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Rat
\import Arith.Real.InfReal
\import Arith.Real.LowerReal
\import Arith.Real.UpperReal
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\open LinearOrder \hiding (<=)

\func \infix 4 <LU (x : ExUpperReal) (y : LowerReal) : \Prop => ∃ (a : Rat) (x.U a) (y.L a)

\lemma <LU-transitive {x : UpperReal} {y z : LowerReal} (p : x <LU y) (q : y <= z) : x <LU z => {?hidden_proof}

\class Real \extends InfReal, UpperReal {
  | LU-focus (eps : Rat) : eps > 0 -> ∃ (a : L) (U (a + eps))
  | LU-located => \lam {q} {r} q<r => (\case LU-focus (r - q) (RatField.pos_>0 q<r) \with {
    | inP (s, Ls, Us+r-q) => \case trichotomy q s \with {
      | less q<s => byLeft (L-closed Ls q<s)
      | equals q=s => byLeft (transportInv L q=s Ls)
      | greater s<q => byRight $ U-closed Us+r-q $ transport (_ <) (equation : q + (r - q) = r) (<_+-left (r - q) s<q)
    }
  })
  | L-inh => TruncP.map (LU-focus 1 idp) (\lam x => (x.1, x.2))
  | U-inh => TruncP.map (LU-focus 1 idp) (\lam x => (x.1 + 1, x.3))
  | LU-focus => \lam eps eps>0 => (\case U-inh \with {
    | inP (r, Ur) => \case LU-focus-bound r eps>0 \with {
      | byLeft Lr => absurd (LU-disjoint Lr Ur)
      | byRight s => inP s
    }
  })
}
  \where {
    \open DiscreteOrderedField
    \open DiscreteField
    \open LinearlyOrderedSemiring

    \use \coerce fromRat (x : Rat) : Real \cowith
      | InfReal => InfReal.fromRat x
      | UpperReal => UpperReal.fromRat x
      | LU-focus => \lam eps eps>0 => inP (x - eps * finv 2, linarith, linarith)

    \lemma real-ext {x y : Real} (p : \Pi {a : Rat} -> x.L a <-> y.L a) : x = y => {?hidden_proof}

    \lemma real-lower-ext {x y : Real} (p : x = {LowerReal} y) : x = y => {?hidden_proof}

    \lemma fromRat-inj {x y : Rat} (p : fromRat x = fromRat y) : x = y => {?hidden_proof}

    \lemma <=-upper {x y : Real} : x RealAbGroup.<= y <-> x ExUpperReal.<= y => {?hidden_proof}

    \lemma =-upper {x y : Real} : (x = y) <-> (x = {ExUpperReal} y) => {?hidden_proof}
  }


\lemma real-upperReal : AddMonoidHom RealAbGroup ExUpperRealAbMonoid (\lam x => x) => {?hidden_proof}

\instance RealPointed : Pointed Real 
  | ide => Real.fromRat 1

\instance RealAbGroup : LinearlyOrderedAbGroup Real 
  | zro => Real.fromRat 0
  | + => +
  | zro-left => Real.real-lower-ext $ +-lower *> {LowerReal} zro-left
  | +-comm => Real.real-lower-ext $ +-lower *> {LowerReal} +-comm *> {LowerReal} inv {LowerReal} +-lower
  | +-assoc => Real.real-lower-ext $ +-lower *> {LowerReal} pmap {LowerReal} (LowerRealAbMonoid.+ _) +-lower *> {LowerReal} LowerRealAbMonoid.+-assoc *> {LowerReal} pmap 
    (_ LowerRealAbMonoid.+) (inv {LowerReal} +-lower) *> {LowerReal} inv {LowerReal} +-lower
  | negative => negative
  | negative-left => \lam {x : Real} => exts (\lam a => ext (\lam r => (\case +_L.1 r \with {  | inP (b, x<-b, c, c<x, a<b+c) => a<b+c <∘ linarith (x.LU-less c<x $ negative_L.1 x<-b)}),
    \lam a<0 => (\case x.LU-focus (a * ratio -1 2) linarith \with {
    | inP (b, b<x, x<b-a/2) => +_L.2 $ inP (RatField.negative (b RatField.+ a * ratio -1 2), negative_L.2 $ simplify x<b-a/2, b, b<x, linarith)})),
    \lam a => ext (\lam r => (\case +_U.1 r \with {  | inP (b, -b<x, c, x<c, b+c<a) => linarith (x.LU-less (negative_U.1 -b<x) x<c) <∘ b+c<a}),
    \lam a>0 => (\case x.LU-focus (a * ratio 1 2) linarith \with {
    | inP (b, b<x, x<b+a/2) => +_U.2 $ inP (RatField.negative b, negative_U.2 $ simplify b<x, _, x<b+a/2, linarith)})))
  | isPos => \lam (x : Real) => x.L 0
  | zro/>0 => \case __ \with {}
| positive_+ => \lam x>0 y>0 => (\case L-rounded x>0 \with {
  | inP (a, a<x, a>0) => +_L.2 $ inP (a, a<x, 0, y>0, simplify a>0)
})
| <_+-comparison => \lam x y r => (\case +_L.1 r \with {
  | inP (b, b<x, c, c<y, b+c>0) => \case dec<_<= 0 b \with {
    | inl b>0 => byLeft (L-closed b<x b>0)
    | inr b<=0 => byRight (L-closed c<y linarith)
  }
})
| <_+-connectedness => \lam p q => exts (\lam a => ext (\lam a<x => (\case dec<_<= a 0 \with {  | inl a<0 => a<0  | inr a>=0 => absurd $ p $ LowerReal.L_<= a<x a>=0}),
  \lam a<0 => (\case LU-located a<0 \with {  | byLeft a<x => a<x  | byRight x<0 => absurd $ q $ negative_L.2 x<0})),
  \lam a => ext (\lam x<a => (\case dec<_<= 0 a \with {  | inl a>0 => a>0  | inr a<=0 => absurd $ q $ negative_L.2 $ UpperReal.U_<= x<a a<=0}),
  \lam a>0 => (\case LU-located a>0 \with {  | byLeft x>0 => absurd $ p x>0  | byRight x<a => x<a})))
| meet => meet
| meet-left => \lam r => (\case +_L.1 r \with {
  | inP (b, s, c, x<-c, b+c>0) => <-irreflexive $ Real.LU-less (meet_L.1 s).1 (U-closed (negative_L.1 x<-c) linarith)
})
| meet-right => \lam r => (\case +_L.1 r \with {
  | inP (_, s, c, y<-c, b+c>0) => <-irreflexive $ Real.LU-less (meet_L.1 s).2 (U-closed (negative_L.1 y<-c) linarith)
})
| meet-univ => \lam z<=x z<=y r => (\case +_L.1 r \with {
  | inP (b, b<z, c, r, b+c>0) => \case meet_U.1 $ negative_L.1 r \with {
    | byLeft x<-c => z<=x $ +_L.2 $ inP (b, b<z, c, negative_L.2 x<-c, b+c>0)
    | byRight y<-c => z<=y $ +_L.2 $ inP (b, b<z, c, negative_L.2 y<-c, b+c>0)
  }
})
| join => join
| join-left => \lam r => (\case +_L.1 r \with {
  | inP (b, b<x, c, r, b+c>0) => LU-disjoint b<x $ U-closed (join_U.1 $ negative_L.1 r).1 linarith
})
| join-right => \lam r => (\case +_L.1 r \with {
  | inP (b, b<y, c, r, b+c>0) => LU-disjoint b<y (U-closed (join_U.1 $ negative_L.1 r).2 linarith)
})
| join-univ => \lam x<=z y<=z r => (\case +_L.1 r \with {
  | inP (b, e, c, z<-c, b+c>0) => \case join_L.1 e \with {
    | byLeft b<x => x<=z $ +_L.2 $ inP (b, b<x, c, z<-c, b+c>0)
    | byRight b<y => y<=z $ +_L.2 $ inP (b, b<y, c, z<-c, b+c>0)
  }
})
  \where {
    \open OrderedSemiring

    \infixl 6 + (x y : Real) : Real \cowith
      | InfReal => x InfRealAbMonoid.+ y
      | U-inh => \case x.U-inh, y.U-inh \with {
        | inP (a, x<a), inP (b, y<b) => inP (a RatField.+ b RatField.+ 1, InfRealAbMonoid.+_U.2 $ inP (a, x<a, b, y<b, linarith))
      }

    \lemma +_L {x y : Real} {a : Rat} : Real.L {x + y} a <-> ∃ (b : x.L) (c : y.L) (a < b RatField.+ c) => {?hidden_proof}

    \lemma +_U {x y : Real} {a : Rat} : Real.U {x + y} a <-> ∃ (b : x.U) (c : y.U) (b RatField.+ c < a) => {?hidden_proof}

    \lemma +-upper {x y : Real} : x + y = x ExUpperReal.+ y => {?hidden_proof}

    \lemma +-lower {x y : Real} : x + y = x LowerRealAbMonoid.+ y => {?hidden_proof}

    \lemma +-rat {x y : Rat} : x + y = {Real} x RatField.+ y => {?hidden_proof}

    \lemma +-inf {x y : Real} : x + y = x InfRealAbMonoid.+ y => {?hidden_proof}

    \lemma *n-upper {n : Nat} {x : Real} : n RealAbGroup.*n x = n ExUpperRealAbMonoid.*n x => {?hidden_proof}

    negative (x : Real) : Real \cowith
      | L => \lam a => x.U (RatField.negative a)
      | L-inh => \case x.U-inh \with {
        | inP (a, x<a) => inP (RatField.negative a, simplify x<a)
      }
    | L-closed => \lam x<-q q'<q => x.U-closed x<-q (RatField.negative_< q'<q)
    | L-rounded => \lam x<-q => (\case x.U-rounded x<-q \with {
      | inP (r, x<r, r<-q) => inP (RatField.negative r, simplify x<r, RatField.negative_<-right r<-q)
    })
    | U => \lam a => x.L (RatField.negative a)
    | U-inh => \case x.L-inh \with {
      | inP (a, a<x) => inP (RatField.negative a, simplify a<x)
    }
    | U-closed => \lam -q<x q<q' => x.L-closed -q<x (RatField.negative_< q<q')
    | U-rounded => \lam -q<x => (\case x.L-rounded -q<x \with {
      | inP (r, r<x, -q<r) => inP (RatField.negative r, simplify r<x, RatField.negative_<-left -q<r)
    })
    | LU-disjoint => \lam p q => x.LU-disjoint q p
    | LU-located => \lam q<r => (\case x.LU-located (RatField.negative_< q<r) \with {
      | byLeft -r<x => byRight -r<x
      | byRight x<-q => byLeft x<-q
    })

    \lemma negative_L {x : Real} {a : Rat} : Real.L {negative x} a <-> x.U (RatField.negative a) => {?hidden_proof}

    \lemma negative_U {x : Real} {a : Rat} : Real.U {negative x} a <-> x.L (RatField.negative a) => {?hidden_proof}

    \lemma negative-rat {x : Rat} : negative x = {Real} RatField.negative x => {?hidden_proof}

    \lemma minus-rat {x y : Rat} : x - {RealAbGroup} y = {Real} x - y => {?hidden_proof}

    meet (x y : Real) : Real \cowith
      | InfReal => InfRealAbMonoid.meet x y
      | U-inh => \case x.U-inh \with {
        | inP (a, x<a) => inP (a, InfRealAbMonoid.meet_U.2 $ byLeft x<a)
      }

    \lemma meet-inf {x y : Real} : meet x y = InfRealAbMonoid.meet x y => {?hidden_proof}

    \lemma meet_L {x y : Real} {a : Rat} : Real.L {meet x y} a <-> (\Sigma (x.L a) (y.L a)) => {?hidden_proof}

    \lemma meet_U {x y : Real} {a : Rat} : Real.U {meet x y} a <-> x.U a || y.U a => {?hidden_proof}

    join (x y : Real) : Real \cowith
      | InfReal => InfRealAbMonoid.join x y
      | U-inh => \case x.U-inh, y.U-inh \with {
        | inP (a, x<a), inP (b, y<b) => inP (a ∨ b, InfRealAbMonoid.join_U.2 (x.U_<= x<a join-left, y.U_<= y<b join-right))
      }

    \lemma join-inf {x y : Real} : join x y = InfRealAbMonoid.join x y => {?hidden_proof}

    \lemma join_L {x y : Real} {a : Rat} : Real.L {join x y} a <-> x.L a || y.L a => {?hidden_proof}

    \lemma join_U {x y : Real} {a : Rat} : Real.U {join x y} a <-> (\Sigma (x.U a) (y.U a)) => {?hidden_proof}

    \lemma join-rat {x y : Rat} : join x y = {Real} x ∨ y => {?hidden_proof}

    \lemma join-upper {x y : Real} : join x y = ExUpperReal.join x y => {?hidden_proof}

    \lemma zro<ide : Real.fromRat 0 RealAbGroup.< Real.fromRat 1 => {?hidden_proof}

    \lemma lower_<-char {x y : Real} : x LowerRealAbMonoid.< y <-> x RealAbGroup.< y => {?hidden_proof}

    \lemma lower_<=-char {x y : Real} : x LowerRealAbMonoid.<= y <-> x RealAbGroup.<= y => {?hidden_proof}

    \lemma diff-rat {x y : Rat} : x - {RealAbGroup} y = {Real} x - y => {?hidden_proof}

    \lemma abs-rat {x : Rat} : RealAbGroup.abs x = {Real} RatField.abs x => {?hidden_proof}

    \lemma dist-rat {x y : Rat} : RealAbGroup.abs (x - {RealAbGroup} y) = {Real} RatField.abs (x - y) => {?hidden_proof}

    \lemma half+half {x : Rat} : RatField.half x + RatField.half x = Real.fromRat x => {?hidden_proof}
  }


\open RealAbGroup(negative_L, +_L)

\lemma real_<-rat-char {x y : Real} : x < y <-> ∃ (a : Rat) (x.U a) (y.L a) => {?hidden_proof}

\lemma real_<-char {x y : Real} : x < y <-> ∃ (a : Rat) (x < a) ((a : Real) < y) => {?hidden_proof}

\lemma real_<_L {a : Rat} {x : Real} : (a : Real) < x <-> x.L a => {?hidden_proof}

\lemma real_<_U {a : Rat} {x : Real} : x < a <-> x.U a => {?hidden_proof}

\lemma real_<_InfReal {x y : Real} : x < y <-> x InfRealAbMonoid.< y => {?hidden_proof}

\lemma real_<=_InfReal {x y : Real} : x <= y <-> x InfRealAbMonoid.<= y => {?hidden_proof}

\lemma rat_real_< {a b : Rat} : a < b <-> Real.fromRat a < Real.fromRat b => {?hidden_proof}

\lemma rat_real_<= {a b : Rat} : a <= b <-> Real.fromRat a <= Real.fromRat b => {?hidden_proof}

\lemma rat_real_meet {a b : Rat} : Real.fromRat (a ∧ b) = Real.fromRat a ∧ Real.fromRat b => {?hidden_proof}

\lemma rat_real_join {a b : Rat} : Real.fromRat (a ∨ b) = Real.fromRat a ∨ Real.fromRat b => {?hidden_proof}

\lemma rat_real_abs {a : Rat} : Real.fromRat (RatField.abs a) = RealAbGroup.abs (Real.fromRat a) => {?hidden_proof}

\instance RealDenseOrder : UnboundedDenseLinearOrder 
  | LinearOrder => RealAbGroup
  | isDense => \lam x<z => (\case real_<-rat-char.1 x<z \with {
    | inP (a, x<a, a<z) => inP (a, real_<_U.2 x<a, real_<_L.2 a<z)
  })
  | withoutUpperBound => \lam x => (\case U-inh {x} \with {
    | inP (a, x<a) => inP (a, real_<_U.2 x<a)
  })
  | withoutLowerBound => \lam x => (\case L-inh {x} \with {
    | inP (a, a<x) => inP (a, real_<_L.2 a<x)
  })

\lemma <=_L-char {x y : Real} : x <= y <-> (\Pi {a : Rat} -> x.L a -> y.L a) => {?hidden_proof}

\lemma <=_U-char {x y : Real} : x <= y <-> (\Pi {a : Rat} -> y.U a -> x.U a) => {?hidden_proof}

\lemma real-located {x a b : Real} (p : a < b) : a < x || x < b => {?hidden_proof}

\lemma real-focus (x : Real) {eps : Real} (eps>0 : 0 < eps) : ∃ (a : Real) (a < x) (x < a + eps) => {?hidden_proof}

\lemma real_join_L {a b : Rat} {x : Real} (a<x : x.L a) (b<x : x.L b) : x.L (a ∨ b) => {?hidden_proof}

\lemma LU-focus-bound-real {x : InfReal} (B : Real) {eps : Real} (eps>0 : eps > 0) : B InfRealAbMonoid.< x || Given (a : Real) (a InfRealAbMonoid.< x) (x < a + eps) => {?hidden_proof}

\lemma inf-real-located {x : InfReal} {a b : Real} (p : a < b) : a InfRealAbMonoid.< x || x < b => {?hidden_proof}

\func inf-real-real (x : InfReal) {B : Real} (x<B : x < B) : Real \cowith
  | InfReal => x
  | U-inh => U-inh {inf-real-bounded x $ inP (B, x<B)}

\func inf-real-bounded (x : InfReal) (xB : ∃ (B : Real) (x < B)) : Real \cowith
  | InfReal => x
  | U-inh => \case xB \with {
    | inP (B, inP (a, x<a, a<B)) => \case U-inh {B} \with {
      | inP (q, B<q) => inP (q, U-closed x<a $ InfReal.LU-less a<B B<q)
    }
  }