\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Rat
\import Arith.Real.InfReal
\import Arith.Real.LowerReal
\import Arith.Real.UpperReal
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\open LinearOrder \hiding (<=)

\func \infix 4 <LU (x : ExUpperReal) (y : LowerReal) : \Prop => ∃ (a : Rat) (x.U a) (y.L a)

\lemma <LU-transitive {x : UpperReal} {y z : LowerReal} (p : x <LU y) (q : y <= z) : x <LU z => {?hidden_proof}

\record Real \extends InfReal, UpperReal {
  | LU-focus (eps : Rat) : eps > 0 -> ∃ (a : L) (U (a + eps))
  | LU-located => \lam {q} {r} q<r => (\case LU-focus (r - q) (RatField.pos_>0 q<r) \with {
    | inP (s, Ls, Us+r-q) => \case trichotomy q s \with {
      | less q<s => byLeft (L-closed Ls q<s)
      | equals q=s => byLeft (transportInv L q=s Ls)
      | greater s<q => byRight $ U-closed Us+r-q $ transport (_ <) (equation : q + (r - q) = r) (<_+-left (r - q) s<q)
    }
  })
  | L-inh => TruncP.map (LU-focus 1 idp) (\lam x => (x.1, x.2))
  | U-inh => TruncP.map (LU-focus 1 idp) (\lam x => (x.1 + 1, x.3))
  | LU-focus => \lam eps eps>0 => (\case U-inh \with {
    | inP (r, Ur) => \case LU-focus-bound r eps>0 \with {
      | byLeft Lr => absurd (LU-disjoint Lr Ur)
      | byRight s => inP s
    }
  })

  \lemma LU_*-focus-right (x>0 : L 0) {d : Rat} (d>1 : 1 < d) : ∃ (a : Rat) (0 < a) (L a) (U (a * d)) => {?hidden_proof}

  \lemma LU_*-focus-left (x>0 : L 0) {c : Rat} (c<1 : c < 1) : ∃ (b : Rat) (L (b * c)) (U b) => {?hidden_proof}
}
  \where {
    \open DiscreteOrderedField
    \open DiscreteField
    \open LinearlyOrderedSemiring

    \use \coerce fromRat (x : Rat) : Real \cowith
      | InfReal => InfReal.fromRat x
      | UpperReal => UpperReal.fromRat x
      | LU-focus => {?hidden_proof}

    \lemma real-ext {x y : Real} (p : \Pi {a : Rat} -> x.L a <-> y.L a) : x = y => {?hidden_proof}

    \lemma real-lower-ext {x y : Real} (p : x = {LowerReal} y) : x = y => {?hidden_proof}

    \lemma fromRat-inj {x y : Rat} (p : fromRat x = fromRat y) : x = y => {?hidden_proof}

    \lemma <=-upper {x y : Real} : x RealAbGroup.<= y <-> x ExUpperReal.<= y => {?hidden_proof}

    \lemma =-upper {x y : Real} : (x = y) <-> (x = {ExUpperReal} y) => {?hidden_proof}
  }


\lemma real-upperReal : AddMonoidHom RealAbGroup ExUpperRealAbMonoid (\lam x => x) => {?hidden_proof}

\instance RealPointed : Pointed Real 
  | ide => Real.fromRat 1

\instance RealAbGroup : LinearlyOrderedAbGroup Real 
  | zro => Real.fromRat 0
  | + => +
  | zro-left => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | negative => negative
  | negative-left => {?hidden_proof}
  | isPos => \lam (x : Real) => x.L 0
  | zro/>0 => {?hidden_proof}
  | positive_+ => {?hidden_proof}
  | <_+-comparison => {?hidden_proof}
  | <_+-connectedness => {?hidden_proof}
  | meet => meet
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | join => join
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  \where {
    \open OrderedSemiring

    \sfunc \infixl 6 + (x y : Real) : Real \cowith
      | InfReal => x InfRealAbMonoid.+ y
      | U-inh => {?hidden_proof}

    \lemma +_L {x y : Real} {a : Rat} : Real.L {x + y} a <-> ∃ (b : x.L) (c : y.L) (a < b RatField.+ c) => {?hidden_proof}

    \lemma +_U {x y : Real} {a : Rat} : Real.U {x + y} a <-> ∃ (b : x.U) (c : y.U) (b RatField.+ c < a) => {?hidden_proof}

    \lemma +-upper {x y : Real} : x + y = x ExUpperReal.+ y => {?hidden_proof}

    \lemma +-lower {x y : Real} : x + y = x LowerRealAbMonoid.+ y => {?hidden_proof}

    \lemma +-rat {x y : Rat} : x + y = {Real} x RatField.+ y => {?hidden_proof}

    \lemma +-inf {x y : Real} : x + y = x InfRealAbMonoid.+ y => {?hidden_proof}

    \lemma *n-upper {n : Nat} {x : Real} : n RealAbGroup.*n x = n ExUpperRealAbMonoid.*n x => {?hidden_proof}

    \sfunc negative (x : Real) : Real \cowith
      | L => \lam a => x.U (RatField.negative a)
      | L-inh => {?hidden_proof}
      | L-closed => {?hidden_proof}
      | L-rounded => {?hidden_proof}
      | U => \lam a => x.L (RatField.negative a)
      | U-inh => {?hidden_proof}
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}
      | LU-disjoint => {?hidden_proof}
      | LU-located => {?hidden_proof}

    \lemma negative_L {x : Real} {a : Rat} : Real.L {negative x} a <-> x.U (RatField.negative a) => {?hidden_proof}

    \lemma negative_U {x : Real} {a : Rat} : Real.U {negative x} a <-> x.L (RatField.negative a) => {?hidden_proof}

    \lemma negative-rat {x : Rat} : negative x = {Real} RatField.negative x => {?hidden_proof}

    \lemma minus-rat {x y : Rat} : x - {RealAbGroup} y = {Real} x - y => {?hidden_proof}

    \sfunc meet (x y : Real) : Real \cowith
      | InfReal => InfRealAbMonoid.meet x y
      | U-inh => {?hidden_proof}

    \lemma meet-inf {x y : Real} : meet x y = InfRealAbMonoid.meet x y => {?hidden_proof}

    \lemma meet_L {x y : Real} {a : Rat} : Real.L {meet x y} a <-> (\Sigma (x.L a) (y.L a)) => {?hidden_proof}

    \lemma meet_U {x y : Real} {a : Rat} : Real.U {meet x y} a <-> x.U a || y.U a => {?hidden_proof}

    \sfunc join (x y : Real) : Real \cowith
      | InfReal => InfRealAbMonoid.join x y
      | U-inh => {?hidden_proof}

    \lemma join-inf {x y : Real} : join x y = InfRealAbMonoid.join x y => {?hidden_proof}

    \lemma join_L {x y : Real} {a : Rat} : Real.L {join x y} a <-> x.L a || y.L a => {?hidden_proof}

    \lemma join_U {x y : Real} {a : Rat} : Real.U {join x y} a <-> (\Sigma (x.U a) (y.U a)) => {?hidden_proof}

    \lemma join-rat {x y : Rat} : join x y = {Real} x ∨ y => {?hidden_proof}

    \lemma join-upper {x y : Real} : join x y = ExUpperReal.join x y => {?hidden_proof}

    \lemma zro<ide : Real.fromRat 0 RealAbGroup.< Real.fromRat 1 => {?hidden_proof}

    \lemma lower_<-char {x y : Real} : x LowerRealAbMonoid.< y <-> x RealAbGroup.< y => {?hidden_proof}

    \lemma lower_<=-char {x y : Real} : x LowerRealAbMonoid.<= y <-> x RealAbGroup.<= y => {?hidden_proof}

    \lemma diff-rat {x y : Rat} : x - {RealAbGroup} y = {Real} x - y => {?hidden_proof}

    \lemma abs-rat {x : Rat} : RealAbGroup.abs x = {Real} RatField.abs x => {?hidden_proof}

    \lemma dist-rat {x y : Rat} : RealAbGroup.abs (x - {RealAbGroup} y) = {Real} RatField.abs (x - y) => {?hidden_proof}

    \lemma half+half {x : Rat} : RatField.half x + RatField.half x = Real.fromRat x => {?hidden_proof}
  }


\open RealAbGroup (negative_L, +_L)

\lemma real_<-rat-char {x y : Real} : x < y <-> ∃ (a : Rat) (x.U a) (y.L a) => {?hidden_proof}

\lemma real_<-char {x y : Real} : x < y <-> ∃ (a : Rat) (x < a) ((a : Real) < y) => {?hidden_proof}

\lemma real_<_L {a : Rat} {x : Real} : (a : Real) < x <-> x.L a => {?hidden_proof}

\lemma real_<_U {a : Rat} {x : Real} : x < a <-> x.U a => {?hidden_proof}

\lemma real_<_InfReal {x y : Real} : x < y <-> x InfRealAbMonoid.< y => {?hidden_proof}

\lemma real_<=_InfReal {x y : Real} : x <= y <-> x InfRealAbMonoid.<= y => {?hidden_proof}

\lemma rat_real_< {a b : Rat} : a < b <-> Real.fromRat a < Real.fromRat b => {?hidden_proof}

\lemma rat_real_<= {a b : Rat} : a <= b <-> Real.fromRat a <= Real.fromRat b => {?hidden_proof}

\lemma rat_real_meet {a b : Rat} : Real.fromRat (a ∧ b) = Real.fromRat a ∧ Real.fromRat b => {?hidden_proof}

\lemma rat_real_join {a b : Rat} : Real.fromRat (a ∨ b) = Real.fromRat a ∨ Real.fromRat b => {?hidden_proof}

\lemma rat_real_abs {a : Rat} : Real.fromRat (RatField.abs a) = RealAbGroup.abs (Real.fromRat a) => {?hidden_proof}

\instance RealDenseOrder : UnboundedDenseLinearOrder 
  | LinearOrder => RealAbGroup
  | isDense => {?hidden_proof}
  | withoutUpperBound => {?hidden_proof}
  | withoutLowerBound => {?hidden_proof}

\lemma <=_L-char {x y : Real} : x <= y <-> (\Pi {a : Rat} -> x.L a -> y.L a) => {?hidden_proof}

\lemma <=_U-char {x y : Real} : x <= y <-> (\Pi {a : Rat} -> y.U a -> x.U a) => {?hidden_proof}

\lemma real-located {x a b : Real} (p : a < b) : a < x || x < b => {?hidden_proof}

\lemma real-focus (x : Real) {eps : Real} (eps>0 : 0 < eps) : ∃ (a : Real) (a < x) (x < a + eps) => {?hidden_proof}

\lemma real_join_L {a b : Rat} {x : Real} (a<x : x.L a) (b<x : x.L b) : x.L (a ∨ b) => {?hidden_proof}

\lemma LU-focus-bound-real {x : InfReal} (B : Real) {eps : Real} (eps>0 : eps > 0) : B InfRealAbMonoid.< x || Given (a : Real) (a InfRealAbMonoid.< x) (x < a + eps) => {?hidden_proof}

\lemma inf-real-located {x : InfReal} {a b : Real} (p : a < b) : a InfRealAbMonoid.< x || x < b => {?hidden_proof}

\func inf-real-real (x : InfReal) {B : Real} (x<B : x < B) : Real \cowith
  | InfReal => x
  | U-inh => {?hidden_proof}

\func inf-real-bounded (x : InfReal) (xB : ∃ (B : Real) (x < B)) : Real \cowith
  | InfReal => x
  | U-inh => {?hidden_proof}