\import Category
\import Category.Meta
\import Logic
\import Paths
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete

\instance PrecoverSpaceCat : Cat PrecoverSpace 
  | Hom => PrecoverMap
  | id => \lam X => PrecoverMap.id
  | o => PrecoverMap.∘
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  | univalence => {?hidden_proof}

\instance CoverSpaceCat : Cat CoverSpace 
  | Hom => CoverMap
  | id => \lam X => CoverMap.id
  | o => CoverMap.∘
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  | univalence => {?hidden_proof}