\import Function
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Logic.TFAE
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.RatherBelow
\import Topology.TopSpace

\func IsCauchyFilter {S : CoverSpace} (F : SetFilter S) : \Prop => \Pi {C : Set (Set S)} -> isCauchy C -> ∃ (U : C) (F U)

\lemma filter-limit-cauchy {X : CoverSpace} {F : SetFilter X} {a : X} (Fa : X.IsFilterLimit F a) : IsCauchyFilter F => {?hidden_proof}

\class WeaklyCauchyFilter \extends WeaklyProperFilter {
  | S : CoverSpace
  | X => S
  | isCauchyFilter {C : Set (Set S)} : isCauchy C -> ∃ (U : C) (F U)
}

\class CauchyFilter \extends WeaklyCauchyFilter, ProperFilter

\class CauchyMap \extends ContMap {
  \override Dom : CoverSpace
  \override Cod : CoverSpace
  | func-cauchy (F : CauchyFilter Dom) : (CauchyFilter Cod) {
    | ProperFilter => ProperFilter-map func F
  }
  | func-cont => \lam Uo => cauchy-open.2 (\lam {x} Ufx => (\case isCauchyFilter {func-cauchy (pointCF x)} $ cauchy-open.1 Uo Ufx \with {
    | inP (V, h, fx<=<V) => cauchy-subset (unfolds in fx<=<V) $ later (\lam {W} g Wx {y} Wy => h (<=<_<= fx<=<V idp) $ g (x, (idp, Wx)) Wy)}))
}
  \where {
    \lemma fromContMap {X : CompleteCoverSpace} {Y : CoverSpace} (f : ContMap X Y) : CauchyMap X Y f => {?hidden_proof}
  }


\class StronglyCauchyMap \extends CauchyMap {
  | func-weak-cauchy (F : WeaklyCauchyFilter Dom) : (WeaklyCauchyFilter Cod) {
    | WeaklyProperFilter => WeaklyProperFilter-map func F
  }
  | func-cauchy => \lam F => \new CauchyFilter {
    | isCauchyFilter => isCauchyFilter {func-weak-cauchy F}
  }
}

\class CoverMap \extends PrecoverMap, StronglyCauchyMap {
  \override Dom : CoverSpace
  \override Cod : CoverSpace
  | func-weak-cauchy => \lam F => \new WeaklyCauchyFilter {
    | isCauchyFilter => \lam Cc => (\case isCauchyFilter {F} (func-cover Cc) \with {
      | inP (U, inP (V, CV, p), FU) => inP (V, CV, transport F p FU)
    })
  }
}
  \where {
    \func id {X : CoverSpace} : CoverMap X X \cowith
      | PrecoverMap => PrecoverMap.id

    \func compose \alias \infixl 8 ∘ {X Y Z : CoverSpace} (g : CoverMap Y Z) (f : CoverMap X Y) : CoverMap X Z \cowith
      | PrecoverMap => g PrecoverMap.∘ f

    \func const {Y X : CoverSpace} (x : X) : CoverMap Y X \cowith
      | PrecoverMap => PrecoverMap.const x

    \lemma closure-univ {X : \Set} {A : Set (Set X) -> \Prop} {S : CoverSpace X} {Y : CoverSpace} 
    (AS : \Pi {C : Set (Set X)} -> isCauchy C -> ClosurePrecoverSpace.Closure A C) (f : Y -> X) 
    (Ap : ∀ {C : A} (isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)))) : CoverMap Y S f => {?hidden_proof}

    \lemma id-denseEmbedding {X : CoverSpace} : PrecoverMap.IsDenseEmbedding {id {X}} => {?hidden_proof}
  }


\lemma CoverTransfer-map {X : \Set} {Y : CoverSpace} (f : X -> Y) : CoverMap (CoverTransfer f) Y f => {?hidden_proof}

\lemma CoverTransfer-univ {X Z : CoverSpace} {Y : \Set} (f : X -> Y) (g : Y -> Z) (fg : CoverMap X Z (\lam x => g (f x))) : CoverMap X (CoverTransfer g) f => {?hidden_proof}

\lemma CoverTransfer_<=< {X : \Set} {Y : CoverSpace} {f : X -> Y} {x : X} {U : Set X} (x<=<U : single x <=< {CoverTransfer f} U) :
  ∃ (V : Set Y) (f ^-1 V ⊆ U) (single (f x) <=< V) => {?hidden_proof}

\instance CauchyFilterPoset (S : CoverSpace) : Poset (CauchyFilter S) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => \lam c => c
  | <=-transitive => \lam f g c => g (f c)
  | <=-antisymmetric => \lam f g => exts (\lam U => ext (f, g))

\type \infix 4 CF~ {S : CoverSpace} (F G : WeaklyCauchyFilter S) : \Prop => \Pi {C : Set (Set S)} -> isCauchy C -> ∃ (U : C) (\Sigma (F U) (G U))

\lemma CF~-sym {S : CoverSpace} {F G : WeaklyCauchyFilter S} (p : F CF~ G) : G CF~ F => {?hidden_proof}

\func CF~_meet {S : CoverSpace} {F G : CauchyFilter S} (p : F CF~ G) : CauchyFilter S \cowith
  | ProperFilter => F ∧ {ProperFilterSemilattice S} G
  | isCauchyFilter => p

\lemma CF~_<= {S : CoverSpace} {F G : WeaklyCauchyFilter S} (p : F ⊆ G) : F CF~ G => {?hidden_proof}

\lemma CF~_<=< {S : CoverSpace} {F G : CauchyFilter S} (F~G : F CF~ G) {U V : Set S} (p : U <=< V) (FU : F U) : G V => {?hidden_proof}

\instance CauchyFilterEquivalence (S : CoverSpace) : Equivalence (CauchyFilter S) 
  | ~ => \lam F G => F CF~ G
  | ~-transitive => \lam p q c => (\case p (isRegular c) \with {
    | inP (U, inP (V, CV, U<=<V), (FU, GU)) => inP (V, CV, (filter-mono FU (<=<_<= U<=<V), CF~_<=< q U<=<V GU))
  })
  | ~-reflexive => \lam c => (\case isCauchyFilter c \with {
    | inP (U, CU, FU) => inP (U, CU, (FU, FU))
  })
  | ~-symmetric => CF~-sym

\class RegularCauchyFilter \extends CauchyFilter {
  | isRegularFilter {U : Set S} : F U -> ∃ (V : Set S) (V <=< U) (F V)
}
  \where {
    \lemma Reg_CF~_<= {X : CoverSpace} {F : RegularCauchyFilter X} {G : CauchyFilter X} (p : F CF~ G) : F ⊆ G => {?hidden_proof}

    \lemma equality {X : CoverSpace} {F G : RegularCauchyFilter X} (p : F CF~ G) : F = G => {?hidden_proof}

    \lemma ratherBelow {X : CoverSpace} (R : Set X -> Set X -> \Prop) (Rl : \Pi {U V W : Set X} -> R U V -> V ⊆ W -> R U W) (Rs : \Pi {U V : Set X} -> R V U -> V ⊆ U) 
    (Xr : ∀ {C : isCauchy} (isCauchy (\lam V => ∃ (U : C) (R V U)))) (F : RegularCauchyFilter X) {U : Set X} (FU : F U) : ∃ (V : Set X) (R V U) (F V) => {?hidden_proof}
  }


\func regCF {X : CoverSpace} (F : CauchyFilter X) : RegularCauchyFilter X \cowith
  | F => \lam U => \Pi {G : CauchyFilter X} -> G ⊆ F -> G U
  | filter-mono => \lam q p c => filter-mono (q c) p
  | filter-top => \lam _ => filter-top
  | filter-meet => \lam p q c => filter-meet (p c) (q c)
  | isProper => \lam p => F.isProper (p <=-refl)
  | isCauchyFilter => \lam c => (\case F.isCauchyFilter (isRegular c) \with {
    | inP (U, inP (V, CV, U<=<V), FU) => inP (V, CV, \lam p => CF~_<=< (CF~-sym $ CF~_<= p) U<=<V FU)
  })
  | isRegularFilter => \lam c => (\case c {\new CauchyFilter {  | F => \lam U => ∃ (V W : Set X) (W <=< V) (V <=< U) (F W)
    | filter-mono => \lam inP (V, W, W<=<V, V<=<U, FW) p => inP (V, W, W<=<V, <=<-left V<=<U p, FW)
    | filter-top => inP (top, top, <=<_top, <=<_top, filter-top)
    | filter-meet => \lam inP (V, W, W<=<V, V<=<U, FW) inP (V', W', W'<=<V', V'<=<U', FW') =>
      inP (V ∧ V', W ∧ W', <=<_meet W<=<V W'<=<V', <=<_meet V<=<U V'<=<U', filter-meet FW FW')
    | isProper => \lam inP (V, W, W<=<V, V<=<U, FW) => TruncP.map (isProper FW) (\lam (x, Wx) => (x, <=<_<= V<=<U (<=<_<= W<=<V Wx)))
    | isCauchyFilter => \lam Cc => (\case F.isCauchyFilter $ isRegular $ isRegular Cc \with {
      | inP (W, inP (V, inP (U, CU, V<=<U), W<=<V), FW) => inP (U, CU, inP (V, W, W<=<V, V<=<U, FW))  })}} 
  (\lam {U} inP (V, W, W<=<V, V<=<U, FW) => filter-mono FW $ <=<_<= W<=<V <=∘ <=<_<= V<=<U)
   \with {
    | inP (V, W, W<=<V, V<=<U, FW) => inP (V, V<=<U, \lam p => CF~_<=< (CF~-sym $ CF~_<= p) W<=<V FW)
  })

\lemma regCF_<= {S : CoverSpace} {F : CauchyFilter S} : regCF F ⊆ F => {?hidden_proof}

\open RatherBelow

\func pointCF {S : CoverSpace} (x : S) : RegularCauchyFilter S \cowith
  | F => \lam U => single x <=< U
  | filter-mono => <=<-left
  | filter-top => <=<_top
  | filter-meet => \lam p q => <=<-right (meet-univ <=-refl <=-refl) (<=<_meet p q)
  | isProper => \lam p => inP (x, <=<_<= p idp)
  | isCauchyFilter => \lam c => S.cauchy-regular-cover c x
  | isRegularFilter => \lam p => (\case S.cauchy-regular-cover (isRegular $ unfolds in p) x \with {
    | inP (V, inP (W, f, V<=<W), x<=<V) => inP (V, <=<-left V<=<W $ f (x, (idp, <=<_<= V<=<W $ <=<_<= x<=<V idp)), x<=<V)
  })

\class SeparatedCoverSpace \extends CoverSpace, HausdorffTopSpace {
  | isSeparatedCoverSpace {x y : E} : (\Pi {C : Set (Set E)} -> isCauchy C -> ∃ (U : C) (\Sigma (U x) (U y))) -> x = y
  | isHausdorff => \lam p => isSeparatedCoverSpace (separated-char 6 7 p)
  | isSeparatedCoverSpace => \lam p => isHausdorff (separated-char 7 6 p)
}
  \where {
    \lemma separated-char {S : CoverSpace} {x y : S} : TFAE (pointCF x ⊆ pointCF y, pointCF x CF~ pointCF y, pointCF x = pointCF y, \Pi {U : Set S} -> single x <=< U <-> single y <=< U, 
      \Pi {U : Set S} -> single x <=< U -> U y, \Pi {U V : Set S} -> single x <=< U -> single y <=< V -> ∃ (U ∧ V), ∀ {U V : isOpen} (U x) (V y) ∃ (U ∧ V), 
      \Pi {C : Set (Set S)} -> isCauchy C -> ∃ (U : C) (\Sigma (U x) (U y))) => {?hidden_proof}
  }


\lemma embedding-inj {X : SeparatedCoverSpace} {Y : PrecoverSpace} {f : PrecoverMap X Y} (fe : f.IsEmbedding) : IsInj f => {?hidden_proof}

\func IsCompleteCoverSpace (S : CoverSpace) => \Pi (F : RegularCauchyFilter S) -> ∃ (x : S) (pointCF x ⊆ F)
  \where {
    \lemma cauchyFilterToPoint (Sc : IsCompleteCoverSpace S) (F : CauchyFilter S) : ∃ (x : S) (pointCF x ⊆ F) => {?hidden_proof}
  }


\class CompleteCoverSpace \extends SeparatedCoverSpace {
  | isComplete : IsCompleteCoverSpace \this
}

\lemma func-cauchy_<= {X Y : CoverSpace} {f : CoverMap X Y} (F G : CauchyFilter X) (p : F ⊆ G) : f.func-cauchy F ⊆ f.func-cauchy G => {?hidden_proof}

\func dense-filter-lift {X Y : CoverSpace} (f : CoverMap X Y) (fd : f.IsDenseEmbedding) (F : CauchyFilter Y) : CauchyFilter X \cowith
  | F => \lam U => ∃ (V' V : Set Y) (f ^-1 V ⊆ U) (V' <=< V) (F V')
  | filter-mono => \lam inP (V', V, p, V'<=<V, FV') U<=U' => inP (V', V, p <=∘ U<=U', V'<=<V, FV')
  | filter-top => inP (top, top, \lam _ => (), <=<_top, filter-top)
  | filter-meet => \lam inP (U', U, p, U'<=<U, FU') inP (V', V, q, V'<=<V, FV') =>
    inP (U' ∧ V', U ∧ V, MeetSemilattice.meet-monotone p q, <=<_meet U'<=<U V'<=<V, filter-meet FU' FV')
  | isProper => \lam inP (V', V, p, V'<=<V, FV') => (\case F.isProper FV' \with {
    | inP (y, V'y) => \case dense-char.1 fd.1 (<=<-right (single_<= V'y) V'<=<V) \with {
      | inP (x, Vfx) => inP (x, p Vfx)
    }
  })
  | isCauchyFilter => \lam Cc => (\case F.isCauchyFilter $ isRegular $ fd.2 Cc \with {
    | inP (V', inP (V, inP (U, CU, p), V'<=<V), FV') => inP (U, CU, inP (V', V, p, V'<=<V, FV'))
  })
  \where {
    \lemma map-equiv (fd : f.IsDenseEmbedding) : f.func-cauchy (dense-filter-lift f fd F) CF~ F => {?hidden_proof}
  }


cauchy-lift {X Y : CoverSpace} {Z : CompleteCoverSpace} (f : CoverMap X Y) (\property fd : f.IsDenseEmbedding) (g : CauchyMap X Z) (y : Y) : Z 
  => Z.filter-point $ g.func-cauchy $ dense-filter-lift f fd (pointCF y)

\func dense-cauchy-lift {X Y : CoverSpace} {Z : CompleteCoverSpace} (f : CoverMap X Y) (fd : f.IsDenseEmbedding) (g : CauchyMap X Z) : CauchyMap Y Z \cowith
  | func => cauchy-lift f fd g
  | func-cauchy => \lam F => \new CauchyFilter {
    | isCauchyFilter => \lam Cc => (\case isCauchyFilter {g.func-cauchy $ dense-filter-lift f fd F} (isRegular Cc) \with {
      | inP (U', inP (U, CU, U'<=<U), inP (V', V, p, V'<=<V, FV')) =>
      inP (U, CU,  filter-mono FV'  (\lam {y} V'y => transportInv U (\peval cauchy-lift f fd g y) $ <=<_<=
        (Z.filter-point-elem U'<=<U (\case <=<-inter $ <=<-right (single_<= V'y) V'<=<V \with {  | inP (V'', y<=<V'', V''<=<V) => inP $ later (V'', V, p, V''<=<V, y<=<V'')})) 
          idp))
    })
  }

\func dense-lift {X Y : CoverSpace} {Z : CompleteCoverSpace} (f : CoverMap X Y) (fd : f.IsDenseEmbedding) (g : CoverMap X Z) : CoverMap Y Z \cowith
  | CauchyMap => dense-cauchy-lift f fd g
  | func-cover => \lam Dc => cauchy-refine (isRegular $ fd.2 $ g.func-cover $ isRegular Dc)
    (\lam {V'} inP (V, inP (U, inP (W', inP (W, DW, W'<=<W), p), q), V'<=<V) =>
  inP (_, inP (W, DW, idp),  \lam {y} V'y => transportInv W (\peval cauchy-lift f fd g y) $ <=<_<=
    (Z.filter-point-elem W'<=<W (\case <=<-inter (<=<-right (single_<= V'y) V'<=<V) \with {
    | inP (V'', y<=<V'', V''<=<V) => inP $ later (V'', V, rewrite p in q, V''<=<V, y<=<V'')})) idp))

\lemma dense-lift-char {X Y : CoverSpace} {Z : CompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) {g : CoverMap X Z} (x : X) : cauchy-lift f fd g (f x) = g x => {?hidden_proof}

\lemma dense-lift-neighborhood {X Y : CoverSpace} {Z : CompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) {g : CoverMap X Z} (y : Y) (W : Set Z) :
  single (cauchy-lift f fd g y) <=< W <-> ∃ (W' : Set Z) (W' <=< W) (V : Set Y) (f ^-1 V ⊆ g ^-1 W') (single y <=< V) => {?hidden_proof}

\open CompleteCoverSpace

\lemma dense-lift-natural {X : CoverSpace} {Y Z : CompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) {g : CoverMap X Z} (F : CauchyFilter X) :
  dense-lift f fd g (Y.filter-point $ f.func-cauchy F) = Z.filter-point (g.func-cauchy F) => {?hidden_proof}

\lemma dense-complete {X Y : CoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) (p : \Pi (F : RegularCauchyFilter X) -> ∃ (y : Y) (pointCF y ⊆ f.func-cauchy F)) : IsCompleteCoverSpace Y 
  => {?hidden_proof}

\func completion {S : CoverSpace} : CoverMap S Completion.coverSpace \cowith
  | func => pointCF
  | func-cover => \lam inP (C, Cc, f) => cauchy-refine (isRegular Cc)
    (\case __ \with {  | inP (U', CU', U<=<U') => \case f CU' \with {
      | inP (V, DV, p) => inP (pointCF ^-1 V, inP (V, DV, idp), \lam Ux => p $ <=<-right (single_<= Ux) U<=<U')  }})
  \where {
    \lemma dense-aux {F : RegularCauchyFilter S} {V : Set (RegularCauchyFilter S)} (r : single F <=< {Completion.coverSpace} V) : F (\lam x => V (completion x)) => {?hidden_proof}

    \lemma isDenseEmbedding : completion.IsDenseEmbedding => {?hidden_proof}
  }


\instance Completion (X : CoverSpace) : CompleteCoverSpace (RegularCauchyFilter X) 
  | CoverSpace => coverSpace
  | isSeparatedCoverSpace => \lam p => RegularCauchyFilter.equality (\lam Cc => (\case p (makeCover Cc) \with {  | inP (_, inP (U, CU, idp), r) => inP (U, CU, r)}))
  | isComplete => dense-complete completion.isDenseEmbedding (\lam F => inP (F, completion.dense-aux {_} {F} __))
  \where {
    \func mkSet (U : Set X) : Set (RegularCauchyFilter X) => \lam F => F U

    \lemma mkSet_<= {U V : Set X} (p : U ⊆ V) : mkSet U ⊆ mkSet V => {?hidden_proof}

    \lemma mkSet-open {U : Set X} (Uo : isOpen U) : isOpen {Completion X} (mkSet U) => {?hidden_proof}

    \lemma pointCF_^-1_<=< {F : RegularCauchyFilter X} {U : Set (RegularCauchyFilter X)} (p : single F <=< {Completion X} U) : F (pointCF ^-1 U) => {?hidden_proof}

    \lemma mkSet_<=<-point {F : RegularCauchyFilter X} {U : Set X} : single F <=< {Completion X} mkSet U <-> F U => {?hidden_proof}

    \func isCCauchy (D : Set (Set (RegularCauchyFilter X))) => ∃ (C : X.isCauchy) (∀ {U : C} ∃ (V : D) (mkSet U ⊆ V))

    \lemma makeCover {C : Set (Set X)} (Cc : isCauchy C) : isCCauchy (\lam V => ∃ (U : C) (V = mkSet U)) => {?hidden_proof}

    \func coverSpace : CoverSpace (RegularCauchyFilter X) \cowith
      | isCauchy => isCCauchy
      | cauchy-cover => \lam {D} inP (C, Cc, p) F => (
        \have | inP (U, CU, FU) => isCauchyFilter Cc
              | inP (V, DV, q) => p CU
        \in inP (V, DV, q FU))
      | cauchy-top => inP (single top, cauchy-top, \lam _ => inP (top, idp, \lam _ => ()))
      | cauchy-refine => \lam inP (E, Ec, g) f => inP (E, Ec, \lam EU => (  \have | inP (V, CV, p) => g EU        | inP (W, DW, q) => f CV  \in inP (W, DW, p <=∘ q)))
      | cauchy-glue => \lam {C} inP (C', C'c, f) {D} Dc => inP (_,  cauchy-glue C'c {\lam U' V' => ∃ (U : C) (V : D U) (mkSet U' ⊆ U) (mkSet V' ⊆ V)}
        (\lam {U'} C'U' => (  \have | inP (U, CU, U'<=U) => f C'U'        | inP (D', D'c, g) => Dc CU
        \in cauchy-refine D'c (\lam {V'} D'V' => (\case g D'V' \with {  | inP (V, DV, V'<=V) => inP (V', inP (U, CU, V, DV, U'<=U, V'<=V), <=-refl)})))),
        \lam {W'} inP (U', V', C'U', inP (U, CU, V, DV, U'<=U, V'<=V), W'=U'V') =>
        inP (U ∧ V, inP (U, V, CU, DV, idp), rewrite W'=U'V' (\lam {F} FU'V' => (U'<=U $ filter-mono FU'V' meet-left, V'<=V $ filter-mono FU'V' meet-right)))
      )
      | isRegular => \lam {D} inP (C, Cc, f) => (
        \have <=<_mkFilters {U' U : Set X} (p : U' <=< U) : mkSet U' <=< mkSet U =>
                unfolds $ inP (_, p, \lam {W} g => inP (mkSet W, \lam (F, (FU', FW)) => (\case isProper (filter-meet FU' FW) \with {  | inP s => mkSet_<= (g s)}), <=-refl))
        \in inP (_, isRegular Cc,  \lam {U'} inP (U, CU, U'<=<U) => (\case f CU \with {
              | inP (V, DV, U<=V) => inP (mkSet U', inP (V, DV, <=<-left (<=<_mkFilters U'<=<U) U<=V), <=-refl)})))
  }


\func completion-lift {X : CoverSpace} {Z : CompleteCoverSpace} (g : CoverMap X Z) : PrecoverMap (Completion X) Z => dense-lift completion completion.isDenseEmbedding g

\lemma completion-lift-char {X : CoverSpace} {Z : CompleteCoverSpace} {g : CoverMap X Z} (x : X) : completion-lift g (pointCF x) = g x => {?hidden_proof}

\lemma completion-lift-unique {X : CoverSpace} {Z : SeparatedCoverSpace} (g h : PrecoverMap (Completion X) Z) (p : \Pi (x : X) -> g (pointCF x) = h (pointCF x)) (y : Completion X) : g y = h y 
  => {?hidden_proof}

\lemma completion-lift-neighborhood {X : CoverSpace} {Z : CompleteCoverSpace} (g : CoverMap X Z) (y : Completion X) (W : Set Z) :
  single (completion-lift g y) <=< W <-> ∃ (W' : Set Z) (W' <=< W) (V : Set X) (y V) (V ⊆ g ^-1 W') => {?hidden_proof}

\lemma completion-lift-natural {X : CoverSpace} {Z : CompleteCoverSpace} {g : CoverMap X Z} (F : CauchyFilter X) :
  completion-lift g (CompleteCoverSpace.filter-point $ completion.func-cauchy F) = CompleteCoverSpace.filter-point (g.func-cauchy F) => {?hidden_proof}

\lemma complete-char {X : CoverSpace} : TFAE (CompleteCoverSpace {  | CoverSpace => X}, ∃ (g : PrecoverMap (Completion X) X) (\Pi (x : X) -> g (pointCF x) = x), 
  ∃ (g : PrecoverMap (Completion X) X) (\Pi (x : X) -> g (pointCF x) = x) (\Pi (y : Completion X) -> pointCF (g y) = y)) => {?hidden_proof}

\lemma Separated-char (X : CoverSpace) : TFAE (SeparatedCoverSpace {  | CoverSpace => X}, \Pi {Y : PrecoverSpace} {f : PrecoverMap X Y} -> f.IsEmbedding -> IsInj f, IsInj (completion {X}), 
  ∃ (Y : SeparatedCoverSpace) (f : PrecoverMap X Y) (IsInj f)) => {?hidden_proof}

\func regPrecoverCauchyFilter {X : PrecoverSpace} (F : ProperFilter X) (Fc : ∀ {C : isCauchy} ∃ (U : C) (F U)) : CauchyFilter (RegPrecoverSpace X) \cowith
  | ProperFilter => F
  | isCauchyFilter => \lam Cc => ClosurePrecoverSpace.closure-filter F (\lam inP ((A, A<=X), CAc) => Fc $ A<=X CAc) Cc

\lemma regPrecoverSpace-extend-coverMap {X : PrecoverSpace} {Y : CoverSpace} (f : PrecoverMap X Y) : CoverMap (RegPrecoverSpace X) Y f => {?hidden_proof}