\import Function
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Logic.TFAE
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.RatherBelow
\import Topology.TopSpace

\func IsCauchyFilter {S : CoverSpace} (F : SetFilter S) : \Prop => \Pi {C : Set (Set S)} -> isCauchy C -> ∃ (U : C) (F U)

\lemma filter-limit-cauchy {X : CoverSpace} {F : SetFilter X} {a : X} (Fa : X.IsFilterLimit F a) : IsCauchyFilter F => {?hidden_proof}

\class WeaklyCauchyFilter \extends WeaklyProperFilter {
  | S : CoverSpace
  | X => S
  | isCauchyFilter {C : Set (Set S)} : isCauchy C -> ∃ (U : C) (F U)
}

\class CauchyFilter \extends WeaklyCauchyFilter, ProperFilter

\class CauchyMap \extends ContMap {
  \override Dom : CoverSpace
  \override Cod : CoverSpace
  | func-cauchy (F : CauchyFilter Dom) : (CauchyFilter Cod) {
    | ProperFilter => ProperFilter-map func F
  }
  | func-cont => \lam Uo => cauchy-open.2 (\lam {x} Ufx => (\case isCauchyFilter {func-cauchy (pointCF x)} $ cauchy-open.1 Uo Ufx \with {
    | inP (V, h, fx<=<V) => cauchy-subset (unfolds in fx<=<V) $ later (\lam {W} g Wx {y} Wy => h (<=<_<= fx<=<V idp) $ g (x, (idp, Wx)) Wy)}))
}
  \where {
    \lemma fromContMap {X : CompleteCoverSpace} {Y : CoverSpace} (f : ContMap X Y) : CauchyMap X Y f => {?hidden_proof}
  }


\class StronglyCauchyMap \extends CauchyMap {
  | func-weak-cauchy (F : WeaklyCauchyFilter Dom) : (WeaklyCauchyFilter Cod) {
    | WeaklyProperFilter => WeaklyProperFilter-map func F
  }
  | func-cauchy => \lam F => \new CauchyFilter {
    | isCauchyFilter => isCauchyFilter {func-weak-cauchy F}
  }
}

\class CoverMap \extends PrecoverMap, StronglyCauchyMap {
  \override Dom : CoverSpace
  \override Cod : CoverSpace
  | func-weak-cauchy => \lam F => \new WeaklyCauchyFilter {
    | isCauchyFilter => \lam Cc => (\case isCauchyFilter {F} (func-cover Cc) \with {
      | inP (U, inP (V, CV, p), FU) => inP (V, CV, transport F p FU)
    })
  }
}
  \where {
    \func id {X : CoverSpace} : CoverMap X X \cowith
      | PrecoverMap => PrecoverMap.id

    \func compose \alias \infixl 8 ∘ {X Y Z : CoverSpace} (g : CoverMap Y Z) (f : CoverMap X Y) : CoverMap X Z \cowith
      | PrecoverMap => g PrecoverMap.∘ f

    \func const {Y X : CoverSpace} (x : X) : CoverMap Y X \cowith
      | PrecoverMap => PrecoverMap.const x

    \lemma closure-univ {X : \Set} {A : Set (Set X) -> \Prop} {S : CoverSpace X} {Y : CoverSpace} 
    (AS : \Pi {C : Set (Set X)} -> isCauchy C -> ClosurePrecoverSpace.Closure A C) (f : Y -> X) 
    (Ap : ∀ {C : A} (isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)))) : CoverMap Y S f => {?hidden_proof}

    \lemma id-denseEmbedding {X : CoverSpace} : PrecoverMap.IsDenseEmbedding {id {X}} => {?hidden_proof}
  }


\lemma CoverTransfer-map {X : \Set} {Y : CoverSpace} (f : X -> Y) : CoverMap (CoverTransfer f) Y f => {?hidden_proof}

\lemma CoverTransfer-univ {X Z : CoverSpace} {Y : \Set} (f : X -> Y) (g : Y -> Z) (fg : CoverMap X Z (\lam x => g (f x))) : CoverMap X (CoverTransfer g) f => {?hidden_proof}

\lemma CoverTransfer_<=< {X : \Set} {Y : CoverSpace} {f : X -> Y} {x : X} {U : Set X} (x<=<U : single x <=< {CoverTransfer f} U) :
  ∃ (V : Set Y) (f ^-1 V ⊆ U) (single (f x) <=< V) => {?hidden_proof}

\instance CauchyFilterPoset (S : CoverSpace) : Poset (CauchyFilter S) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}

\type \infix 4 CF~ {S : CoverSpace} (F G : WeaklyCauchyFilter S) : \Prop => \Pi {C : Set (Set S)} -> isCauchy C -> ∃ (U : C) (\Sigma (F U) (G U))

\lemma CF~-sym {S : CoverSpace} {F G : WeaklyCauchyFilter S} (p : F CF~ G) : G CF~ F => {?hidden_proof}

\func CF~_meet {S : CoverSpace} {F G : CauchyFilter S} (p : F CF~ G) : CauchyFilter S \cowith
  | ProperFilter => F ∧ {ProperFilterSemilattice S} G
  | isCauchyFilter => {?hidden_proof}

\lemma CF~_<= {S : CoverSpace} {F G : WeaklyCauchyFilter S} (p : F ⊆ G) : F CF~ G => {?hidden_proof}

\lemma CF~_<=< {S : CoverSpace} {F G : CauchyFilter S} (F~G : F CF~ G) {U V : Set S} (p : U <=< V) (FU : F U) : G V => {?hidden_proof}

\instance CauchyFilterEquivalence (S : CoverSpace) : Equivalence (CauchyFilter S) 
  | ~ => \lam F G => F CF~ G
  | ~-transitive => {?hidden_proof}
  | ~-reflexive => {?hidden_proof}
  | ~-symmetric => {?hidden_proof}

\class RegularCauchyFilter \extends CauchyFilter {
  | isRegularFilter {U : Set S} : F U -> ∃ (V : Set S) (V <=< U) (F V)
}
  \where {
    \lemma Reg_CF~_<= {X : CoverSpace} {F : RegularCauchyFilter X} {G : CauchyFilter X} (p : F CF~ G) : F ⊆ G => {?hidden_proof}

    \lemma equality {X : CoverSpace} {F G : RegularCauchyFilter X} (p : F CF~ G) : F = G => {?hidden_proof}

    \lemma ratherBelow {X : CoverSpace} (R : Set X -> Set X -> \Prop) (Rl : \Pi {U V W : Set X} -> R U V -> V ⊆ W -> R U W) (Rs : \Pi {U V : Set X} -> R V U -> V ⊆ U) 
    (Xr : ∀ {C : isCauchy} (isCauchy (\lam V => ∃ (U : C) (R V U)))) (F : RegularCauchyFilter X) {U : Set X} (FU : F U) : ∃ (V : Set X) (R V U) (F V) => {?hidden_proof}
  }


\func regCF {X : CoverSpace} (F : CauchyFilter X) : RegularCauchyFilter X \cowith
  | F => \lam U => \Pi {G : CauchyFilter X} -> G ⊆ F -> G U
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isProper => {?hidden_proof}
  | isCauchyFilter => {?hidden_proof}
  | isRegularFilter => {?hidden_proof}

\lemma regCF_<= {S : CoverSpace} {F : CauchyFilter S} : regCF F ⊆ F => {?hidden_proof}

\open RatherBelow

\func pointCF {S : CoverSpace} (x : S) : RegularCauchyFilter S \cowith
  | F => \lam U => single x <=< U
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isProper => {?hidden_proof}
  | isCauchyFilter => {?hidden_proof}
  | isRegularFilter => {?hidden_proof}

\class SeparatedCoverSpace \extends CoverSpace, HausdorffTopSpace {
  | isSeparatedCoverSpace {x y : E} : (\Pi {C : Set (Set E)} -> isCauchy C -> ∃ (U : C) (\Sigma (U x) (U y))) -> x = y
  | isHausdorff => \lam p => isSeparatedCoverSpace (separated-char 6 7 p)
  | isSeparatedCoverSpace => \lam p => isHausdorff (separated-char 7 6 p)
}
  \where {
    \lemma separated-char {S : CoverSpace} {x y : S} : TFAE (pointCF x ⊆ pointCF y, pointCF x CF~ pointCF y, pointCF x = pointCF y, \Pi {U : Set S} -> single x <=< U <-> single y <=< U, 
      \Pi {U : Set S} -> single x <=< U -> U y, \Pi {U V : Set S} -> single x <=< U -> single y <=< V -> ∃ (U ∧ V), ∀ {U V : isOpen} (U x) (V y) ∃ (U ∧ V), 
      \Pi {C : Set (Set S)} -> isCauchy C -> ∃ (U : C) (\Sigma (U x) (U y))) => {?hidden_proof}
  }


\lemma embedding-inj {X : SeparatedCoverSpace} {Y : PrecoverSpace} {f : PrecoverMap X Y} (fe : f.IsEmbedding) : IsInj f => {?hidden_proof}

\func IsCompleteCoverSpace (S : CoverSpace) => \Pi (F : RegularCauchyFilter S) -> ∃ (x : S) (pointCF x ⊆ F)
  \where {
    \lemma cauchyFilterToPoint (Sc : IsCompleteCoverSpace S) (F : CauchyFilter S) : ∃ (x : S) (pointCF x ⊆ F) => {?hidden_proof}
  }


\class CompleteCoverSpace \extends SeparatedCoverSpace {
  | isComplete : IsCompleteCoverSpace \this
}

\lemma func-cauchy_<= {X Y : CoverSpace} {f : CoverMap X Y} (F G : CauchyFilter X) (p : F ⊆ G) : f.func-cauchy F ⊆ f.func-cauchy G => {?hidden_proof}

\func dense-filter-lift {X Y : CoverSpace} (f : CoverMap X Y) (fd : f.IsDenseEmbedding) (F : CauchyFilter Y) : CauchyFilter X \cowith
  | F => \lam U => ∃ (V' V : Set Y) (f ^-1 V ⊆ U) (V' <=< V) (F V')
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isProper => {?hidden_proof}
  | isCauchyFilter => {?hidden_proof}
  \where {
    \lemma map-equiv (fd : f.IsDenseEmbedding) : f.func-cauchy (dense-filter-lift f fd F) CF~ F => {?hidden_proof}
  }


cauchy-lift {X Y : CoverSpace} {Z : CompleteCoverSpace} (f : CoverMap X Y) (\property fd : f.IsDenseEmbedding) (g : CauchyMap X Z) (y : Y) : Z 
  => Z.filter-point $ g.func-cauchy $ dense-filter-lift f fd (pointCF y)

\func dense-cauchy-lift {X Y : CoverSpace} {Z : CompleteCoverSpace} (f : CoverMap X Y) (fd : f.IsDenseEmbedding) (g : CauchyMap X Z) : CauchyMap Y Z \cowith
  | func => cauchy-lift f fd g
  | func-cauchy => {?hidden_proof}

\func dense-lift {X Y : CoverSpace} {Z : CompleteCoverSpace} (f : CoverMap X Y) (fd : f.IsDenseEmbedding) (g : CoverMap X Z) : CoverMap Y Z \cowith
  | CauchyMap => dense-cauchy-lift f fd g
  | func-cover => {?hidden_proof}

\lemma dense-lift-char {X Y : CoverSpace} {Z : CompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) {g : CoverMap X Z} (x : X) : cauchy-lift f fd g (f x) = g x => {?hidden_proof}

\lemma dense-lift-neighborhood {X Y : CoverSpace} {Z : CompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) {g : CoverMap X Z} (y : Y) (W : Set Z) :
  single (cauchy-lift f fd g y) <=< W <-> ∃ (W' : Set Z) (W' <=< W) (V : Set Y) (f ^-1 V ⊆ g ^-1 W') (single y <=< V) => {?hidden_proof}

\open CompleteCoverSpace

\lemma dense-lift-natural {X : CoverSpace} {Y Z : CompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) {g : CoverMap X Z} (F : CauchyFilter X) :
  dense-lift f fd g (Y.filter-point $ f.func-cauchy F) = Z.filter-point (g.func-cauchy F) => {?hidden_proof}

\lemma dense-complete {X Y : CoverSpace} {f : CoverMap X Y} (fd : f.IsDenseEmbedding) (p : \Pi (F : RegularCauchyFilter X) -> ∃ (y : Y) (pointCF y ⊆ f.func-cauchy F)) : IsCompleteCoverSpace Y 
  => {?hidden_proof}

\func completion {S : CoverSpace} : CoverMap S Completion.coverSpace \cowith
  | func => pointCF
  | func-cover => {?hidden_proof}
  \where {
    \lemma dense-aux {F : RegularCauchyFilter S} {V : Set (RegularCauchyFilter S)} (r : single F <=< {Completion.coverSpace} V) : F (\lam x => V (completion x)) => {?hidden_proof}

    \lemma isDenseEmbedding : completion.IsDenseEmbedding => {?hidden_proof}
  }


\instance Completion (X : CoverSpace) : CompleteCoverSpace (RegularCauchyFilter X) 
  | CoverSpace => coverSpace
  | isSeparatedCoverSpace => {?hidden_proof}
  | isComplete => {?hidden_proof}
  \where {
    \func mkSet (U : Set X) : Set (RegularCauchyFilter X) => \lam F => F U

    \lemma mkSet_<= {U V : Set X} (p : U ⊆ V) : mkSet U ⊆ mkSet V => {?hidden_proof}

    \lemma mkSet-open {U : Set X} (Uo : isOpen U) : isOpen {Completion X} (mkSet U) => {?hidden_proof}

    \lemma pointCF_^-1_<=< {F : RegularCauchyFilter X} {U : Set (RegularCauchyFilter X)} (p : single F <=< {Completion X} U) : F (pointCF ^-1 U) => {?hidden_proof}

    \lemma mkSet_<=<-point {F : RegularCauchyFilter X} {U : Set X} : single F <=< {Completion X} mkSet U <-> F U => {?hidden_proof}

    \func isCCauchy (D : Set (Set (RegularCauchyFilter X))) => ∃ (C : X.isCauchy) (∀ {U : C} ∃ (V : D) (mkSet U ⊆ V))

    \lemma makeCover {C : Set (Set X)} (Cc : isCauchy C) : isCCauchy (\lam V => ∃ (U : C) (V = mkSet U)) => {?hidden_proof}

    \func coverSpace : CoverSpace (RegularCauchyFilter X) \cowith
      | isCauchy => isCCauchy
      | cauchy-cover => {?hidden_proof}
      | cauchy-top => {?hidden_proof}
      | cauchy-refine => {?hidden_proof}
      | cauchy-glue => {?hidden_proof}
      | isRegular => {?hidden_proof}
  }


\func completion-lift {X : CoverSpace} {Z : CompleteCoverSpace} (g : CoverMap X Z) : PrecoverMap (Completion X) Z => dense-lift completion completion.isDenseEmbedding g

\lemma completion-lift-char {X : CoverSpace} {Z : CompleteCoverSpace} {g : CoverMap X Z} (x : X) : completion-lift g (pointCF x) = g x => {?hidden_proof}

\lemma completion-lift-unique {X : CoverSpace} {Z : SeparatedCoverSpace} (g h : PrecoverMap (Completion X) Z) (p : \Pi (x : X) -> g (pointCF x) = h (pointCF x)) (y : Completion X) : g y = h y 
  => {?hidden_proof}

\lemma completion-lift-neighborhood {X : CoverSpace} {Z : CompleteCoverSpace} (g : CoverMap X Z) (y : Completion X) (W : Set Z) :
  single (completion-lift g y) <=< W <-> ∃ (W' : Set Z) (W' <=< W) (V : Set X) (y V) (V ⊆ g ^-1 W') => {?hidden_proof}

\lemma completion-lift-natural {X : CoverSpace} {Z : CompleteCoverSpace} {g : CoverMap X Z} (F : CauchyFilter X) :
  completion-lift g (CompleteCoverSpace.filter-point $ completion.func-cauchy F) = CompleteCoverSpace.filter-point (g.func-cauchy F) => {?hidden_proof}

\lemma complete-char {X : CoverSpace} : TFAE (CompleteCoverSpace {  | CoverSpace => X}, ∃ (g : PrecoverMap (Completion X) X) (\Pi (x : X) -> g (pointCF x) = x), 
  ∃ (g : PrecoverMap (Completion X) X) (\Pi (x : X) -> g (pointCF x) = x) (\Pi (y : Completion X) -> pointCF (g y) = y)) => {?hidden_proof}

\lemma Separated-char (X : CoverSpace) : TFAE (SeparatedCoverSpace {  | CoverSpace => X}, \Pi {Y : PrecoverSpace} {f : PrecoverMap X Y} -> f.IsEmbedding -> IsInj f, IsInj (completion {X}), 
  ∃ (Y : SeparatedCoverSpace) (f : PrecoverMap X Y) (IsInj f)) => {?hidden_proof}

\func regPrecoverCauchyFilter {X : PrecoverSpace} (F : ProperFilter X) (Fc : ∀ {C : isCauchy} ∃ (U : C) (F U)) : CauchyFilter (RegPrecoverSpace X) \cowith
  | ProperFilter => F
  | isCauchyFilter => {?hidden_proof}

\lemma regPrecoverSpace-extend-coverMap {X : PrecoverSpace} {Y : CoverSpace} (f : PrecoverMap X Y) : CoverMap (RegPrecoverSpace X) Y f => {?hidden_proof}