\import Data.Bool
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Operations
\import Order.Directed
\import Order.Lattice
\import Order.PartialOrder
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.CoverSpace.Product

\func DirectedCoverSpace (I : DirectedSet) : CoverSpace I => RegPrecoverSpace precover
  \where {
    \func precover : PrecoverSpace I \cowith
      | isCauchy => \lam C => \Sigma (∃ (U : C) (N : I) (\Pi {n : I} -> N <= n -> U n)) (\Pi (n : I) -> ∃ (V : C) (V n))
      | cauchy-cover => {?hidden_proof}
      | cauchy-top => {?hidden_proof}
      | cauchy-refine => {?hidden_proof}
      | cauchy-glue => {?hidden_proof}

    \lemma makePrecover (N : I) : precover.isCauchy (\lam V => (V = (\lam n => N <= n)) || Given (n : I) (V = single n)) => {?hidden_proof}
  }


\func EventualityFilter {I : DirectedSet} : CauchyFilter (DirectedCoverSpace I) 
=> regPrecoverCauchyFilter (\new ProperFilter {  | F => \lam U => ∃ (N : I) ∀ {n} (N <= n -> U n)  | filter-mono => \lam inP (N, f) p => inP (N, \lam q => p $ f q)
  | filter-top => \case I.isInhabitted \with {    | inP x => inP (x, \lam _ => ())  }
| filter-meet => \lam inP (N, f) inP (M, g) => (\case isDirected N M \with {
  | inP (L, N<=L, M<=L) => inP (L, \lam p => (f $ N<=L <=∘ p, g $ M<=L <=∘ p))})| isProper => \lam inP (N, f) => inP (N, f <=-refl)}) $ later 
(\lam (inP (U, CU, N, g), _) => inP (U, CU, inP (N, g)))

\func DirectProdCover {I : DirectedSet} {X : CoverSpace} (D : Set (Set (\Sigma I X))) : \Prop 
  => \Sigma (X.isCauchy (\lam U => ∃ (N : I) (V : D) (\Pi {n : I} {x : X} -> N <= n -> U x -> V (n, x)))) 
  (\Pi (n : I) -> X.isCauchy (\lam U => ∃ (V : D) ∀ {x : U} (V (n, x))))
  \where {
    \protected \func Space : PrecoverSpace (\Sigma I X) \cowith
      | isCauchy => DirectProdCover
      | cauchy-cover => {?hidden_proof}
      | cauchy-top => {?hidden_proof}
      | cauchy-refine => {?hidden_proof}
      | cauchy-glue => {?hidden_proof}
  }


\lemma directedProdCover-char {I : DirectedSet} {X : CoverSpace} {D : Set (Set (\Sigma I X))} : isCauchy {DirectedCoverSpace.precover ⨯ X} D <-> DirectProdCover D => {?hidden_proof}