\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.RatherBelow
\import Topology.TopSpace

\instance WeaklyCauchyFilterPoset (S : CoverSpace) : Poset (WeaklyCauchyFilter S) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}

\func WCF~_meet {S : CoverSpace} {F G : WeaklyCauchyFilter S} (p : F CF~ G) : WeaklyCauchyFilter S \cowith
  | WeaklyProperFilter => F ∧ {WeaklyProperFilterSemilattice S} G
  | isCauchyFilter => {?hidden_proof}

\lemma WCF~_<=< {S : CoverSpace} {F G : WeaklyCauchyFilter S} (F~G : F CF~ G) {V U : Set S} (p : V s<=< U) (FV : F V) : G U => {?hidden_proof}

\instance WeaklyCauchyFilterEquivalence (S : StronglyRegularCoverSpace) : Equivalence (WeaklyCauchyFilter S) 
  | ~ => CF~
  | ~-transitive => {?hidden_proof}
  | ~-reflexive => {?hidden_proof}
  | ~-symmetric => {?hidden_proof}

\class StronglyRegularCauchyFilter \extends WeaklyCauchyFilter {
  | isStronglyRegularFilter {U : Set S} : F U -> ∃ (V : Set S) (V s<=< U) (F V)
}
  \where {
    \lemma Reg_CF~_<= {X : StronglyRegularCoverSpace} {F : StronglyRegularCauchyFilter X} {G : WeaklyCauchyFilter X} (p : F CF~ G) : F ⊆ G => {?hidden_proof}

    \lemma equality {X : StronglyRegularCoverSpace} {F G : StronglyRegularCauchyFilter X} (p : F CF~ G) : F = G => {?hidden_proof}
  }


\lemma contMap-cauchy {X : StronglyCompleteCoverSpace} {Y : CoverSpace} (f : ContMap X Y) : StronglyCauchyMap X Y f => {?hidden_proof}

\func sregCF {X : StronglyRegularCoverSpace} (F : WeaklyCauchyFilter X) : StronglyRegularCauchyFilter X \cowith
  | F => \lam U => \Pi {G : WeaklyCauchyFilter X} -> G ⊆ F -> G U
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isWeaklyProper => {?hidden_proof}
  | isCauchyFilter => {?hidden_proof}
  | isStronglyRegularFilter => {?hidden_proof}

\lemma sregCF_<= {S : StronglyRegularCoverSpace} {F : WeaklyCauchyFilter S} : sregCF F ⊆ F => {?hidden_proof}

\open RatherBelow

\func pointSCF {S : StronglyRegularCoverSpace} (x : S) : StronglyRegularCauchyFilter S \cowith
  | F => \lam U => single x <=< U
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isWeaklyProper => {?hidden_proof}
  | isCauchyFilter => {?hidden_proof}
  | isStronglyRegularFilter => {?hidden_proof}

\class StronglySeparatedCoverSpace \extends SeparatedCoverSpace, StronglyRegularCoverSpace, StronglyHausdorffTopSpace {
  | isStronglyHausdorff => \lam {x} {y} p => isSeparatedCoverSpace (\lam Cc => (\case cauchy-regular-cover (isStronglyRegular Cc) x \with {
    | inP (V, inP (U, CU, V<=<U), x<=<V) => \case cauchy-regular-cover V<=<U y \with {
      | inP (_, byLeft idp, y<=<nV) => absurd $ p (interior {_} {V}) (interior {_} {Compl V}) x<=<V y<=<nV (\lam (z, (z<=<V, z<=<nV)) => <=<_<= z<=<nV idp (<=<_<= z<=<V idp))
      | inP (_, byRight idp, y<=<U) => inP (U, CU, (s<=<_<= V<=<U $ <=<_<= x<=<V idp, <=<_<= y<=<U idp))  }}))
}

\func IsStronglyCompleteCoverSpace (S : StronglyRegularCoverSpace) => \Pi (F : StronglyRegularCauchyFilter S) -> ∃ (x : S) (pointSCF x ⊆ F)
  \where {
    \lemma cauchyFilterToPoint (Sc : IsStronglyCompleteCoverSpace S) (F : WeaklyCauchyFilter S) : ∃ (x : S) (pointSCF x ⊆ F) => {?hidden_proof}
  }


\class StronglyCompleteCoverSpace \extends StronglySeparatedCoverSpace, CompleteCoverSpace {
  | isStronglyComplete : IsStronglyCompleteCoverSpace \this
  | isComplete => \lam F => (\case isStronglyComplete (sregCF F) \with {
    | inP (x, p) => inP (x, p <=∘ sregCF_<=)
  })
}

\func weaklyDense-filter-lift {X Y : CoverSpace} (f : CoverMap X Y) (fd : f.IsWeaklyDenseEmbedding) (F : WeaklyCauchyFilter Y) : WeaklyCauchyFilter X \cowith
  | F => \lam U => ∃ (V' V : Set Y) (f ^-1 V ⊆ U) (V' <=< V) (F V')
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isWeaklyProper => {?hidden_proof}
  | isCauchyFilter => {?hidden_proof}
  \where {
    \lemma map-equiv (fd : f.IsWeaklyDenseEmbedding) : f.func-weak-cauchy (weaklyDense-filter-lift f fd F) CF~ F => {?hidden_proof}
  }


\func weaklyDense-cauchy-lift {X : CoverSpace} {Y : StronglyRegularCoverSpace} {Z : StronglyCompleteCoverSpace} (f : CoverMap X Y) (fd : f.IsWeaklyDenseEmbedding) 
(g : StronglyCauchyMap X Z) : StronglyCauchyMap Y Z \cowith
  | func => \lam y => Z.weak-filter-point $ g.func-weak-cauchy $ weaklyDense-filter-lift f fd (pointSCF y)
  | func-weak-cauchy => {?hidden_proof}

\func weaklyDense-lift {X : CoverSpace} {Y : StronglyRegularCoverSpace} {Z : StronglyCompleteCoverSpace} (f : CoverMap X Y) (fd : f.IsWeaklyDenseEmbedding) 
(g : CoverMap X Z) : CoverMap Y Z \cowith
  | func => \lam y => Z.weak-filter-point $ g.func-weak-cauchy $ weaklyDense-filter-lift f fd (pointSCF y)
  | func-cover => {?hidden_proof}

\lemma weaklyDense-lift-char {X : CoverSpace} {Y : StronglyRegularCoverSpace} {Z : StronglyCompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsWeaklyDenseEmbedding) 
{g : CoverMap X Z} (x : X) : weaklyDense-lift f fd g (f x) = g x => {?hidden_proof}

\lemma weaklyDense-lift-neighborhood {X : CoverSpace} {Y : StronglyRegularCoverSpace} {Z : StronglyCompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsWeaklyDenseEmbedding) 
{g : CoverMap X Z} (y : Y) (W : Set Z) :
  single (weaklyDense-lift f fd g y) <=< W <-> ∃ (W' : Set Z) (W' s<=< W) (V : Set Y) (f ^-1 V ⊆ g ^-1 W') (single y <=< V) => {?hidden_proof}

\open StronglyCompleteCoverSpace

\lemma weaklyDense-lift-natural {X : CoverSpace} {Y Z : StronglyCompleteCoverSpace} {f : CoverMap X Y} (fd : f.IsWeaklyDenseEmbedding) {g : CoverMap X Z} (F : WeaklyCauchyFilter X) :
  weaklyDense-lift f fd g (Y.weak-filter-point $ f.func-weak-cauchy F) = Z.weak-filter-point (g.func-weak-cauchy F) => {?hidden_proof}

\lemma func-weak-cauchy_<= {X Y : CoverSpace} {f : CoverMap X Y} (F G : WeaklyCauchyFilter X) (p : F ⊆ G) : f.func-weak-cauchy F ⊆ f.func-weak-cauchy G => {?hidden_proof}

\lemma dense-stronglyComplete {X Y : StronglyRegularCoverSpace} {f : CoverMap X Y} (fd : f.IsWeaklyDenseEmbedding) 
(p : \Pi (F : StronglyRegularCauchyFilter X) -> ∃ (y : Y) (pointSCF y ⊆ f.func-weak-cauchy F)) : IsStronglyCompleteCoverSpace Y => {?hidden_proof}

\func strongCompletion {S : StronglyRegularCoverSpace} : CoverMap S StrongCompletion.coverSpace \cowith
  | func => pointSCF
  | func-cover => {?hidden_proof}
  \where {
    \lemma dense-aux {F : StronglyRegularCauchyFilter S} {V : Set (StronglyRegularCauchyFilter S)} (r : single F <=< {StrongCompletion.coverSpace} V) :
      F (\lam x => V (strongCompletion x)) => {?hidden_proof}

    \lemma isDenseEmbedding : PrecoverMap.IsWeaklyDenseEmbedding {strongCompletion {S}} => {?hidden_proof}
  }


\instance StrongCompletion (X : StronglyRegularCoverSpace) : StronglyCompleteCoverSpace (StronglyRegularCauchyFilter X) 
  | StronglyRegularCoverSpace => coverSpace
  | isSeparatedCoverSpace => {?hidden_proof}
  | isStronglyComplete => {?hidden_proof}
  \where {
    \func mkSet (U : Set X) : Set (StronglyRegularCauchyFilter X) => \lam F => F U

    \lemma mkSet_<= {U V : Set X} (p : U ⊆ V) : mkSet U ⊆ mkSet V => {?hidden_proof}

    \func isCCauchy (D : Set (Set (StronglyRegularCauchyFilter X))) => ∃ (C : X.isCauchy) (∀ {U : C} ∃ (V : D) (mkSet U ⊆ V))

    \lemma makeCover {C : Set (Set X)} (Cc : isCauchy C) : isCCauchy (\lam V => ∃ (U : C) (V = mkSet U)) => {?hidden_proof}

    \func coverSpace : StronglyRegularCoverSpace (StronglyRegularCauchyFilter X) \cowith
      | isCauchy => isCCauchy
      | cauchy-cover => {?hidden_proof}
      | cauchy-top => {?hidden_proof}
      | cauchy-refine => {?hidden_proof}
      | cauchy-glue => {?hidden_proof}
      | isStronglyRegular => {?hidden_proof}

    \lemma pointSCF_^-1_<=< {F : StronglyRegularCauchyFilter X} {U : Set (StronglyRegularCauchyFilter X)} (p : single F <=< {StrongCompletion X} U) : F (pointSCF ^-1 U) => {?hidden_proof}

    \lemma mkSet_<=<-point {F : StronglyRegularCauchyFilter X} {U : Set X} : single F <=< {StrongCompletion X} mkSet U <-> F U => {?hidden_proof}
  }
