\import Function.Meta
\import Logic
\import Logic.Meta
\import Order.Lattice
\import Order.PartialOrder
\import Set.Subset
\import Topology.CoverSpace
\import Topology.TopSpace

\func TopCover {X : TopSpace} (Xr : X.IsRegular) : CoverSpace X \cowith
  | isCauchy => \lam C => \Pi (x : X) -> ∃ (U : C) (V : X.isOpen) (V x) (V ⊆ U)
  | cauchy-cover => {?hidden_proof}
  | cauchy-top => {?hidden_proof}
  | cauchy-refine => {?hidden_proof}
  | cauchy-glue => {?hidden_proof}
  | isRegular => {?hidden_proof}

\lemma top-cover-unit {X : TopSpace} {Xr : X.IsRegular} : ContMap X (TopCover Xr) (\lam x => x) => {?hidden_proof}