\import Function.Meta
\import Logic
\import Logic.Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths.Meta
\import Set.Subset

\class Filter {
  | A : TopMeetSemilattice
  | F : A -> \Prop
  | filter-mono {a b : A} : F a -> a <= b -> F b
  | filter-top : F top
  | filter-meet {a b : A} : F a -> F b -> F (a ∧ b)
}
  \where {
    \func principal {A : TopMeetSemilattice} (a : A) : Filter A \cowith
      | F => a <=
      | filter-mono => <=∘
      | filter-top => top-univ
      | filter-meet => meet-univ
  }


\class CompleteFilter \extends Filter {
  \override A : CompleteLattice
  | filter-Join {J : \Set} {f : J -> A} : F (Join f) -> ∃ (j : J) (F (f j))
}

\class SetFilter \extends Filter {
  | X : \Set
  | A => SetLattice X
}

\func SetFilter-map {X Y : \Set} (f : X -> Y) (F : SetFilter X) : SetFilter Y \cowith
  | F => \lam V => F (f ^-1 V)
  | filter-mono => \lam d p => filter-mono d (p __)
  | filter-top => filter-top
  | filter-meet => filter-meet

\class WeaklyProperFilter \extends SetFilter {
  | isWeaklyProper : Not (F bottom)
}

\class ProperFilter \extends WeaklyProperFilter {
  | isProper {U : Set X} : F U -> ∃ U
  | isWeaklyProper => \lam Fb => (\case isProper Fb \with {
    | inP (x, inP ((), _))
  })
}

\func pointFilter {X : \Set} (x : X) : ProperFilter X \cowith
  | F => \lam U => U x
  | filter-mono => \lam d p => p d
  | filter-top => ()
  | filter-meet => \lam p q => (p, q)
  | isProper => \lam Ux => inP (x, Ux)

\func WeaklyProperFilter-map {X Y : \Set} (f : X -> Y) (F : WeaklyProperFilter X) : WeaklyProperFilter Y \cowith
  | SetFilter => SetFilter-map f F
  | isWeaklyProper => \lam d => F.isWeaklyProper $ F.filter-mono d (\lam inP ((), _) => {?})

\func ProperFilter-map {X Y : \Set} (f : X -> Y) (F : ProperFilter X) : ProperFilter Y \cowith
  | SetFilter => SetFilter-map f F
  | isProper => \lam d => TruncP.map (isProper d) (\lam s => (f s.1, s.2))

\instance WeaklyProperFilterSemilattice (X : \Set) : MeetSemilattice (WeaklyProperFilter X) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => \lam c => c
  | <=-transitive => \lam f g c => g (f c)
  | <=-antisymmetric => \lam f g => exts (\lam U => ext (f, g))
  | meet => \lam F G => \new WeaklyProperFilter {
    | F => \lam U => \Sigma (F U) (G U)
    | filter-mono => \lam s p => (filter-mono s.1 p, filter-mono s.2 p)
    | filter-top => (filter-top, filter-top)
    | filter-meet => \lam s t => (filter-meet s.1 t.1, filter-meet s.2 t.2)
    | isWeaklyProper => \lam s => isWeaklyProper s.1
  }
  | meet-left => \lam s => s.1
  | meet-right => \lam s => s.2
  | meet-univ => \lam f g c => (f c, g c)

\instance ProperFilterSemilattice (X : \Set) : MeetSemilattice (ProperFilter X) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => \lam c => c
  | <=-transitive => \lam f g c => g (f c)
  | <=-antisymmetric => \lam f g => exts (\lam U => ext (f, g))
  | meet => \lam F G => \new ProperFilter {
    | F => \lam U => \Sigma (F U) (G U)
    | filter-mono => \lam s p => (filter-mono s.1 p, filter-mono s.2 p)
    | filter-top => (filter-top, filter-top)
    | filter-meet => \lam s t => (filter-meet s.1 t.1, filter-meet s.2 t.2)
    | isProper => \lam s => isProper s.1
  }
  | meet-left => \lam s => s.1
  | meet-right => \lam s => s.2
  | meet-univ => \lam f g c => (f c, g c)