\import Function.Meta
\import Logic
\import Logic.Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths.Meta
\import Set.Subset

\class Filter {
  | A : TopMeetSemilattice
  | F : A -> \Prop
  | filter-mono {a b : A} : F a -> a <= b -> F b
  | filter-top : F top
  | filter-meet {a b : A} : F a -> F b -> F (a ∧ b)
}
  \where {
    \func principal {A : TopMeetSemilattice} (a : A) : Filter A \cowith
      | F => a <=
      | filter-mono => {?hidden_proof}
      | filter-top => {?hidden_proof}
      | filter-meet => {?hidden_proof}
  }


\class CompleteFilter \extends Filter {
  \override A : CompleteLattice
  | filter-Join {J : \Set} {f : J -> A} : F (Join f) -> ∃ (j : J) (F (f j))
}

\class SetFilter \extends Filter {
  | X : \Set
  | A => SetLattice X
}

\func SetFilter-map {X Y : \Set} (f : X -> Y) (F : SetFilter X) : SetFilter Y \cowith
  | F => \lam V => F (f ^-1 V)
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}

\class WeaklyProperFilter \extends SetFilter {
  | isWeaklyProper : Not (F bottom)
}

\class ProperFilter \extends WeaklyProperFilter {
  | isProper {U : Set X} : F U -> ∃ U
  | isWeaklyProper => \lam Fb => (\case isProper Fb \with {
    | inP (x, inP ((), _))
  })
}

\func pointFilter {X : \Set} (x : X) : ProperFilter X \cowith
  | F => \lam U => U x
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isProper => {?hidden_proof}

\func WeaklyProperFilter-map {X Y : \Set} (f : X -> Y) (F : WeaklyProperFilter X) : WeaklyProperFilter Y \cowith
  | SetFilter => SetFilter-map f F
  | isWeaklyProper => {?hidden_proof}

\func ProperFilter-map {X Y : \Set} (f : X -> Y) (F : ProperFilter X) : ProperFilter Y \cowith
  | SetFilter => SetFilter-map f F
  | isProper => {?hidden_proof}

\instance WeaklyProperFilterSemilattice (X : \Set) : MeetSemilattice (WeaklyProperFilter X) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | meet => \lam F G => \new WeaklyProperFilter {
    | F => \lam U => \Sigma (F U) (G U)
    | filter-mono => \lam s p => (filter-mono s.1 p, filter-mono s.2 p)
    | filter-top => (filter-top, filter-top)
    | filter-meet => \lam s t => (filter-meet s.1 t.1, filter-meet s.2 t.2)
    | isWeaklyProper => \lam s => isWeaklyProper s.1
  }
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}

\instance ProperFilterSemilattice (X : \Set) : MeetSemilattice (ProperFilter X) 
  | <= => \lam F G => F ⊆ G
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | meet => \lam F G => \new ProperFilter {
    | F => \lam U => \Sigma (F U) (G U)
    | filter-mono => \lam s p => (filter-mono s.1 p, filter-mono s.2 p)
    | filter-top => (filter-top, filter-top)
    | filter-meet => \lam s t => (filter-meet s.1 t.1, filter-meet s.2 t.2)
    | isProper => \lam s => isProper s.1
  }
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}