\import Algebra.Monoid
\import Arith.Nat
\import Category
\import Category.Functor
\import Category.Limit
\import Equiv
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set

\instance SetCat : Cat \Set 
  | Hom => \lam X Y => X -> Y
  | id => \lam _ => \lam x => x
  | o => \lam g f => \lam x => g (f x)
  | id-left => {?hidden_proof}
  | id-right => {?hidden_proof}
  | o-assoc => {?hidden_proof}
  | univalence => {?hidden_proof}

SIP_Set (Str : \Set -> \hType (\suc \lp)) (isHom : \Pi {x y : \Set} -> Str x -> Str y -> (x -> y) -> \hType (\suc \lp)) 
(st : \Pi {X : \Set} {S1 S2 : Str X} -> isHom S1 S2 (\lam x => x) -> isHom S2 S1 (\lam x => x) -> S1 = S2) {X Y : \Set} (e : Iso {SetCat} {X} {Y}) 
(S1 : Str X) (S2 : Str Y) (p : isHom S1 S2 e.f) (q : isHom S2 S1 e.hinv) :
  \Sigma (p : X = Y) (Path (\lam i => Str (p @ i)) S1 S2) (\Pi (x : X) -> transport (\lam Z => Z) p x = e.f x) => 
  \have (p, q, s) => SIP SetCat Str isHom st e S1 S2 p q
  \in (p, q, \lam x => inv (transport_pi (\lam _ => X) (\lam Z => Z) p (\lam z => z) x) *> path (\lam i => (s @ i) x))

\instance SetCoproduct {J : \Type} (F : J -> \Set) : Product {J} {SetCat.op} F 
  | apex => Trunc0 (\Sigma (j : J) (F j))
  | proj => \lam j x => in0 (j, x)
  | tupleMap => \lam f in0 (j, x) => f j x
  | tupleBeta => {?hidden_proof}
  | tupleEq => {?hidden_proof}

\instance SetCoequalizer {X Y : \Set} (f g : X -> Y) : Equalizer {SetCat.op} f g 
  | apex => Quotient (\lam y y' => \Sigma (x : X) (f x = y) (g x = y'))
  | eql => in~
  | equal => {?hidden_proof}
  | isEqualizer => {?hidden_proof}

\instance SetBicat : BicompleteCat 
  | Cat => SetCat
  | limit => \lam F => \new Limit {
    | apex => Cone F (\Sigma)
    | coneMap => \lam j x => coneMap {x} j ()
    | coneCoh => \lam h => ext (\lam s => pmap (__ ()) (coneCoh {s} h))
    | isLimit => \lam Z => \new QEquiv {
      | ret => \lam c z => \new Cone {
        | coneMap => \lam j _ => coneMap {c} j z
        | coneCoh => \lam h => ext (\lam _ => pmap (__ z) (coneCoh {c} h))
      }
      | ret_f => idpe
      | f_sec => idpe
    }
  }
  | colimit => \lam {J : Precat} G => limits<=pr+eq {SetCat.op} (\lam J G => SetCoproduct G) (\lam {X} {Y} f g => SetCoequalizer f g) {J.op} (Functor.op {G})
  \where {
    \lemma cone-isLim (c : Cone {  | D => SetCat}) (e : Equiv (conePullback c (\Sigma))) : Limit {
      | Cone => c
    } => {?hidden_proof}
  }


\type SetColimit {J : SmallPrecat} (F : Functor J SetCat) => Quotient {\Sigma (j : J) (F j)} (\lam s s' => \Sigma (p : Hom s.1 s'.1) (F.Func p s.2 = s'.2))
  \where {
    \func inC {J : SmallPrecat} {F : Functor J SetCat} (s : \Sigma (j : J) (F j)) : SetColimit F => in~ s

    \lemma ~-cequiv {J : SmallPrecat} {F : Functor J SetCat} {s s' : \Sigma (j : J) (F j)} (f : Hom s.1 s'.1) (p : F.Func f s.2 = s'.2) : in~ s = {SetColimit F} in~ s' => {?hidden_proof}

    \lemma unext-ub {J : JoinSemilattice} {F : Functor J SetCat} {s s' : \Sigma (j : J) (F j)} (p : inC s = inC s') :
      ∃ (j : J) (p : s.1 <= j) (q : s'.1 <= j) (F.Func p s.2 = F.Func q s'.2) => {?hidden_proof}

    \lemma Func-app {J : SmallPrecat} (F : Functor J SetCat) {j1 j2 j3 : J} {f : Hom j1 j2} {g : Hom j2 j3} {a : F j1} : F.Func (g ∘ f) a = F.Func g (F.Func f a) => {?hidden_proof}

    \lemma poset-app {J : Poset} {F : Functor J SetCat} {j j' : J} {f g : j <= j'} {a : F j} : F.Func f a = F.Func g a => {?hidden_proof}

    \lemma poset-id {J : Poset} {F : Functor J SetCat} {j : J} {p : j <= j} {a : F j} : F.Func p a = a => {?hidden_proof}

    \func inMap (j : J) (a : F j) : SetColimit F => in~ (j, a)

    \lemma inMap-coh {j j' : J} (f : Hom j j') (a : F j) : inMap j a = inMap j' (F.Func f a) => {?hidden_proof}
  }


\func NatFunctor {C : Precat} (F : Nat -> C) (f : \Pi {n : Nat} -> Hom (F n) (F (suc n))) : Functor NatSemiring C \cowith
  | F => F
  | Func => \lam p => natHom (_, <=_exists p)
  | Func-id => {?hidden_proof}
  | Func-o => {?hidden_proof}
  \where {
    \lemma sigma-isProp {n m : Nat} : isProp (\Sigma (k : Nat) (n + k = m)) => {?hidden_proof}

    \func natHom {n m : Nat} (s : \Sigma (k : Nat) (n + k = m)) : Hom (F n) (F m) \elim m, s
      | _, (0, idp) => id (F n)
      | 0, (suc k, ())
      | suc m, (suc k, q) => f ∘ natHom (k, pmap pred q)

    \lemma natHom_id {n : Nat} : natHom (0, idp) = id (F n) => {?hidden_proof}

    \lemma natHom-comp {n m k : Nat} {s : \Sigma (l : Nat) (n + l = m)} {t : \Sigma (l : Nat) (m + l = k)} :
      natHom (s.1 + t.1, inv +-assoc *> pmap (+ _) s.2 *> t.2) = natHom t ∘ natHom s => {?hidden_proof}
  }
