\import Arith.Nat
\import Data.Array (Index, forall, forall-char, map, taild)
\import Data.Bool
\import Data.Fin (nat_fin_=)
\import Data.List \hiding (nil, ::, map)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set

\type TFAE (l : Array \Prop) : \Prop => \Pi (i j : Fin l.len) -> l i -> l j
  \where {
    \lemma proof' {l : Array \Prop} (p : Array (\Sigma (s : \Sigma (Fin l.len) (Fin l.len)) (l s.1 -> l s.2))) {s : So (checkConnected (map __.1 p) l.len)} : TFAE l => {?hidden_proof}
      \where {
        \func Graph (A : \Set) => Array (\Sigma A A)

\data Path {A : \Set} (G : Graph A) (a a' : A) : \Prop 
          | trivial (a = a')
          | step (i : Fin G.len) (a = (G i).1) (Path G (G i).2 a')

        \lemma path-proof {l : Array \Prop} (p : Array (\Sigma (s : \Sigma (Fin l.len) (Fin l.len)) (l s.1 -> l s.2))) {i j : Fin l.len} (c : Path (map __.1 p) i j) (a : l i) : l j 
          => {?hidden_proof}

        \func checkConnected (\strict G : Graph Nat) (t : Nat) : Bool => forall (\lam i => checkConnected1 G i t) (\new (Array Nat t (\lam i => i)))

        \func checkConnected1 (G : Graph Nat) (i t : Nat) : Bool => 
          \let! r => collect G (i List.:: List.nil) (i List.:: List.nil) t
          \in forall (contains r) (\new (Array Nat t (\lam j => j)))

        \func step1 (G : Graph Nat) (ex : List Nat) (i : Nat) : List Nat \elim G
          | nil => List.nil
          | e :: G => \case decideEq i e.1 \with {
            | yes q => if (contains ex e.2) (step1 G ex i) (e.2 List.:: step1 G ex i)
            | no q => step1 G ex i
          }

        \func makeStep (G : Graph Nat) (\strict ex : List Nat) (l : List Nat) : List Nat \elim l
          | List.nil => List.nil
          | i List.:: l => 
            \let! s => step1 G ex i
            \in s ++ makeStep G (union s ex) l

        \func collect (G : Graph Nat) (\strict acc : List Nat) (l : List Nat) (n : Nat) : List Nat \elim n
          | 0 => acc
          | suc n => 
            \let! l' => makeStep G acc l
            \in collect G (union l' acc) l' n

        \lemma checkConnected-correct {n : Nat} {G : Graph (Fin n)} (s : checkConnected G n = true) (i j : Fin n) : Path G i j => {?hidden_proof}

        \lemma Path-Nat_Fin {n : Nat} {G : Graph (Fin n)} {i j : Fin n} (p : Path {Nat} G i j) : Path G i j => {?hidden_proof}

        \lemma checkConnected1-correct {n : Nat} {G : Graph (Fin n)} (i j : Fin n) (s : checkConnected1 G i n = true) : Path G i j => {?hidden_proof}

        \func step1' (G : Graph Nat) (i : Nat) : List Nat \elim G
          | nil => List.nil
          | e :: G => \case decideEq i e.1 \with {
            | yes q => e.2 List.:: step1' G i
            | no q => step1' G i
          }

        \func makeStep' (G : Graph Nat) (l : List Nat) : List Nat \elim l
          | List.nil => List.nil
          | i List.:: l => step1' G i ++ makeStep' G l

        \func collect' (G : Graph Nat) (l : List Nat) (n : Nat) : List Nat \elim n
          | 0 => List.nil
          | suc n => makeStep' G l ++ collect' G (makeStep' G l) n

        \lemma step1'-correct {G : Graph Nat} {i j : Nat} (c : InList j (step1' G i)) : TruncP (Index (i, j) G) => {?hidden_proof}

        \lemma makeStep'-correct {G : Graph Nat} {l : List Nat} {j : Nat} (c : InList j (makeStep' G l)) : ∃ (i : Nat) (InList i l) (Index (i, j) G) => {?hidden_proof}

        \lemma collect'-correct {G : Graph Nat} {l : List Nat} {n j : Nat} (c : InList j (collect' G l n)) : ∃ (i : Nat) (InList i l) (Path G i j) => {?hidden_proof}

        \lemma step1->step1' {G : Graph Nat} {ex : List Nat} {i a : Nat} (c : InList a (step1 G ex i)) : InList a (step1' G i) => {?hidden_proof}

        \lemma makeStep->makeStep' {G : Graph Nat} {ex l : List Nat} {a : Nat} (c : InList a (makeStep G ex l)) : InList a (makeStep' G l) => {?hidden_proof}

        \lemma step1'_makeStep' {G : Graph Nat} {l : List Nat} {a b : Nat} (p : InList b l) (c : InList a (step1' G b)) : InList a (makeStep' G l) => {?hidden_proof}

        \lemma makeStep'-monotone {G : Graph Nat} {l l' : List Nat} {a : Nat} (p : \Pi (a : Nat) -> InList a l -> InList a l') (c : InList a (makeStep' G l)) : InList a (makeStep' G l') 
          => {?hidden_proof}

        \lemma collect'-monotone {G : Graph Nat} {l l' : List Nat} {n : Nat} (p : \Pi (a : Nat) -> InList a l -> InList a l') {i : Nat} (c : InList i (collect' G l n)) : InList i (collect' G l' n) 
          => {?hidden_proof}

        \lemma collect->collect' {G : Graph Nat} {acc l : List Nat} {n a : Nat} (c : InList a (collect G acc l n)) : InList a (acc ++ collect' G l n) => {?hidden_proof}
      }


\meta proof P=>P proof' (later P)

    \lemma cycle' {n : Nat} {l : Array \Prop (suc n)} (p : DArray {suc n} (\lam i => l i -> l (suc i Nat.mod suc n))) : TFAE l => {?hidden_proof}
      \where {
        \lemma aux2 {n : Nat} {l : Array \Prop (suc n)} (p : DArray {n} (\lam i => l i -> l (suc i))) (q : l n -> l 0) : TFAE l => {?hidden_proof}

        \lemma aux {n : Nat} {l : Array \Prop (suc n)} (p : DArray {n} (\lam i => l i -> l (suc i))) {i j : Fin (suc n)} {k : Nat} (q : i Nat.+ k = j) (a : l i) : l j => {?hidden_proof}
      }


\meta cycle P=>P cycle' (later P)
  }
