\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Arith.Rat
\import Arith.Real.UpperReal
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.CoverSpace.CompletionTools
\import Topology.CoverSpace.Product
\import Topology.MetricSpace
\import Topology.MetricSpace.ExComplete
\import Topology.MetricSpace.UpperReal
\import Topology.NormedAbGroup
\import Topology.NormedAbGroup.Real.Functions
\import Topology.RatherBelow
\import Topology.TopAbGroup.Complete
\import Topology.TopSpace
\import Topology.TopSpace.Product

\func dense-normed-lift {X Y : ExPseudoNormedAbGroup} {Z : CompleteExNormedAbGroup} (f : NormedIsometricMap X Y) (fd : f.IsDense) (g : NormedAbGroupMap X Z) : NormedAbGroupMap Y Z 
\cowith
  | MetricMap => dense-metric-lift f fd g
  | TopAbGroupMap => dense-topAb-lift f (fd, f.embedding->topEmbedding $ f.embedding->coverEmbedding (f.dense->uniformEmbedding fd).2) g
  | func-norm => {?hidden_proof}
  \where {
    \lemma char {X Y : ExPseudoNormedAbGroup} {Z : CompleteExNormedAbGroup} (f : NormedIsometricMap X Y) (fd : f.IsDense) (g : NormedAbGroupMap X Z) {x : X} :
      dense-normed-lift f fd g (f x) = g x => {?hidden_proof}
  }


\instance ExNormedAbGroupCompletion (X : ExPseudoNormedAbGroup) : CompleteExNormedAbGroup 
  | CompleteExMetricSpace => ExMetricCompletion X
  | CompleteTopAbGroup => TopAbGroupCompletion X
  | norm => norm
  | norm-dist => {?hidden_proof}
  \where {
    \lemma filter-norm_dist {F : RegularCauchyFilter X} : norm F = (ExMetricCompletion X).dist F (pointCF 0) => {?hidden_proof}

    \lemma norm-cont : ContMap (ExMetricCompletion X) ExUpperRealMetric norm => {?hidden_proof}
  }


\func completion-exNormed-isometry {X : ExPseudoNormedAbGroup} : NormedIsometricMap X (ExNormedAbGroupCompletion X) \cowith
  | IsometricMap => completion-ex-isometry
  | func-+ => {?hidden_proof}

\instance SeparatedNormedAbGroupReflection (X : ExPseudoNormedAbGroup) : ExNormedAbGroup (Quot X) 
  | zro => in~ 0
  | + => +
  | zro-left => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | negative => negative
  | negative-left => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | norm => norm
  | norm_zro => {?hidden_proof}
  | norm_negative => {?hidden_proof}
  | norm_+ => {?hidden_proof}
  | norm-ext => {?hidden_proof}
  \where {
    \type Quot (X : ExPseudoNormedAbGroup) => Quotient {X} (\lam x x' => X.norm (x - x') = 0)

    \func inN {X : ExPseudoNormedAbGroup} (x : X) : Quot X => in~ x

    \lemma ~-nequiv {X : ExPseudoNormedAbGroup} {x x' : X} (e : X.norm (x - x') = 0) : inN x = inN x' => {?hidden_proof}

    \lemma inN-isometry {X : ExPseudoNormedAbGroup} : NormedIsometricMap X (SeparatedNormedAbGroupReflection X) inN => {?hidden_proof}
  }


\func separated-completion {X : ExPseudoNormedAbGroup} : NormedIsometricMap (SeparatedNormedAbGroupReflection X) (ExNormedAbGroupCompletion X) \cowith
  | func => func
  | func-+ => {?hidden_proof}
  | func-norm-isometry => {?hidden_proof}
  \where {
    \lemma isDense : (separated-completion {X}).IsDense => {?hidden_proof}
  }
