\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Arith.Rat
\import Arith.Real.UpperReal
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.CoverSpace.CompletionTools
\import Topology.CoverSpace.Product
\import Topology.MetricSpace
\import Topology.MetricSpace.ExComplete
\import Topology.MetricSpace.UpperReal
\import Topology.NormedAbGroup
\import Topology.NormedAbGroup.Real.Functions
\import Topology.RatherBelow
\import Topology.TopAbGroup.Complete
\import Topology.TopSpace
\import Topology.TopSpace.Product

\func dense-normed-lift {X Y : ExPseudoNormedAbGroup} {Z : CompleteExNormedAbGroup} (f : NormedIsometricMap X Y) (fd : f.IsDense) (g : NormedAbGroupMap X Z) : NormedAbGroupMap Y Z 
\cowith
  | MetricMap => dense-metric-lift f fd g
  | TopAbGroupMap => dense-topAb-lift f (fd, f.embedding->topEmbedding $ f.embedding->coverEmbedding (f.dense->uniformEmbedding fd).2) g
  | func-norm => rewrite (norm_dist, norm_dist) $ transport (dist __ _ <= _) 
    (dense-topAb-lift f (fd, f.embedding->topEmbedding $ f.embedding->coverEmbedding (f.dense->uniformEmbedding fd).2) g).func-zro $ func-dist 
    {dense-metric-lift f fd g}
  \where {
    \lemma char {X Y : ExPseudoNormedAbGroup} {Z : CompleteExNormedAbGroup} (f : NormedIsometricMap X Y) (fd : f.IsDense) (g : NormedAbGroupMap X Z) {x : X} :
      dense-normed-lift f fd g (f x) = g x => {?hidden_proof}
  }


\instance ExNormedAbGroupCompletion (X : ExPseudoNormedAbGroup) : CompleteExNormedAbGroup 
  | CompleteExMetricSpace => ExMetricCompletion X
  | CompleteTopAbGroup => TopAbGroupCompletion X
  | norm => norm
  | norm-dist => \lam {F} {G} =>
  dense-lift-unique (ProductTopSpace.prod completion completion) (ProductTopSpace.prod.isDense completion.isDenseEmbedding.1 completion.isDenseEmbedding.1) 
    (dist-uniform-map {ExMetricCompletion X}) (norm-cont ContMap.∘ (TopAbGroupCompletion X).subtract-cont)
      (\lam s => completion-ex-isometry.func-isometry
      *> norm-dist *> norm_dist *> dist-symm *> inv completion-ex-isometry.func-isometry *> inv filter-norm_dist *> pmap norm 
      (inv lift2-char *> TopAbGroupCompletion.subtract_- {X})) (F, G)
  \where {
    \lemma filter-norm_dist {F : RegularCauchyFilter X} : norm F = (ExMetricCompletion X).dist F (pointCF 0) => {?hidden_proof}

    \lemma norm-cont : ContMap (ExMetricCompletion X) ExUpperRealMetric norm => {?hidden_proof}
  }


\func completion-exNormed-isometry {X : ExPseudoNormedAbGroup} : NormedIsometricMap X (ExNormedAbGroupCompletion X) \cowith
  | IsometricMap => completion-ex-isometry
  | func-+ => completion-topAb.func-+

\instance SeparatedNormedAbGroupReflection (X : ExPseudoNormedAbGroup) : ExNormedAbGroup (Quot X) 
  | zro => in~ 0
  | + => +
  | zro-left => \lam {x} => (\case \elim x \with {
    | in~ x => ~-nequiv (simplify norm_zro)
  })
  | +-assoc => \lam {x} {y} {z} => (\case \elim x, \elim y, \elim z \with {
    | in~ x, in~ y, in~ z => ~-nequiv (simplify norm_zro)
  })
  | negative => negative
  | negative-left => \lam {x} => (\case \elim x \with {
    | in~ x => ~-nequiv (simplify norm_zro)
  })
  | +-comm => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ x, in~ y => ~-nequiv (simplify norm_zro)
  })
  | norm => norm
  | norm_zro => norm_zro
  | norm_negative => \lam {x} => (\case \elim x \with {
    | in~ x => norm_negative
  })
  | norm_+ => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ x, in~ y => norm_+
  })
  | norm-ext => \lam {x} => (\case \elim x \with {
    | in~ x => \lam p => ~-nequiv $ pmap X.norm simplify *> p
  })
  \where {
    \type Quot (X : ExPseudoNormedAbGroup) => Quotient {X} (\lam x x' => X.norm (x - x') = 0)

    \func inN {X : ExPseudoNormedAbGroup} (x : X) : Quot X => in~ x

    \lemma ~-nequiv {X : ExPseudoNormedAbGroup} {x x' : X} (e : X.norm (x - x') = 0) : inN x = inN x' => {?hidden_proof}

    \lemma inN-isometry {X : ExPseudoNormedAbGroup} : NormedIsometricMap X (SeparatedNormedAbGroupReflection X) inN => {?hidden_proof}
  }


\func separated-completion {X : ExPseudoNormedAbGroup} : NormedIsometricMap (SeparatedNormedAbGroupReflection X) (ExNormedAbGroupCompletion X) \cowith
  | func => func
  | func-+ => \lam {x} {y} => (\case \elim x, \elim y \with {
    | in~ x, in~ y => inv TopAbGroupCompletion.+-char
  })
  | func-norm-isometry => \lam {x} => (\case \elim x \with {
    | in~ x => completion-exNormed-isometry.func-norm-isometry
  })
  \where {
    \lemma isDense : (separated-completion {X}).IsDense => {?hidden_proof}
  }
