\import Algebra.Group
\import Algebra.Group.Symmetric
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ordered
\import Algebra.Ring
\import Algebra.Ring.Poly
\import Algebra.Semiring
\import Algebra.StrictlyOrdered
\import Arith.Complex
\import Arith.Fin
\import Arith.Fin.Order
\import Arith.Int
\import Arith.Nat
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Arith.Real.InfReal
\import Arith.Real.Root
\import Arith.Real.UpperReal
\import Data.Array
\import Data.Fin
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\open Monoid (pow)
\open LinearlyOrderedAbGroup

\func array-eps-max {n : Nat} (n>0 : n > 0) (eps : Real) (eps>0 : eps > 0) (c : Array Real n) :
  ∃ (k : Fin n) (\Pi (i : Fin n) -> c i < c k + eps) \elim n, c
  | 0, _ => \case n>0
  | 1, c => inP (0, \lam i => \let i0 : i = 0 => \case \elim i \with {
  0 => idp
  } \in rewrite i0 (
    \let A0 => transportInv (\lam x => x < c 0 + eps) (LinearlyOrderedAbGroup.zro-right {RealAbGroup}) (LinearlyOrderedAbGroup.<_+-right {RealAbGroup} (c 0) eps>0)
    \in rewriteI {1} (zro-right {_} {c 0}) (rewriteI {1} (zro-right {_} {c 0}) A0)))
  | suc (suc n), c0 :: cs =>
    \let | half => Real.fromRat (rat 1 2 (\case __) idp)
         | eps/2 => eps * half
         | eps2>0 : eps/2 > 0 => OrderedSemiring.<_*_positive_positive eps>0 (rat_real_<.1 idp)
    \in \case array-eps-max {suc n} NatOrder.zero<suc eps/2 eps2>0 cs \with {
    inP (k, Pk) => \case real-located {c0} {cs k - eps/2} {cs k + eps} linarith \with {
      | byLeft a => inP (0, \lam i => \case \elim i \with {
        | 0 => linarith
        | suc i => \let A0 => Pk i \in linarith
      })
      | byRight b => inP (suc k, \lam i => \case \elim i \with {
        | 0 => b
        | suc i => \let A0 => Pk i \in linarith
      })
    }
    }

\func one_third : Real => Real.fromRat (ratio 1 3)

\func KeyLemma {n : Nat} (eps : Real)
               (eps>0 : eps > 0)
               (a : Array Real (suc (suc n)))
               (a0>eps : a 0 > eps)
               (ai>=0 : \Pi (i : Fin (suc n)) -> a (suc i) >= 0)
               (an=1 : a (suc n) = {RealField} 1) :
  \let | N => 2 * n + 3 \in
    ∃ (r0 : Real) (k : Fin (suc N) -> Fin (suc n))
    (k_monotone : \Pi (j : Fin N) -> k (Fin.fromNat {N} (suc j)) <= {NatSemiring} k j)
    (C1 : a (suc (k 0)) * pow r0 (suc (k 0)) = a 0 - eps)
    (C2 : \Pi (j : Fin (suc N)) (i : Fin (suc n)) ->
      a (suc (k j)) * pow (r0 * pow one_third j) (suc (k j)) >
      a (suc i) * pow (r0 * pow one_third j) (suc i) - eps) =>
  \case base {n} {eps} {eps>0} {a} {a0>eps} {ai>=0} {an=1} n \with {
    | inP (k0, r0, r0>0, invC1, invC2) =>
      \let
        | l+n>=n : \Pi (l : Fin (suc n)) -> n <= l NatSemiring.+ (Fin.fromNat {n} n) =>
          \lam l => rewrite (L2 n) (transport (n <=) (+-comm {NatSemiring} {n} {l}) (<=_+ {NatSemiring} <=-refl zero<=_))
        | N => 2 * n + 3
      \in \case finiteDependentChoice {\Sigma (j : Nat) (kj : Fin (suc n)) (P : ineq r0 j kj)}
                  (\lam (j, kj, Pj) (j+1,kj+1,Pj+1) => \Sigma (kj+1 <= {NatSemiring} kj) (j+1 = {NatSemiring} suc j))
                  (0, k0, \lam l => rewrite ide-right (invC2 l (l+n>=n l))) (step r0 r0>0) N \with {
        | inP (f, p, mon) =>
          inP (r0,
               \lam j => (f j).2,
               \lam j => rewrite (fin_mod_id (suc j)) (mon j).1,
               rewrite p invC1,
               \lam j => rewrite (sucPreserving-isId {N} (\lam k => (f k).1) (\lam k => (mon k).2) (pmap __.1 p) j) in (f j).3)
      }
  } \where {
  \func sucPreserving-isId {n : Nat} (f : Fin (suc n) -> Nat)
                           (plus1 : \Pi (x : Fin n) -> f (suc x) = suc (f x))
                           (f0 : f 0 = 0) (x : Fin (suc n)) : f x = {NatSemiring} x \elim x
    | 0 => f0
    | suc x => plus1 x *> pmap suc (sucPreserving-isId f plus1 f0 x)

  \func step (r0 : Real) (r0>0 : r0 > 0) :
    \Pi (tuple_j : \Sigma (j : Nat) (kj : Fin (suc n)) (ineq r0 j kj)) ->
      ∃ (tuple_j+1 : \Sigma (j+1 : Nat) (kj+1 : Fin (suc n)) (ineq r0 j+1 kj+1))
      (\Sigma (tuple_j+1.2 <= {NatSemiring} tuple_j.2) (tuple_j+1.1 = {NatSemiring} suc tuple_j.1)) =>
    \lam (j, kj, IH) =>
      \let
        | half : Real => Real.fromRat (rat 1 2 (\case __) idp)
        | eps/2 : Real => eps * half
        | eps-eps/2 : eps/2 - eps = negative eps/2 => AddGroup.cancel-left eps/2 (rewrite (AddGroup.toZero idp, inv +-assoc, inv Ring.ldistr, RealAbGroup.half+half {1}, ide-right) (AddGroup.toZero idp))
        | eps2>0 : eps/2 > 0 => OrderedSemiring.<_*_positive_positive eps>0 (rat_real_<.1 idp)
        | -eps2-eps2=-eps : negative eps/2 + negative eps/2 = negative eps => rewrite (inv AbGroup.negative_+-comm, inv ldistr, RealAbGroup.half+half {1}, ide-right) idp
        | r : Real => r0 * pow one_third j
        | one/3>0 : ratio 1 3 > {RealField} 0 => linarith -- Can't be substituted into r>0 proof below
        | r>0 : r > {RealField} 0 => OrderedSemiring.<_*_positive_positive r0>0 (OrderedSemiring.pow>0 one/3>0 {j})
        | one/3^kj>0 : pow one_third (suc kj) > 0 => OrderedSemiring.pow>0 one/3>0 {suc kj}
        | rNext : Real => r0 * pow one_third (suc j)
        | rNext=r/3 : rNext = r * one_third => inv *-assoc
        | kLen : Nat => suc kj
        | kLen<= : kLen <= suc n => suc_<_<= (fin_< kj)
        | c : Array Real kLen => mkArray (\lam t => a (suc (fin-inc_<= kLen<= t)) * pow rNext (suc (fin-inc_<= kLen<= t)))
      \in \case array-eps-max {kLen} NatOrder.zero<suc eps/2 eps2>0 c \with {
        | inP (k', Pk') =>
          \let
            | k'<kj : k' <= {NatSemiring} kj => suc<=suc.conv (suc_<_<= (fin_< k'))
            | k'<n+1 : k' < {NatSemiring} suc n => <∘r {NatSemiring} {k'} {kj} {suc n} k'<kj (fin_< kj)
            | kj+1 : Fin (suc n) => fin-inc_<= kLen<= k'
            | kj+1<=kj : kj+1 <= {NatSemiring} kj => rewrite toFin=id k'<kj
            | max-eps/2 : \Pi (t : Fin kLen) ->
              a (suc (fin-inc_<= kLen<= k')) * pow rNext (suc (fin-inc_<= kLen<= k')) >
              a (suc (fin-inc_<= kLen<= t)) * pow rNext (suc (fin-inc_<= kLen<= t)) - eps/2 => \lam t => \let A0 => Pk' t \in linarith
            | A0 : kj+1 LinearOrder.<= {NatSemiring} toFin k' {suc n} k'<n+1 => rewrite toFin=id (<=-refl {NatSemiring})
          \in inP ((suc j, kj+1, \lam i =>
            \let
              | LE (i<kLen : (i : Nat) < kLen) =>
                \let
                  | t : Fin kLen => toFin i i<kLen
                  | inc_t=i : fin-inc_<= kLen<= t = {Fin (suc n)} i => fin_nat-inj (toFin=id *> inv (rewrite toFin=id idp))
                \in <_+-left (negative eps) (rewrite inc_t=i in Pk' t)
            \in \case LinearOrder.Dec.trichotomy i kj \with {
              | Tri.less i<kj => <∘ (LE linarith) (rewrite (+-assoc, eps-eps/2) linarith) -- <∘ (LE linarith) (rewrite (+-assoc, eps-eps/2) linarith)
              | Tri.equals i=kj => <∘ (LE (rewrite i=kj id<suc)) (rewrite (+-assoc, eps-eps/2) linarith)
              | Tri.greater kj<i =>
                \let
                  | eps*1/3^kj<eps/2 : eps * pow one_third (suc kj) < eps/2 => <_*_positive-right eps>0 (L4 kj)
                  | A3 : a (suc i) * pow rNext (suc i) - eps RealField.< a (suc kj) * pow rNext (suc kj) - eps/2 =>
                    rewrite (rNext=r/3, CMonoid.pow_*-comm {_} {r} {one_third} {suc i}, CMonoid.pow_*-comm {_} {r} {one_third} {suc kj})
                      (rewriteI (*-assoc {_} {a (suc i)}, *-assoc {_} {a (suc kj)}) (rewrite (+-assoc, -eps2-eps2=-eps) in
                      <_+-left {_} (negative eps/2) ( <-transitive (LinearlyOrderedAbMonoid.<=_+-left (<=_*_positive-right (PosetSemiring.<=_*_positive_positive (ai>=0 i)
                        (PosetSemiring.pow>=0 {RealField} {r} {suc i} (<=-less r>0))) (<=-less (L6 (NatOrder.<.suc<suc kj<i))))
                        (OrderedAddGroup.negative_< eps*1/3^kj<eps/2))
                        (rewrite PseudoRing.rdistr_- in <_*_positive-left (IH i) one/3^kj>0))))
                  | fin-inc_kj : fin-inc_<= kLen<= (toFin kj id<suc) = kj => fin_nat-inj (rewrite toFin=id toFin=id) \in
                  <∘ A3 (rewrite (+-assoc, AddGroup.toZero idp, zro-right, fin-inc_kj) in <_+-left (negative eps/2) (Pk' (toFin kj id<suc)))
            }), (kj+1<=kj, idp))
      }

  \func ineq(r0 : Real) (j : Nat) (kj : Fin (suc n)) =>
    \Pi (i : Fin (suc n)) -> a (suc kj) * pow (r0 * pow one_third j) (suc kj) > a (suc i) * pow (r0 * pow one_third j) (suc i) - eps

  \lemma L1 {n : Nat} : suc (Fin.fromNat {n} n) = {Fin (suc (suc n))} suc n =>
    nat_fin_= (rewrite (L2 n, mod_< id<suc) idp)

  \lemma L2 (n : Nat) : Fin.fromNat {n} n = {Nat} n =>
    unfold Fin.fromNat (mod_< id<suc)

  \lemma L3 {n : Nat} {m l : Fin (suc n)} (l+m=n : l NatSemiring.+ m = {NatSemiring} n) : n - {FinRing} m = {Fin (suc n)} l =>
    AddGroup.cancel-right {FinRing} m (rewrite (nat_fin_= {suc n} {n} {l + m} (inv (rewrite l+m=n idp)))
      ((rewrite (negative-left {FinRing} {m}) in +-assoc {FinRing} {l Nat.+ m} {negative m} {m}) *> zro-right))

  \lemma L4 (m : Nat) : pow {RealField} (ratio 1 3) (suc m) < ratio 1 2 \elim m
    | 0 => linarith
    | suc m => <∘ (<_*_positive-left (L4 m) linarith) linarith

  \lemma L5 {i k : Nat} : pow {RealField} (ratio 1 3) i > pow {RealField} (ratio 1 3) (i + suc k) \elim k
    | 0 => rewriteI {1} ide-right (<_*_positive-right {_} {pow {RealField} (ratio 1 3) i} (OrderedSemiring.pow>0 linarith) linarith)
    | suc k => <∘ (<_*_positive-left (rewriteI {5} ide-right (<_*_positive-right (OrderedSemiring.pow>0 linarith) linarith )) linarith) L5

  \lemma L6 {i k : Nat} (p : k < i) : pow {RealField} (ratio 1 3) i < pow {RealField} (ratio 1 3) k =>
    \let | A0 : i /= 0 => \lam q => \case rewrite q in p \in
      rewriteI (suc_pred A0) (rewrite (<=_exists (<_suc_<= (rewriteI (suc_pred A0) in p))) in L5 {k} {pred i -' k})

  \func base (m : Fin (suc n)) :
    ∃ (k0 : Fin (suc n)) (r0 : Real) (r0>0 : r0 > 0)
    (a (suc k0) * pow r0 (suc k0) = a 0 - eps)
    (\Pi (l : Fin (suc n)) (l NatSemiring.+ m >= n) ->
      a (suc k0) * pow r0 (suc k0) > a (suc l) * pow r0 (suc l) - eps) \elim m
    | 0 =>
      \let | A0 => pow_root {suc n} suc/=0 {a 0 - eps} (\let A1 => a0>eps \in linarith)
      \in inP (n, root (suc n) (a 0 - eps), root>0 (\lam _ => linarith) linarith, rewrite L1 (rewrite {3} L2 (rewrite (A0, an=1, ide-left) idp)),
               \lam l A2 =>
                 \let
                   | A3 : \Pi {x : Real} -> x - eps < x => \let eps>0 => eps>0 \in \lam {_} => linarith
                   | A4 => rewrite (AddGroup.minus_zro, zro-left) in L3 {n} {0} {l}
                   | A5 : l < {NatSemiring} Nat.suc n => rewriteI (fin_mod_id l) (mod<right (\lam _ => linarith))
                   | A6 : l = {Fin (suc n)} n => inv (A4 (<=-antisymmetric (suc<=suc.conv (suc_<_<= A5)) (rewrite zro-right in A2)))
                 \in rewrite (A6, L1) A3)
    | suc m => \case base m \with {
      | inP (k0, r0, r0>0, A0, A1) =>
        \let
          | i => n - {FinRing} suc m
          | eps>0 => eps>0
          | a0-eps>0 : a 0 - eps > 0 => \let A2 => a0>eps \in linarith \in
          \case real-located {a (suc i) * pow r0 (suc i)} {a 0 - eps} {a 0} linarith \with {
            | ||.byLeft A2 =>
              \let
                | r0^i+1>0 => OrderedSemiring.pow>0 r0>0 {suc i}
                | r0^-i-1 => OrderedField.pinv (pow {RealField} r0 (suc i)) r0^i+1>0
                | ai+1>0 => rewrite (*-assoc, OrderedField.pinv-right, ide-right) in OrderedSemiring.<_*_positive_positive {RealField} {_} {r0^-i-1} (<∘ a0-eps>0 A2) (OrderedField.pinv>0 r0^i+1>0)
                | A3 => OrderedSemiring.<_*_positive_positive a0-eps>0 (OrderedField.pinv>0 ai+1>0)
                | i+1/=0 : suc i /= {Nat} 0 => \case __
                | r0new => root (suc i) ((a 0 - eps) * OrderedField.pinv (a (suc i)) ai+1>0)
                | r0new<r0 => rewrite (root_pow i+1/=0 (<=-less r0>0)) in
                root-monotone i+1/=0 (<=-less A3)
                  (rewriteI (RealField.ide-right {pow {RealField} r0 (suc i)}, OrderedField.pinv-right {_} {a (suc i)} ai+1>0, *-assoc)
                    (<_*_positive-left (rewrite *-comm A2) (OrderedField.pinv>0 ai+1>0)))
                | A4 : a (suc i) RealField.* (pow {RealField} r0new i RealField.* r0new) = {Real} a 0 - {RealField} eps =>
                  rewrite (pow_root {suc i} i+1/=0 (<=-less A3)) (rewrite {1} *-comm (rewriteI (*-assoc {RealField}) (rewrite OrderedField.pinv-right ide-left)))
              \in inP (i, r0new, root>0 i+1/=0 A3, A4, \lam l _ =>
                \case LinearOrder.Dec.trichotomy (l + {NatSemiring} suc m) n \with {
                  | less _ => absurd linarith
                  | equals A5 => rewrite (L3 {n} {suc m} A5) linarith
                  | greater A5 =>
                    \let
                      | A6 => A1 l (<_suc_<= linarith)
                      | l+1/=0 : suc l /= {Nat} 0 => \case __
                    \in rewrite A4 (rewriteI A0 (<-transitive-right (<=_+ (<=_*_positive-right (ai>=0 l)
                      (<=-less (LinearlyOrderedSemiring.pow_<-monotone l+1/=0 (<=-less (root>0 i+1/=0 A3)) r0new<r0))) (<=-refl {RealField} {negative eps})) A6))
                })
            | ||.byRight A2 => inP (k0, r0, r0>0, A0, \lam l _ =>
              \case LinearOrder.Dec.trichotomy (l + {NatSemiring} suc m) n \with {
                | less A4 => absurd linarith
                | equals A4 => rewrite A0 (<_+-left (negative eps) (rewrite (L3 {n} {suc m} A4) in A2))
                | greater A4 => A1 l (<_suc_<= linarith)
              } )
          }
    }
}

{- | Stabilization Lemma (Pigeonhole Principle)
A non-increasing sequence in a finite set of cardinality $n+1$ must have three consecutive equal values
if the sequence is at least $2n+3$ elements long. -}
\lemma three-consecutive-equals {n N : Nat} (N>2n : N > 2 * n)
                                (k : Fin (suc (suc N)) -> Fin (suc n))
                                (monotone : \Pi (j : Fin (suc N)) -> k (suc j) <= {NatSemiring} k j) :
  ∃ (j : Fin N) (k j = k (suc j)) (k (suc j) = k (suc (suc j))) =>
  helper n N N>2n k (<_suc_<= (fin_< (k 0))) monotone \where {
  \lemma helper {n : Nat} (b N : Nat) (N>2b : N > 2 * b)
                (k : Fin (suc (suc N)) -> Fin (suc n))
                (k0<=b : (k 0 : Nat) <= b)
                (monotone : \Pi (j : Fin (suc N)) -> k (suc j) <= {NatSemiring} k j) :
    TruncP (\Sigma (j : Fin N) (k j = k (suc j)) (k (suc j) = k (suc (suc j)))) \elim b, N, N>2b
    | _, 0, ()
    | 0, suc N', _ =>
      \let | k0=0 : (k 0 : Nat) = 0 => <=-antisymmetric k0<=b zero<=_
           | k1<=0 : (k 1 : Nat) <= 0 => <=-transitive (monotone 0) k0<=b
           | k1=0 : (k 1 : Nat) = 0 => <=-antisymmetric k1<=0 zero<=_
           | k2<=0 : (k 2 : Nat) <= 0 => <=-transitive (monotone 1) k1<=0
           | k2=0 : (k 2 : Nat) = 0 => <=-antisymmetric k2<=0 zero<=_
      \in inP (0, fin_nat-inj (k0=0 *> inv k1=0), fin_nat-inj (k1=0 *> inv k2=0))
    | suc b', 1, NatOrder.suc<suc p => \case p
    | suc b', suc (suc N'), N>2b =>
      \case LinearOrder.Dec.trichotomy {FinOrder (suc n)} (k 0) (k 1) \with {
        | Tri.less k0<k1 => absurd (monotone 0 k0<k1)
        | Tri.equals k0=k1 =>
          \case LinearOrder.Dec.trichotomy {FinOrder (suc n)} (k 1) (k 2) \with {
            | Tri.less k1<k2 => absurd (monotone 1 k1<k2)
            | Tri.equals k1=k2 => inP (0, k0=k1, k1=k2)
            | Tri.greater k1>k2 =>
              \let | k1<=suc-b' : (k 1 : Nat) <= suc b' => transport (\lam x => (x : Nat) <= suc b') k0=k1 k0<=b
                   | k2<k1 : (k 2 : Nat) < (k 1 : Nat) => k1>k2
                   | k2<=b' : (k 2 : Nat) <= b' => <_suc_<= (k2<k1 <∘l k1<=suc-b')
                   | k'' : Fin (suc (suc N')) -> Fin (suc n) => \lam j => k (suc (suc j))
                   | N'>2b' : N' > 2 * b' => NatOrder.unsuc< (NatOrder.unsuc< N>2b)
              \in \case helper {n} b' N' N'>2b' k'' k2<=b' (\lam j => monotone (suc (suc j))) \with {
                | inP (j, eq1, eq2) => inP (suc (suc j), eq1, eq2)
              }
          }
        | Tri.greater k0>k1 =>
          \let | k1<k0 : (k 1 : Nat) < (k 0 : Nat) => k0>k1
               | k1<=b' : (k 1 : Nat) <= b' => <_suc_<= (k1<k0 <∘l k0<=b)
               | k' : Fin (suc (suc (suc N'))) -> Fin (suc n) => \lam j => k (suc j)
               | N'>2b' : suc N' > 2 * b' => <-transitive id<suc (NatOrder.unsuc< N>2b)
          \in \case helper {n} b' (suc N') N'>2b' k' k1<=b' (\lam j => monotone (suc j)) \with {
            | inP (j, eq1, eq2) => inP (suc j, eq1, eq2)
          }
      }
}

\lemma geom_sum_upper {n k : Nat} (k>0 : 0 < k) (k<n : k < n) :
  AddMonoid.BigSum {RealAbGroup} (\lam (i : Fin (n -' k)) => pow {RealField} (ratio 1 3) (suc i)) <
  Real.fromRat (ratio 1 2) * (Real.fromRat 1 - pow {RealField} (ratio 1 3) n) =>
  \let
    | m : Nat => n -' k
    | x : Real => ratio 1 3
    | half : Real => Real.fromRat (ratio 1 2)
    | sum0 : Real => AddMonoid.BigSum {RealAbGroup} (\lam (j : Fin m) => pow {RealField} x j)
    | sum1 : Real => AddMonoid.BigSum {RealAbGroup} (\lam (i : Fin m) => pow {RealField} x (suc i))
    | m<n : m < n => transport (m <) (<=_exists (<=-transitive (id<=suc {k}) (suc_<_<= k<n))) (NatSemiring.<_+-left m {0} {k} k>0)
    | pow-n<pow-m : pow {RealField} x n < pow {RealField} x m => KeyLemma.L6 {n} {m} m<n
    | sum1=x*sum0 : sum1 = x * sum0 =>
      \let
        | arr0 : Array Real m => \new Array Real m (\lam (i : Fin m) => pow {RealField} x i)
        | arr1 : Array Real m => map (x *) arr0
      \in AddMonoid.BigSum-ext {RealAbGroup}
        (\lam i => idp *> inv (Monoid.pow-left {RealField} {x} {i})) *>
      AddMonoid.BigSum-ext {RealAbGroup} (\lam _ => idp) *> inv (RealField.BigSum-ldistr {x} {arr0})
    | x=half*oneMinusX : x = half * (Real.fromRat 1 - x) => linarith
    | sum1=half =>
      sum1                                        ==< sum1=x*sum0 >==
      x * sum0                                    ==< pmap (__ * sum0) x=half*oneMinusX             >==
      (half * (Real.fromRat 1 - x)) * sum0        ==< *-assoc                                       >==
      half * ((Real.fromRat 1 - x) * sum0)        ==< pmap (half *) RealField.geometric-partial-sum >==
      half * (Real.fromRat 1 - pow {RealField} x m) `qed
  \in rewrite sum1=half linarith

