\import Equiv
\import Function.Meta
\import InfCat.Basics
\import InfCat.Fibration.CovariantLift
\import InfCat.Functor.Equiv
\import InfCat.Functor.FullyFaithful
\import InfCat.Paths
\import InfCat.SubCat.Full
\import Logic
\import Logic.Meta
\import Logic.Unique
\import Meta
\import Paths

-- | {B} is a cocartesian fibration if every arrow in the base has a cocartesian lift from every point of the fiber.
\type IsCocartesianFib {A : \Cat} (B : A ->⁺ \Cat) : \Prop
  => \Pi {a a' : A} (f : a ~> a') (b : B a) -> ∃ (l : CovLift B f b) (IsCocartesianLift l)

\lemma cocartesianFib-char {A : \Cat} {B : A ->⁺ \Cat}
  : IsCocartesianFib B <-> IsHEquiv {FullSubCat {\Sigma⁺ (s : \Sigma⁺ (a a' : A) (f : a ~> a') (b : B a)) (CovLift B s.3 s.4)} \lam t => IsCocartesianLift t.2}
                                    {\Sigma⁺ (a a' : A) (f : a ~> a') (b : B a)}
                                    (\lam x => (FullSubCat.inc x).1)
  => \let | S => \Sigma⁺ (a a' : A) (f : a ~> a') (b : B a)
          | T => \Sigma⁺ (s : S) (CovLift B s.3 s.4)
     \in (\lam cf => (ff-surj-equiv {FullSubCat {T} \lam t => IsCocartesianLift t.2} {S} {\lam x => (FullSubCat.inc x).1}).1
            (\lam x y => IsEquiv.trans (FullSubCat.inc-ff x y) (cocartesian-ff B (FullSubCat.inc-con {T} {_} {x})),
             \lam s => \case cf s.3 s.4 \with {
               | inP (l,lc) => TruncP.map (FullSubCat.inc-sat {T} {_} {s,l} lc) \lam (d,p) => (d, pmap __.1 p)
             }),
          \lam e {a} {a'} f b => \let d => IsHEquiv.ret e (a,a',f,b)
            \in transport (\lam s => ∃ (l : CovLift B s.3 s.4) (IsCocartesianLift l)) (IsHEquiv.f_ret e) (inP ((FullSubCat.inc d).2, FullSubCat.inc-con {_} {_} {d})))

\sfunc cocartesianFib-lift {A : \Cat} {B : A ->⁺ \Cat} (Bf : IsCocartesianFib B) {a a' :⁺ A} (f :⁺ a ~> a') (b :⁺ B a) : CovLift B f b
  => \have e => cocartesianFib-char.1 Bf
     \in transport+ (\lam s => CovLift B s.3 s.4) (IsHEquiv.f_ret e) (FullSubCat.inc $ IsHEquiv.ret e (a,a',f,b)).2
  \where {
    \lemma isCocartesian {a a' : A} (f : a ~> a') (b : B a) : IsCocartesianLift (cocartesianFib-lift {A} {B} Bf f b)
      => transportInv IsCocartesianLift (\peval cocartesianFib-lift {A} {B} Bf f b) $
          transport-cocartesian $ FullSubCat.inc-con {_} {_} {IsHEquiv.ret (cocartesianFib-char.1 Bf) (a,a',f,b)}

    \private \lemma transport-cocartesian {s t : \Sigma⁺ (a a' : A) (f : a ~> a') (b : B a)} {p : s = t} {l : CovLift B s.3 s.4} (lc : IsCocartesianLift l)
      : IsCocartesianLift (transport+ (\lam s => CovLift B s.3 s.4) p l) \elim p
      | idp => lc
  }

{- | Given a family {F} and a map {p}, if a lift {l} in the pullback of {F} along {p} is cocartesian over {S},
 -   then it is cocartesian over {X}.
 -}
\lemma cocartesianLift-pullback {X S : \Cat} {F : S ->⁺ \Cat} (p : X ->⁺ S) {a a' : X} {m : a ~> a'} {b : F (p a)}
                                {l : CovLift (\lam x => F (p x)) m b} (lc : IsCocartesianLift {S} {F} {p a} {p a'} {dmap p m} (l.1, l.2))
  : IsCocartesianLift l
  => \lam g l' => Contr.Contr_QEquiv (later \new QEquiv {
    | f v => (v.1, dpath \lam i => dpath \lam j => v.2 j i)
    | ret w => (w.1, dpath \lam i => dpath \lam j => w.2 j i)
    | ret_f v => idp
    | f_sec w => idp
  }) $ cocartesian-square F idd (dmap p g) (dpath \lam i => dpath \lam j => p (fill2 m g j i)) idd (l.1, l.2) lc (l'.1, l'.2)