\import Function
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Paths
\import Set

\class Transitive {
  | A : \Set
  | \infix 4 ~ : A -> A -> \Prop
  | ~-transitive {x y z : A} : x ~ y -> y ~ z -> x ~ z
}
  \where {
\data Closure {A : \Type} (R : A -> A -> \Type) (x y : A) : \Prop 
      | cin (R x y)
      | ctrans {z : A} (Closure R x z) (Closure R z y)
      \where {
        \func isTransitive {A : \Set} (R : A -> A -> \Type) : Transitive A \cowith
          | ~ => \lam x y => Closure R x y
          | ~-transitive => ctrans

        \lemma isSymmetric {A : \Set} {R : A -> A -> \Type} (sym : \Pi {a a' : A} -> R a a' -> R a' a) {a a' : A} (c : Closure R a a') : Closure R a' a => {?hidden_proof}

        \lemma univ {A : \Set} {R : A -> A -> \Type} (E : Transitive A) (f : \Pi {x y : A} -> R x y -> x ~ y) {x y : A} (c : Closure R x y) : x ~ y => {?hidden_proof}

        \lemma ofTransitive (E : Transitive) {x y : E} (c : Closure ~ x y) : x ~ y => {?hidden_proof}

        \lemma toEquality {A B : \Set} (f : A -> B) {R : A -> A -> \Type} (p : \Pi {a a' : A} -> R a a' -> f a = f a') {a a' : A} (c : Closure R a a') : f a = f a' => {?hidden_proof}
      }

  }


\class Equivalence \extends Transitive {
  | ~-reflexive {x : A} : x ~ x
  | ~-symmetric {x y : A} : x ~ y -> y ~ x
}
  \where {
    \func map {A B : \Set} (f : A -> B) (E : Equivalence B) : Equivalence A \cowith
      | ~ => \lam a a' => f a ~ f a'
      | ~-transitive => ~-transitive
      | ~-reflexive => ~-reflexive
      | ~-symmetric => ~-symmetric

\data Closure {A : \Type} (R : A -> A -> \Type) (x y : A) : \Prop 
      | cin (R x y)
      | crefl (x = y)
      | csym (Closure R y x)
      | ctrans {z : A} (Closure R x z) (Closure R z y)
      \where {
        \func isEquivalence {A : \Set} (R : A -> A -> \Type) : Equivalence A \cowith
          | ~ => \lam x y => Closure R x y
          | ~-reflexive => \lam {x} => crefl idp
          | ~-symmetric => \lam {x} {y} x~y => csym x~y
          | ~-transitive => \lam {x} {y} {z} x~y y~z => ctrans x~y y~z

        \lemma univ {A : \Set} {R : A -> A -> \Type} (E : Equivalence A) (f : \Pi {x y : A} -> R x y -> x ~ y) {x y : A} (c : Closure R x y) : x ~ y => {?hidden_proof}

        \lemma ofEquivalence (E : Equivalence) {x y : E} (c : Closure ~ x y) : x ~ y => {?hidden_proof}
      }

  }


\data Quotient {A : \Type} (R : A -> A -> \Type) : \Set 
  | in~ A
  | ~-equiv (x y : A) (R x y) : in~ x = in~ y
  \where {
    \open Equivalence

    \lemma in-surj {A : \Type} {R : A -> A -> \Type} : IsSurj (in~ {A} {R}) => {?hidden_proof}

    \lemma equality {A : \Type} {R : A -> A -> \Type} {x y : A} (p : in~ x = {Quotient R} in~ y) : Closure R x y => {?hidden_proof}

    \lemma equalityEquiv (E : Equivalence) {x y : E} (p : in~ x = {Quotient ~} in~ y) : x ~ y => {?hidden_proof}

    \lemma equalityClosure (E : Equivalence) {R : E -> E -> \Type} (s : \Pi {x y : E} -> R x y -> x ~ y) {x y : E} (p : in~ x = {Quotient R} in~ y) : x ~ y => {?hidden_proof}

    \lemma fromEquality {A : \Type} {R : A -> A -> \Type} {x y : A} (p : Closure R x y) : in~ x = {Quotient R} in~ y => {?hidden_proof}

    \func map {A B : \Type} (f : A -> B) {R : A -> A -> \Type} {Q : B -> B -> \Type} (p : \Pi {a a' : A} -> R a a' -> Q (f a) (f a')) (x : Quotient R) : Quotient Q \elim x
      | in~ a => in~ (f a)
      | ~-equiv x y r => ~-pequiv (p r)

    \func liftArray {k : Nat} {A : Fin k -> \Type} (R : \Pi {j : Fin k} -> A j -> A j -> \Type) (refl : \Pi {j : Fin k} (x : A j) -> R x x) 
    (ts : DArray (\lam j => Quotient (R {j}))) : Quotient {DArray A} (\lam f g => \Pi (j : Fin ts.len) -> R (f j) (g j)) \elim k, ts
      | 0, nil => in~ nil
      | suc k, :: a l => \case \elim a, liftArray (\lam {j} => R {suc j}) (\lam {j} => refl {suc j}) l \with {
        | in~ a, in~ a1 => in~ (a :: a1)
        | in~ a, ~-equiv x y r i => ~-equiv _ _ (later (\case \elim __ \with {  | 0 => refl _  | suc j => r j})) i
        | ~-equiv x y r i, in~ a => ~-equiv _ _ (later (\case \elim __ \with {  | 0 => r  | suc j => refl _})) i
      }

    \func liftArrayFun {k : Nat} {A : Fin k -> \Type} (R : \Pi {j : Fin k} -> A j -> A j -> \Type) (refl : \Pi {j : Fin k} (x : A j) -> R x x) {B : \Type} 
    (S : B -> B -> \Type) (h : DArray A -> B) (p : \Pi (l l' : DArray A) -> (\Pi (j : Fin k) -> R (l j) (l' j)) -> S (h l) (h l')) 
    (ts : DArray (\lam j => Quotient (R {j}))) : Quotient S => \case liftArray R refl ts \with {
      | in~ l => in~ (h l)
      | ~-equiv x y r i => ~-equiv (h x) (h y) (p x y r) i
    }

    \lemma liftChoice {A : Choice} (B : A -> \Set) (R : \Pi {a : A} -> B a -> B a -> \Type) (f : \Pi (a : A) -> Quotient (\lam b b' => R {a} b b')) :
      ∃ (g : (\Pi (a : A) -> B a)) ∀ a (in~ (g a) = f a) => {?hidden_proof}
  }


\func ~-pequiv {A : \Type} {R : A -> A -> \Type} {x y : A} (r : R x y) : in~ x = in~ y => path (~-equiv x y r)

\type SubQuotient {A : \Type} (R : A -> A -> \Type) => Quotient {\Sigma (a : A) (R a a)} (\lam p q => R p.1 q.1)

\func QuotientDec {R : Equivalence} (D : \Pi (a a' : R) -> Dec (a ~ a')) : DecSet (Quotient ~) \cowith
  | decideEq => \lam in~ a in~ a' => (\case D a a' \with {
    | yes e => yes (~-pequiv e)
    | no q => no (\lam r => q (Quotient.equalityEquiv R r))
  })