\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidLocalization
\import Algebra.Monoid.Sub
\import Algebra.Ordered
\import Algebra.Pointed
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\open LocAbType

\instance LocPosetAbMonoid {M : PosetAbMonoid} (S : SubAddMonoid M) : PosetAbMonoid (LocAbType S) 
  | AbMonoid => LocAbMonoid S
  | <= => <=
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | <=_+ => {?hidden_proof}

\instance GrothendieckOrderedAbGroup (M : PosetAbMonoid) : PosetAbGroup (MaxLocAbType M) 
  | AbGroup => GrothendieckAbGroup M
  | PosetAbMonoid => LocPosetAbMonoid SubAddMonoid.max

\instance LocPosetMeetSemilattice {M : MeetSemilatticeAbMonoid} (S : SubAddMonoid M) : MeetSemilatticeAbMonoid (LocAbType S) 
  | PosetAbMonoid => LocPosetAbMonoid S
  | meet => meet
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | meet_+-left => {?hidden_proof}

\instance GrothendieckMeetLattice (M : MeetSemilatticeAbMonoid) : LatticeAbGroup.FromMeet (MaxLocAbType M) 
  | PosetAbGroup => GrothendieckOrderedAbGroup M
  | MeetSemilatticeAbMonoid => LocPosetMeetSemilattice SubAddMonoid.max