\import Equiv
\import Equiv.Fiber
\import Equiv.Path
\import Equiv.Sigma
\import Function.Meta
\import InfCat.Basics
\import InfCat.CatPushout
\import InfCat.Equiv
\import InfCat.Objects
\import InfCat.Paths
\import Logic
\import Logic.Unique
\import Meta
\import Paths
\import Paths.Meta

\type IsOrthogonal {A B C D : \Cat} (f : A ->⁺ B) (g : C ->⁺ D) : \Prop
  => IsEquiv {Ob (B ->⁺ C)} {\Sigma (uv : \Sigma (A ->⁺ C) (B ->⁺ D)) (\Pi (x :⁺ A) -> uv.2 (f x) = g (uv.1 x))}
      (\lam h => ((\lam x => unob h (f x), \lam y => g (unob h y)), \lam x => idp))

\lemma IsOrthogonal-char {A B C D : \Cat} {f : A ->⁺ B} {g : C ->⁺ D}
  : IsOrthogonal f g <-> (\Pi (u : A ->⁺ C) (v : B ->⁺ D) (s : \Pi (x :⁺ A) -> v (f x) = g (u x)) ->
                          Contr (\Sigma (h : B ->⁺ C) (t1 : \Pi (x :⁺ A) -> h (f x) = u x) (t2 : \Pi (y :⁺ B) -> g (h y) = v y)
                                        (\Pi (x :⁺ A) -> inv (t2 (f x)) *> pmap+ g (t1 x) = s x)))
  => (\lam gr u v s => Contr.Contr_QEquiv (transQEquiv (sigma-right \lam h => later $ sigmaEquiv _ _ _) $
        transQEquiv {_} {\Sigma (h : Ob (B ->⁺ C)) (\Sigma (t : (\lam x =>⁺ h.1 (f x), \lam y =>⁺ g (h.1 y)) = (u,v)) ((\lam x =>⁺ inv (path \lam i => (t i).2 (f x)) *> path (\lam i => g ((t i).1 x))) = s))}
          (sigma-right \lam h => later $ sigma-right \lam t => later $ pathEquiv-right $ later $ simp_coe \lam x => coe_path_pmap (path \lam i => (t i).2 (f x)) (path \lam i => g ((t i).1 x)) $ pmap+ (*> _) (inv *>_inv) *> *>-assoc)
          (later \new QEquiv {
            | f a => (unob a.1, \lam x => path \lam i => (a.2.1 i).1 x, \lam y => path \lam i => (a.2.1 i).2 y, \lam x => path \lam i => a.2.2 i x)
            | ret b => (ob b.1, (path \lam i => (\lam x => b.2 x i, \lam y => b.3 y i), path \lam i x => b.4 x i))
            | ret_f => idpe
            | f_sec => idpe
          })) $ IsEquiv=>contrFibers gr ((u,v),s),
      \lam gr => contrFibers=>IsEquiv $ later \lam s => Contr.Contr_QEquiv (transQEquiv
              (transQEquiv {_}
                {\Sigma (a : Ob (B ->⁺ C)) (\Sigma (s1 : (\lam x =>⁺ unob a (f x), \lam y =>⁺ g (unob a y)) = s.1)
                        ((\lam x =>⁺ inv (path \lam i => (s1 i).2 (f x)) *> pmap+ g (path \lam i => (s1 i).1 x)) = s.2))}
                (later \new QEquiv {
                  | f a => (ob a.1, (path \lam i => (\lam x => a.2 x i, \lam y => a.3 y i), path \lam i x => a.4 x i))
                  | ret b => (unob b.1, \lam x => path \lam i => (b.2.1 i).1 x, \lam y => path \lam i => (b.2.1 i).2 y, \lam x => path \lam i => b.2.2 i x)
                  | ret_f => idpe
                  | f_sec => idpe
                })
                (sigma-right \lam h => later $ sigma-right \lam t => later $ pathEquiv-right $ inv $ later $ simp_coe \lam x =>
                  coe_path_pmap (path \lam i => (t i).2 (f x)) (path \lam i => g ((t i).1 x)) $ pmap+ (*> _) (inv *>_inv) *> *>-assoc))
              (symQEquiv $ sigma-right \lam h => later $ sigmaEquiv _ _ _))
            (gr s.1.1 s.1.2 s.2))

\lemma IsOrthogonal_o-right {A B C D E : \Cat} {f : A ->⁺ B} {g : C ->⁺ D} (fg : IsOrthogonal f g) {h : D ->⁺ E} (fh : IsOrthogonal f h)
  : IsOrthogonal f (\lam x => h (g x))
  => IsOrthogonal-char.2 \lam u v s => Contr.Contr_QEquiv
      (transQEquiv {_}
        {\Sigma (b1 : \Sigma (h : B ->⁺ C) (\Pi (x :⁺ A) -> h (f x) = u x))
                (\Sigma (a1 : \Sigma (h : B ->⁺ D) ((\lam y =>⁺ g (b1.1 y)) = h))
                        (\Sigma (r : \Sigma (t1 : \Pi (x :⁺ A) -> a1.1 (f x) = g (u x)) ((\lam x =>⁺ inv (path \lam i => a1.2 i (f x)) *> pmap+ g (b1.2 x)) = t1))
                                (\Sigma (t2 : \Pi (y :⁺ B) -> h (a1.1 y) = v y) (\Pi (x :⁺ A) -> inv (t2 (f x)) *> pmap+ h (r.1 x) = s x))))}
        (later \new QEquiv {
          | f a => ((a.2.1, a.2.2), ((a.1.1, path \lam i y => a.2.3 y i), ((a.1.2, path \lam i x => a.2.4 x i), (a.1.3, a.1.4))))
          | ret b => ((b.2.1.1, b.2.2.1.1, b.2.2.2.1, b.2.2.2.2), (b.1.1, b.1.2, \lam y => path \lam i => b.2.1.2 i y, \lam x => path \lam i => b.2.2.1.2 i x))
          | ret_f => idpe
          | f_sec => idpe
        })
        (transQEquiv {_}
          {\Sigma (b1 : \Sigma (h : B ->⁺ C) (\Pi (x :⁺ A) -> h (f x) = u x))
                  (\Sigma (t2 : \Pi (y :⁺ B) -> h (g (b1.1 y)) = v y) (\Pi (x :⁺ A) -> inv (t2 (f x)) *> pmap+ h (idp *> pmap+ g (b1.2 x)) = s x))}
          (sigma-right \lam b1 => later $ transQEquiv (contr-left (lsigma _)) (contr-left (lsigma _)))
          (later \new QEquiv {
            | f a => (a.1.1, a.1.2, a.2.1, \lam x => pmap+ (\lam z => _ *> pmap+ h z) (inv idp_*>) *> a.2.2 x)
            | ret b => ((b.1, b.2), (b.3, \lam x => pmap+ (\lam z => _ *> pmap+ h z) idp_*> *> b.4 x))
            | ret_f a => ext (idp, ext (idp, ext \lam x => inv *>-assoc *> pmap+ (*> _) (inv (pmap+_*> \lam z => _ *> pmap+ h z) *> pmap+ (pmap+ (\lam z => _ *> pmap+ h z) __) *>_inv) *> idp_*>))
            | f_sec b =>
              \have lem (x :⁺ A) : pmap+ (\lam z => inv (b.3 (f x)) *> pmap+ h z) (inv (idp_*> {_} {_} {_} {pmap+ g (b.2 x)})) *> pmap+ (\lam z => inv (b.3 (f x)) *> pmap+ h z) idp_*> *> b.4 x = b.4 x
                        => inv *>-assoc *> pmap+ (*> _) (inv (pmap+_*> \lam z => _ *> pmap+ h z) *> pmap+ (pmap+ (\lam z => _ *> pmap+ h z) __) inv_*>) *> idp_*>
              \in path \lam i => (b.1, b.2, b.3, \lam x => lem x i)
          })))
      (sigma-Contr (IsOrthogonal-char.1 fh (\lam x => g (u x)) v s) \lam a => IsOrthogonal-char.1 fg u a.1 a.2)

\lemma IsOrthogonal_o-left {A B C D E : \Cat} {h : D ->⁺ E} {f : A ->⁺ B} (fh : IsOrthogonal f h) {g : B ->⁺ C} (gh : IsOrthogonal g h)
  : IsOrthogonal (\lam x => g (f x)) h
  => IsOrthogonal-char.2 \lam u v s => Contr.Contr_QEquiv (transQEquiv {_}
        {\Sigma (b1 : \Sigma (h2 : C ->⁺ D) (\Pi (y :⁺ C) -> h (h2 y) = v y))
                (\Sigma (a1 : \Sigma (h1 : B ->⁺ D) ((\lam x =>+ b1.1 (g x)) = h1))
                        (\Sigma (r : \Sigma (t2 : \Pi (y :⁺ B) -> h (a1.1 y) = v (g y)) (\Pi (y :⁺ B) -> inv (b1.2 (g y)) *> path (\lam i => h (a1.2 i y)) = inv (t2 y)))
                                (\Sigma (t1 : \Pi (x :⁺ A) -> a1.1 (f x) = u x)
                                        (\Pi (x :⁺ A) -> inv (r.1 (f x)) *> pmap+ h (t1 x) = s x))))}
        (later \new QEquiv {
          | f a => ((a.2.1, a.2.3), ((a.1.1, path \lam i x => a.2.2 x i), ((a.1.3, a.2.4), (a.1.2, a.1.4))))
          | ret b => ((b.2.1.1, b.2.2.2.1, b.2.2.1.1, b.2.2.2.2), (b.1.1, \lam x => path \lam i => b.2.1.2 i x, b.1.2, b.2.2.1.2))
          | ret_f => idpe
          | f_sec => idpe
        })
        (transQEquiv {_}
          {\Sigma (b1 : \Sigma (h2 : C ->⁺ D) (\Pi (y :⁺ C) -> h (h2 y) = v y))
                  (\Sigma (t1 : \Pi (x :⁺ A) -> b1.1 (g (f x)) = u x)
                          (\Pi (x :⁺ A) -> inv (b1.2 (g (f x))) *> pmap+ h (t1 x) = s x))}
          (sigma-right \lam b1 => later $ transQEquiv (contr-left (lsigma \lam x =>⁺ b1.1 (g x))) $
            contr-left $ later $ isProp=>isContr (isContr=>isProp $ Contr.Contr_QEquiv (later \new QEquiv {
              | f s => (\lam y => inv (s.1 y), \lam y => path (\lam i => s.2 i y) *> inv inv_inv)
              | ret t => (\lam y => inv (t.1 y), path \lam i y => t.2 y i)
              | ret_f s => ext (ext \lam y => inv_inv,
                                simp_coe $ *>_ext+ *> pmap funExt+ {_} {later \lam x => path \lam i => s.2 i x}
                                   (ext \lam y => *>-assoc *> pmap+ (_ *> __) inv_*>))
              | f_sec t => ext (ext \lam y => inv_inv, simp_coe \lam y => coe_path_pmap idp (pmap+ (inv __) inv_inv) $
                            pmap+ (_ *> __) inv_inv-coh+ *> *>-assoc *> pmap+ (_ *> __) inv_*> *> inv idp_*>)
            }) $ lsigma \lam y =>⁺ inv (b1.2 (g y))) (\lam y => b1.2 (g y), \lam y => idp))
          (later \new QEquiv {
            | f a => (a.1.1, a.2.1, a.1.2, a.2.2)
            | ret b => ((b.1, b.3), (b.2, b.4))
            | ret_f => idpe
            | f_sec => idpe
          })))
      (sigma-Contr (IsOrthogonal-char.1 fh u (\lam y => v (g y)) s) (\lam a => IsOrthogonal-char.1 gh a.1 v (\lam y => inv (a.3 y))))

\lemma IsOrthogonal_IsHEquiv-right {A B C D : \Cat} {f : A ->⁺ B} {g : C ->⁺ D} (ge : IsHEquiv g) : IsOrthogonal f g \elim ge
  | inP ge => inP \new QEquiv {
    | ret s => ob \lam y => ge.finv (s.1.2 y)
    | ret_f (ob h) => pmap ob $ ext \lam y => ge.finv_f _
    | f_sec s => ext (ext (ext \lam x => pmap+ ge.finv (s.2 x) *> ge.finv_f _,
                           ext \lam y => ge.coh_inv _),
                      simp_coe \lam x => coe_path_pmap _ (pmap+ g (pmap+ ge.finv (s.2 x) *> ge.finv_f _)) $
                      idp_*> *> pmap+_*> g *> pmap+ (_ *> __) ge.coh_inv_f *> homotopy-isNatural+ _ _ ge.coh_inv _)
  }

\lemma IsOrthogonal_IsHEquiv-left {A B C D : \Cat} {f : A ->⁺ B} {g : C ->⁺ D} (fe : IsHEquiv f) : IsOrthogonal f g \elim fe
  | inP fe => inP \new QEquiv {
    | ret s => ob \lam x => s.1.1 (fe.finv x)
    | ret_f (ob h) => pmap ob $ ext \lam x => pmap+ h (fe.coh_inv x)
    | f_sec s => ext (ext (ext \lam x => pmap+ s.1.1 (fe.finv_f x),
                           ext \lam y => inv (s.2 _) *> pmap+ s.1.2 (fe.coh_inv y)),
                      simp_coe \lam x => coe_path_pmap
                        (inv (s.2 (fe.finv (f x))) *> pmap+ s.1.2 (fe.coh_inv (f x)))
                        (path \lam i => g (s.1.1 (fe.finv_f x i)))
                        (pmap+ (*> _) (inv inv_*>) *> *>-assoc *> pmap+ (_ *> __) (inv (homotopy-isNatural+ _ _ s.2 _))
                         *> pmap+ (_ *> pmap+ s.1.2 __ *> _) fe.coh_inv_f *> inv *>-assoc))
  }

\lemma IsOrthogonal-retraction {A B C D : \Cat} {f : A ->⁺ B} {g : C ->⁺ D} (fg : IsOrthogonal f g)
                               {r : B ->⁺ A} (rf : \Pi (x :⁺ A) -> r (f x) = x) : IsOrthogonal r g
  => IsEquiv.fromMonoRetraction (\lam {h} {h'} p => exts \lam x => pmap+ h.1 (inv (rf x)) *> path (\lam i => (p i).1.1 (f x)) *> pmap+ h'.1 (rf x)) $ later \new Retraction {
    | sec s => ob \lam x => s.1.1 (f x)
    | f_sec s =>
      \have aux => aux s.1.1 s.1.2 s.2
      \in ext (path \lam i => (\lam x => aux.1 x i, \lam x => (inv (s.2 (f x)) *> pmap+ s.1.2 (rf x)) i),
               simp_coe \lam y => coe_path_pmap _ (pmap+ g (aux.1 y)) $ idp_*> *> aux.2 y *> inv *>-assoc)
  }
  \where {
    \private \sfunc aux (u : B ->⁺ C) (v : A ->⁺ D) (s : \Pi (x :⁺ B) -> v (r x) = g (u x))
      : \Sigma (p : \Pi (b :⁺ B) -> u (f (r b)) = u b) (\Pi (b :⁺ B) -> pmap+ g (p b) = inv (s _) *> pmap+ v (rf _) *> s b)
      => \have t => IsEquiv.splitSurj (pmapIsEquiv fg {ob \lam y => u (f (r y))} {ob u}) $
                      ext (path \lam i => (\lam x => u (f (rf x i)), \lam y => (inv (s _) *> pmap+ v (rf _) *> s y) i),
                           simp_coe \lam x => coe_path_pmap _ (pmap+ (\lam x => g (u (f x))) (rf x)) $ idp_*> *>
                            inv (rotatePathLeft $ pmap+ (pmap+ v __ *> _) (homotopy_app-comm+ (\lam x => r (f x)) rf x)
                              *> homotopy-isNatural+ _ _ s (pmap+ f (rf x))))
         \in (\lam y => path \lam i => unob (t.1 i) y, \lam y => path (\lam i => pmap (__.1.2 y) (t.2 i)))
  }

\lemma IsOrthogonal_CatPushout {A B C D E : \Cat} {f : A ->⁺ B} {g : A ->⁺ C} {h : D ->⁺ E} (gh : IsOrthogonal g h)
  : IsOrthogonal {B} {CatPushout f g} cinl h
  => IsOrthogonal-char.2 \lam u v s => Contr.Contr_QEquiv (symQEquiv $ transQEquiv {_}
        {\Sigma (p : \Pi (y :⁺ CatPushout f g) -> \Sigma (d :⁺ D) (t2 : h d = v y)) (\Sigma (t1 : \Pi (x :⁺ B) -> (p (cinl x)).1 = u x)
                (\Pi (x :⁺ B) -> pmap+ h (t1 x) *> inv (s x) = (p (cinl x)).2))}
        (later \new QEquiv {
          | f s => (\lam w => (s.1 w, s.3 w), (s.2, \lam y => rotatePathRight $ rotatePathLeft.conv (s.4 y)))
          | ret r => (\lam w => (r.1 w).1, r.2.1, \lam w => (r.1 w).2, \lam y => rotatePathLeft $ rotatePathRight.conv (r.2.2 y))
          | ret_f s => path \lam i => (s.1, s.2, s.3, \lam y => (pmap+ (rotatePathLeft __) rotatePathRight.conv_dir *> rotatePathLeft.dir_conv (s.4 y)) i)
          | f_sec r => path \lam i => (r.1, (r.2.1, \lam y => (pmap+ (rotatePathRight __) rotatePathLeft.conv_dir *> rotatePathRight.dir_conv (r.2.2 y)) i))
        })
        {?}) $
      IsOrthogonal-char.1 gh (\lam x => u (f x)) (\lam z => v (cinr z)) \lam x => pmap+ v (inv (path (cglue x))) *> s (f x)

\lemma IsOrthogonal-codiag {A B C D : \Cat} {f : A ->⁺ B} {g : C ->⁺ D} (fg : IsOrthogonal f g)
  : IsOrthogonal {CatPushout f f} (CatPushout.rec id+ id+ \lam x => idp) g
  => IsOrthogonal-retraction (IsOrthogonal_CatPushout fg) idpe