\import Algebra.Group
\import Algebra.Monoid
\import Category
\import Paths
\import Set

\instance Aut {A : \Type} (a : A) : Group (Trunc0 (a = a)) 
  | ide => in0 idp
  | * => \lam p q => (\case \elim p \with {
    | in0 p' => Trunc0.map q (\lam q' => p' *> q')
  })
  | ide-left => {?hidden_proof}
  | *-assoc => {?hidden_proof}
  | inverse => \lam x => Trunc0.map x inv
  | inverse-left => {?hidden_proof}

\func End {C : Precat} (c : C) : Monoid (Hom c c) \cowith
  | ide => id c
  | * => ∘
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  | *-assoc => {?hidden_proof}