\import Algebra.Group
\import Algebra.Monoid.Product
\import Paths

\instance ProductGroup (G H : Group) : Group 
  | Monoid => ProductMonoid G H
  | inverse => \lam p => (inverse p.1, inverse p.2)
  | inverse-left => {?hidden_proof}
  | inverse-right => {?hidden_proof}

\instance ProductAddGroup (A B : AddGroup) : AddGroup 
  | AddMonoid => ProductAddMonoid A B
  | negative => \lam p => (negative p.1, negative p.2)
  | negative-left => {?hidden_proof}
  | negative-right => {?hidden_proof}

\instance ProductCGroup (G H : CGroup) : CGroup 
  | Group => ProductGroup G H
  | CMonoid => ProductCMonoid G H

\instance ProductAbGroup (A B : AbGroup) : AbGroup 
  | AddGroup => ProductAddGroup A B
  | AbMonoid => ProductAbMonoid A B