\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Ordered
\import Algebra.Ordered.RieszSpace
\import Algebra.Pointed
\import Algebra.QModule
\import Algebra.Ring
\import Algebra.Ring.UnitAlgebra
\import Analysis.Limit
\import Arith.Nat
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Arith.Real.UpperReal
\import Arith.Real.UpperRealLattice
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Filter
\import Topology.BanachAlgebra
\import Topology.BanachSpace
\import Topology.MetricSpace
\import Topology.NormedAbGroup
\import Topology.NormedAbGroup.Real
\import Topology.StoneCStarAlgebra
\import Topology.NormedRing
\import Topology.TopPoset
\import Topology.TopSpace
\import Topology.TopSpace.Product

\instance UnitC*Algebra (A : StoneC*PseudoAlgebra) : StoneC*Algebra (\Sigma Real A) 
  | Ring => UnitAlgebra RealField A.toRealAlgebra
  | *-comm => {?hidden_proof}
  | isDivisible => {?hidden_proof}
  | norm (x : \Sigma Real A) : ExUpperReal 
    => RealAbGroup.abs x.1 ExUpperRealLattice.∨ Join (\lam (s : \Sigma (y : A) (A.norm y <= 1)) => A.norm (x.1 A.*r s.1 + x.2 * s.1))
  | norm_zro => {?hidden_proof}
  | norm_negative => {?hidden_proof}
  | norm_+ => {?hidden_proof}
  | norm-double => {?hidden_proof}
  | norm-bounded => {?hidden_proof}
  | norm_*_<= {x y : \Sigma Real A} : norm (x * {UnitAlgebra RealField A.toRealAlgebra} y) <= norm x * norm y => {?hidden_proof}
  | norm_ide_<= => {?hidden_proof}
  | norm-ext => {?hidden_proof}
  | isCompleteMetric => {?hidden_proof}
  | c*-sum => {?hidden_proof}
  | c*-square => {?hidden_proof}
  \where {
    \open ExUpperRealAbMonoid (<-rat)
    \open ExUpperRealSemigroup (<=_*)

    \lemma inhabitted : ∃ (y : A) (A.norm y <= 1) => {?hidden_proof}
  }


\func StoneC*AlgebraRieszSpace (A : StoneC*Algebra) : RieszSpace A => RieszSpace.fromAbs (\lam a => TruncP.map (abs-aux a) (\lam s => (s.1, s.3, s.4, s.5)))
  \where {
    \protected \func StoneC*AlgebraTopPoset : HausdorffTopPosetAbGroup \cowith
      | TopAbGroup => A
      | PosetAbGroup => A
      | positive-closed => {?hidden_proof}

    \protected \lemma abs-aux (a : A) : ∃ (b : A) (b * b = a * a) (a <= b) (negative a <= b) ∀ {c} (a <= c -> negative a <= c -> b <= c) => {?hidden_proof}

    \protected \lemma abs-square {a : A} : (StoneC*AlgebraRieszSpace A).abs a * (StoneC*AlgebraRieszSpace A).abs a = a * a => {?hidden_proof}

    \protected \func c*abs (a : A) (a<=1 : a <= 1) (-a<=1 : negative a <= 1) : A => sqrt-t (a * a, square-norm)
      \where {
        \open RealBanachAlgebra
        \open RealBanachAlgebra.sqrt (yfunc, zfunc, zfunc-lim, UnitBall)
        \open ExUpperRealSemigroup (<=_*)

        \lemma yfunc>=0 {x : A} (x<=1 : x <= 1) {n : Nat} : 0 <= yfunc n x => {?hidden_proof}

        \lemma square-norm : norm (1 - a * a) <= 1 => {?hidden_proof}

        \lemma c*abs>=id {x : A} {x<=1 : x <= 1} {-x<=1 : negative x <= 1} : x <= c*abs x x<=1 -x<=1 => {?hidden_proof}
          \where {
            \lemma induction (n : Nat) : x <= 1 - yfunc n (x * x) => {?hidden_proof}
          }


        \lemma c*abs>=neg {x : A} {x<=1 : x <= 1} {-x<=1 : negative x <= 1} : negative x <= c*abs x x<=1 -x<=1 => {?hidden_proof}

        \lemma zfunc_pow>0 {w : A} (w<=1 : w <= 1) (|1-w|<1 : (norm (1 - w)).U 1) : zfunc-lim (w * w, square-norm w<=1 $ ExUpperReal.<_<= |1-w|<1) = w => {?hidden_proof}
          \where {
            \lemma square-norm (w<=1 : w <= 1) (|1-w|<=1 : norm (1 - w) <= 1) : norm (1 - w * w) <= 1 => {?hidden_proof}
          }


        \lemma zfunc_pow {w : A} (w<=1 : w <= 1) (|1-w|<=1 : norm (1 - w) <= 1) : zfunc-lim (w * w, zfunc_pow>0.square-norm w<=1 |1-w|<=1) = w => {?hidden_proof}

        \lemma zfunc_pow' {w : A} (w>=0 : 0 <= w) (w<=1 : w <= 1) => {?hidden_proof}

        \lemma yfunc-step {x : A} (x<=1 : x <= 1) {n : Nat} : yfunc n x <= yfunc (suc n) x => {?hidden_proof}

        \lemma zfunc-lim-meet {s : UnitBall {A}} (s<=1 : s.1 <= 1) : A.IsMeet (zfunc __ s.1) (zfunc-lim s) => {?hidden_proof}

        \lemma yfunc-mono {x y : A} (x<=y : x <= y) (y<=1 : y <= 1) {n : Nat} : yfunc n y <= yfunc n x => {?hidden_proof}

        \lemma c*abs-univ-bounded {x : A} {x<=1 : x <= 1} {-x<=1 : negative x <= 1} {w : A} (w<=1 : w <= 1) (|1-w|<=1 : norm (1 - w) <= 1) (x<=w : x <= w) (-x<=w : negative x <= w) : c*abs x x<=1 -x<=1 <= w 
          => {?hidden_proof}

        \func sqrt-t (s : UnitBall {A}) => sqrt s.1 s.2

        \lemma square-inj {x y : A} (x>=0 : 0 <= x) (x<=1 : x <= 1) (y>=0 : 0 <= y) (y<=1 : y <= 1) (xx=yy : x * x = y * y) : x = y => {?hidden_proof}

        \lemma elem>=0 {a x : A} (a<=x : a <= x) (-a<=x : negative a <= x) : 0 <= x => {?hidden_proof}

        \lemma c*abs>=0 {x : A} {x<=1 : x <= 1} {-x<=1 : negative x <= 1} : 0 <= c*abs x x<=1 -x<=1 => {?hidden_proof}

        \lemma c*abs<=1 {x : A} {x<=1 : x <= 1} {-x<=1 : negative x <= 1} : c*abs x x<=1 -x<=1 <= 1 => {?hidden_proof}

        \lemma c*abs_*q {q : Rat} (q>=0 : 0 <= q) (q<=1 : q <= 1) {x : A} {x<=1 : x <= 1} {-x<=1 : negative x <= 1} {qx<=1 : q A.*q x <= 1} 
        {-qx<=1 : negative (q A.*q x) <= 1} : q A.*q c*abs x x<=1 -x<=1 = c*abs (q A.*q x) qx<=1 -qx<=1 => {?hidden_proof}

        \lemma c*abs-univ {w : A} (a<=w : a <= w) (-a<=w : negative a <= w) : c*abs a a<=1 -a<=1 <= w => {?hidden_proof}
      }

  }


\func StoneC*PseudoAlgebraRieszSpace (A : StoneC*PseudoAlgebra) : RieszSpace A => RieszSpace.fromAbs {StoneC*PseudoAlgebaPoset}
  (\lam a => (\case StoneC*AlgebraRieszSpace.abs-aux {UnitC*Algebra A} (0, a) \with {  | inP (b, bb=aa, a<=b, -a<=b, bu) => 
    \have bc : b = (0, b.2) => ext (RealField.isReduced $ pmap __.1 bb=aa *> RealField.zro_*-left, idp)
    \in inP (b.2, transport (_ <=) bc a<=b, transport2 <= (ext (RealAbGroup.negative_zro, idp)) bc -a<=b, 
          \lam a<=c -a<=c => transport (<= _) bc $ bu a<=c $ =_<= (ext (RealAbGroup.negative_zro, idp)) <=∘ -a<=c)}))
  \where {
    \func StoneC*PseudoAlgebaPoset : PosetQModule \cowith
      | QModule => A
      | <= => \lam a b => unit-algebra {_} {A.toRealAlgebra} a <= unit-algebra {_} {A.toRealAlgebra} b
      | <=-refl => {?hidden_proof}
      | <=-transitive => {?hidden_proof}
      | <=-antisymmetric => {?hidden_proof}
      | <=_+ => {?hidden_proof}
      | <=_*n-div => {?hidden_proof}
  }
