package org.arend.lib.meta.field;

import org.arend.ext.concrete.ConcreteFactory;
import org.arend.ext.concrete.expr.ConcreteArgument;
import org.arend.ext.concrete.expr.ConcreteExpression;
import org.arend.ext.core.context.CoreBinding;
import org.arend.ext.core.definition.CoreClassDefinition;
import org.arend.ext.core.definition.CoreClassField;
import org.arend.ext.core.expr.CoreClassCallExpression;
import org.arend.ext.core.expr.CoreExpression;
import org.arend.ext.core.expr.CoreFunCallExpression;
import org.arend.ext.core.expr.CoreInferenceReferenceExpression;
import org.arend.ext.core.ops.NormalizationMode;
import org.arend.ext.error.MissingArgumentsError;
import org.arend.ext.instance.SubclassSearchParameters;
import org.arend.ext.reference.ArendRef;
import org.arend.ext.typechecking.ContextData;
import org.arend.ext.typechecking.ExpressionTypechecker;
import org.arend.ext.typechecking.TypedExpression;
import org.arend.ext.typechecking.meta.Dependency;
import org.arend.ext.util.Pair;
import org.arend.lib.meta.equation.binop_matcher.FunctionMatcher;
import org.arend.lib.meta.equationNew.ring.CRingEquationMeta;
import org.arend.lib.meta.equationNew.term.TermOperation;
import org.arend.lib.meta.equationNew.term.TermType;
import org.arend.lib.util.Utils;
import org.arend.lib.util.Values;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

/**
 * Backward (goal) mode for denominator clearing.
 *
 * <p>The Java side only reifies the source expression and preserves each
 * {@code Monoid.Inv} witness in an {@code Eval} certificate.  Fraction
 * normalization, denominator clearing, and their correctness live in
 * {@code Algebra.Solver.Field}.  That backend reuses {@code CRingSolverModel}
 * to compute the canonical cross-products; this class intentionally contains
 * no second ring normalizer.  Proof-bearing {@code Monoid.Inv} projections
 * are reified directly; a total {@code DiscreteField.finv} is reified only
 * when an {@code x != 0} proof can be elaborated into a witness.</p>
 */
public class FieldSimpMeta extends CRingEquationMeta {
  @Dependency(name = "Monoid.Inv")          private CoreClassDefinition invClass;
  @Dependency(name = "Monoid.DivBase.val")  private CoreClassField invValue;
  @Dependency(name = "Monoid.DivBase.inv")  private CoreClassField invProjection;

  @Dependency(name = "DiscreteField")             private CoreClassDefinition discreteField;
  @Dependency(name = "DiscreteField.finv")        private CoreClassField finv;
  @Dependency(name = "DiscreteField.nonZero-Inv") private ArendRef nonZeroInv;

  @Dependency(name = "FieldTerm.var")       private ArendRef fieldVar;
  @Dependency(name = "FieldTerm.coef")      private ArendRef fieldCoef;
  @Dependency(name = "FieldTerm.:zro")      private ArendRef fieldZro;
  @Dependency(name = "FieldTerm.:ide")      private ArendRef fieldIde;
  @Dependency(name = "FieldTerm.:negative") private ArendRef fieldNegative;
  @Dependency(name = "FieldTerm.:+")        private ArendRef fieldAdd;
  @Dependency(name = "FieldTerm.:*")        private ArendRef fieldMul;
  @Dependency(name = "FieldTerm.:inverse")  private ArendRef fieldInverse;

  @Dependency(name = "eval-var")      private ArendRef evalVar;
  @Dependency(name = "eval-coef")     private ArendRef evalCoef;
  @Dependency(name = "eval-zro")      private ArendRef evalZro;
  @Dependency(name = "eval-ide")      private ArendRef evalIde;
  @Dependency(name = "eval-negative") private ArendRef evalNegative;
  @Dependency(name = "eval-add")      private ArendRef evalAdd;
  @Dependency(name = "eval-mul")      private ArendRef evalMul;
  @Dependency(name = "eval-inverse")  private ArendRef evalInverse;

  @Dependency(name = "field-terms-equality")     private ArendRef fieldTermsEquality;
  @Dependency(name = "field-terms-equality-raw") private ArendRef fieldTermsEqualityRaw;

  @Override
  public boolean @Nullable [] argumentExplicitness() {
    // The implicit argument is a tuple (or a single expression) of reusable
    // nonzero evidence templates.  The optional explicit argument proves the
    // raw, denominator-free equality generated by field_simp.
    return new boolean[] { false, true };
  }

  @Override
  public int numberOfOptionalExplicitArguments() {
    return 1;
  }

  @Override
  public boolean allowExcessiveArguments() {
    return false;
  }

  @Override
  public boolean requireExpectedType() {
    return true;
  }

  @Override
  public @Nullable TypedExpression invokeMeta(
      @NotNull ExpressionTypechecker typechecker,
      @NotNull ContextData contextData) {
    CoreExpression expectedType = contextData.getExpectedType();
    if (expectedType == null) {
      typechecker.getErrorReporter().report(new MissingArgumentsError(1, contextData.getMarker()));
      return null;
    }

    CoreFunCallExpression equality = Utils.toEquality(
        expectedType.normalize(NormalizationMode.WHNF),
        typechecker.getErrorReporter(),
        contextData.getMarker());
    if (equality == null) {
      return null;
    }

    CoreExpression carrierType = equality.getDefCallArguments().getFirst().normalize(NormalizationMode.WHNF);
    if (carrierType instanceof CoreInferenceReferenceExpression inference &&
        inference.getSubstExpression() == null && inference.getVariable() != null) {
      typechecker.solveEquationsFor(inference.getVariable());
      if (inference.getSubstExpression() != null) {
        carrierType = inference.getSubstExpression().normalize(NormalizationMode.WHNF);
      }
    }

    Pair<TypedExpression, CoreClassCallExpression> instance = Utils.findInstanceWithClassCall(
        new SubclassSearchParameters(getClassDef()),
        carrier,
        carrierType,
        typechecker,
        contextData.getMarker(),
        getClassDef());
    if (instance == null) {
      return null;
    }

    ConcreteFactory factory = contextData.getFactory().withData(contextData.getMarker());
    List<? extends ConcreteArgument> arguments = contextData.getArguments();
    ConcreteExpression evidenceArgument =
        arguments.isEmpty() || arguments.getFirst().isExplicit()
            ? null
            : arguments.getFirst().getExpression();
    ConcreteExpression clearedProof =
        arguments.isEmpty() || !arguments.getLast().isExplicit()
            ? null
            : arguments.getLast().getExpression();
    List<? extends ConcreteExpression> evidenceTemplates = evidenceArgument == null
        ? List.of()
        : Utils.getArgumentList(evidenceArgument);
    List<CoreBinding> localBindings = typechecker.getFreeBindingsList();

    Values<CoreExpression> values = new Values<>(typechecker, contextData.getMarker());
    List<TermOperation> ringOperations = getOperations(
        instance.proj1,
        instance.proj2,
        typechecker,
        factory,
        contextData.getMarker());
    FunctionMatcher finvMatcher = instance.proj2.getDefinition().isSubClassOf(discreteField)
        ? FunctionMatcher.makeFieldMatcher(
            instance.proj2,
            instance.proj1,
            finv,
            typechecker,
            factory,
            contextData.getMarker(),
            1)
        : null;
    FieldSimpRule rule = new FieldSimpRule(
        this,
        typechecker,
        factory,
        instance.proj1,
        values,
        ringOperations,
        finvMatcher,
        evidenceTemplates,
        localBindings);

    CoreExpression leftValue = equality.getDefCallArguments().get(1);
    CoreExpression rightValue = equality.getDefCallArguments().get(2);
    FieldSimpRule.Result left = rule.reify(leftValue);
    FieldSimpRule.Result right = rule.reify(rightValue);

    // A typed local avoids reusing an array literal at several function-typed
    // positions, where the concrete typechecker would eta-expand that syntax.
    ArendRef envRef = factory.local("env");
    ConcreteExpression env = Utils.makeArray(
        values.getValues().stream().map(value -> factory.core(value.computeTyped())).toList(),
        factory);
    ConcreteExpression envReference = factory.ref(envRef);
    ConcreteExpression leftEvaluation = rule.evaluation(left, envReference, values.getValues().size());
    ConcreteExpression rightEvaluation = rule.evaluation(right, envReference, values.getValues().size());

    ConcreteExpression crossProof = clearedProof == null
        ? factory.ref(typechecker.getPrelude().getIdpRef())
        : clearedProof;

    // Fix the selected ring instance explicitly. This matters when two ring
    // structures share a carrier; the remaining hidden arguments are inferred
    // from the Eval certificates.
    ConcreteExpression result = factory.appBuilder(
            factory.ref(clearedProof == null ? fieldTermsEquality : fieldTermsEqualityRaw))
        .app(factory.core(instance.proj1), false)
        .app(leftEvaluation)
        .app(rightEvaluation)
        .app(crossProof)
        .build();

    ConcreteExpression envType = factory.app(
        factory.ref(typechecker.getPrelude().getArrayRef()),
        true,
        factory.core(equality.getDefCallArguments().getFirst().computeTyped()),
        factory.number(values.getValues().size()));
    result = factory.letExpr(
        false,
        false,
        List.of(factory.letClause(envRef, List.of(), envType, env)),
        result);

    return typechecker.typecheck(result, expectedType);
  }

  @Nullable FieldSimpRule.Kind kindOfRingOperation(@NotNull Object data) {
    if (data.equals(getZroTerm())) return FieldSimpRule.Kind.ZRO;
    if (data.equals(getIdeTerm())) return FieldSimpRule.Kind.IDE;
    if (data.equals(getAddTerm())) return FieldSimpRule.Kind.ADD;
    if (data.equals(getMulTerm())) return FieldSimpRule.Kind.MUL;
    if (data.equals(getNegativeTerm())) return FieldSimpRule.Kind.NEGATIVE;
    if (data.equals(getCoefTerm())) return FieldSimpRule.Kind.COEF;
    return null;
  }

  @NotNull TermOperation toFieldOperation(
      @NotNull FieldSimpRule.Kind kind,
      @NotNull TermOperation ringOperation) {
    ArendRef constructor = switch (kind) {
      case ZRO -> fieldZro;
      case IDE -> fieldIde;
      case ADD -> fieldAdd;
      case MUL -> fieldMul;
      case NEGATIVE -> fieldNegative;
      case COEF -> fieldCoef;
      case VAR, INVERSE -> throw new IllegalArgumentException("Not a ring operation");
    };
    return new TermOperation(
        kind,
        (factory, arguments) -> factory.app(factory.ref(constructor), true, arguments),
        ringOperation.matcher(),
        ringOperation.argTypes());
  }

  @NotNull TermOperation inverseOperation() {
    return new TermOperation(
        FieldSimpRule.Kind.INVERSE,
        (factory, arguments) -> factory.app(factory.ref(fieldInverse), true, arguments),
        expression -> null,
        List.of(new TermType.OpType(null)));
  }

  @NotNull CoreClassDefinition invClass() {
    return invClass;
  }

  @NotNull CoreClassField invValue() {
    return invValue;
  }

  @NotNull CoreClassField invProjection() {
    return invProjection;
  }

  @NotNull CoreClassField finv() {
    return finv;
  }

  @NotNull ArendRef nonZeroInv() {
    return nonZeroInv;
  }

  @NotNull ArendRef fieldVar() {
    return fieldVar;
  }

  @NotNull ArendRef evalVar() {
    return evalVar;
  }

  @NotNull ArendRef evalCoef() {
    return evalCoef;
  }

  @NotNull ArendRef evalZro() {
    return evalZro;
  }

  @NotNull ArendRef evalIde() {
    return evalIde;
  }

  @NotNull ArendRef evalNegative() {
    return evalNegative;
  }

  @NotNull ArendRef evalAdd() {
    return evalAdd;
  }

  @NotNull ArendRef evalMul() {
    return evalMul;
  }

  @NotNull ArendRef evalInverse() {
    return evalInverse;
  }
}
