\import Equiv
\import Equiv.Fiber
\import Equiv.Sigma
\import Function.Meta
\import Homotopy.Fibration
\import InfCat.Basics
\import InfCat.Functor.Equiv
\import InfCat.Paths
\import InfCat.Rezk
\import InfCat.Square
\import Logic
\import Logic.Meta
\import Logic.Unique
\import Meta
\import Paths
\import Paths.Meta

\type IsFFMap {C D : \Cat} (f : C ->⁺ D) : \Prop
  => \Pi (x y : C) -> IsEquiv {x ~> y} (\lam p => dmap f p)
  \where {
    \lemma section-ff (ff : IsFFMap f) {g : D ->⁺ C} (fg : \Pi (y :⁺ D) -> f (g y) = y) : IsFFMap g
      => \lam x y => IsEquiv.leftFactor (ff (g x) (g y)) $
            Paths.transportInv {D ->⁺ D} (\lam h => IsEquiv (dmap h)) (ext fg) (inP idEquiv)

    \lemma section-surj (ff : IsFFMap f) {g : D ->⁺ C} (fg : \Pi (y :⁺ D) -> f (g y) = y) : IsSurjMap g
      => \lam x => inP (f x, (iso_= (IsEquiv.ret (ff _ _) (=_~> (fg (f x)))) (IsEquiv.ret (ff _ _) (=_~> (inv (fg (f x)))))
            (IsEquiv.isInj (ff _ _) $ dmap_comp f *> pmap2+ comp (IsEquiv.f_ret (ff _ _)) (IsEquiv.f_ret (ff _ _)) *> =_~>_comp *> pmap+ =_~> *>_inv)
            (IsEquiv.isInj (ff x x) $ dmap_comp f *> pmap2+ comp (IsEquiv.f_ret (ff _ _)) (IsEquiv.f_ret (ff _ _)) *> =_~>_comp *> pmap+ =_~> inv_*>)).1)

    \lemma isConservative (ff : IsFFMap f) {x y : C} {p : x ~> y} (fpi : IsIso (dmap f p)) : IsIso p \elim fpi
      | inP r => inP (IsEquiv.ret (ff y x) r.1,
                      IsEquiv.isInj (ff y y) $ dmap_comp f *> pmap (comp __ _) (IsEquiv.f_ret (ff y x)) *> r.2,
                      IsEquiv.isInj (ff x x) $ dmap_comp f *> pmap (comp _ __) (IsEquiv.f_ret (ff y x)) *> r.3)

    \lemma isObEmbedding (ff : IsFFMap f) : Embedding {C} {D} (\lam x => f x) \cowith
      | isEmb x y => IsEquiv.toQEquiv $ propExt.conv
          (IsEquiv.parallelEquiv =-char =-char (\lam p => ext $ inv $ dmap_=_~> f))
          (subtype-equiv (ff x y) (dmap_IsIso f) (isConservative ff))

    \lemma fibProp (ff : IsFFMap f) (y : D) : isProp (\Sigma (x : C) (f x = y))
      => Embedding.embeddingFiber-isProp (isObEmbedding ff) y

    -- | A fully faithful functor induces equivalences on squares with a fixed boundary.
    \lemma squares (ff : IsFFMap f) {a b c d : C} (ab : a ~> b) (bd : b ~> d) (ac : a ~> c) (cd : c ~> d)
      : IsEquiv {DPath (\lam i => ab i ~> cd i) ac bd} {DPath (\lam i => f (ab i) ~> f (cd i)) (dmap f ac) (dmap f bd)} (\lam s => dpath \lam i => dmap f (s i))
      => squares-at f (ff a d) ab bd ac cd
  }

-- | A functor that is fully faithful on arrows from {a} to {d} induces equivalences on squares from {a} to {d} with a fixed boundary.
\lemma squares-at {C D : \Cat} (f : C ->⁺ D) {a b c d : C} (e : IsEquiv {a ~> d} (dmap f)) (ab : a ~> b) (bd : b ~> d) (ac : a ~> c) (cd : c ~> d)
  : IsEquiv {DPath (\lam i => ab i ~> cd i) ac bd} {DPath (\lam i => f (ab i) ~> f (cd i)) (dmap f ac) (dmap f bd)} (\lam s => dpath \lam i => dmap f (s i))
  => \let | bf => conn-right ab
          | tf => conn-right ac
          | cf => dpath \lam i => dpath \lam j => fill2 ac cd i j
     \in propExt.conv (IsEquiv.parallelEquiv (inP (square-char.gen-equiv bf tf cf))
            (inP (square-char.gen-equiv (dpath \lam i => dmap f (bf i)) (dpath \lam i => dmap f (tf i)) (dpath \lam i => dmap f (cf i))))
            (\lam s => inv (square-char.forward-gen.natural f {a} {b} {c} {d} {ab} {bd} {ac} bf tf {comp ac cd} cf s)))
          (triangles-at f e)
  \where {
    -- | A functor that is fully faithful on arrows from {a} to {d} induces equivalences on triangles from {a} to {d} with a fixed boundary.
    \private \lemma triangles-at {C D : \Cat} (f : C ->⁺ D) {a b d : C} (e : IsEquiv {a ~> d} (dmap f)) {ab : a ~> b} {bd : b ~> d} {ad : a ~> d}
      : IsEquiv {DPath (\lam i => a ~> bd i) ab ad} {DPath (\lam i => f a ~> dmap f bd i) (dmap f ab) (dmap f ad)} (\lam t => dpath \lam i => dmap f (t i))
      => fiberwiseEquiv e {DPath (\lam i => a ~> bd i) ab} (\lam ad t => dpath \lam i => dmap f (t i))
          (contr-equiv (segal-contr.flipped ab bd) (segal-contr.flipped (dmap f ab) (dmap f bd))) ad
  }

\lemma ffMap-char {C D : \Cat} {f : C ->⁺ D}
  : IsFFMap f <-> IsEquiv {\Sigma (j : \Sigma C C) (j.1 ~> j.2)} {\Sigma (j : \Sigma C C) (f j.1 ~> f j.2)} (\lam s => (s.1, dmap f s.2))
  => <->trans (later (\lam ff j => ff j.1 j.2, \lam e x y => e (x,y))) $ <->_=.2 $ totalEquiv {\Sigma C C} {\lam j => j.1 ~> j.2} \lam j => dmap f

\lemma ffMap-pullback {B C D : \Cat} (g : B ->⁺ D) {f : C ->⁺ D} (ff : IsFFMap f)
  : IsFFMap {\Sigma⁺ (x : B) (\Sigma⁺ (y : C) (f y = g x))} __.1
  => \lam s t => inP $ transQEquiv (dpath-sigma-equiv \lam _ x => \Sigma⁺ (y : C) (f y = g x)) $
        contr-right {s.1 ~> t.1} \lam r => ff-surj-equiv.contr ff (\lam i =>⁺ g (r i))

-- | A composite of fully faithful maps is fully faithful.
\lemma ffMap-comp {A B C : \Cat} {f : A ->⁺ B} {g : B ->⁺ C} (ff : IsFFMap f) (gf : IsFFMap g) : IsFFMap (\lam a => g (f a))
  => \lam x y => IsEquiv.trans (ff x y) (gf (f x) (f y))

-- | If {g} and `g ∘ f` are fully faithful, then so is {f}.
\lemma ffMap-leftFactor {A B C : \Cat} {f : A ->⁺ B} {g : B ->⁺ C} (gf : IsFFMap g) (gff : IsFFMap (\lam a => g (f a))) : IsFFMap f
  => \lam x y => IsEquiv.leftFactor (gf (f x) (f y)) (gff x y)

\type IsSurjMap {C D : \Cat} (f : C ->⁺ D) : \Prop
  => \Pi (y : D) -> ∃ (x : C) (f x = y)

\lemma ff-surj-equiv {C D : \Cat} {f : C ->⁺ D} : (\Sigma (IsFFMap f) (IsSurjMap f)) <-> IsHEquiv f
  => (\lam (ff,fs) => IsHEquiv.rightFactor
        (\have | fs2 => \lam y =>⁺ (section ff fs y).2
               | r => section (IsFFMap.section-ff ff fs2) (IsFFMap.section-surj ff fs2)
         \in IsHEquiv.biEquiv {_} {_} {_} {f} fs2 \lam x => (r x).2)
        (Paths.transportInv IsHEquiv (ext \lam x => (section ff fs x).2) idHEquiv),
      \lam (inP e) => (\lam x y => inP \new QEquiv {
        | ret p => comp (=_~> (inv (e.finv_f x))) (comp (dmap e.finv p) (=_~> (e.finv_f y)))
        | ret_f p => pmap+ (comp _) (~>-natural (\lam x => =_~> (e.finv_f x)))
                  *> comp-assoc *> pmap+ (comp __ p) (=_~>_comp *> pmap+ =_~> inv_*>) *> comp_idd-left
        | f_sec p => dmap_comp f *> pmap2+ comp (dmap_=_~> f) (dmap_comp f
                      *> pmap+ (comp _) (dmap_=_~> f *> pmap+ =_~> e.coh_inv_f)
                      *> ~>-natural (\lam y => =_~> (e.coh_inv y)))
                  *> comp-assoc *> pmap+ (comp __ _) (pmap+ (\lam x => comp _ (=_~> x)) (inv e.coh_inv_f)
                      *> =_~>_comp *> pmap+ =_~> (inv (pmap+_*> f) *> pmap+ (pmap+ f) inv_*>)) *> comp_idd-left
      }, \lam y => inP (e.finv y, e.f_finv y)))
  \where {
    \protected \lemma contr {C D : \Cat} {f : C ->⁺ D} (ff : IsFFMap f) (h : DI ->⁺ D)
                            {tl : \Sigma⁺ (x : C) (f x = h dleft)} {tr : \Sigma⁺ (x : C) (f x = h dright)}
      : Contr (DPath (\lam i => \Sigma⁺ (x : C) (f x = h i)) tl tr)
      => Contr.Contr_QEquiv (symQEquiv (fib-equiv f h)) $
          IsEquiv=>contrFibers (ff tl.1 tr.1) $ comp (comp (=_~> tl.2) (dpath h)) (=_~> (inv tr.2))
      \where {
        -- | Lifts of {h} to the pullback of {f} along {h} are the fibers of {f} on homs.
        \func fib-equiv {C D : \Cat} (f : C ->⁺ D) (h : DI ->⁺ D)
                        {tl : \Sigma⁺ (x : C) (f x = h dleft)} {tr : \Sigma⁺ (x : C) (f x = h dright)}
          : QEquiv {DPath (\lam i => \Sigma⁺ (x : C) (f x = h i)) tl tr}
                   {Fib (dmap f) (comp (comp (=_~> tl.2) (dpath h)) (=_~> (inv tr.2)))}
          => transQEquiv (dpath-sigma-equiv \lam i x => f x = h i) $ sigma-right \lam r =>
               path-square-equiv (dmap f r) (dpath h) `transQEquiv`
               square-equiv (dmap f r) _ `transQEquiv` equiv2

        \private \func equiv2 {C : \Cat} {a b c : C} {f : a ~> b} {p : c = b} {g : a ~> c}
          : QEquiv {comp g (=_~> p) = f} {g = comp f (=_~> (inv p))} \elim p
          | idp => Paths.transport2 (\lam x y => QEquiv {x = f} {g = y}) (inv comp_idd-right) (inv comp_idd-right) idEquiv
      }

    \private \lemma section {C D : \Cat} {f : C ->⁺ D} (ff : IsFFMap f) (fs : IsSurjMap f) (y :⁺ D) : \Sigma⁺ (x : C) (f x = y)
      \level⁺ \lam h tl tr => (contr ff h).toSigma
      => \case fs y \with {
        | inP r => (r.1, r.2)
      }
  }

-- | A fully faithful map admits a lift of any map whose values lie in its image.
\sfunc ffMap-lift {B C : \Cat} {f : B ->⁺ C} (ff : IsFFMap f) {D : \Cat} (g : D ->⁺ C)
                  (gs : \Pi (y : D) -> ∃ (x : B) (f x = g y))
  : \Sigma (h : D ->⁺ B) (\Pi (y :⁺ D) -> f (h y) = g y)
  => \have e : IsHEquiv {\Sigma⁺ (x : D) (\Sigma⁺ (y : B) (f y = g x))} __.1
              => ff-surj-equiv.1 (ffMap-pullback g ff, \lam y => \case gs y \with {
                   | inP (x,fx=gy) => inP ((y, (x,fx=gy)), idp)
                 })
     \in (\lam y =>⁺ (IsHEquiv.ret e y).2.1, \lam y => (IsHEquiv.ret e y).2.2 *> pmap+ g (IsHEquiv.f_ret e))

-- | A functor over {A} that is fully faithful on total categories induces equivalences on paths over arrows of {A}.
\lemma relative-ff {A : \Cat} {F G : A ->⁺ \Cat} (H : \Pi (k :⁺ \Sigma⁺ (x : A) (F x)) -> G k.1)
                   (ff : IsFFMap {\Sigma⁺ (x : A) (F x)} {\Sigma⁺ (x : A) (G x)} (\lam k => (k.1, H k)))
                   {x y : A} (r : x ~> y) (u : F x) (v : F y)
  : IsEquiv {DPath (\lam i => F (r i)) u v} {DPath (\lam i => G (r i)) (H (x,u)) (H (y,v))} (\lam w => dpath \lam i => H (r i, w i))
  => fiberwiseEquiv {x ~> y} (inP idEquiv) {\lam r => DPath (\lam i => F (r i)) u v} (\lam r w => dpath \lam i => H (r i, w i))
      (propExt.dir (IsEquiv.parallelEquiv (inP (dpath-sigma-equiv \lam _ => F)) (inP (dpath-sigma-equiv \lam _ => G)) (\lam _ => idp)) (ff (x,u) (y,v))) r
  \where
    -- | Conversely, equivalences on paths over arrows of {A} give a fully faithful functor on total categories.
    \lemma conv {A : \Cat} {F G : A ->⁺ \Cat} (H : \Pi (k :⁺ \Sigma⁺ (x : A) (F x)) -> G k.1)
                (rel : \Pi {x y : A} (r : x ~> y) (u : F x) (v : F y) ->
                  IsEquiv {DPath (\lam i => F (r i)) u v} {DPath (\lam i => G (r i)) (H (x,u)) (H (y,v))} (\lam w => dpath \lam i => H (r i, w i)))
      : IsFFMap {\Sigma⁺ (x : A) (F x)} {\Sigma⁺ (x : A) (G x)} (\lam k => (k.1, H k))
      => \lam s t => propExt.conv (IsEquiv.parallelEquiv {_} {_} {_} {_} {dmap \lam k => later (k.1, H k)}
                                     (inP (dpath-sigma-equiv \lam _ => F)) (inP (dpath-sigma-equiv \lam _ => G)) (\lam _ => idp))
           (propExt.dir (totalEquiv {s.1 ~> t.1} {\lam r => DPath (\lam i => F (r i)) s.2 t.2} (\lam r w => dpath \lam i => H (r i, w i))) (rel __ s.2 t.2))