\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.Sub
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.Local
\import Algebra.Ring.Localization
\import Algebra.Semiring
\import Function.Meta
\import Logic
\import Meta
\import Order.Lattice
\import Order.LinearOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\open Monoid
\open LocRing

\lemma localization-inv {R : CRing} (S : SubMonoid R) (a : SType S) (r : R) (p : S (a.1 * r)) : Inv (inl~ a) (in~ (a.2 * r, a.1 * r, p)) => {?hidden_proof}
  \where {
    \lemma converse (j : Inv (inl~ a)) : TruncP (\Sigma (r : R) (S (a.1 * r))) => {?hidden_proof}
  }


\lemma localization-zro {R : CRing} (S : SubMonoid R) (a : SType S) (s : R) (c : S s) (p : a.1 * s = zro) : inl~ a = zro => {?hidden_proof}

\lemma localization-nonTrivial {R : CRing} (S : SubMonoid R) (p : Not (S zro)) : 0 /= {LocRing S} 1 => {?hidden_proof}

\lemma localization-isLocal {R : CRing} (S : SubMonoid R) (nt : Not (S zro)) (loc : \Pi (x y : R) -> S y -> (\Sigma (r : R) (S (x * r))) || (\Sigma (r : R) (S ((x + y) * r)))) : LocalCRing {
  | CRing => LocRing S
} => {?hidden_proof}

\lemma localization-isField {R : CRing} (S : SubMonoid R) (nt : Not (S zro)) (loc : \Pi (x y : R) -> S y -> (\Sigma (r : R) (S (x * r))) || (\Sigma (r : R) (S ((x + y) * r)))) 
(fp : \Pi (x : R) -> (\Pi (r : R) -> Not (S (x * r))) -> TruncP (\Sigma (s : R) (S s) (x * s = zro))) : Field {
  | CRing => LocRing S
} => {?hidden_proof}

\func localization-isDiscreteField {R : CRing} (S : SubMonoid R) (nt : Not (S zro)) (fp : \Pi (x : R) -> (\Sigma (s : R) (S s) (x * s = zro)) || (\Sigma (r : R) (S (x * r)))) : DiscreteField {
  | CRing => LocRing S
} \cowith
  | zro/=ide => {?hidden_proof}
  | eitherZeroOrInv => {?hidden_proof}

\func localization-isOrderedField (R : OrderedCRing) : OrderedField \cowith
  | Field => localization-isField (positiveSubset R) zro/>0
    (\lam x y y>0 => (\case <_+-comparison (negative x) (x + y) (transport isPos simplify y>0) \with {
    | byLeft -x>0 => byLeft (negative ide, simplify -x>0)  | byRight x+y>0 => byRight (ide, simplify x+y>0)}))
    (\lam x x-ni => inP (ide, ide>zro, ide-right *> <_+-connectedness (\lam x>0 => x-ni ide (simplify x>0)) (\lam -x>0 => x-ni (negative ide) (simplify -x>0))))
  | isPos => isPositive
  | zro/>0 => {?hidden_proof}
  | positive_+ => {?hidden_proof}
  | ide>zro => {?hidden_proof}
  | <_+-comparison => {?hidden_proof}
  | <_+-connectedness => {?hidden_proof}
  | positive_* => {?hidden_proof}
  | positive=>#0 => {?hidden_proof}
  | #0=>eitherPosOrNeg => {?hidden_proof}
  | meet => meet
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | join => join
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  \where {
    \open OrderedAddGroup
    \open LinearOrder
    \open LinearlyOrderedSemiring \hiding (Dec)

    \func positiveSubset (R : OrderedCRing) : SubMonoid R \cowith
      | contains => isPos
      | contains_ide => {?hidden_proof}
      | contains_* => {?hidden_proof}

    \func isPositive {R : OrderedCRing} (x : Type {R} {positiveSubset R}) : \Prop \elim x
      | in~ x => isPos x.1
      | ~-equiv x y x~y => propExt (\lam x>0 => OrderedRing.pos_*-cancel-right (transport isPos x~y (positive_* x>0 y.3)) x.3) 
        (\lam y>0 => OrderedRing.pos_*-cancel-right (transport isPos (inv x~y) (positive_* y>0 x.3)) y.3)
  }


\func localization-isDiscreteOrderedField (R : OrderedCRing.Dec) : DiscreteOrderedField \cowith
  | DiscreteField => localization-isDiscreteField (localization-isOrderedField.positiveSubset R) zro/>0
    (\lam x => (\case +_trichotomy x \with {  | less x<0 => byRight (negative ide, simplify (R.<0_neg x<0))
    | equals x=0 => byLeft (ide, ide>zro, simplify x=0)  | greater x>0 => byRight (ide, simplify (R.>0_pos x>0))}))
  | OrderedField => localization-isOrderedField R
  \where {
    \open OrderedRing
  }
