\import Algebra.Algebra
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.QModule
\import Algebra.Ring
\import Analysis.FuncLimit
\import Analysis.Limit
\import Arith.Nat
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Arith.Real.Root \using ( sqrt \as sqrtR )
\import Arith.Real.UpperReal
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Operations
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set.Subset
\import Topology.BanachSpace
\import Topology.CoverSpace.Complete
\import Topology.CoverSpace.CompletionTools
\import Topology.CoverSpace.Product
\import Topology.MetricSpace
\import Topology.NormedAbGroup
\import Topology.NormedAbGroup.ExComplete
\import Topology.NormedAbGroup.Real
\import Topology.NormedAbGroup.Real.Functions
\import Topology.NormedRing
\import Topology.TopAbGroup.Complete
\import Topology.TopAbGroup.Product
\import Topology.TopSpace
\import Topology.TopSpace.Product

\class BanachAlgebra \extends BanachSpace, QAlgebra, CompleteExNormedRing

\class RealPreBanachAlgebra \extends RealPreBanachSpace, ExPseudoNormedRing

\class RealBanachPseudoAlgebra \extends RealBanachSpace, QPseudoAlgebra, ExPseudoNormedPseudoRing, CompleteExNormedAbGroup
  \where {
    \open CoverMap
    \open ProductCoverSpace
  }


\class RealBanachAlgebra \extends RealBanachPseudoAlgebra, BanachAlgebra, RealPreBanachAlgebra
  \where {
    \open CoverMap
    \open ProductCoverSpace

    rfunc (n : Nat) : Rat \elim n
      | 0 => 0
      | suc n => ratio 1 2 * (1 + rfunc n * rfunc n)

    \lemma rfunc>=0 {n : Nat} : 0 <= rfunc n => {?hidden_proof}

    \lemma rfunc<=1 {n : Nat} : rfunc n <= 1 => {?hidden_proof}

    \lemma rfunc-inc {n : Nat} : rfunc n <= rfunc (suc n) => {?hidden_proof}

    \lemma rfunc-rec {n : Nat} : rfunc (suc (suc n)) - rfunc (suc n) = ratio 1 2 * ((rfunc (suc n) + rfunc n) * (rfunc (suc n) - rfunc n)) => {?hidden_proof}

    \lemma rfunc-bound {eps : Rat} (eps>0 : 0 < eps) {n : Nat} (p : rfunc n <= 1 - eps) : 1 - rfunc n <= RatField.pow (1 - ratio 1 2 * eps) n => {?hidden_proof}

    \lemma rfunc-limit : TopSpace.IsLimit rfunc 1 => {?hidden_proof}
  }


\instance BanachAlgebraCompletion (X : RealPreBanachAlgebra) : RealBanachAlgebra 
  | BanachSpace => BanachCompletion X
  | * => *-func
  | *-assoc => {?hidden_proof}
  | ldistr => {?hidden_proof}
  | rdistr => {?hidden_proof}
  | ide => pointCF 1
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  | norm_*_<= => {?hidden_proof}
  | norm_ide_<= => {?hidden_proof}
  \where {
    \open ProductCoverSpace
    \open CoverMap
    \open TopAbGroupCompletion

    \func *-cover : CoverMap (Completion X ⨯ Completion X) (Completion X) => lift2 *-locally-uniform

    \func *-func (x y : RegularCauchyFilter X) => *-cover (x, y)
  }
