\import Data.Bool
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.TFAE
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.RatherBelow
\import Topology.TopSpace
\open Set
\open ClosurePrecoverSpace

\class PrecoverSpace \extends TopSpace {
  | isCauchy : Set (Set E) -> \Prop
  | cauchy-cover {C : Set (Set E)} : isCauchy C -> \Pi (x : E) -> ∃ (U : C) (U x)
  | cauchy-top : isCauchy (single top)
  | cauchy-refine {C D : Set (Set E)} : isCauchy C -> Refines C D -> isCauchy D
  | cauchy-glue {C : Set (Set E)} : isCauchy C -> \Pi {D : Set E -> Set (Set E)} -> (\Pi {U : Set E} -> C U -> isCauchy (D U)) -> isCauchy (\lam U => ∃ (V W : Set E) (C V) (D V W) (U = V ∧ W))
  | cauchy-open {S : Set E} : isOpen S <-> ∀ {x : S} (isCauchy (\lam U => U x -> U ⊆ S))
  | open-top => cauchy-open.2 (\lam _ => cauchy-refine cauchy-top (\lam {U} _ => inP (U, \lam _ _ => (), <=-refl)))
  | open-inter => \lam Uo Vo => cauchy-open.2 $ later
    (\lam {x} (Ux, Vx) => cauchy-refine (cauchy-glue (cauchy-open.1 Uo Ux) (\lam _ => cauchy-open.1 Vo Vx)) 
    (\lam inP (U', V', Uc, Vc, W=U'V') => inP (U' ∧ V', \lam (U'x, V'x) {y} (U'y, V'y) => (Uc U'x U'y, Vc V'x V'y), =_<= W=U'V')))
  | open-Union => \lam So => cauchy-open.2 $ later 
    (\lam {x} inP (U, SU, Ux) => cauchy-refine (cauchy-open.1 (So SU) Ux) (\lam {V} Vc => inP (V, \lam Vx => Vc Vx <=∘ Set.Union-cond SU, <=-refl)))
  | isOpen => isOpen
  | cauchy-open => cauchy-open-impl
}
  \where {
    \lemma PrecoverSpace-ext {X : \Set} {S T : PrecoverSpace X} (p : \Pi {C : Set (Set X)} -> S.isCauchy C <-> T.isCauchy C) : S = T => {?hidden_proof}
  }


\lemma cauchy-subset {X : PrecoverSpace} {C D : Set (Set X)} (Cc : isCauchy C) (e : \Pi {U : Set X} -> C U -> D U) : isCauchy D => {?hidden_proof}

\lemma top-cauchy {X : PrecoverSpace} {C : Set (Set X)} (Ct : C top) : isCauchy C => {?hidden_proof}

\lemma cauchy-inter {X : PrecoverSpace} {C D : Set (Set X)} (Cc : isCauchy C) (Dc : isCauchy D) : isCauchy (\lam U => ∃ (V W : Set X) (C V) (D W) (U = V ∧ W)) => {?hidden_proof}

\lemma cauchy-array-inter {X : PrecoverSpace} (Cs : Array (Given X.isCauchy)) :
  isCauchy (\lam V => ∃ (Us : Array (Set X) Cs.len) (\Pi (j : Fin Cs.len) -> (Cs j).1 (Us j)) (V = MeetSemilattice.Big_∧ (top :: Us))) => {?hidden_proof}

\class PrecoverMap \extends ContMap {
  \override Dom : PrecoverSpace
  \override Cod : PrecoverSpace
  | func-cover {D : Set (Set Cod)} : isCauchy D -> isCauchy (\lam U => ∃ (V : D) (U = func ^-1 V))
  | func-cont => \lam Uo =>
    cauchy-open.2 $ later (\lam {x} Ufx => cauchy-refine (func-cover (cauchy-open.1 Uo Ufx)) (\lam inP (W, c, d) => inP (func ^-1 W, \lam a {_} => c a, =_<= d)))
}
  \where {
    \func id {X : PrecoverSpace} : PrecoverMap X X \cowith
      | func => \lam x => x
      | func-cover => \lam Dc => cauchy-subset Dc (\lam {U} DU => inP $ later (U, DU, idp))

    \func compose \alias \infixl 8 ∘ {X Y Z : PrecoverSpace} (g : PrecoverMap Y Z) (f : PrecoverMap X Y) : PrecoverMap X Z \cowith
      | func => \lam x => g (f x)
      | func-cover => \lam Dc => cauchy-subset (f.func-cover $ g.func-cover Dc) (\lam inP (V, inP (W, DW, q), p) => inP $ later (W, DW, p *> rewrite q idp))

    \func const {Y X : PrecoverSpace} (x : X) : PrecoverMap Y X \cowith
      | func => \lam _ => x
      | func-cover => \lam Dc => top-cauchy (\case cauchy-cover Dc x \with {  | inP (U, DU, Ux) => inP $ later (U, DU, ext (\lam y => ext (\lam _ => Ux, \lam _ => ())))})

    \lemma id-denseEmbedding {X : PrecoverSpace} : PrecoverMap.IsDenseEmbedding {id {X}} => {?hidden_proof}

    \lemma embedding-left {X Y Z : PrecoverSpace} (f : PrecoverMap X Y) (g : PrecoverMap Y Z) (fg : PrecoverMap.IsEmbedding {g ∘ f}) : f.IsEmbedding => {?hidden_proof}
  }


\type \infix 4 <=< {X : PrecoverSpace} (V U : Set X) : \Prop => isCauchy (\lam W => Given (V ∧ W) -> W ⊆ U)

\lemma <=<_single {X : PrecoverSpace} {x : X} {U : Set X} : single x <=< U <-> isCauchy (\lam W => W x -> W ⊆ U) => {?hidden_proof}

\lemma <=<_<= {X : PrecoverSpace} {V U : Set X} (p : V <=< U) : V <= U => {?hidden_proof}

\lemma <=<_^-1 {X Y : PrecoverSpace} {f : PrecoverMap X Y} {U V : Set Y} (U<=<V : U <=< V) : f ^-1 U <=< f ^-1 V => {?hidden_proof}

\lemma <=<-cont {X : PrecoverSpace} {Y : CoverSpace} {f : ContMap X Y} {x : X} {U : Set Y} (fx<=<U : single (f x) <=< U) : single x <=< f ^-1 U => {?hidden_proof}

\type \infix 4 s<=< {X : PrecoverSpace} (V U : Set X) : \Prop => isCauchy (\lam W => (W = Compl V) || (W = U))

\lemma s<=<_<=< {X : PrecoverSpace} {V U : Set X} (p : V s<=< U) : V <=< U => {?hidden_proof}

\lemma s<=<_<= {X : PrecoverSpace} {V U : Set X} (p : V s<=< U) : V <= U => {?hidden_proof}

\lemma s<=<_bottom {X : PrecoverSpace} {U : Set X} : bottom s<=< U => {?hidden_proof}

\lemma s<=<_^-1 {X Y : PrecoverSpace} (f : PrecoverMap X Y) {U V : Set Y} (U<=<V : U s<=< V) : f ^-1 U s<=< f ^-1 V => {?hidden_proof}

\instance RegularRatherBelow {X : PrecoverSpace} : RatherBelow {SetLattice X} <=< 
  | <=<_top => unfolds $ top-cauchy (\lam _ => <=-refl)
  | <=<-left => \lam p q => cauchy-subset (unfolds in p) (\lam f t => f t <=∘ q)
  | <=<-right => \lam p q => cauchy-subset (unfolds in q) $ later (\lam {Z} f (x, (Wx, Zx)) => f (x, (p Wx, Zx)))
  | <=<_meet => \lam U<=<U' V<=<V' => cauchy-subset (cauchy-inter (unfolds in U<=<U') V<=<V') $ later
    (\lam inP (U'', V'', t1, t2, p) => rewrite p (\lam (x, ((Ux, Vx), (U''x, V''x))) => MeetSemilattice.meet-monotone (t1 (x, (Ux, U''x))) (t2 (x, (Vx, V''x)))))

\instance StronglyRatherBelow {X : PrecoverSpace} : RatherBelow {SetLattice X} s<=< 
  | <=<_top => unfolds $ top-cauchy $ byRight idp
  | <=<-left => \lam p q => cauchy-refine (unfolds in p) 
    (\lam {U'} => later (\case __ \with {  | byLeft r => rewrite r $ inP (_, byLeft idp, <=-refl)  | byRight r => rewrite r $ inP (_, byRight idp, q)}))
  | <=<-right => \lam p q => cauchy-refine (unfolds in q)
    (\lam {U'} => later (\case __ \with {  | byLeft r => inP (_, byLeft idp, rewrite r (\lam nVx Wx => nVx (p Wx)))  | byRight r => inP (U', byRight r, <=-refl)}))
  | <=<_meet => \lam U<=<U' V<=<V' => cauchy-refine (cauchy-inter (unfolds in U<=<U') V<=<V') $ later
    (\lam inP (U'', V'', t1, t2, p) => rewrite p
    (\case \elim t1, \elim t2 \with {  | byLeft r, _ => inP (_, byLeft idp, rewrite r (\lam (nUx, _) (Ux, _) => nUx Ux))
    | _, byLeft r => inP (_, byLeft idp, rewrite r (\lam (_, nVx) (_, Vx) => nVx Vx))  | byRight q, byRight r => inP (_, byRight $ pmap2 ∧ q r, <=-refl)
  }))

\class CoverSpace \extends PrecoverSpace {
  | isRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V <=< U))
}
  \where {
    \lemma CoverSpace-ext {X : \Set} {S T : CoverSpace X} (p : \Pi {C : Set (Set X)} -> S.isCauchy C <-> T.isCauchy C) : S = T => {?hidden_proof}
  }


\lemma <=<-inter {X : CoverSpace} {x : X} {U : Set X} (x<=<U : single x <=< U) : ∃ (V : Set X) (single x <=< V) (V <=< U) => {?hidden_proof}

\lemma s<=<-inter {X : StronglyRegularCoverSpace} {x : X} {U : Set X} (x<=<U : single x <=< U) : ∃ (V : Set X) (single x s<=< V) (V s<=< U) => {?hidden_proof}

\lemma denseSet-char {X : CoverSpace} {S : Set X} : TFAE (IsDenseSet S, \Pi {x : X} {U : Set X} -> single x <=< U -> ∃ (x' : S) (U x'), 
  ∀ {C : isCauchy} (isCauchy (\lam V => ∃ (U : C) (V ⊆ U) (Given V -> ∃ (x : S) (U x))))) => {?hidden_proof}

\lemma dense-char {X : PrecoverSpace} {Y : CoverSpace} {f : PrecoverMap X Y} : f.IsDense <-> (\Pi {y : Y} {U : Set Y} -> single y <=< U -> ∃ (x : X) (U (f x))) => {?hidden_proof}

\class StronglyRegularCoverSpace \extends CoverSpace {
  | isStronglyRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V s<=< U))
  | isRegular => \lam Cc => cauchy-subset (isStronglyRegular Cc) (\lam inP (V, CV, Us<=<V) => inP $ later (V, CV, s<=<_<=< Us<=<V))
}

\class OmegaRegularCoverSpace \extends CoverSpace {
  | isOmegaRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V RegularRatherBelow.<=<o U))
  | isRegular => \lam Cc => cauchy-subset (isOmegaRegular Cc) (\lam inP (V, CV, p) => inP $ later (V, CV, RegularRatherBelow.<=<o_<=< p))
}

\class CompletelyRegularCoverSpace \extends OmegaRegularCoverSpace {
  | isCompletelyRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V RegularRatherBelow.<=<c U))
  | isOmegaRegular => \lam Cc => cauchy-subset (isCompletelyRegular Cc) (\lam inP (V, CV, U<=<cV) => inP $ later (V, CV, RatherBelow.<=<c_<=<o U<=<cV))
}

\class CompletelyStronglyRegularCoverSpace \extends StronglyRegularCoverSpace, CompletelyRegularCoverSpace {
  | isCompletelyStronglyRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V StronglyRatherBelow.<=<c U))
  | isStronglyRegular => \lam Cc => cauchy-subset (isCompletelyStronglyRegular Cc) (\lam {V} inP (U, CU, V<=<U) => inP $ later (U, CU, RatherBelow.<=<c_<=< V<=<U))
  | isCompletelyRegular => \lam Cc => cauchy-subset (isCompletelyStronglyRegular Cc) (\lam {V} inP (U, CU, V<=<U) => inP $ later (U, CU, StronglyRatherBelow.<=<c-func s<=<_<=< V<=<U))
}

\func AntiDiscreteCover (X : \Set) : CompletelyStronglyRegularCoverSpace X \cowith
  | isCauchy => \lam C => C top
  | cauchy-cover => \lam Ct x => inP (top, Ct, ())
  | cauchy-top => idp
  | cauchy-refine => \lam Ct e => (\case e Ct \with {
    | inP (V, DV, t<=V) => rewrite (<=-antisymmetric t<=V top-univ) DV
  })
  | cauchy-glue => \lam Ct e => inP (top, top, Ct, e Ct, <=-antisymmetric (\lam _ => ((), ())) top-univ)
  | isCompletelyStronglyRegular => \lam Ct => inP (top, Ct, RatherBelow.Interpolative.<=<_top)

\func DiscreteCover (X : \Set) : CompletelyRegularCoverSpace X \cowith
  | TopSpace => DiscreteTopSpace X
  | isCauchy => \lam C => \Pi (x : X) -> ∃ (U : C) (U x)
  | cauchy-cover => \lam c => c
  | cauchy-top => \lam x => inP (top, idp, ())
  | cauchy-refine => \lam c d x => (
    \have | inP (U, CU, Ux) => c x
          | inP (V, DV, U<=V) => d CU
    \in inP (V, DV, U<=V Ux))
  | cauchy-glue => \lam c d x => (
    \have | inP (U, CU, Ux) => c x
          | inP (V, DV, Vx) => d CU x
    \in inP (U ∧ V, inP (U, V, CU, DV, idp), (Ux, Vx)))
  | isCompletelyRegular => \lam f x => (\case f x \with {
    | inP (U, CU, Ux) => inP (U,  inP (U, CU, 
      inP (=, \lam p => rewrite p (\lam x => inP (single x, \lam (y, (Uy, x=y)) => rewrite x=y $ single_<= Uy, idp)), \lam p => inP (_, idp, p), idp)), Ux
    )
  })
  | cauchy-open => (\lam _ Sx x' => inP (= x', \lam p => rewrite p $ single_<= Sx, idp), \lam _ => ())

\func PrecoverTransfer {X : \Set} {Y : PrecoverSpace} (f : X -> Y) : PrecoverSpace X \cowith
  | isCauchy => \lam C => Y.isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U))
  | cauchy-cover => \lam Ec x => (\case cauchy-cover Ec (f x) \with {
    | inP (U, inP (V, CV, p), Ufx) => inP (V, CV, p Ufx)
  })
  | cauchy-top => top-cauchy $ inP $ later (top, idp, top-univ)
  | cauchy-refine => \lam Ec r => cauchy-subset Ec (\lam inP (V, CV, p) => (\case r CV \with {  | inP (W, DW, V<=W) => inP $ later (W, DW, p <=∘ V<=W)}))
  | cauchy-glue => \lam {C} Ec {D} Fc => cauchy-subset (cauchy-glue Ec {\lam U V => ∃ (U' : C) (f ^-1 U ⊆ U') (V' : D U') (f ^-1 V ⊆ V')} 
    (\lam inP (U', CU', p) => cauchy-subset (Fc CU') (\lam {V} inP (V', DU'V', q) => inP $ later (U', CU', p, V', DU'V', q)))) 
  (\lam {_} inP (U, V, _, inP (U', CU', p, V', DU'V', q), idp) => inP $ later (_, inP (U', V', CU', DU'V', idp), MeetSemilattice.meet-monotone p q))
  \where {
    \lemma makeCauchy {C : Set (Set Y)} (Cc : isCauchy C) : isCauchy {PrecoverTransfer f} (\lam U => ∃ (V : C) (U = f ^-1 V)) => {?hidden_proof}
  }


\lemma PrecoverTransfer-map {X : \Set} {Y : PrecoverSpace} (f : X -> Y) : PrecoverMap (PrecoverTransfer f) Y f => {?hidden_proof}

\lemma PrecoverTransfer-char {X Y : PrecoverSpace} {f : PrecoverMap X Y} {C : Set (Set X)} (Dc : isCauchy {PrecoverTransfer f} C) : X.isCauchy C => {?hidden_proof}

\lemma PrecoverTransfer-univ {X Z : PrecoverSpace} {Y : \Set} {f : X -> Y} {g : Y -> Z} (fg : PrecoverMap X Z (\lam x => g (f x))) : PrecoverMap X (PrecoverTransfer g) f => {?hidden_proof}

\func ClosurePrecoverSpace {X : \Set} (A : Set (Set X) -> \Prop) (CA : \Pi {C : Set (Set X)} -> A C -> \Pi (x : X) -> ∃ (U : C) (U x)) : PrecoverSpace X \cowith
  | isCauchy => Closure A
  | cauchy-cover => \lam CC x => closure-filter (pointFilter x) (\lam AC => CA AC x) CC
  | cauchy-top => closure-top idp
  | cauchy-refine => closure-refine
  | cauchy-glue => closure-trans __ __ idp
  \where {
\data Closure {X : \Set} (A : Set (Set X) -> \Prop) (C : Set (Set X)) : \Prop 
      | closure (A C)
      | closure-top (C = single top)
      | closure-refine {D : Set (Set X)} (Closure A D) (Refines D C)
      | closure-trans {D : Set (Set X)} (Closure A D) {E : \Pi (U : Set X) -> Set (Set X)} (\Pi {U : Set X} -> D U -> Closure A (E U)) (C = (\lam U => ∃ (V W : Set X) (D V) (E V W) (U = V ∧ W)))

    \lemma closure-inter {A : Set (Set X) -> \Prop} {C D : Set (Set X)} (Cc : Closure A C) (Dc : Closure A D) : Closure A (\lam W => ∃ (U V : Set X) (C U) (D V) (W = U ∧ V)) => {?hidden_proof}

    \lemma closure-subset {X : \Set} {A : Set (Set X) -> \Prop} {C D : Set (Set X)} (Dc : Closure A D) (D<=C : D ⊆ C) : Closure A C => {?hidden_proof}

    \lemma closure-filter {A : Set (Set X) -> \Prop} (F : SetFilter X) (CA : \Pi {C : Set (Set X)} -> A C -> ∃ (U : C) (F U)) {C : Set (Set X)} (CC : Closure A C) : ∃ (U : C) (F U) 
      => {?hidden_proof}

    \lemma closure-cauchy {S : PrecoverSpace X} {A : Set (Set X) -> \Prop} (AS : \Pi {C : Set (Set X)} -> A C -> S.isCauchy C) {C : Set (Set X)} (CC : Closure A C) : S.isCauchy C 
      => {?hidden_proof}

    \lemma closure-univ-cover {Y : PrecoverSpace} {f : Y -> X} (Ap : ∀ {C : A} (isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)))) {C : Set (Set X)} (Cc : Closure A C) :
      isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)) => {?hidden_proof}

    \lemma closure-univ {S : PrecoverSpace X} {Y : PrecoverSpace} (AS : \Pi {C : Set (Set X)} -> isCauchy C -> Closure A C) (f : Y -> X) 
    (Ap : ∀ {C : A} (isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)))) : PrecoverMap Y S f => {?hidden_proof}

    \lemma closure-univ-closure {Y : \Set} {B : Set (Set Y) -> \Prop} (f : Y -> X) (Ap : ∀ {C : A} (Closure B (\lam V => ∃ (U : Set X) (C U) (V = f ^-1 U)))) {C : Set (Set X)} 
    (Cc : Closure A C) : Closure B (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)) => {?hidden_proof}

    \lemma closure-univ-closure-id {B : Set (Set X) -> \Prop} (Ap : ∀ {C : A} (Closure B C)) {C : Set (Set X)} (Cc : Closure A C) : Closure B C => {?hidden_proof}

    \lemma closure-map {X Y : \Set} (f : Set X -> Set Y) (ft : \Pi {y : Y} -> f top y) (fm : \Pi {U V : Set X} -> U ⊆ V -> f U ⊆ f V) 
    (fi : \Pi {U V : Set X} -> f U ∧ f V ⊆ f (U ∧ V)) {A : Set (Set X) -> \Prop} {C : Set (Set X)} {D : Set (Set Y)} (eCD : ∀ {U : C} ∃ (V : D) (f U ⊆ V)) 
    (CC : Closure A C) : Closure (\lam D => ∃ (C : A) ∀ {U : C} ∃ (V : D) (f U ⊆ V)) D => {?hidden_proof}

    \lemma closure-embedding {S : PrecoverSpace X} {Y : PrecoverSpace} (AS : \Pi {C : Set (Set X)} -> isCauchy C -> Closure A C) (f : PrecoverMap S Y) 
    (p : \Pi {C : Set (Set X)} -> A C -> isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U))) : f.IsEmbedding => {?hidden_proof}
      \where {
        \lemma aux {C : Set (Set X)} (CC : Closure A C) : isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U)) => {?hidden_proof}
      }

  }


\instance PrecoverLattice (X : \Set) : CompleteLattice (PrecoverSpace X) 
  | <= => \lam A B => \Pi {C : Set (Set X)} -> isCauchy {A} C -> isCauchy {B} C
  | <=-refl => \lam c => c
  | <=-transitive => \lam f g c => g (f c)
  | <=-antisymmetric => \lam f g => PrecoverSpace.PrecoverSpace-ext (\lam {C} => (f, g))
  | top => DiscreteCover X
  | top-univ => \lam {A} c => cauchy-cover {A} c
  | Join => \lam {J} f => ClosurePrecoverSpace (\lam C => ∃ (j : J) (isCauchy {f j} C)) (\lam e x => (\case \elim e \with {  | inP (j, Cc) => cauchy-cover Cc x}))
  | Join-cond => \lam j Cc => closure $ inP (j, Cc)
  | Join-univ => \lam e => closure-cauchy $ later (\case __ \with {  | inP (j, Cc) => e j Cc})

\func CoverTransfer {X : \Set} {Y : CoverSpace} (f : X -> Y) : CoverSpace X \cowith
  | TopSpace => TopTransfer f
  | isCauchy => isCauchy {PrecoverTransfer f}
  | cauchy-cover => cauchy-cover {PrecoverTransfer f}
  | cauchy-top => cauchy-top {PrecoverTransfer f}
  | cauchy-refine => cauchy-refine {PrecoverTransfer f}
  | cauchy-glue => cauchy-glue {PrecoverTransfer f}
  | isRegular => \lam Dc => cauchy-subset (isRegular Dc)
    (\lam {V} inP (U, inP (W, CW, p), V<=<U) => inP $ later 
    (_, inP (W, CW, <=<-left (cauchy-subset (unfolds in V<=<U) (\lam {W} g => inP $ later (_, \lam (x, s) {_} => g (f x, s), <=-refl))) p), <=-refl))
  | cauchy-open => \lam {S} => (
    \lam inP (V, Vo, p) Sx => cauchy-subset (cauchy-open.1 Vo $ rewrite p in Sx) (\lam {W} g => inP $ later (f ^-1 W, \lam Wfx {y} Wfy => rewrite p $ g Wfx Wfy, <=-refl)),
      \lam c => inP (Union (\lam V' => \Sigma (isOpen V') (f ^-1 V' ⊆ S)), open-Union __.1,
      <=-antisymmetric (\lam {x} Sx => (\case Y.cauchy-regular-cover (c Sx) (f x) \with {
      | inP (V, inP (U, g, p), fx<=<V) => inP (_, (Y.interior {V}, \lam {x'} fx'<=<V => g (p $ <=<_<= fx<=<V idp) (p $ <=<_<= fx'<=<V idp)), fx<=<V)})) 
    (\lam inP (V, (_, p), Vfx) => p Vfx))
    )

\func CoverSub {X : CoverSpace} (S : Set X) : CoverSpace (Set.Total S) => CoverTransfer __.1

\func ClosureCoverSpace {X : \Set} (A : Set (Set X) -> \Prop) (CA : \Pi {C : Set (Set X)} -> A C -> \Pi (x : X) -> ∃ (U : C) (U x)) 
(AS : \Pi {C : Set (Set X)} -> A C -> Closure A (\lam V => ∃ (U : C) (Closure A (\lam W => Given (V ∧ W) -> W ⊆ U)))) : CoverSpace X \cowith
  | PrecoverSpace => ClosurePrecoverSpace A CA
  | isRegular => closure-regular {ClosurePrecoverSpace A CA} RegularRatherBelow (\lam AC => closure-subset (AS AC) (\lam inP (U, CU, c) => inP (U, CU, c)))
  \where {
    \lemma closure-regular {X : PrecoverSpace} (RB : RatherBelow {SetLattice X}) {A : Set (Set X) -> \Prop} 
    (AS : \Pi {C : Set (Set X)} -> A C -> Closure A (\lam V => ∃ (U : C) (RB.R V U))) {C : Set (Set X)} (CC : Closure A C) :
      Closure A (\lam V => ∃ (U : C) (RB.R V U)) => {?hidden_proof}

    \lemma closure-pred {X : PrecoverSpace} (P : Set X -> \Prop) (Pt : P top) (Pm : ∀ {U V : P} (P (U ∧ V))) {A : Set (Set X) -> \Prop} (AP : ∀ {C : A} {U : C} (P U)) 
    {C : Set (Set X)} (CC : Closure A C) : ∃ (D : Closure A) (∀ {V : D} (P V)) (∀ {V : D} ∃ (U : C) (V ⊆ U)) => {?hidden_proof}
  }


\func ClosureRegularCoverSpace {X : \Set} (A : Set (Set X) -> \Prop) (CA : \Pi {C : Set (Set X)} -> A C -> \Pi (x : X) -> ∃ (U : C) (U x)) 
(AI : \Pi {C : Set (Set X)} -> A C -> ∃ (D : A) ∀ {V : D} ∃ (U : C) ∀ {V' : D} (Given (V ∧ V') -> V' ⊆ U)) : CompletelyRegularCoverSpace X \cowith
  | PrecoverSpace => ClosurePrecoverSpace A CA
  | isCompletelyRegular => ClosureCoverSpace.closure-regular {ClosurePrecoverSpace A CA} RegularRatherBelow.Interpolative
    (\case AI __ \with {  | inP (D, AD, f) => closure-subset (closure AD)    (\case f __ \with {
      | inP (U, CU, g) => inP (U, CU,  inP (\lam V' U' => ∃ (E : A) ∀ {W : E} (Given (V' ∧ W) -> W ⊆ U'), \lam inP (E, AE, h) => closure-subset (closure AE) (\lam EW => h EW),
            \lam {V'} inP (E, AE, h) => (\case AI AE \with {
        | inP (F, AF, k) => inP (Union (\lam W => Given (F W) (V' ∧ W)), inP (F, AF, \lam c s => Union-cond $ later (c, s.1, s.2)),
          inP (F, AF,  \lam FW (x, (inP (W', (FW', y, (V'y, W'y)), W'x), Wx)) => (\case k FW' \with {
          | inP (U, EU, l) => l FW (x, (W'x, Wx)) <=∘ h EU (y, (V'y, l FW' (y, (W'y, W'y)) W'y))})))}), inP (D, AD, g)))})})

\instance CoverLattice (X : \Set) : CompleteLattice (CoverSpace X) 
  | <= => \lam A B => \Pi {C : Set (Set X)} -> isCauchy {A} C -> isCauchy {B} C
  | <=-refl => \lam c => c
  | <=-transitive => \lam f g c => g (f c)
  | <=-antisymmetric => \lam f g => CoverSpace.CoverSpace-ext (\lam {C} => (f, g))
  | top => DiscreteCover X
  | top-univ => \lam {A} c => cauchy-cover {A} c
  | Join => \lam f => \new CoverSpace {
    | PrecoverSpace => Join {PrecoverLattice X} f
    | isRegular => ClosureCoverSpace.closure-regular {Join f} RegularRatherBelow $ later
      (\case __ \with {
      | inP (j, Cc) => closure $ inP (j, cauchy-subset (isRegular {f j} Cc) $ later (\lam {U} inP (V, CV, U<=<V) => inP (V, CV, Join-cond {PrecoverLattice X} j {f} U<=<V)))
      })
  }
  | Join-cond => \lam j {f} => Join-cond {PrecoverLattice X} j
  | Join-univ => Join-univ {PrecoverLattice X}
  | join => \lam A B => \new CoverSpace {
    | PrecoverSpace => A ∨ {PrecoverLattice X} B
    | isRegular => ClosureCoverSpace.closure-regular {A ∨ B} RegularRatherBelow $ later
      (\case __ \with {
      | inP (true, Cc) => closure $ inP (true, cauchy-subset (isRegular Cc) $ later (\lam {U} inP (V, CV, U<=<V) => inP (V, CV, join-left {PrecoverLattice X} {A} {B} U<=<V)))
        | inP (false, Cc) => closure $ inP (false, cauchy-subset (isRegular Cc) $ later (\lam {U} inP (V, CV, U<=<V) => inP (V, CV, join-right {PrecoverLattice X} {A} {B} U<=<V)))
      })
  }
  | join-left => join-left {PrecoverLattice X}
  | join-right => join-right {PrecoverLattice X}
  | join-univ => join-univ {PrecoverLattice X}

\func RegPrecoverSpace (X : PrecoverSpace) : CoverSpace X => CompleteLattice.SJoin {CoverLattice X} (\lam A => A <= {PrecoverLattice X} X)

\func regPrecoverSpace {X : PrecoverSpace} : PrecoverMap X (RegPrecoverSpace X) \cowith
  | func => \lam x => x
  | func-cover => \lam d => CompleteLattice.SJoin-univ {PrecoverLattice X} {\lam A => A <= {PrecoverLattice X} X} (\lam p => p) $ transport (isCauchy {RegPrecoverSpace X}) 
    (ext (\lam U => ext (\lam DU => inP (U, DU, idp), \lam inP (V, DV, U=V) => rewrite U=V DV))) d

\lemma regPrecoverSpace-extend {X : PrecoverSpace} {Y : CoverSpace} (f : PrecoverMap X Y) : PrecoverMap (RegPrecoverSpace X) Y f => {?hidden_proof}