\import Data.Bool
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.TFAE
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.RatherBelow
\import Topology.TopSpace
\open Set
\open ClosurePrecoverSpace

\class PrecoverSpace \extends TopSpace {
  | isCauchy : Set (Set E) -> \Prop
  | cauchy-cover {C : Set (Set E)} : isCauchy C -> \Pi (x : E) -> ∃ (U : C) (U x)
  | cauchy-top : isCauchy (single top)
  | cauchy-refine {C D : Set (Set E)} : isCauchy C -> Refines C D -> isCauchy D
  | cauchy-glue {C : Set (Set E)} : isCauchy C -> \Pi {D : Set E -> Set (Set E)} -> (\Pi {U : Set E} -> C U -> isCauchy (D U)) -> isCauchy (\lam U => ∃ (V W : Set E) (C V) (D V W) (U = V ∧ W))
  | cauchy-open {S : Set E} : isOpen S <-> ∀ {x : S} (isCauchy (\lam U => U x -> U ⊆ S))
  | open-top => cauchy-open.2 (\lam _ => cauchy-refine cauchy-top (\lam {U} _ => inP (U, \lam _ _ => (), <=-refl)))
  | open-inter => \lam Uo Vo => cauchy-open.2 $ later
    (\lam {x} (Ux, Vx) => cauchy-refine (cauchy-glue (cauchy-open.1 Uo Ux) (\lam _ => cauchy-open.1 Vo Vx)) 
    (\lam inP (U', V', Uc, Vc, W=U'V') => inP (U' ∧ V', \lam (U'x, V'x) {y} (U'y, V'y) => (Uc U'x U'y, Vc V'x V'y), =_<= W=U'V')))
  | open-Union => \lam So => cauchy-open.2 $ later 
    (\lam {x} inP (U, SU, Ux) => cauchy-refine (cauchy-open.1 (So SU) Ux) (\lam {V} Vc => inP (V, \lam Vx => Vc Vx <=∘ Set.Union-cond SU, <=-refl)))
  | isOpen => isOpen
  | cauchy-open => cauchy-open-impl
}
  \where {
    \lemma PrecoverSpace-ext {X : \Set} {S T : PrecoverSpace X} (p : \Pi {C : Set (Set X)} -> S.isCauchy C <-> T.isCauchy C) : S = T => {?hidden_proof}
  }


\lemma cauchy-subset {X : PrecoverSpace} {C D : Set (Set X)} (Cc : isCauchy C) (e : \Pi {U : Set X} -> C U -> D U) : isCauchy D => {?hidden_proof}

\lemma top-cauchy {X : PrecoverSpace} {C : Set (Set X)} (Ct : C top) : isCauchy C => {?hidden_proof}

\lemma cauchy-inter {X : PrecoverSpace} {C D : Set (Set X)} (Cc : isCauchy C) (Dc : isCauchy D) : isCauchy (\lam U => ∃ (V W : Set X) (C V) (D W) (U = V ∧ W)) => {?hidden_proof}

\lemma cauchy-array-inter {X : PrecoverSpace} (Cs : Array (Given X.isCauchy)) :
  isCauchy (\lam V => ∃ (Us : Array (Set X) Cs.len) (\Pi (j : Fin Cs.len) -> (Cs j).1 (Us j)) (V = MeetSemilattice.Big_∧ (top :: Us))) => {?hidden_proof}

\class PrecoverMap \extends ContMap {
  \override Dom : PrecoverSpace
  \override Cod : PrecoverSpace
  | func-cover {D : Set (Set Cod)} : isCauchy D -> isCauchy (\lam U => ∃ (V : D) (U = func ^-1 V))
  | func-cont => \lam Uo =>
    cauchy-open.2 $ later (\lam {x} Ufx => cauchy-refine (func-cover (cauchy-open.1 Uo Ufx)) (\lam inP (W, c, d) => inP (func ^-1 W, \lam a {_} => c a, =_<= d)))
}
  \where {
    \func id {X : PrecoverSpace} : PrecoverMap X X \cowith
      | func => \lam x => x
      | func-cover => {?hidden_proof}

    \func compose \alias \infixl 8 ∘ {X Y Z : PrecoverSpace} (g : PrecoverMap Y Z) (f : PrecoverMap X Y) : PrecoverMap X Z \cowith
      | func => \lam x => g (f x)
      | func-cover => {?hidden_proof}

    \func const {Y X : PrecoverSpace} (x : X) : PrecoverMap Y X \cowith
      | func => \lam _ => x
      | func-cover => {?hidden_proof}

    \lemma id-denseEmbedding {X : PrecoverSpace} : PrecoverMap.IsDenseEmbedding {id {X}} => {?hidden_proof}

    \lemma embedding-left {X Y Z : PrecoverSpace} (f : PrecoverMap X Y) (g : PrecoverMap Y Z) (fg : PrecoverMap.IsEmbedding {g ∘ f}) : f.IsEmbedding => {?hidden_proof}
  }


\type \infix 4 <=< {X : PrecoverSpace} (V U : Set X) : \Prop => isCauchy (\lam W => Given (V ∧ W) -> W ⊆ U)

\lemma <=<_single {X : PrecoverSpace} {x : X} {U : Set X} : single x <=< U <-> isCauchy (\lam W => W x -> W ⊆ U) => {?hidden_proof}

\lemma <=<_<= {X : PrecoverSpace} {V U : Set X} (p : V <=< U) : V <= U => {?hidden_proof}

\lemma <=<_^-1 {X Y : PrecoverSpace} {f : PrecoverMap X Y} {U V : Set Y} (U<=<V : U <=< V) : f ^-1 U <=< f ^-1 V => {?hidden_proof}

\lemma <=<-cont {X : PrecoverSpace} {Y : CoverSpace} {f : ContMap X Y} {x : X} {U : Set Y} (fx<=<U : single (f x) <=< U) : single x <=< f ^-1 U => {?hidden_proof}

\type \infix 4 s<=< {X : PrecoverSpace} (V U : Set X) : \Prop => isCauchy (\lam W => (W = Compl V) || (W = U))

\lemma s<=<_<=< {X : PrecoverSpace} {V U : Set X} (p : V s<=< U) : V <=< U => {?hidden_proof}

\lemma s<=<_<= {X : PrecoverSpace} {V U : Set X} (p : V s<=< U) : V <= U => {?hidden_proof}

\lemma s<=<_bottom {X : PrecoverSpace} {U : Set X} : bottom s<=< U => {?hidden_proof}

\lemma s<=<_^-1 {X Y : PrecoverSpace} (f : PrecoverMap X Y) {U V : Set Y} (U<=<V : U s<=< V) : f ^-1 U s<=< f ^-1 V => {?hidden_proof}

\instance RegularRatherBelow {X : PrecoverSpace} : RatherBelow {SetLattice X} <=< 
  | <=<_top => {?hidden_proof}
  | <=<-left => {?hidden_proof}
  | <=<-right => {?hidden_proof}
  | <=<_meet => {?hidden_proof}

\instance StronglyRatherBelow {X : PrecoverSpace} : RatherBelow {SetLattice X} s<=< 
  | <=<_top => {?hidden_proof}
  | <=<-left => {?hidden_proof}
  | <=<-right => {?hidden_proof}
  | <=<_meet => {?hidden_proof}

\class CoverSpace \extends PrecoverSpace {
  | isRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V <=< U))
}
  \where {
    \lemma CoverSpace-ext {X : \Set} {S T : CoverSpace X} (p : \Pi {C : Set (Set X)} -> S.isCauchy C <-> T.isCauchy C) : S = T => {?hidden_proof}
  }


\lemma <=<-inter {X : CoverSpace} {x : X} {U : Set X} (x<=<U : single x <=< U) : ∃ (V : Set X) (single x <=< V) (V <=< U) => {?hidden_proof}

\lemma s<=<-inter {X : StronglyRegularCoverSpace} {x : X} {U : Set X} (x<=<U : single x <=< U) : ∃ (V : Set X) (single x s<=< V) (V s<=< U) => {?hidden_proof}

\lemma denseSet-char {X : CoverSpace} {S : Set X} : TFAE (IsDenseSet S, \Pi {x : X} {U : Set X} -> single x <=< U -> ∃ (x' : S) (U x'), 
  ∀ {C : isCauchy} (isCauchy (\lam V => ∃ (U : C) (V ⊆ U) (Given V -> ∃ (x : S) (U x))))) => {?hidden_proof}

\lemma dense-char {X : PrecoverSpace} {Y : CoverSpace} {f : PrecoverMap X Y} : f.IsDense <-> (\Pi {y : Y} {U : Set Y} -> single y <=< U -> ∃ (x : X) (U (f x))) => {?hidden_proof}

\class StronglyRegularCoverSpace \extends CoverSpace {
  | isStronglyRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V s<=< U))
  | isRegular => \lam Cc => cauchy-subset (isStronglyRegular Cc) (\lam inP (V, CV, Us<=<V) => inP $ later (V, CV, s<=<_<=< Us<=<V))
}

\class OmegaRegularCoverSpace \extends CoverSpace {
  | isOmegaRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V RegularRatherBelow.<=<o U))
  | isRegular => \lam Cc => cauchy-subset (isOmegaRegular Cc) (\lam inP (V, CV, p) => inP $ later (V, CV, RegularRatherBelow.<=<o_<=< p))
}

\class CompletelyRegularCoverSpace \extends OmegaRegularCoverSpace {
  | isCompletelyRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V RegularRatherBelow.<=<c U))
  | isOmegaRegular => \lam Cc => cauchy-subset (isCompletelyRegular Cc) (\lam inP (V, CV, U<=<cV) => inP $ later (V, CV, RatherBelow.<=<c_<=<o U<=<cV))
}

\class CompletelyStronglyRegularCoverSpace \extends StronglyRegularCoverSpace, CompletelyRegularCoverSpace {
  | isCompletelyStronglyRegular {C : Set (Set E)} : isCauchy C -> isCauchy (\lam V => ∃ (U : C) (V StronglyRatherBelow.<=<c U))
  | isStronglyRegular => \lam Cc => cauchy-subset (isCompletelyStronglyRegular Cc) (\lam {V} inP (U, CU, V<=<U) => inP $ later (U, CU, RatherBelow.<=<c_<=< V<=<U))
  | isCompletelyRegular => \lam Cc => cauchy-subset (isCompletelyStronglyRegular Cc) (\lam {V} inP (U, CU, V<=<U) => inP $ later (U, CU, StronglyRatherBelow.<=<c-func s<=<_<=< V<=<U))
}

\func AntiDiscreteCover (X : \Set) : CompletelyStronglyRegularCoverSpace X \cowith
  | isCauchy => \lam C => C top
  | cauchy-cover => {?hidden_proof}
  | cauchy-top => {?hidden_proof}
  | cauchy-refine => {?hidden_proof}
  | cauchy-glue => {?hidden_proof}
  | isCompletelyStronglyRegular => {?hidden_proof}

\func DiscreteCover (X : \Set) : CompletelyRegularCoverSpace X \cowith
  | TopSpace => DiscreteTopSpace X
  | isCauchy => \lam C => \Pi (x : X) -> ∃ (U : C) (U x)
  | cauchy-cover => {?hidden_proof}
  | cauchy-top => {?hidden_proof}
  | cauchy-refine => {?hidden_proof}
  | cauchy-glue => {?hidden_proof}
  | isCompletelyRegular => {?hidden_proof}
  | cauchy-open => {?hidden_proof}

\func PrecoverTransfer {X : \Set} {Y : PrecoverSpace} (f : X -> Y) : PrecoverSpace X \cowith
  | isCauchy => \lam C => Y.isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U))
  | cauchy-cover => {?hidden_proof}
  | cauchy-top => {?hidden_proof}
  | cauchy-refine => {?hidden_proof}
  | cauchy-glue => {?hidden_proof}
  \where {
    \lemma makeCauchy {C : Set (Set Y)} (Cc : isCauchy C) : isCauchy {PrecoverTransfer f} (\lam U => ∃ (V : C) (U = f ^-1 V)) => {?hidden_proof}
  }


\lemma PrecoverTransfer-map {X : \Set} {Y : PrecoverSpace} (f : X -> Y) : PrecoverMap (PrecoverTransfer f) Y f => {?hidden_proof}

\lemma PrecoverTransfer-char {X Y : PrecoverSpace} {f : PrecoverMap X Y} {C : Set (Set X)} (Dc : isCauchy {PrecoverTransfer f} C) : X.isCauchy C => {?hidden_proof}

\lemma PrecoverTransfer-univ {X Z : PrecoverSpace} {Y : \Set} {f : X -> Y} {g : Y -> Z} (fg : PrecoverMap X Z (\lam x => g (f x))) : PrecoverMap X (PrecoverTransfer g) f => {?hidden_proof}

\func ClosurePrecoverSpace {X : \Set} (A : Set (Set X) -> \Prop) (CA : \Pi {C : Set (Set X)} -> A C -> \Pi (x : X) -> ∃ (U : C) (U x)) : PrecoverSpace X \cowith
  | isCauchy => Closure A
  | cauchy-cover => {?hidden_proof}
  | cauchy-top => {?hidden_proof}
  | cauchy-refine => {?hidden_proof}
  | cauchy-glue => {?hidden_proof}
  \where {
\data Closure {X : \Set} (A : Set (Set X) -> \Prop) (C : Set (Set X)) : \Prop 
      | closure (A C)
      | closure-top (C = single top)
      | closure-refine {D : Set (Set X)} (Closure A D) (Refines D C)
      | closure-trans {D : Set (Set X)} (Closure A D) {E : \Pi (U : Set X) -> Set (Set X)} (\Pi {U : Set X} -> D U -> Closure A (E U)) (C = (\lam U => ∃ (V W : Set X) (D V) (E V W) (U = V ∧ W)))

    \lemma closure-inter {A : Set (Set X) -> \Prop} {C D : Set (Set X)} (Cc : Closure A C) (Dc : Closure A D) : Closure A (\lam W => ∃ (U V : Set X) (C U) (D V) (W = U ∧ V)) => {?hidden_proof}

    \lemma closure-subset {X : \Set} {A : Set (Set X) -> \Prop} {C D : Set (Set X)} (Dc : Closure A D) (D<=C : D ⊆ C) : Closure A C => {?hidden_proof}

    \lemma closure-filter {A : Set (Set X) -> \Prop} (F : SetFilter X) (CA : \Pi {C : Set (Set X)} -> A C -> ∃ (U : C) (F U)) {C : Set (Set X)} (CC : Closure A C) : ∃ (U : C) (F U) 
      => {?hidden_proof}

    \lemma closure-cauchy {S : PrecoverSpace X} {A : Set (Set X) -> \Prop} (AS : \Pi {C : Set (Set X)} -> A C -> S.isCauchy C) {C : Set (Set X)} (CC : Closure A C) : S.isCauchy C 
      => {?hidden_proof}

    \lemma closure-univ-cover {Y : PrecoverSpace} {f : Y -> X} (Ap : ∀ {C : A} (isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)))) {C : Set (Set X)} (Cc : Closure A C) :
      isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)) => {?hidden_proof}

    \lemma closure-univ {S : PrecoverSpace X} {Y : PrecoverSpace} (AS : \Pi {C : Set (Set X)} -> isCauchy C -> Closure A C) (f : Y -> X) 
    (Ap : ∀ {C : A} (isCauchy (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)))) : PrecoverMap Y S f => {?hidden_proof}

    \lemma closure-univ-closure {Y : \Set} {B : Set (Set Y) -> \Prop} (f : Y -> X) (Ap : ∀ {C : A} (Closure B (\lam V => ∃ (U : Set X) (C U) (V = f ^-1 U)))) {C : Set (Set X)} 
    (Cc : Closure A C) : Closure B (\lam U => ∃ (V : Set X) (C V) (U = f ^-1 V)) => {?hidden_proof}

    \lemma closure-univ-closure-id {B : Set (Set X) -> \Prop} (Ap : ∀ {C : A} (Closure B C)) {C : Set (Set X)} (Cc : Closure A C) : Closure B C => {?hidden_proof}

    \lemma closure-map {X Y : \Set} (f : Set X -> Set Y) (ft : \Pi {y : Y} -> f top y) (fm : \Pi {U V : Set X} -> U ⊆ V -> f U ⊆ f V) 
    (fi : \Pi {U V : Set X} -> f U ∧ f V ⊆ f (U ∧ V)) {A : Set (Set X) -> \Prop} {C : Set (Set X)} {D : Set (Set Y)} (eCD : ∀ {U : C} ∃ (V : D) (f U ⊆ V)) 
    (CC : Closure A C) : Closure (\lam D => ∃ (C : A) ∀ {U : C} ∃ (V : D) (f U ⊆ V)) D => {?hidden_proof}

    \lemma closure-embedding {S : PrecoverSpace X} {Y : PrecoverSpace} (AS : \Pi {C : Set (Set X)} -> isCauchy C -> Closure A C) (f : PrecoverMap S Y) 
    (p : \Pi {C : Set (Set X)} -> A C -> isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U))) : f.IsEmbedding => {?hidden_proof}
      \where {
        \lemma aux {C : Set (Set X)} (CC : Closure A C) : isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U)) => {?hidden_proof}
      }

  }


\instance PrecoverLattice (X : \Set) : CompleteLattice (PrecoverSpace X) 
  | <= => \lam A B => \Pi {C : Set (Set X)} -> isCauchy {A} C -> isCauchy {B} C
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | top => DiscreteCover X
  | top-univ => {?hidden_proof}
  | Join => \lam {J} f => ClosurePrecoverSpace (\lam C => ∃ (j : J) (isCauchy {f j} C)) (\lam e x => (\case \elim e \with {  | inP (j, Cc) => cauchy-cover Cc x}))
  | Join-cond => {?hidden_proof}
  | Join-univ => {?hidden_proof}

\func CoverTransfer {X : \Set} {Y : CoverSpace} (f : X -> Y) : CoverSpace X \cowith
  | TopSpace => TopTransfer f
  | isCauchy => isCauchy {PrecoverTransfer f}
  | cauchy-cover => {?hidden_proof}
  | cauchy-top => {?hidden_proof}
  | cauchy-refine => {?hidden_proof}
  | cauchy-glue => {?hidden_proof}
  | isRegular => {?hidden_proof}
  | cauchy-open => {?hidden_proof}

\func CoverSub {X : CoverSpace} (S : Set X) : CoverSpace (Set.Total S) => CoverTransfer __.1

\func ClosureCoverSpace {X : \Set} (A : Set (Set X) -> \Prop) (CA : \Pi {C : Set (Set X)} -> A C -> \Pi (x : X) -> ∃ (U : C) (U x)) 
(AS : \Pi {C : Set (Set X)} -> A C -> Closure A (\lam V => ∃ (U : C) (Closure A (\lam W => Given (V ∧ W) -> W ⊆ U)))) : CoverSpace X \cowith
  | PrecoverSpace => ClosurePrecoverSpace A CA
  | isRegular => {?hidden_proof}
  \where {
    \lemma closure-regular {X : PrecoverSpace} (RB : RatherBelow {SetLattice X}) {A : Set (Set X) -> \Prop} 
    (AS : \Pi {C : Set (Set X)} -> A C -> Closure A (\lam V => ∃ (U : C) (RB.R V U))) {C : Set (Set X)} (CC : Closure A C) :
      Closure A (\lam V => ∃ (U : C) (RB.R V U)) => {?hidden_proof}

    \lemma closure-pred {X : PrecoverSpace} (P : Set X -> \Prop) (Pt : P top) (Pm : ∀ {U V : P} (P (U ∧ V))) {A : Set (Set X) -> \Prop} (AP : ∀ {C : A} {U : C} (P U)) 
    {C : Set (Set X)} (CC : Closure A C) : ∃ (D : Closure A) (∀ {V : D} (P V)) (∀ {V : D} ∃ (U : C) (V ⊆ U)) => {?hidden_proof}
  }


\func ClosureRegularCoverSpace {X : \Set} (A : Set (Set X) -> \Prop) (CA : \Pi {C : Set (Set X)} -> A C -> \Pi (x : X) -> ∃ (U : C) (U x)) 
(AI : \Pi {C : Set (Set X)} -> A C -> ∃ (D : A) ∀ {V : D} ∃ (U : C) ∀ {V' : D} (Given (V ∧ V') -> V' ⊆ U)) : CompletelyRegularCoverSpace X \cowith
  | PrecoverSpace => ClosurePrecoverSpace A CA
  | isCompletelyRegular => {?hidden_proof}

\instance CoverLattice (X : \Set) : CompleteLattice (CoverSpace X) 
  | <= => \lam A B => \Pi {C : Set (Set X)} -> isCauchy {A} C -> isCauchy {B} C
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | top => DiscreteCover X
  | top-univ => {?hidden_proof}
  | Join => \lam f => \new CoverSpace {
    | PrecoverSpace => Join {PrecoverLattice X} f
    | isRegular => ClosureCoverSpace.closure-regular {Join f} RegularRatherBelow $ later
      (\case __ \with {
      | inP (j, Cc) => closure $ inP (j, cauchy-subset (isRegular {f j} Cc) $ later (\lam {U} inP (V, CV, U<=<V) => inP (V, CV, Join-cond {PrecoverLattice X} j {f} U<=<V)))
      })
  }
  | Join-cond => {?hidden_proof}
  | Join-univ => {?hidden_proof}
  | join => \lam A B => \new CoverSpace {
    | PrecoverSpace => A ∨ {PrecoverLattice X} B
    | isRegular => ClosureCoverSpace.closure-regular {A ∨ B} RegularRatherBelow $ later
      (\case __ \with {
      | inP (true, Cc) => closure $ inP (true, cauchy-subset (isRegular Cc) $ later (\lam {U} inP (V, CV, U<=<V) => inP (V, CV, join-left {PrecoverLattice X} {A} {B} U<=<V)))
        | inP (false, Cc) => closure $ inP (false, cauchy-subset (isRegular Cc) $ later (\lam {U} inP (V, CV, U<=<V) => inP (V, CV, join-right {PrecoverLattice X} {A} {B} U<=<V)))
      })
  }
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}

\func RegPrecoverSpace (X : PrecoverSpace) : CoverSpace X => CompleteLattice.SJoin {CoverLattice X} (\lam A => A <= {PrecoverLattice X} X)

\func regPrecoverSpace {X : PrecoverSpace} : PrecoverMap X (RegPrecoverSpace X) \cowith
  | func => \lam x => x
  | func-cover => {?hidden_proof}

\lemma regPrecoverSpace-extend {X : PrecoverSpace} {Y : CoverSpace} (f : PrecoverMap X Y) : PrecoverMap (RegPrecoverSpace X) Y f => {?hidden_proof}