\import Algebra.Group
\import Algebra.Module
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Semiring
\import Logic
\import Operations
\import Order.Lattice
\import Paths
\import Paths.Meta
\import Set.Subset
\import Topology.TopAbGroup
\import Topology.TopAbGroup.Complete
\import Topology.TopAbGroup.Product
\import Topology.TopRing
\import Topology.TopSpace
\import Topology.TopSpace.Product

\class TopLModule \extends LModule, TopAbGroup {
  \override R : TopRing
  | *c-cont : ContMap (ProductTopSpace R \this) \this (\lam s => s.1 *c s.2)
  | negative-cont => transport (ContMap \this \this) {-1 *c __} (ext (\lam a => neg_ide_*c)) (*c-cont ContMap.∘ ProductTopSpace.tuple (ContMap.const -1) ContMap.id)
}

\class HausdorffTopLModule \extends TopLModule, HausdorffTopAbGroup

\class CompleteTopLModule \extends HausdorffTopLModule, CompleteTopAbGroup

\func RingTopLModule (R : TopRing) : TopLModule R R \cowith
  | TopAbGroup => R
  | *c => *
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  | *c-cont => {?hidden_proof}

\instance ProductTopLModule {R : TopRing} (X Y : TopLModule R) : TopLModule R (\Sigma X Y) 
  | TopAbGroup => ProductTopAbGroup X Y
  | *c => \lam r (x, y) => (r *c x, r *c y)
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  | *c-cont => {?hidden_proof}

\instance TopLModuleHasProduct (R : TopRing) : HasProduct (TopLModule R) 
  | Product => ProductTopLModule {R}