\import Data.Bool
\import Function.Meta($)
\import Logic
\import Logic.Meta
\import Meta
\import Order.Directed
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.SetHom
\import Set.Filter
\import Set.Subset

\class TopSpace \extends BaseSet {
  | isOpen : Set E -> \Prop
  | open-top : isOpen top
  | open-inter {U V : Set E} : isOpen U -> isOpen V -> isOpen (U ∧ V)
  | open-Union {S : Set (Set E)} : ∀ {U : S} (isOpen U) -> isOpen (Set.Union S)
}

\func DiscreteTopSpace (X : \Set) : TopSpace X \cowith
  | isOpen => \lam _ => \Sigma
  | open-top => {?hidden_proof}
  | open-inter => {?hidden_proof}
  | open-Union => {?hidden_proof}

\func NFilter {X : TopSpace} (x : X) : ProperFilter X \cowith
  | F => \lam U => ∃ (V : isOpen) (V x) (V ⊆ U)
  | filter-mono => {?hidden_proof}
  | filter-top => {?hidden_proof}
  | filter-meet => {?hidden_proof}
  | isProper => {?hidden_proof}

\func IsWeaklyDenseSet {X : TopSpace} (S : Set X) : \Prop => \Pi {U : Set X} -> isOpen U -> Not (Given (y : S) (U y)) -> Not (Given U)

\func IsDenseSet {X : TopSpace} (S : Set X) : \Prop => \Pi {x : X} {U : Set X} -> isOpen U -> U x -> ∃ (y : S) (U y)

\lemma denseSet->weaklyDense {X : TopSpace} {S : Set X} (d : IsDenseSet S) : IsWeaklyDenseSet S => {?hidden_proof}

\class ContMap \extends SetHom {
  \override Dom : TopSpace
  \override Cod : TopSpace
  | func-cont {U : Cod -> \Prop} : isOpen U -> isOpen (\lam x => U (func x))
}
  \where {
    \func id {X : TopSpace} : ContMap X X \cowith
      | func => \lam x => x
      | func-cont => {?hidden_proof}

    \func compose \alias \infixl 8 ∘ {X Y Z : TopSpace} (g : ContMap Y Z) (f : ContMap X Y) : ContMap X Z \cowith
      | func => \lam x => g (f x)
      | func-cont => {?hidden_proof}

    \func const {Y X : TopSpace} (x : X) : ContMap Y X \cowith
      | func => \lam _ => x
      | func-cont => {?hidden_proof}
  }


\lemma limit-transport {X : TopSpace} {I : DirectedSet} {f g : I -> X} {l : X} (fl : X.IsLimit f l) (p : \Pi (n : I) -> g n = f n) : X.IsLimit g l => {?hidden_proof}

\lemma const-limit {I : DirectedSet} {X : TopSpace} {x : X} : X.IsLimit (\lam (_ : I) => x) x => {?hidden_proof}

\lemma cont-limit {I : DirectedSet} {X Y : TopSpace} {f : I -> X} {l : X} (p : X.IsLimit f l) (g : ContMap X Y) : Y.IsLimit (\lam n => g (f n)) (g l) => {?hidden_proof}

\func IsCont {X Y : TopSpace} (f : X -> Y) : \Prop => ContMap X Y f

\func IsContAt {X Y : TopSpace} (f : X -> Y) (x : X) : \Prop => ∀ {V : Y.isOpen} (V (f x)) ∃ (U : X.isOpen) (U x) (U ⊆ f ^-1 V)

\lemma cont-char {X Y : TopSpace} {f : X -> Y} : IsCont f <-> (\Pi (x : X) -> IsContAt f x) => {?hidden_proof}

\lemma contAt-comp {X Y Z : TopSpace} (f : X -> Y) (g : Y -> Z) {x : X} (fc : IsContAt f x) (gc : IsContAt g (f x)) : IsContAt (\lam x => g (f x)) x => {?hidden_proof}

\lemma contAt-left {X Y Z : TopSpace} {f : X -> Y} (g : ContMap Y Z) {x : X} (fc : IsContAt f x) : IsContAt (\lam x => g (f x)) x => {?hidden_proof}

\lemma contAt-right {X Y Z : TopSpace} (f : ContMap X Y) (g : Y -> Z) {x : X} (gc : IsContAt g (f x)) : IsContAt (\lam x => g (f x)) x => {?hidden_proof}

\lemma contAt-limit {I : DirectedSet} {X Y : TopSpace} {f : I -> X} {l : X} (p : X.IsLimit f l) {g : X -> Y} (gc : IsContAt g l) : Y.IsLimit (\lam n => g (f n)) (g l) => {?hidden_proof}

\lemma cont-limit-point {X Y : TopSpace} (f : ContMap X Y) {S : Set Y} {x : X} (xl : X.IsLimitPoint x (f ^-1 S)) : Y.IsLimitPoint (f x) S => {?hidden_proof}

\lemma cont-closed {X Y : TopSpace} (f : ContMap X Y) {S : Set Y} (Sc : Y.IsClosed S) : X.IsClosed (f ^-1 S) => {?hidden_proof}

\class HausdorffTopSpace \extends TopSpace {
  | isHausdorff {x y : E} : ∀ {U V : isOpen} (U x) (V y) ∃ (U ∧ V) -> x = y
}

\class StronglyHausdorffTopSpace \extends HausdorffTopSpace, SeparatedSet {
  | isStronglyHausdorff {x y : E} : ∀ {U V : isOpen} (U x) (V y) (Not (Not (Given (U ∧ V)))) -> x = y
  | isHausdorff => \lam p => isStronglyHausdorff (\lam Uo Vo Ux Vy q => (\case p Uo Vo Ux Vy \with {  | inP r => q r}))
  | separatedEq => \lam {x} p => isStronglyHausdorff (\lam Uo Vo Ux Vy q => p (\lam x=y => q (x, (Ux, rewrite x=y Vy))))
}

\lemma denseSet-lift-unique {X : TopSpace} {Y : HausdorffTopSpace} {S : Set X} (Sd : IsDenseSet S) (f g : ContMap X Y) (p : \Pi {x : X} -> S x -> f x = g x) {x : X} : f x = g x => {?hidden_proof}

\lemma dense-lift-unique {X Y : TopSpace} {Z : HausdorffTopSpace} (f : ContMap X Y) (fd : f.IsDense) (g h : ContMap Y Z) (p : \Pi (x : X) -> g (f x) = h (f x)) (y : Y) : g y = h y 
  => {?hidden_proof}

\lemma weaklyDenseSet-lift-unique {X : TopSpace} {Y : StronglyHausdorffTopSpace} {S : Set X} (Sd : IsWeaklyDenseSet S) (f g : ContMap X Y) (f=g : \Pi {x : X} -> S x -> f x = g x) 
{x : X} : f x = g x => {?hidden_proof}

\lemma weaklyDense-lift-unique {X Y : TopSpace} {Z : StronglyHausdorffTopSpace} (f : ContMap X Y) (fd : f.IsWeaklyDense) (g h : ContMap Y Z) (p : \Pi (x : X) -> g (f x) = h (f x)) 
(y : Y) : g y = h y => {?hidden_proof}

\func TopTransfer {X : \Set} {Y : TopSpace} (f : X -> Y) : TopSpace X \cowith
  | isOpen => \lam U => ∃ (V : isOpen) (U = f ^-1 V)
  | open-top => {?hidden_proof}
  | open-inter => {?hidden_proof}
  | open-Union => {?hidden_proof}

\lemma TopTransfer-map {X : \Set} {Y : TopSpace} (f : X -> Y) : ContMap (TopTransfer f) Y f => {?hidden_proof}

\lemma TopTransfer-lift {X Y : TopSpace} {U : Set Y} (f : ContMap X Y) (p : \Pi (x : X) -> U (f x)) : ContMap X (TopTransfer {Set.Total U} __.1) (\lam x => (f x, p x)) => {?hidden_proof}

\func TopSub {X : TopSpace} (S : Set X) : TopSpace (Set.Total S) => TopTransfer __.1

\lemma TopSub-func {X Y : TopSpace} (f : ContMap X Y) {U : Set X} {V : Set Y} (p : ∀ {x : U} (V (f x))) : ContMap (TopSub U) (TopSub V) (\lam s => (f s.1, p s.2)) => {?hidden_proof}

\lemma TopSub-inc {X : TopSpace} {U V : Set X} (p : U ⊆ V) : ContMap (TopSub U) (TopSub V) (\lam s => (s.1, p s.2)) => {?hidden_proof}

\lemma TopSub-limit {X : TopSpace} {S : Set X} {I : DirectedSet} {f : I -> Set.Total S} {x : Set.Total S} (l : X.IsLimit (\lam n => (f n).1) x.1) : TopSpace.IsLimit {TopSub S} f x 
  => {?hidden_proof}

\func IsRelativelyHausdorff {X Y : TopSpace} (f : X -> Y) : \Prop => \Pi {x x' : X} -> ∀ {U V : X.isOpen} (U x) (V x') ∃ (U ∧ V) -> f x = f x' -> x = x'

\lemma denseSet-relative-lift-unique {X Y Z : TopSpace} (p : Y -> Z) (ph : IsRelativelyHausdorff p) {S : Set X} (Sd : IsDenseSet S) (f g : ContMap X Y) 
(dp : \Pi {x : X} -> S x -> f x = g x) (dq : \Pi {x : X} -> p (f x) = p (g x)) {x : X} : f x = g x => {?hidden_proof}

\lemma dense-relative-lift-unique {X Y Z W : TopSpace} (p : Z -> W) (ph : IsRelativelyHausdorff p) (f : ContMap X Y) (fd : f.IsDense) (g h : ContMap Y Z) 
(dp : \Pi (x : X) -> g (f x) = h (f x)) (dq : \Pi {y : Y} -> p (g y) = p (h y)) (y : Y) : g y = h y => {?hidden_proof}