\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.RatherBelow
\open Set
\open ClosurePrecoverSpace

\class PreuniformSpace \extends PrecoverSpace {
  | isUniform : Set (Set E) -> \Prop
  | uniform-cover {C : Set (Set E)} : isUniform C -> \Pi (x : E) -> ∃ (U : C) (U x)
  | uniform-top : isUniform (single top)
  | uniform-refine {C D : Set (Set E)} : isUniform C -> Refines C D -> isUniform D
  | uniform-inter {C D : Set (Set E)} : isUniform C -> isUniform D -> isUniform (CoverInter C D)
  | uniform-cauchy {C : Set (Set E)} : isCauchy C <-> Closure isUniform C
  | cauchy-cover => \lam Cc x => closure-filter (pointFilter x) (\lam Cu => uniform-cover Cu x) $ uniform-cauchy.1 Cc
  | cauchy-top => uniform-cauchy.2 $ closure-top idp
  | cauchy-refine => \lam Cc e => uniform-cauchy.2 $ closure-refine (uniform-cauchy.1 Cc) e
  | cauchy-glue => \lam Cc e => uniform-cauchy.2 $ closure-trans (uniform-cauchy.1 Cc) (\lam CU => uniform-cauchy.1 $ e CU) idp
  | isCauchy => isCauchy
  | uniform-cauchy => uniform-cauchy-impl

  \protected \default isCauchy : Set (Set E) -> \Prop => Closure isUniform

  \protected \default uniform-cauchy-impl {C} : isCauchy C <-> Closure isUniform C => <->refl

  \lemma makeCauchy {C : Set (Set E)} (Cu : isUniform C) : CoverSpace.isCauchy C => {?hidden_proof}

  \func IsProperUniform : \Prop => ∀ {C : isUniform} (isUniform (\lam U => \Sigma (C U) (∃ U)))

  \func IsWeaklyProperUniform : \Prop => \Pi {C : Set (Set E)} -> isUniform (\lam U => (U = {Set E} bottom) || C U) -> isUniform C

  \lemma proper_weaklyProper (p : IsProperUniform) : IsWeaklyProperUniform => {?hidden_proof}

  \lemma inhabited_weaklyProper (p : TruncP E) : IsWeaklyProperUniform => {?hidden_proof}

  \lemma uniform-inter-big (Cs : Array (Set (Set E))) (Cu : ∀ (C : Cs) (isUniform C)) : isUniform (CoverInterBig Cs) => {?hidden_proof}

  \lemma uniform-separated {x y : E} : ∀ {C : CoverSpace.isCauchy} ∃ (U : C) (\Sigma (U x) (U y)) <-> ∀ {C : isUniform} ∃ (U : C) (\Sigma (U x) (U y)) => {?hidden_proof}
}
  \where {
    \func star {X : \Set} (V : Set X) (C : Set (Set X)) : Set X => Union (\lam W => \Sigma (C W) (Given (V ∧ W)))

    \lemma star-monotone {X : \Set} {V U : Set X} (p : V ⊆ U) {C D : Set (Set X)} (r : Refines C D) : star V C ⊆ star U D => {?hidden_proof}
  }


\func \infix 4 <=* {X : PreuniformSpace} (V U : Set X) : \Prop => ∃ (C : isUniform) (PreuniformSpace.star V C ⊆ U)

\lemma <=*-char {X : PreuniformSpace} {V U : Set X} : V <=* U <-> isUniform (\lam W => Given (V ∧ W) -> W ⊆ U) => {?hidden_proof}

\class RegularPreuniformSpace \extends PreuniformSpace, CoverSpace {
  | uniform-regular {C : Set (Set E)} : isUniform C -> isCauchy (\lam V => ∃ (U : C) (V <=* U))
  | isRegular => \lam Cc => uniform-cauchy.2 $ ClosureCoverSpace.closure-regular RegularRatherBelow 
    (\lam Cu => uniform-cauchy.1 $ cauchy-subset (uniform-regular Cu) (\lam {V} inP (U, CU, V<=*U) => inP $ later (U, CU, <=*_<=< V<=*U))) 
    (uniform-cauchy.1 Cc)

  \lemma <=*-cauchy-regular {C : Set (Set E)} (Cc : isCauchy C) : isCauchy (\lam V => ∃ (U : C) (V <=* U)) => {?hidden_proof}
}
  \where {
    \func fromCoverSpace (X : CoverSpace) : RegularPreuniformSpace X \cowith
      | isUniform => isCauchy
      | uniform-cover => {?hidden_proof}
      | uniform-top => {?hidden_proof}
      | uniform-refine => {?hidden_proof}
      | uniform-inter => {?hidden_proof}
      | isCauchy => isCauchy
      | uniform-cauchy => {?hidden_proof}
      | uniform-regular => {?hidden_proof}
  }


\class UniformSpace \extends RegularPreuniformSpace, CompletelyRegularCoverSpace {
  | uniform-star {C : Set (Set E)} : isUniform C -> ∃ (D : isUniform) ∀ {V : D} ∃ (U : C) ∀ {W : D} (Given (V ∧ W) -> W ⊆ U)
  | uniform-regular => \lam Cu => (\case uniform-star Cu \with {
    | inP (D, Du, h) => uniform-cauchy.2 $ closure $ uniform-subset Du (\lam {V} DV => (\case h DV \with {
      | inP (U, CU, g) => inP $ later (U, CU, inP (D, Du, \lam {y} inP (W, (DW, s), Wy) => g DW s Wy))}))
  })
  | isCompletelyRegular => \lam Cc => cauchy-subset (uniform-cauchy.2 $ isCompletelyRegular {ClosureRegularCoverSpace isUniform uniform-cover uniform-star} (uniform-cauchy.1 Cc))
    (\lam {V} inP (U, CU, V<=<U) => inP $ later (U, CU, unfolds $ unfolds at V<=<U $ TruncP.map V<=<U (\lam (R', c, d, e) => (R', \lam r => uniform-cauchy.2 $ c r, d, e))))

  \lemma <=*-inter {V U : Set E} (p : V <=* U) : ∃ (V' : Set E) (V <=* V') (V' <=* U) => {?hidden_proof}

  \lemma <=*-regular {C : Set (Set E)} (Cu : isUniform C) : isUniform (\lam V => ∃ (U : C) (V <=* U)) => {?hidden_proof}

  \lemma <=<-regular {C : Set (Set E)} (Cu : isUniform C) : isUniform (\lam V => ∃ (U : C) (V <=< U)) => {?hidden_proof}
}

\lemma <=*_<=< {X : PreuniformSpace} {V U : Set X} (p : V <=* U) : V <=< U => {?hidden_proof}

\instance StarRatherBelow {X : PreuniformSpace} : RatherBelow (<=* {X}) 
  | <=<-left => {?hidden_proof}
  | <=<-right => {?hidden_proof}
  | <=<_top => {?hidden_proof}
  | <=<_meet => {?hidden_proof}

\lemma uniform-subset {X : PreuniformSpace} {C D : Set (Set X)} (Cc : isUniform C) (e : \Pi {U : Set X} -> C U -> D U) : isUniform D => {?hidden_proof}

\lemma top-uniform {X : PreuniformSpace} {C : Set (Set X)} (Ct : C top) : isUniform C => {?hidden_proof}

\lemma uniform-embedding-char {X : PreuniformSpace} {Y : PrecoverSpace} {f : PrecoverMap X Y} : f.IsEmbedding <-> ∀ {C : isUniform} (isCauchy (\lam V => ∃ (U : C) (f ^-1 V ⊆ U))) => {?hidden_proof}

\record LocallyUniformMap \extends CoverMap {
  \override Dom : RegularPreuniformSpace
  \override Cod : RegularPreuniformSpace
  | func-locally-uniform {E : Set (Set Cod)} : isUniform E -> ∃ (C : isUniform) ∀ {U : C} (isUniform (\lam V => ∃ (W : E) (U ∧ V ⊆ func ^-1 W)))
  | func-cover => \lam {E'} E'c => closure-univ-cover (\lam {E} Eu =>
    uniform-cauchy.2 (\case func-locally-uniform Eu \with {  | inP (C, Cu, e) => closure-refine (closure-trans (closure Cu) (\lam CU => closure (e CU)) idp) 
        (\lam {Z} inP (U, V, CU, inP (W, EW, q), p) => inP $ later (_, inP (W, EW, idp), rewrite p q))})) (uniform-cauchy.1 E'c)
}

\record UniformMap \extends LocallyUniformMap {
  | func-uniform {E : Set (Set Cod)} : isUniform E -> isUniform (\lam U => ∃ (V : E) (U = func ^-1 V))
  | func-locally-uniform => \lam Eu => inP (_, func-uniform Eu, \lam inP (V, EV, p) => uniform-subset (func-uniform Eu) (\lam _ => inP $ later (V, EV, rewrite p meet-left)))

  \func IsUniformEmbedding : \Prop => \Pi {C : Set (Set Dom)} -> isUniform C -> isUniform (\lam V => ∃ (U : C) (func ^-1 V ⊆ U))

  \lemma embedding->coverEmbedding (e : IsUniformEmbedding) : CoverMap.IsEmbedding => {?hidden_proof}

  \func IsDenseUniformEmbedding : \Prop => \Sigma IsDense IsUniformEmbedding

  \func IsWeaklyDenseUniformEmbedding : \Prop => \Sigma IsWeaklyDense IsUniformEmbedding
}
  \where {
    \func id {X : RegularPreuniformSpace} : UniformMap X X \cowith
      | func => \lam x => x
      | func-uniform => {?hidden_proof}

    \func compose \alias \infixl 8 ∘ {X Y Z : RegularPreuniformSpace} (g : UniformMap Y Z) (f : UniformMap X Y) : UniformMap X Z \cowith
      | func => \lam x => g (f x)
      | func-uniform => {?hidden_proof}

    \func const {X Y : RegularPreuniformSpace} (y : Y) : UniformMap X Y \cowith
      | func => \lam _ => y
      | func-uniform => {?hidden_proof}

    \lemma lift {X Y Z : RegularPreuniformSpace} {f : X -> Y} (g : UniformMap Y Z) (ge : g.IsUniformEmbedding) (fg : UniformMap X Z (\lam x => g (f x))) : UniformMap X Y f 
      => {?hidden_proof}
  }


\func RegularPreuniformTransfer {X : \Set} {Y : RegularPreuniformSpace} (f : X -> Y) : RegularPreuniformSpace X \cowith
  | CoverSpace => CoverTransfer f
  | isUniform => \lam C => isUniform (\lam V => ∃ (U : C) (f ^-1 V ⊆ U))
  | uniform-cover => {?hidden_proof}
  | uniform-top => {?hidden_proof}
  | uniform-refine => {?hidden_proof}
  | uniform-inter => {?hidden_proof}
  | uniform-cauchy => {?hidden_proof}
  | uniform-regular => {?hidden_proof}

\func UniformTransfer {X : \Set} {Y : UniformSpace} (f : X -> Y) : UniformSpace X \cowith
  | RegularPreuniformSpace => RegularPreuniformTransfer f
  | uniform-star => {?hidden_proof}

\type \infix 4 s<=* {X : PreuniformSpace} (V U : Set X) : \Prop => isUniform (\lam W => (W = Compl V) || (W = U))

\lemma s<=*_s<=< {X : PreuniformSpace} {V U : Set X} (p : V s<=* U) : V s<=< U => {?hidden_proof}

\lemma s<=*_<=* {X : PreuniformSpace} {V U : Set X} (p : V s<=* U) : V <=* U => {?hidden_proof}

\instance StronglyStarRatherBelow {X : PreuniformSpace} : RatherBelow (s<=* {X}) 
  | <=<_top => {?hidden_proof}
  | <=<-left => {?hidden_proof}
  | <=<-right => {?hidden_proof}
  | <=<_meet => {?hidden_proof}

\class StronglyRegularPreuniformSpace \extends RegularPreuniformSpace, StronglyRegularCoverSpace {
  | uniform-strongly-regular {C : Set (Set E)} : isUniform C -> isCauchy (\lam V => ∃ (U : C) (V s<=* U))
  | uniform-regular => \lam Cu => cauchy-subset (uniform-strongly-regular Cu) (\lam {V} inP (U, CU, p) => inP $ later (U, CU, s<=*_<=* p))
  | isStronglyRegular => \lam Cc => uniform-cauchy.2 $ ClosureCoverSpace.closure-regular StronglyRatherBelow
    (\lam Cu => uniform-cauchy.1 $ cauchy-subset (uniform-strongly-regular Cu) (\lam {V} inP (U, CU, p) => inP $ later (U, CU, uniform-cauchy.2 $ closure p))) 
  (uniform-cauchy.1 Cc)

  \lemma s<=*-cauchy-regular {C : Set (Set E)} (Cc : CoverSpace.isCauchy C) : CoverSpace.isCauchy (\lam V => ∃ (U : C) (V s<=* U)) => {?hidden_proof}
}
  \where {
    \func fromCoverSpace (X : StronglyRegularCoverSpace) : StronglyRegularPreuniformSpace X \cowith
      | isUniform => isCauchy
      | uniform-cover => {?hidden_proof}
      | uniform-top => {?hidden_proof}
      | uniform-refine => {?hidden_proof}
      | uniform-inter => {?hidden_proof}
      | isCauchy => isCauchy
      | uniform-cauchy => {?hidden_proof}
      | uniform-strongly-regular => {?hidden_proof}
  }


\class StronglyRegularUniformSpace \extends UniformSpace, StronglyRegularPreuniformSpace {
  | uniform-strongly-star {C : Set (Set E)} : isUniform C -> ∃ (D : isUniform) ∀ {V : D} ∃ (U : C) ∀ {W : D} (Not (Given (V ∧ W)) || W ⊆ U)
  | uniform-star => \lam Cu => (\case uniform-strongly-star Cu \with {
    | inP (D, Du, h) => inP (D, Du,  \lam DV => (\case h DV \with {
      | inP (U, CU, g) => inP (U, CU, \lam DW s {y} Wy => (\case g DW \with {  | byLeft e => absurd (e s)  | byRight e => e Wy}))}))
  })
  | uniform-strongly-regular => \lam Cu => (\case uniform-strongly-star Cu \with {
    | inP (D, Du, h) => uniform-cauchy.2 $ closure $ uniform-subset Du
      (\lam {V} DV => (\case h DV \with {  | inP (U, CU, g) => inP $ later    (U, CU,  uniform-refine Du
        (\lam {W} DW => later (\case g DW \with {  | byLeft p => inP (_, byLeft idp, \lam {x} Wx Vx => p (x, (Vx, Wx)))  | byRight p => inP (U, byRight idp, p)}))
          )}))
  })

  \lemma s<=*-regular {C : Set (Set E)} (Cu : isUniform C) : isUniform (\lam V => ∃ (U : C) (V s<=* U)) => {?hidden_proof}

  \lemma s<=<-regular {C : Set (Set E)} (Cu : isUniform C) : isUniform (\lam V => ∃ (U : C) (V s<=< U)) => {?hidden_proof}
}

\func StronglyRegularUniformTransfer {X : \Set} {Y : StronglyRegularUniformSpace} (f : X -> Y) : StronglyRegularUniformSpace X \cowith
  | PreuniformSpace => UniformTransfer f
  | uniform-strongly-star => {?hidden_proof}