\import Category
\import Category.Meta
\import Logic
\import Paths
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete

\instance PrecoverSpaceCat.{u} : Cat PrecoverSpace.{u}
  | Hom => PrecoverMap
  | id => PrecoverMap.id
  | o => PrecoverMap.∘
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  | univalence => sip \lam c d => PrecoverSpace.PrecoverSpace-ext \lam {C} =>
      (\lam Cc => cauchy-subset (func-cover {d} Cc) \lam (inP (V,CV,p)) => transportInv C p CV,
       \lam Cc => cauchy-subset (func-cover {c} Cc) \lam (inP (V,CV,p)) => transportInv C p CV)

\instance CoverSpaceCat.{u} : Cat CoverSpace.{u}
  | Hom => CoverMap
  | id => CoverMap.id
  | o => CoverMap.∘
  | id-left => idp
  | id-right => idp
  | o-assoc => idp
  | univalence => sip \lam c d => CoverSpace.CoverSpace-ext \lam {C} =>
      (\lam Cc => cauchy-subset (func-cover {d} Cc) \lam (inP (V,CV,p)) => transportInv C p CV,
       \lam Cc => cauchy-subset (func-cover {c} Cc) \lam (inP (V,CV,p)) => transportInv C p CV)
