\import Category
\import Category.Functor
\import Category.Limit
\import Category.Slice
\import Category.Subcat
\import Equiv(QEquiv)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta

\class Presieve {
  | C : Precat
  | x : C
  | S : \Pi {y : C} -> Hom y x -> \Prop
}
  \where {
    \lemma idLimit {C D : Precat} {F : Functor C.op D} {x : C} (S : Presieve x) (xS : S (id x)) : Limit {
      | Cone => Cone.map F S.cone
    } => {?hidden_proof}

    \open Limit

    \lemma transLimit {C : SmallPrecat} {D : Precat} {F : Functor C.op D} {a : C} (S1 S2 : Presieve a) (L1 : \Pi {b : C} (h : Hom b a) -> Limit {
      | Cone => Cone.map F (Presieve.cone {S1.pullback h})})
      (L2 : \Pi {b : C} {h : Hom b a} -> S1 h -> Limit {  | Cone => Cone.map F (Presieve.cone {S2.pullback h})}) : Limit {
      | Cone => Cone.map F S2.cone
    } => {?hidden_proof}
  }


\class Sieve \extends Presieve {
  | isSieve : \Pi {z y : C} (g : Hom z y) {f : Hom y x} -> S f -> S (f ∘ g)
}
  \where {
    \func map {C D : Precat} (F : Functor C D) (s : Sieve {C}) : Sieve {D} \cowith
      | x => F s.x
      | S => \lam {y} h => ∃ (z : C) (f : Hom y (F z)) (g : Hom z s.x) (h = F.Func g ∘ f) (s g)
      | isSieve => {?hidden_proof}
  }


\class Site \extends Precat \lp {
  | isCover (x : Ob) : Sieve x -> \Prop
  | cover-stable {x y : Ob} (h : Hom x y) {s : Sieve y} (c : isCover y s) : isCover x (s.pullback h)
}

\class SitePrehom \extends Functor \lp {
  \override C : Site
  \override D : Site
  | F-cover {x : C} {s : Sieve x} : isCover x s -> isCover (F x) (Sieve.map \this s)
}

\func inducedSite {C : SmallPrecat} {D : Site} (F : Functor C D) : Site \cowith
  | Precat => C
  | isCover => \lam x s => ∃ (s' : Sieve (F x)) (isCover (F x) s') ∀ {y} (h : Hom y x) (s h = s' (F.Func h))
  | cover-stable => {?hidden_proof}

\class SiteWithBasis \extends Site, PrecatWithPullbacks (\lp, \lp) {
  | isBasicCover (x : Ob) {J : \Set} (g : J -> SlicePrecat x) : \Prop
  | basicCover-stable {x y : Ob} (f : Hom x y) {J : \Set} {g : J -> SlicePrecat y} : isBasicCover y g -> isBasicCover x (\lam j => pullbackFunctor f (g j))
  | isCover => \lam x s => ∃ (J : \Set) (g : (J -> SlicePrecat x)) (isBasicCover x g) (\Pi (j : J) -> s (g j).2)
  | cover-stable => \lam h {s} inP (J, g, c, d) =>
    inP (J, \lam j => pullbackFunctor h (g j), basicCover-stable h c, \lam j => transportInv (s {_}) (Pullback.pbCoh {pullback h (g j).2}) (isSieve _ (d j)))
}

\class SiteWithBasisPrehom \extends Functor \lp {
  \override C : SiteWithBasis
  \override D : SiteWithBasis
  | F-basicCover {x : C} {J : \Set} {g : J -> SlicePrecat x} : isBasicCover x g -> isBasicCover (F x) (\lam j => (F (g j).1, Func (g j).2))
  | F-pullback {x y z : C} {f : Hom x z} {g : Hom y z} : Iso {D} {F (pullback f g)} {pullback (Func f) (Func g)} $ pbMap (Func pbProj1) (Func pbProj2) $ inv Func-o *> pmap Func pbCoh *> Func-o
}