\import Arith.Fin.Order
\import Arith.Nat
\import Data.Fin
\import Data.Or
\import Equiv
\import Function
\import Function.Meta ($)
\import Logic
\import Logic.Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.StrictOrder
\import Paths
\import Set
\import Set.Fin (FinSet)
\import Set.Fin.DFin

\class PigeonholeSet \extends BaseSet {
  | pigeonhole (f : Nat -> E) : ∃ (i j : Nat) (i /= j) (f i = f j)

  \lemma pigeonhole< (f : Nat -> E) : ∃ (i j : Nat) (i < j) (f i = f j) => {?hidden_proof}

  \lemma isEquiv (f : E -> E) (inj : IsInj f) : Equiv f => {?hidden_proof}
}

\class BoundedPigeonholeSet \extends PigeonholeSet {
  | finCard : Nat
  | boundedPigeonhole (f : Fin (suc finCard) -> E) : ∃ (i j : Fin (suc finCard)) (i /= j) (f i = f j)
  | pigeonhole => \lam f => TruncP.map (boundedPigeonhole (\lam j => f j)) (\lam t => (t.1, t.2, fin_nat_/= t.3, t.4))

  \lemma boundedPigeonhole< (f : Fin (suc finCard) -> E) : ∃ (i j : Fin (suc finCard)) (i < j) (f i = f j) => {?hidden_proof}
}

\lemma pigeonhole-surj (A : BoundedPigeonholeSet) {B : \Set} (f : A -> B) (s : IsSurj f) : BoundedPigeonholeSet B A.finCard => {?hidden_proof}

\lemma pigeonhole-fin {n m : Nat} (f : Fin m -> Fin n) (p : n < m) : ∃ (i j : Fin m) (i /= j) (f i = f j) => {?hidden_proof}
  \where {
    \lemma search-pair {n : Nat} {A : DecSet} (f : Fin n -> A) : Dec (∃ (i j : Fin n) (i /= j) (f i = f j)) => {?hidden_proof}

    \lemma aux {n : Nat} {A : DecSet} (f : Fin n -> A) (p : Not (IsInj f)) : ∃ (i j : Fin n) (i /= j) (f i = f j) => {?hidden_proof}
  }
