\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring.Boolean
\import Meta
\import Order.Lattice

\lemma boolRingTest {B : BooleanRing} (a b : B) : B.diff a b * b = 0
  => equation.bRing

\lemma boolRingTest2 {B : BooleanRing} (a b : B) : (a + b) * (a * b) = 0
  => equation.bRing

\lemma boolRingTest3 {B : BooleanRing} (a b : B) : (a - b) * (a ∨ b) = a + b
  => equation.bRing

\lemma boolRingArgTest {B : BooleanRing} (a b : B) (p : a + b = 0) : (a - b) * (a ∨ b) = 0
  => equation.bRing p

\lemma boolRingArgTest2 {B : BooleanRing} (a b c : B) (p : a + (b + c) = 0) : a + b + c = 0
  => equation.bRing p

\lemma boolRingArgTest3 {B : BooleanRing} (a b c : B) (p : a + (b + c) = 0) : a + b = c
  => equation.bRing p

\lemma boolRingForwardTest {B : BooleanRing} (a b : B) (p : (a - b) * (a ∨ b) = 0) : a + b = 0
  => equation.bRing in p

\lemma boolRingProofTest {B : BooleanRing} (a b c : B) (p : a = b + c) : a * b + b = b * c
  => equation.bRing {p}

\lemma boolRingProofTest2 {B : BooleanRing} (a b c : B) (p : a + b = c) : a * b + b = b * c
  => equation.bRing {p}

\lemma boolRingProofTest3 {B : BooleanRing} (a b c : B) (p : b + b * c = c) : b * c + (b + c) = 0
  => equation.bRing {p}

\lemma boolRingProofTest4 {B : BooleanRing} (a b c : B) (p : a = b + c) (q : b + b * c = c) : a * b = c
  => equation.bRing {p,q}

\lemma boolRingProofTest5 {B : BooleanRing} (a b c : B) (p : a = a * b) (q : a = 0) : a * b = 0
  => equation.bRing {1 p} q
