\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Semiring
\import Algebra.Ring
\import Meta

\lemma commRingTest {R : CRing} (a b c : R) : a * b - b * (a + c) + c * b * a = b * c * (a - 1)
  => equation.cRing

\lemma commRingTest2 {R : CRing} (a b : R) : (a + b) * (a - b) = a * a - b * b
  => equation.cRing

\lemma commRingArgTest {R : CRing} (a b : R) (p : 2 * (a * b) = 0) : (a + b) * (a + b) = a * a + b * b
  => equation.cRing p

\lemma commRingForwardTest {R : CRing} (a b : R) (p : (a + b) * (a + b) = a * a + b * b) : 2 * (a * b) = 0
  => equation.cRing in p

\lemma commRingProofTest1 {R : CRing} (a b : R) (p : a * b = 0) : (a + b) * (a + b) = a * a + b * b
  => equation.cRing {p}

\lemma commRingProofTest2 {R : CRing} (a b : R) (p : b = negative b) : (a + b) * (a + b) = a * a + b * b
  => equation.cRing {R.toZero p}

\lemma commRingProofTest3 {R : CRing} (a b c : R) (p : a = b) : a * c = c * b
  => equation.cRing {p}

\lemma commRingProofTest4 {R : CRing} (a b c : R) (p : a = b) (q : b * c = 0) : a * c = 0
  => equation.cRing {p,q}