\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Meta

\lemma testSimp {M : Group} (x y z w : M)
  : (x * (z * inverse y)) * ((ide * y) * (ide * inverse z)) * w = x * ((ide * (y * ide)) * inverse y) * w
  => equation.group

\lemma testArg {M : Group} (x y z : M) (p : x * x = ide)
  : (x * (z * inverse y)) * ((ide * y) * (ide * inverse z)) * x = x * ((ide * (y * ide)) * inverse y) * inverse x
  => equation.group p

\lemma testForward {M : Group} (x y z : M) (p : (x * (z * inverse y)) * ((ide * y) * (ide * inverse z)) * x = x * ((ide * (y * ide)) * inverse y) * inverse x)
  : x * x = ide
  => equation.group in p

\lemma testSimpAdd {M : AddGroup} (x y z w : M)
  : (x + (z + negative y)) + ((zro + y) + (zro + negative z)) + w = x + ((zro + (y + zro)) + negative y) + w
  => equation.addGroup

\lemma testArgAdd {M : AddGroup} (x y z : M) (p : x + x = zro)
  : (x + (z + negative y)) + ((zro + y) + (zro + negative z)) + x = x + ((zro + (y + zro)) + negative y) + negative x
  => equation.addGroup p

\lemma testForwardAdd {M : AddGroup} (x y z : M) (p : (x + (z + negative y)) + ((zro + y) + (zro + negative z)) + x = x + ((zro + (y + zro)) + negative y) + negative x)
  : x + x = zro
  => equation.addGroup in p
