\import Arith.Nat
\import Equiv
\import Equiv.Path
\import Equiv.Sigma
\import Homotopy.Fibration
\import Logic
\import Logic.Unique
\import Order.PartialOrder
\import Paths
\import Paths.Meta

\func \infix 2 ofHLevel_-1+ (A : \Cat) (n : Nat) : \Prop \elim n
  | 0 => ToProp (isProp A) (isProp.levelProp A)
  | suc n => \Pi (a a' : A) -> (a = a') ofHLevel_-1+ n
  \where
    \lemma levelProp (A : \Cat) (n : Nat) (e e' : A ofHLevel_-1+ n) : e = e'
      => prop-pi

\func hLevel-inh {A : \Cat} (n : Nat) (f : A -> A ofHLevel_-1+ n) : A ofHLevel_-1+ n \elim n
  | 0 => toProp \lam a => ToProp.fromProp (f a) a
  | suc n => \lam a => f a a

\func I-isContr : Contr I \cowith
  | center => left
  | contraction i => path (I.squeeze i)

\func \infix 2 ofHLevel_-2+ (A : \Cat) (n : Nat) : \Prop \elim n
  | 0 => Contr A
  | suc n => \Pi (a a' : A) -> (a = a') ofHLevel_-2+ n

-- | A map is `(k-2)`-truncated if its fibers are `(k-2)`-types.
\type IsTruncMap {X Y : \Cat} (n : Nat) (f : X -> Y) : \Prop
  => \Pi (y : Y) -> Fib f y ofHLevel_-2+ n
  \where {
    -- | Truncatedness is invariant under postcomposition with an equivalence.
    \lemma truncMap-post {X Y Z : \Cat} {g : X -> Y} (e : QEquiv {Y} {Z}) {k : Nat}
      : IsTruncMap k (\lam x => e (g x)) <-> IsTruncMap k g
      => \have fib-post y => sigma-right \lam x => IsEquiv.toQEquiv (pmapIsEquiv (inP e) {g x} {y})
         \in (\lam t y => HLevel_-2-retracts (fib-post y) (t (e y)),
              \lam t z => transport (\lam z => Fib (\lam x => e (g x)) z ofHLevel_-2+ k) (e.f_sec z) (HLevel_-2-retracts (symQEquiv (fib-post (e.ret z))) (t (e.ret z))))

    -- | Truncatedness is invariant under precomposition with an equivalence.
    \lemma truncMap-pre {X' X Y : \Cat} (e : QEquiv {X'} {X}) {g : X -> Y} {k : Nat}
      : IsTruncMap k (\lam x' => g (e x')) <-> IsTruncMap k g
      => (\lam t y => HLevel_-2-retracts (symQEquiv (qsigma-left {X'} {X} {\lam x => g x = y} e)) (t y),
          \lam t y => HLevel_-2-retracts (qsigma-left {X'} {X} {\lam x => g x = y} e) (t y))

    \lemma truncMap-proj {A : \Cat} {B : A -> \Cat} {k : Nat}
      : IsTruncMap {\Sigma (x : A) (B x)} {A} k __.1 <-> (\Pi (a : A) -> B a ofHLevel_-2+ k)
      => (\lam t a => HLevel_-2-retracts (symQEquiv (proj-fib B a)) (t a), \lam h a => HLevel_-2-retracts (proj-fib B a) (h a))

    -- | Paths in fibers of {r} are fibers of `pmap r`.
    \lemma fib-path-level {X Y : \Cat} {r : X -> Y} {k : Nat} (h : \Pi {u v : X} -> IsTruncMap k (pmap r {u} {v}))
                          (u v : X) {y : Y} (q : r u = y) (q' : r v = y) : ((u,q) = {Fib r y} (v,q')) ofHLevel_-2+ k \elim q'
      | idp => HLevel_-2-retracts (Fib.equiv (r v) (u,q) (v,idp)) (h q)

    -- | {r} is `(k-1)`-truncated iff the action of {r} on paths is `(k-2)`-truncated.
    \lemma truncMap-suc {X Y : \Cat} {r : X -> Y} {k : Nat}
      : IsTruncMap (suc k) r <-> (\Pi {u v : X} -> IsTruncMap k (pmap r {u} {v}))
      => (\lam t {u} {v} q => HLevel_-2-retracts (symQEquiv (Fib.equiv (r v) (u,q) (v,idp))) (t (r v) (u,q) (v,idp)),
          \lam h y w w' => fib-path-level h w.1 w'.1 w.2 w'.2)
  }

-- # Prop-based and Contr-base hLevels are equivalent

\func HLevel_-2+1=>HLevel_-1 (A : \Cat) (n : Nat) (p : A ofHLevel_-2+ suc n) : A ofHLevel_-1+ n \elim n
  | 0 => toProp \lam a a' => Contr.center {p a a'}
  | suc n => \lam a a' => HLevel_-2+1=>HLevel_-1 (a = a') n (p a a')

\lemma HLevel_-1=>HLevel_-2+1 (A : \Cat) (n : Nat) (p : A ofHLevel_-1+ n) : A ofHLevel_-2+ suc n \elim n
  | 0 => isProp=>PathContr A (ToProp.fromProp p)
  | suc n => \lam a a' => HLevel_-1=>HLevel_-2+1 (a = a') n (p a a')

-- # Every k-level is n-level whenever k <= n

\func HLevel_-1_suc {A : \Cat} {n : Nat} (p : A ofHLevel_-1+ n) : A ofHLevel_-1+ suc n \elim n
  | 0 => \lam a a' => toProp (isProp.=>isSet (ToProp.fromProp p) a a')
  | suc n => \lam a a' => HLevel_-1_suc (p a a')

\func HLevel_-1_+ {A : \Cat} {k : Nat} (n : Nat) (p : A ofHLevel_-1+ k) : A ofHLevel_-1+ k Nat.+ n \elim n
  | 0 => p
  | suc n => HLevel_-1_suc (HLevel_-1_+ n p)

\func HLevel_-1_<= {A : \Cat} (k : Nat) (n : Nat) (q : k <= n) (p : A ofHLevel_-1+ k) : A ofHLevel_-1+ n
  => rewriteI (<=_exists q) (HLevel_-1_+ (n -' k) p)

{- # Properties of hLevels
 - I'm not sure which version of ofHLevel is more convenient, so I proved each lemma twice.
 -}

-- ## Properties of prop-based hLevels

-- | hLevels are closed under retracts
\func HLevel-retracts (s : Section) {n : Nat} (p : s.B ofHLevel_-1+ n) : s.A ofHLevel_-1+ n \elim n
  | 0 => toProp \lam a a' => inv (s.ret_f a) *> pmap s.ret (ToProp.fromProp p (s a) (s a')) *> s.ret_f a'
  | suc n => \lam a a' => HLevel-retracts (pmapSection s) (p (s a) (s a'))

-- | hLevels are closed under pi-types
\func HLevels-pi {A : \Cat} (B : A -> \Cat) {n : Nat} (p : \Pi (a : A) -> B a ofHLevel_-1+ n) : (\Pi (a : A) -> B a) ofHLevel_-1+ n \elim n
  | 0 => toProp (pi-isProp B \lam a => ToProp.fromProp (p a))
  | suc n => \lam f f' => HLevel-retracts (piEquiv B f f') (HLevels-pi (\lam a => f a = f' a) (\lam a => p a (f a) (f' a)))

-- | hLevels are closed under sigma-types
\func HLevels-sigma {A : \Cat} (B : A -> \Cat) {n : Nat} (pA : A ofHLevel_-1+ n) (pB : \Pi (a : A) -> B a ofHLevel_-1+ n) : (\Sigma (a : A) (B a)) ofHLevel_-1+ n \elim n
  | 0 => toProp \lam p p' => ext (ToProp.fromProp pA p.1 p'.1, ToProp.fromProp (pB p'.1) _ _)
  | suc n => \lam p p' => HLevel-retracts (sigmaEquiv B p p') (HLevels-sigma (transport B __ p.2 = p'.2) (pA p.1 p'.1) (\lam s => pB _ _ _))

-- | hLevels are closed under embeddings
\func HLevels-embeddings (e : Embedding) {n : Nat} (p : e.B ofHLevel_-1+ n) : e.A ofHLevel_-1+ n \elim n
  | 0 => toProp \lam a a' => sec {e.isEmb a a'} (ToProp.fromProp p (e a) (e a'))
  | suc n => \lam a a' => HLevels-embeddings (pmapEmbedding e) (p (e a) (e a'))

-- ## Properties of contr-based hLevels

-- | Contr-based hLevels are closed under retracts
\lemma HLevel_-2-retracts (s : Section) {n : Nat} (p : s.B ofHLevel_-2+ n) : s.A ofHLevel_-2+ n \elim n
  | 0 => \have a0 => s.ret (Contr.center {p}) \in Contr.make a0 (\lam a => inv (s.ret_f a0) *> pmap s.ret (isContr=>isProp p (s a0) (s a)) *> s.ret_f a)
  | suc n => \lam a a' => HLevel_-2-retracts (pmapSection s) (p (s a) (s a'))

-- | Contr-based hLevels are closed under pi-types
\lemma HLevels_-2-pi {A : \Cat} (B : A -> \Cat) {n : Nat} (p : \Pi (a : A) -> B a ofHLevel_-2+ n) : (\Pi (a : A) -> B a) ofHLevel_-2+ n \elim n
  | 0 => pi-Contr B p
  | suc n => \lam f f' => HLevel_-2-retracts (piEquiv B f f') (HLevels_-2-pi (\lam a => f a = f' a) (\lam a => p a (f a) (f' a)))

-- | Contr-based hLevels are closed under sigma-types
\lemma HLevels_-2-sigma {A : \Cat} (B : A -> \Cat) {n : Nat} (pA : A ofHLevel_-2+ n) (pB : \Pi (a : A) -> B a ofHLevel_-2+ n) : (\Sigma (a : A) (B a)) ofHLevel_-2+ n \elim n
  | 0 => sigma-Contr pA pB
  | suc n => \lam p p' => HLevel_-2-retracts (sigmaEquiv B p p') (HLevels_-2-sigma (transport B __ p.2 = p'.2) (pA p.1 p'.1) (\lam s => pB _ _ _))
