\import Equiv
\import Equiv.Sigma
\import Equiv.Univalence
\import Logic.Unique
\import Homotopy.Fibration
\import Homotopy.Join
\import Homotopy.Localization.Connected
\import Homotopy.Localization.Universe
\import Homotopy.Pushout
\import Logic
\import Paths
\import Paths.Meta

\lemma genBlakersMassey {d : Data} (x0 : X) (y0 : Y) : isConnectedMap (pbMap {d} {x0} {y0}) => {?hidden_proof}
  \where {
    \open Localization

    \lemma surjective {d : Data} {x0 : X} {y0 : Y} (q : TruncP (\Sigma (y : Y) (Q x0 y))) : isConnectedMap (pbMap {d} {x0} {y0}) => {?hidden_proof}

\class EquivData \extends ReflUniverse (A : \hType) (B : \hType) {
      | M : A -> Connected
      | N : B -> Connected
      | f : \Sigma (a : A) (M a) -> \Sigma (b : B) (N b)
      | g : \Sigma (b : B) (N b) -> \Sigma (a : A) (M a)
      | p : \Pi (a : A) (m : M a) -> (g (f (a, m))).1 = a
      | q : \Pi (b : B) (n : N b) -> (f (g (b, n))).1 = b

      \func eval (a : A) (m : M a) : lift (\lam a => sec {Connected.equiv {M a} (LType B)} (\lam m => lEta (f (a, m)).1)) (lEta a) = lEta (f (a, m)).1 
      => lift-prop (\lam a => sec {Connected.equiv {M a} (LType B)} (\lam m => lEta (f (a, m)).1)) a *> path 
        (\lam i => (f_sec {Connected.equiv {M a} (LType B)} (\lam m => lEta (f (a, m)).1) @ i) m)

      \lemma equiv-lemma : Equiv {LType A} {LType B} (lift (\lam a => sec {Connected.equiv {M a} (LType B)} (\lam m => lEta (f (a, m)).1))) => {?hidden_proof}
    }

\class POData {
      | X : \hType
      | Y : \hType
      | Q : X -> Y -> \hType

      \func PO  => PushoutData {\Sigma (x : X) (y : Y) (Q x y)} __.1 __.2

      \func swap (x : PO) : PushoutData {\Sigma (y : Y) (x : X) (Q x y)} __.1 __.2 
        | pinl b => pinr b
        | pinr c => pinl c
        | pglue (x, y, q) i => pglue (y, x, q) (inv (path (\lam j => j)) @ i)

      \func pbMap {x : X} {y : Y} (q : Q x y) : pinl x = {PO} pinr y => PushoutData.ppglue ((x, y, q) : (\Sigma (x : X) (y : Y) (Q x y)))

      \lemma pullback_pushout-surjective (x : X) (y : Y) (p : pinl x = {PO} pinr y) : TruncP (\Sigma (x' : X) (Q x' y)) => {?hidden_proof}
    }

    \open POData

\class Data \extends ReflUniverse, POData {
      | ch {x x' : X} {y y' : Y} (q0 : Q x y) (q1 : Q x y') (q2 : Q x' y) : isConnectedType (Join (\Sigma (p : y = y') (transport (Q x) p q0 = q1)) (\Sigma (p : x = x') (transport (Q y) p q0 = q2)))
    }

\class DataExt \extends Data {
      | x0 : X
      | y0 : Y
      | q0 : Q x0 y0

      \func code-left {x : X} {w : PO} (p : pinl x = {PO} w) (p' : pinl x0 = w) : \hType => LType (\Sigma (q1 : Q x y0) (pbMap q0 *> inv (pbMap q1) *> p = p'))

      \func code-glue-gen {x : X} {w : PO} (code : pinl x0 = w -> \hType) (p : pinl x = w) (t : \Pi (p' : pinl x0 = w) -> Equiv {code-left p p'} {code p'}) :
        transport (pinl x0 = __ -> \hType) p (code-left idp) = code \elim p
        | idp => path (\lam i p' => Equiv-to-= (t p') @ i)

      \func code-glue {x : X} {y : Y} (q : Q x y) : transport (pinl x0 = __ -> \hType) (pbMap q) (code-left idp) = (\lam p => LType (Fib pbMap p)) 
        => code-glue-gen (\lam p => LType (Fib pbMap p)) (pbMap q) (code.equiv q)

      \func code {w : PO} (p : pinl x0 = w) : \hType \elim w
        | pinl x => code-left idp p
        | pinr y => LType (Fib pbMap p)
        | pglue (x, y, q) i => (pathOver (code-glue q) @ i) p
        \where {
          \func equivData {x : X} {y : Y} (q : Q x y) (p : pinl x0 = {PO} pinr y) : EquivData \cowith
            | isLocal => isLocal
            | localization => localization
            | A => \Sigma (q1 : Q x y0) (pbMap q0 *> inv (pbMap q1) *> pbMap q = p)
            | B => Fib pbMap p
            | M => \lam a => \new Connected {
              | X => Join (\Sigma (p : y0 = y) (transport (Q x) p a.1 = q)) (\Sigma (p : x = x0) (transport (Q y0) p a.1 = q0))
              | connected => ch a.1 q q0
            }
            | N => \lam b => \new Connected {
              | X => Join (\Sigma (p : y = y0) (transport (Q x0) p b.1 = q0)) (\Sigma (p : x0 = x) (transport (Q y) p b.1 = q))
              | connected => ch b.1 q0 q
            }
            | f => \lam ad => LR q p ad.1 ad.2
            | g => \lam bd => RL q0 q p bd.1 bd.2
            | p => LRL q p
            | q => RLR q p

          \lemma equiv {x : X} {y : Y} (q : Q x y) (p : pinl x0 = {PO} pinr y) => {?hidden_proof}

          \func pathLem1 {A : \hType} {a a' a'' : A} (p : a = a') (q : a'' = a') : p *> inv q *> q = p 
            | idp, idp => idp

          \func pathLem2-gen {A : \hType} {a a' a'' : A} {p1 p2 : a = a'} {q : a = a''} (t : p1 *> inv p2 = idp) : p1 *> inv p2 *> q = q \elim q
            | idp => t

          \func pathLem2 {A : \hType} {a a' a'' : A} (p : a = a') (q : a = a'') : p *> inv p *> q = q => pathLem2-gen (*>_inv p)

          \func pathLem3 {A : \hType} {a a' : A} (p : a = a') : pathLem1 p p = pathLem2 p p 
            | idp => idp

          \func LR {x : X} {y : Y} (q : Q x y) (p : pinl x0 = {PO} pinr y) (a : \Sigma (q1 : Q x y0) (pbMap q0 *> inv (pbMap q1) *> pbMap q = p)) 
          (m : Join (\Sigma (p : y0 = y) (transport (Q x) p a.1 = q)) (\Sigma (p : x = x0) (transport (Q y0) p a.1 = q0))) :
            \Sigma (b : Fib pbMap p) (Join (\Sigma (p : y = y0) (transport (Q x0) p b.1 = q0)) (\Sigma (p : x0 = x) (transport (Q y) p b.1 = q))) \elim a, m
            | (a1, a2), jinl (idp, idp) => ((q0, inv (pathLem1 (pbMap q0) (pbMap a1)) *> a2), pinl (idp, idp))
            | (a1, a2), jinr (idp, idp) => ((q, inv (pathLem2 (pbMap a1) (pbMap q)) *> a2), pinr (idp, idp))
            | (a1, a2), pglue ((idp, idp), (idp, idp)) i => ((q0, inv (pathLem3 (pbMap q0) @ i) *> a2), pglue ((idp, idp), (idp, idp)) i)

          \func RL {x : X} {y : Y} (q0 : Q x0 y0) (q : Q x y) (p : pinl x0 = {PO} pinr y) (b : \Sigma (q2 : Q x0 y) (pbMap q2 = p)) 
          (n : Join (\Sigma (p : y = y0) (transport (Q x0) p b.1 = q0)) (\Sigma (p : x0 = x) (transport (Q y) p b.1 = q))) :
            \Sigma (a : \Sigma (q1 : Q x y0) (pbMap q0 *> inv (pbMap q1) *> pbMap q = p)) 
            (Join (\Sigma (p : y0 = y) (transport (Q x) p a.1 = q)) (\Sigma (p : x = x0) (transport (Q y0) p a.1 = q0))) \elim n
            | jinl (idp, idp) => ((q, pathLem1 (pbMap b.1) (pbMap q) *> b.2), pinl (idp, idp))
            | jinr (idp, idp) => ((q0, pathLem2 (pbMap q0) (pbMap b.1) *> b.2), pinr (idp, idp))
            | pglue ((idp, idp), (idp, idp)) i => ((b.1, (pathLem3 (pbMap b.1) @ i) *> b.2), pglue ((idp, idp), (idp, idp)) i)

          \func LRL {x : X} {y : Y} (q : Q x y) (p : pinl x0 = {PO} pinr y) (a : \Sigma (q1 : Q x y0) (pbMap q0 *> inv (pbMap q1) *> pbMap q = p)) 
          (m : Join (\Sigma (p : y0 = y) (transport (Q x) p a.1 = q)) (\Sigma (p : x = x0) (transport (Q y0) p a.1 = q0))) :
            (RL q0 q p (LR q p a m).1 (LR q p a m).2).1 = a \elim a, m
            | (a1, idp), jinl (idp, idp) => path (\lam i => (q, *>_inv (pathLem1 (pbMap q0) (pbMap q)) @ i))
            | (a1, idp), jinr (idp, idp) => path (\lam i => (q0, *>_inv (pathLem2 (pbMap q0) (pbMap q)) @ i))
            | (a1, idp), pglue ((idp, idp), (idp, idp)) j => path (\lam i => (q0, *>_inv (pathLem3 (pbMap q0) @ j) @ i))

          \func RLR {x : X} {y : Y} (q : Q x y) (p : pinl x0 = {PO} pinr y) (b : \Sigma (q2 : Q x0 y) (pbMap q2 = p)) 
          (n : Join (\Sigma (p : y = y0) (transport (Q x0) p b.1 = q0)) (\Sigma (p : x0 = x) (transport (Q y) p b.1 = q))) :
            (LR q p (RL q0 q p b n).1 (RL q0 q p b n).2).1 = b \elim b, n
            | (b1, idp), jinl (idp, idp) => path (\lam i => (q0, inv_*> (pathLem1 (pbMap q0) (pbMap q)) @ i))
            | (b1, idp), jinr (idp, idp) => path (\lam i => (q, inv_*> (pathLem2 (pbMap q0) (pbMap q)) @ i))
            | (b1, idp), pglue ((idp, idp), (idp, idp)) j => path (\lam i => (q0, inv_*> (pathLem3 (pbMap q0) @ j) @ i))
        }


      \func coerce-path-gen {w : PO} (p : pinl x0 = w) (t : transport (pinl x0 = __ -> \hType) p (code-left idp) = code) : code-left idp idp = code p \elim p
        | idp => path ((t @ __) idp)

      \func coerce-path {w : PO} (p : pinl x0 = w) : code-left idp idp = code p => coerce-path-gen p (pmapd (\lam _ => code) p)

      \func Left {w : PO} (p : pinl x0 = w) => \Sigma (q : Q x0 y0) (pbMap q0 *> inv (pbMap q) *> p = p)

      \func code-left-diag {w : PO} (p : pinl x0 = w) (v : code-left idp idp) : code-left p p => lmap {_} {Left idp} {Left p} (\lam t => (t.1, code.pathLem2-gen t.2)) v

      \func coerce-path-glue-gen {w : PO} (p : pinl x0 = w) (t : \Pi (p' : pinl x0 = w) -> Equiv {code-left p p'} {code p'}) (v : code-left idp idp) :
        transport (\lam T => T) (coerce-path-gen p (code-glue-gen code p t)) v = t p (code-left-diag p v) \elim p
        | idp => pmap (t idp) (inv (lmap.id-prop v))

      \func code-center {w : PO} (p : pinl x0 = w) : code p => transport (\lam T => T) (coerce-path p) (lEta point)
        \where {
          \func point : Left idp => (q0, *>_inv (pbMap q0))
        }


      \func code-path (p : pinl x0 = {PO} pinr y0) (c : Fib pbMap p) : code-center p = lEta c \elim c
        | (q, idp) => qed (code-center (pbMap q) ==< pmap (\lam s => transport (\lam T => T) (coerce-path-gen (pbMap q) s) (lEta code-center.point)) 
          (pmapd_pathOver (pinl x0 = __ -> \hType) (\lam _ => code) (pbMap q) (code-glue q) idp) >== transport (\lam T => T) 
          (coerce-path-gen (pbMap q) (code-glue q)) (lEta code-center.point) ==< coerce-path-glue-gen (pbMap q) (code.equiv q) (lEta code-center.point) >== 
          code.equiv q (pbMap q) (code-left-diag (pbMap q) (lEta code-center.point)) ==< pmap (code.equiv q (pbMap q)) 
          (lift-prop (\lam (t : Left idp) => inL ((t.1, code.pathLem2-gen t.2) : Left (pbMap q))) code-center.point) >== code.equiv q (pbMap q) 
          (lEta ((q0, code.pathLem2 (pbMap q0) (pbMap q)) : Left (pbMap q))) ==< EquivData.eval {code.equivData q (pbMap q)} 
          (q0, code.pathLem2 (pbMap q0) (pbMap q)) (pinr (idp, idp)) >== lEta 
          ((q, inv (code.pathLem2 (pbMap q0) (pbMap q)) *> code.pathLem2 (pbMap q0) (pbMap q)) : Fib pbMap p) ==< pmap (\lam x => lEta ((q, x) : Fib pbMap p)) 
          (inv_*> (code.pathLem2 (pbMap q0) (pbMap q))) >== lEta ((q, idp) : Fib pbMap p))

      \lemma code-contr {w : PO} (p : pinl x0 = w) : Contr (code p) => {?hidden_proof}
    }
  }
