\import Equiv
\import Equiv.Fiber
\import Equiv.Univalence
\import Function
\import Homotopy.HLevel
\import Homotopy.Fibration
\import Homotopy.Localization.Accessible
\import Homotopy.Localization.Connected
\import Homotopy.Localization.Universe
\import Logic
\import Logic.Unique
\import Paths
\import Paths.Meta

\func isLocalEquiv {U : Universe} {A B : \hType} (f : A -> B) => \Pi (Z : Local) -> Equiv {B -> Z} {A -> Z} (-o f)

\module Extension
  \where {
    \func ext {A B C : \hType} (f : A -> B) (g : A -> C) => Fib (-o f) g

    \func ext-equiv {A B C : \hType} (f : A -> B) (g : A -> C) : QEquiv {ext f g} {\Pi (b : B) -> \Sigma (c : C) (\Pi (a : A) -> f a = b -> g a = c)} \cowith
      | f => \lam p b => (p.1 b, \lam a fa=b => inv (path ((p.2 @ __) a)) *> pmap p.1 fa=b)
      | ret => \lam K => ((K __).1, path (\lam i a => inv ((K (f a)).2 a idp) @ i))
      | ret_f => \lam b => path (\lam j => (b.1, path (\lam i a => inv_inv (path ((b.2 @ __) a)) @ j @ i)))
      | f_sec => \lam K => (
        \have p (b : B) (a : A) (q : f a = b) => Jl (\lam b' q' => inv (inv ((K (f a)).2 a idp)) *> pmap (K __).1 q' = (K b').2 a q') (inv_inv ((K (f a)).2 a idp)) q
        \in path (\lam i b => ((K b).1, p b __ __ @ i)))

    \lemma contr-equiv {A B C : \hType} (f : A -> B) (p : \Pi (g : A -> C) (b : B) -> Contr (\Sigma (c : C) (\Pi (a : A) -> f a = b -> g a = c))) : Equiv {B -> C} {A -> C} (-o f) 
      => {?hidden_proof}
  }


\lemma connected_isLocalEquiv {U : Universe} {A B : \hType} (f : A -> B) (conn : isConnectedMap f) : isLocalEquiv f => {?hidden_proof}

\lemma localTypesEquiv {U : Universe} {A B : Local} (f : A -> B) : isLocalEquiv f = Equiv f => {?hidden_proof}
  \where {
    \lemma dir {U : Universe} {A B : Local} (f : A -> B) (p : isLocalEquiv f) : Equiv f => {?hidden_proof}
  }


\lemma localEquivMap {U : ReflUniverse} {A B : \hType} (f : A -> B) : isLocalEquiv f = Equiv (lmap f) => {?hidden_proof}