\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Operations
\import Paths
\import Paths.Meta
\import Set.Filter
\import Set.Subset
\import Topology.CoverSpace
\import Topology.CoverSpace.Complete
\import Topology.CoverSpace.CompletionTools
\import Topology.CoverSpace.Product
\import Topology.TopAbGroup
\import Topology.TopAbGroup.Product
\import Topology.TopSpace
\import Topology.TopSpace.Product
\import Topology.UniformSpace.Complete
\open Completion

\class CompleteTopAbGroup \extends TopAbGroup, CompleteUniformSpace

\func dense-topAb-lift {X Y : TopAbGroup} {Z : CompleteTopAbGroup} (f : TopAbGroupMap X Y) (fd : f.IsDenseTopEmbedding) (g : TopAbGroupMap X Z) : TopAbGroupMap Y Z \cowith
  | ContMap => dense-uniform-lift f (f.embedding->uniformEmbedding fd) g
  | func-+ => {?hidden_proof}
  \where {
    \open ProductTopSpace
    \open ContMap
  }


\instance TopAbGroupCompletion (X : TopAbGroup) : CompleteTopAbGroup 
  | CompleteUniformSpace => UniformCompletion X
  | AbGroup => abGroup
  | +-cont => {?hidden_proof}
  | negative-cont => {?hidden_proof}
  | neighborhood-uniform => {?hidden_proof}
  \where {
    \open ProductCoverSpace
    \open CoverMap

    \func abGroup : AbGroup (RegularCauchyFilter X) \cowith
      | zro => pointCF 0
      | + => +-func
      | zro-left => {?hidden_proof}
      | +-assoc => {?hidden_proof}
      | negative => negative-cover
      | negative-left => {?hidden_proof}
      | +-comm => {?hidden_proof}

    \func subtract-cover : CoverMap (Completion X ⨯ Completion X) (Completion X) => lift2 (+-uniform ∘ prod id negative-uniform)

    \lemma subtract_- {F G : RegularCauchyFilter X} : subtract-cover (F, G) = F - {abGroup} G => {?hidden_proof}

    \sfunc +-cover : CoverMap (Completion X ⨯ Completion X) (Completion X) => subtract-cover ∘ prod id negative-cover

    \func +-func (x y : RegularCauchyFilter X) => +-cover (x, y)

    \lemma +-char {x y : X} : +-cover (pointCF x, pointCF y) = pointCF (x + y) => {?hidden_proof}

    \sfunc negative-cover : CoverMap (Completion X) (Completion X) => subtract-cover ∘ tuple (const $ pointCF 0) id

    \lemma negative-char {x : X} : negative-cover (pointCF x) = pointCF (negative x) => {?hidden_proof}

    \lemma topAb-neighborhood {F G : RegularCauchyFilter X} {U : Set (Completion X)} :
      single (F - {abGroup} G) <=< U <-> ∃ (U' : Set (Completion X)) (U' <=< U) (V1 : Set X) (F V1) (V2 : Set X) (G V2) ∀ {x : V1} {y : V2} (U' (pointCF (x - y))) 
      => {?hidden_proof}
  }


\func completion-topAb {X : TopAbGroup} : TopAbGroupMap X (TopAbGroupCompletion X) \cowith
  | UniformMap => uniform-completion
  | func-+ => {?hidden_proof}