\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ordered
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Arith.Real.LowerReal
\import Arith.Real.UpperReal
\import Data.Array
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set.Subset
\open LatticeAbGroup

\func IsSup (A : Set Real) (b : Real) : \Prop => \Sigma (∀ {a : A} (a <= b)) (∀ {eps} (0 < eps) ∃ (x : A) (b < x + eps))
  \where {
    \lemma isLowest {b : Real} (s : IsSup A b) {c : Real} (Ac : ∀ {a : A} (a <= c)) : b <= c => {?hidden_proof}

    \lemma isUnique {b b' : Real} (bs : IsSup A b) (b's : IsSup A b') : b = b' => {?hidden_proof}
  }


\func HasSup (A : Set Real) => \Sigma (B : Real) (IsSup A B)
  \where {
    \use \level levelProp (s t : HasSup A) : s = t => ext (IsSup.isUnique s.2 t.2)
  }


\func makeSup {A : Set Real} {a0 : Real} (Aa0 : A a0) {b : Real} (Ab : ∀ {a : A} (a < b)) 
(As : \Pi {x y : Real} -> x < y -> Given (a : A) (x < a) || ∀ {a : A} (a < y)) : Real \cowith
  | L => \lam z => ∃ (a : A) (Real.L {a} z)
  | L-inh => \case a0.L-inh \with {
    | inP (r, r<a0) => inP (r, inP (a0, Aa0, r<a0))
  }
| L-closed => \lam inP (a, Aa, q<a) q'<q => inP (a, Aa, L-closed q<a q'<q)
| L-rounded => \lam inP (a, Aa, q<a) => (\case L-rounded q<a \with {
  | inP (r, r<a, q<r) => inP (r, inP (a, Aa, r<a), q<r)
})
| U => \lam z => ∃ (z' : Real) (z' < z) ∀ {a : A} (a < z')
| U-inh => \case b.U-inh \with {
  | inP (r, b<r) => inP (r, inP (b, real_<_U.2 b<r, Ab))
}
| U-closed => \lam inP (z, z<q, zb) q<q' => inP (z, z<q <∘ real_<_L.2 q<q', zb)
| U-rounded => \lam inP (z, z<q, zb) => (\case U-rounded (real_<_U.1 z<q) \with {
  | inP (r, z<r, r<q) => inP (r, \case U-rounded z<r \with {  | inP (z', z<z', z'<r) => inP (z', real_<_L.2 z'<r, \lam Aa => zb Aa <∘ real_<_U.2 z<z')}, r<q)
})
| LU-disjoint => \lam inP (a, Aa, q<a) inP (z, z<q, zb) => linarith (real_<_L.2 q<a, zb Aa)
| LU-located => \lam {q} {r} q<r => (\case As $ real_<_L.2 (RatField.mid>left q<r) \with {
  | byLeft (a, Aa, q<a) => byLeft $ inP (a, Aa, real_<_L.1 q<a)
  | byRight rb => byRight $ inP (RatField.mid q r, real_<_L.2 $ RatField.mid<right q<r, rb)
})
  \where {
    \lemma isSup (Aa0 : A a0) (Ab : ∀ {a : A} (a < b)) (As : \Pi {x y : Real} -> x < y -> Given (a : A) (x < a) || ∀ {a : A} (a < y)) : IsSup A (makeSup Aa0 Ab As) => {?hidden_proof}

    \lemma conv {b : Real} (bs : IsSup A b) {x y : Real} (x<y : x < y) : Given (a : A) (x < a) || ∀ {a : A} (a < y) => {?hidden_proof}
  }


\lemma makeSup-pair {A : Set Real} {a0 : Real} (Aa0 : A a0) {b : Real} (Ab : ∀ {a : A} (a < b)) 
(As : \Pi {x y : Real} -> x < y -> Given (a : A) (x < a) || ∀ {a : A} (a < y)) : HasSup A => {?hidden_proof}

\lemma makeSupTB {A : Set Real} {a0 : Real} (Aa0 : A a0) 
(Ac : \Pi {eps : Real} -> 0 < eps -> ∃ (l : Array Real) (∀ (a : l) (A a)) ∀ {x : A} ∃ (y : l) (abs (x - y) < eps)) : HasSup A => {?hidden_proof}

\func IsInf (A : Set Real) (b : Real) : \Prop => \Sigma (∀ {a : A} (b <= a)) (∀ {eps} (0 < eps) ∃ (x : A) (x < b + eps))
  \where {
    \lemma isGreatest {b : Real} (s : IsInf A b) {c : Real} (Ac : ∀ {a : A} (c <= a)) : c <= b => {?hidden_proof}

    \lemma isUnique {b b' : Real} (bs : IsInf A b) (b's : IsInf A b') : b = b' => {?hidden_proof}
  }


\func HasInf (A : Set Real) => \Sigma (B : Real) (IsInf A B)
  \where {
    \use \level levelProp (s t : HasInf A) : s = t => ext (IsInf.isUnique s.2 t.2)
  }


\func makeSupInf {A : Set Real} {b : Real} (bs : IsSup (\lam x => A (negative x)) (negative b)) : IsInf A b => (
  \lam Aa => transport2 <= AddGroup.negative-isInv AddGroup.negative-isInv $ PosetAddGroup.negative_<= $ bs.1 $ transportInv A AddGroup.negative-isInv Aa, 
  \lam eps>0 => (\case bs.2 eps>0 \with {  | inP (x, A-x, -b<x+eps) => inP (negative x, A-x, linarith)})
  )

\lemma makeHasSupInf {A : Set Real} (s : HasSup (\lam x => A (negative x))) : HasInf A => {?hidden_proof}

\func makeInf {A : Set Real} {a0 : Real} (Aa0 : A a0) {b : Real} (Ab : ∀ {a : A} (b < a)) 
(As : \Pi {x y : Real} -> x < y -> ∀ {a : A} (x < a) || Given (a : A) (a < y)) : Real \cowith
  | L => \lam z => ∃ (z' : Real) ((z : Real) < z') ∀ {a : A} (z' < a)
  | L-inh => \case b.L-inh \with {
    | inP (r, r<b) => inP (r, inP (b, real_<_L.2 r<b, Ab))
  }
| L-closed => \lam inP (z, q<z, zb) q'<q => inP (z, real_<_L.2 q'<q <∘ q<z, zb)
| L-rounded => \lam inP (z, q<z, zb) => (\case L-rounded (real_<_L.1 q<z) \with {
  | inP (r, r<z, q<r) => inP (r, \case L-rounded r<z \with {  | inP (z', z<z', z'<r) => inP (z', real_<_L.2 z'<r, \lam Aa => real_<_L.2 z<z' <∘ zb Aa)}, q<r)
})
| U => \lam z => ∃ (a : A) (Real.U {a} z)
| U-inh => \case a0.U-inh \with {
  | inP (r, a0<r) => inP (r, inP (a0, Aa0, a0<r))
}
| U-closed => \lam inP (a, Aa, a<q) q<q' => inP (a, Aa, U-closed a<q q<q')
| U-rounded => \lam inP (a, Aa, a<q) => (\case U-rounded a<q \with {
  | inP (r, a<r, r<q) => inP (r, inP (a, Aa, a<r), r<q)
})
| LU-disjoint => \lam inP (z, q<z, zb) inP (a, Aa, a<q) => linarith (real_<_U.2 a<q, zb Aa)
| LU-located => \lam {q} {r} q<r => (\case As $ real_<_U.2 (RatField.mid<right q<r) \with {
  | byLeft rb => byLeft $ inP (RatField.mid q r, real_<_U.2 $ RatField.mid>left q<r, rb)
  | byRight (a, Aa, q<a) => byRight $ inP (a, Aa, real_<_U.1 q<a)
})
  \where {
    \lemma isInf : IsInf A (makeInf Aa0 Ab As) => {?hidden_proof}

    \lemma conv {b : Real} (bs : IsInf A b) {x y : Real} (x<y : x < y) : ∀ {a : A} (x < a) || Given (a : A) (a < y) => {?hidden_proof}
  }


\lemma makeInfTB {A : Set Real} {a0 : Real} (Aa0 : A a0) 
(Ac : \Pi {eps : Real} -> 0 < eps -> ∃ (l : Array Real) (∀ (a : l) (A a)) ∀ {x : A} ∃ (y : l) (abs (x - y) < eps)) : HasInf A => {?hidden_proof}