\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Int
\import Arith.Rat
\import Arith.Real.LowerReal
\import Arith.Real.UpperReal
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta

\class InfReal \extends LowerReal, ExUpperReal {
  | LU-disjoint {q : Rat} : L q -> U q -> Empty
  | LU-located {q r : Rat} : q < r -> L q || U r
  | LU-focus-bound (B : Rat) {eps : Rat} : eps > 0 -> L B || Given (a : L) (U (a + eps))
  | LU-located => \lam {q} {r} q<r => (\case LU-focus-bound q {r - q} (RatField.pos_>0 q<r) \with {
    | byLeft p => byLeft p
    | byRight (s, Ls, Us+r-q) => \case LinearOrder.trichotomy q s \with {
      | less q<s => byLeft (L-closed Ls q<s)
      | equals q=s => byLeft (transportInv L q=s Ls)
      | greater s<q => byRight $ U-closed Us+r-q $ transport (_ <) (equation : q + (r - q) = r) (<_+-left (r - q) s<q)
    }
  })
  | L-inh => \case LU-focus-bound 1 {1} idp \with {
    | byLeft p => inP (1, p)
    | byRight p => inP (p.1, p.2)
  }
| LU-focus-bound => LU-focus-bound-impl
}
\where {
  \use \coerce fromRat (x : Rat) : InfReal \cowith
    | LowerReal => LowerReal.fromRat x
    | ExUpperReal => ExUpperReal.fromRat x
    | LU-disjoint => \lam q<x x<q => <-irreflexive (q<x <∘ x<q)
    | LU-focus-bound => \lam B {eps} eps>0 => byRight (x - eps * finv 2, linarith, linarith)

  \lemma pow>id (n : Nat) : Monoid.pow (ratio 3 2) n > n => {?hidden_proof}

  \lemma focus-iter (rat : Rat) (rat>=0 : 0 <= rat) (P : Rat -> Rat -> \Prop) (f : \Pi (q r : Rat) -> P q r -> ∃ (q' r' : P) ((r' - q') * rat <= r - q)) (n : Nat) 
  (q r : Rat) (Pqr : P q r) : ∃ (q' r' : P) ((r' - q') * Monoid.pow rat n <= r - q) => {?hidden_proof}

  \lemma real-ext {x y : InfReal} (p : \Pi {a : Rat} -> x.L a <-> y.L a) : x = y => {?hidden_proof}

  \lemma real-lower-ext {x y : InfReal} (p : x = {LowerReal} y) : x = y => {?hidden_proof}
}


\instance InfRealAbMonoid : LinearlyBiorderedAbMonoid InfReal 
  | zro => InfReal.fromRat 0
  | + => +
  | zro-left => InfReal.real-lower-ext $ +-lower *> {LowerReal} zro-left
  | +-comm => InfReal.real-lower-ext $ +-lower *> {LowerReal} +-comm *> {LowerReal} inv {LowerReal} +-lower
  | +-assoc => InfReal.real-lower-ext $ +-lower *> {LowerReal} pmap {LowerReal} (LowerRealAbMonoid.+ _) +-lower *> {LowerReal} +-assoc *> {LowerReal} pmap (_ LowerRealAbMonoid.+) 
    (inv {LowerReal} +-lower) *> {LowerReal} inv {LowerReal} +-lower
  | < => <
  | <-irreflexive => \lam inP (a, x<a, a<x) => LU-disjoint a<x x<a
  | <-transitive => \lam inP (a, x<a, a<y) inP (b, y<b, b<z) => inP (a, x<a, L-closed b<z $ InfReal.LU-less a<y y<b)
  | meet => meet
  | meet-left => \lam inP (a, x<a, a<xy) => absurd $ LU-disjoint (meet_L.1 a<xy).1 x<a
  | meet-right => \lam inP (a, y<a, a<xy) => absurd $ LU-disjoint (meet_L.1 a<xy).2 y<a
  | meet-univ => \lam z<=x z<=y inP (a, xy<a, a<z) => (\case meet_U.1 xy<a \with {
    | byLeft x<a => z<=x $ inP (a, x<a, a<z)
    | byRight y<a => z<=y $ inP (a, y<a, a<z)
  })
  | join => join
  | join-left => \lam inP (a, xy<a, a<x) => LU-disjoint a<x (join_U.1 xy<a).1
  | join-right => \lam inP (a, xy<a, a<y) => LU-disjoint a<y (join_U.1 xy<a).2
  | join-univ => \lam x<=z y<=z inP (a, z<a, a<xy) => (\case join_L.1 a<xy \with {
    | byLeft a<x => x<=z $ inP (a, z<a, a<x)
    | byRight a<y => y<=z $ inP (a, z<a, a<y)
  })
  | <-comparison => \lam y inP (a, x<a, a<z) => (\case L-rounded a<z \with {
    | inP (b, b<z, a<b) => \case LU-located a<b \with {
      | byLeft a<y => byLeft $ inP (a, x<a, a<y)
      | byRight b<y => byRight $ inP (b, b<y, b<z)
    }
  })
  | <-connectedness => \lam p q => InfReal.real-ext (\lam {a} => (\lam a<x => (\case L-rounded a<x \with {  | inP (b, b<x, a<b) => \case LU-located a<b \with {    | byLeft a<y => a<y
      | byRight y<b => absurd $ q $ inP (b, y<b, b<x)  }}),
    \lam a<y => (\case L-rounded a<y \with {  | inP (b, b<y, a<b) => \case LU-located a<b \with {    | byLeft a<x => a<x
      | byRight x<b => absurd $ p $ inP (b, x<b, b<y)  }})))
  | <=_+ => \lam a<=b c<=d inP (x, b+d<x, x<a+c) => (\case +_L.1 x<a+c, +_U.1 b+d<x \with {
    | inP (q, q<a, r, r<c, x<q+r), inP (s, b<s, t, d<t, s+t<x) =>
      <-irreflexive $ x<q+r <∘ RatField.<_+ (InfReal.LU-less q<a $ <=_U.1 a<=b b<s) (InfReal.LU-less r<c $ <=_U.1 c<=d d<t) <∘ s+t<x
  })
  | meet_+-left => InfReal.real-lower-ext $ +-lower *> {LowerReal} pmap (_ LowerRealAbMonoid.+) meet-lower *> {LowerReal} meet_+-left *> {LowerReal} inv 
    (pmap2 LowerRealAbMonoid.meet +-lower +-lower) *> {LowerReal} inv {LowerReal} meet-lower
  | join_+-left => InfReal.real-lower-ext $ +-lower *> {LowerReal} pmap (_ LowerRealAbMonoid.+) join-lower *> {LowerReal} join_+-left *> {LowerReal} inv 
    (pmap2 LowerRealAbMonoid.join +-lower +-lower) *> {LowerReal} inv {LowerReal} join-lower
\where {
  \infixl 6 + (x y : InfReal) : InfReal \cowith
    | LowerReal => x LowerRealAbMonoid.+ y
    | ExUpperReal => x ExUpperReal.+ y
    | LU-disjoint => \lam r1 r2 => (\case LowerRealAbMonoid.+_L.1 r1, ExUpperReal.+_U.1 r2 \with {
      | inP (a, a<x, b, b<y, q<a+b), inP (c, x<c, d, y<d, c+d<q) => linarith (x.LU-less a<x x<c, y.LU-less b<y y<d)
    })
    | LU-focus-bound => \lam B {eps} eps>0 => (
      \have eps/4>0 : 0 RatField.< eps * ratio 1 4 => linarith
      \in \case x.LU-focus-bound 1 eps/4>0, y.LU-focus-bound B eps/4>0 \with {
            | byLeft x>1, byLeft y>B => byLeft $ LowerRealAbMonoid.+_L.2 $ inP (1, x>1, B, y>B, linarith)
            | byLeft _, byRight (y', y'<y, y<y'+eps/4) => \case x.LU-focus-bound (B - y' RatField.+ 1) eps/4>0 \with {
              | byLeft B-y'+1<x => byLeft $ LowerRealAbMonoid.+_L.2 $ inP (_, B-y'+1<x, y', y'<y, linarith)
              | byRight (x', x'<x, x<x'+eps/4) => byRight (x' RatField.+ y' - eps * ratio 1 4, LowerRealAbMonoid.+_L.2 $ inP (x', x'<x, y', y'<y, linarith), 
                ExUpperReal.+_U.2 $ inP (_, x<x'+eps/4, _, y<y'+eps/4, linarith))
            }
            | byRight (x', x'<x, x<x'+eps/4), byLeft _ => \case y.LU-focus-bound (B - x' RatField.+ 1) eps/4>0 \with {
              | byLeft r => byLeft $ LowerRealAbMonoid.+_L.2 $ inP (x', x'<x, _, r, linarith)
              | byRight (y', y'<y, y<y'+eps/4) => byRight (x' RatField.+ y' - eps * ratio 1 4, LowerRealAbMonoid.+_L.2 $ inP (x', x'<x, y', y'<y, linarith), 
                ExUpperReal.+_U.2 $ inP (_, x<x'+eps/4, _, y<y'+eps/4, linarith))
            }
            | byRight (x', x'<x, x<x'+eps/4), byRight (y', y'<y, y<y'+eps/4) =>
            byRight (x' RatField.+ y' - eps * ratio 1 4, LowerRealAbMonoid.+_L.2 $ inP (x', x'<x, y', y'<y, linarith), 
              ExUpperReal.+_U.2 $ inP (_, x<x'+eps/4, _, y<y'+eps/4, linarith))
          })

  \lemma +-lower {x y : InfReal} : x + y = {LowerReal} x LowerRealAbMonoid.+ y => {?hidden_proof}

  \lemma +-rat {x y : Rat} : InfReal.fromRat x + InfReal.fromRat y = InfReal.fromRat (x RatField.+ y) => {?hidden_proof}

  \lemma +_L {x y : InfReal} {a : Rat} : InfReal.L {x + y} a <-> ∃ (b : x.L) (c : y.L) (a RatField.< b RatField.+ c) => {?hidden_proof}

  \lemma +_L_<= {x y : InfReal} {a b : Rat} (b<x : x.L b) {c : Rat} (c<y : y.L c) (a<=b+c : a RatField.<= b RatField.+ c) : InfReal.L {x + y} a => {?hidden_proof}

  \lemma +-upper {x y : InfReal} : x + y = x ExUpperReal.+ y => {?hidden_proof}

  \lemma +_U {x y : InfReal} {a : Rat} : InfReal.U {x + y} a <-> ∃ (b : x.U) (c : y.U) (b RatField.+ c RatField.< a) => {?hidden_proof}

  \lemma +_U_<= {x y : InfReal} {a b : Rat} (x<b : x.U b) {c : Rat} (y<c : y.U c) (b+c<=a : b RatField.+ c RatField.<= a) : InfReal.U {x + y} a => {?hidden_proof}

  \type \infix 4 < (x y : InfReal) => ∃ (a : Rat) (x.U a) (y.L a)

  \lemma <=_L {x y : InfReal} : Not (y < x) <-> ∀ {a : x.L} (y.L a) => {?hidden_proof}

  \lemma <=_U {x y : InfReal} : Not (y < x) <-> ∀ {b : y.U} (x.U b) => {?hidden_proof}

  meet (x y : InfReal) : InfReal \cowith
    | LowerReal => LowerRealAbMonoid.meet x y
    | ExUpperReal => ExUpperReal.meet x y
    | LU-disjoint => \lam s r => (\case ExUpperReal.meet_U.1 r \with {
      | byLeft x<q => <-irreflexive (x.LU-less (LowerRealAbMonoid.meet_L.1 s).1 x<q)
      | byRight y<q => <-irreflexive (y.LU-less (LowerRealAbMonoid.meet_L.1 s).2 y<q)
    })
    | LU-located => \lam q<r => (\case x.LU-located q<r, y.LU-located q<r \with {
      | byLeft q<x, byLeft q<y => byLeft $ LowerRealAbMonoid.meet_L.2 (q<x, q<y)
      | _, byRight y<r => byRight $ ExUpperReal.meet_U.2 (byRight y<r)
      | byRight x<r, _ => byRight $ ExUpperReal.meet_U.2 (byLeft x<r)
    })

  \lemma meet-lower {x y : InfReal} : meet x y = {LowerReal} LowerRealAbMonoid.meet x y => {?hidden_proof}

  \lemma meet_L {x y : InfReal} {a : Rat} : InfReal.L {meet x y} a <-> (\Sigma (x.L a) (y.L a)) => {?hidden_proof}

  \lemma meet_U {x y : InfReal} {a : Rat} : InfReal.U {meet x y} a <-> x.U a || y.U a => {?hidden_proof}

  join (x y : InfReal) : InfReal \cowith
    | LowerReal => LowerRealAbMonoid.join x y
    | ExUpperReal => ExUpperReal.join x y
    | LU-disjoint => \lam e s => (\case LowerRealAbMonoid.join_L.1 e \with {
      | byLeft q<x => <-irreflexive $ x.LU-less q<x (ExUpperReal.join_U.1 s).1
      | byRight q<y => <-irreflexive $ y.LU-less q<y (ExUpperReal.join_U.1 s).2
    })
    | LU-located => \lam q<r => (\case x.LU-located q<r, y.LU-located q<r \with {
      | byLeft q<x, _ => byLeft $ LowerRealAbMonoid.join_L.2 (byLeft q<x)
      | _, byLeft q<y => byLeft $ LowerRealAbMonoid.join_L.2 (byRight q<y)
      | byRight x<r, byRight y<r => byRight $ ExUpperReal.join_U.2 (x<r, y<r)
    })

  \lemma join-lower {x y : InfReal} : join x y = {LowerReal} LowerRealAbMonoid.join x y => {?hidden_proof}

  \lemma join_L {x y : InfReal} {a : Rat} : InfReal.L {join x y} a <-> x.L a || y.L a => {?hidden_proof}

  \lemma join_U {x y : InfReal} {a : Rat} : InfReal.U {join x y} a <-> (\Sigma (x.U a) (y.U a)) => {?hidden_proof}

  \lemma zro<ide : InfReal.fromRat 0 < InfReal.fromRat 1 => {?hidden_proof}

  \lemma <_L {a : Rat} {x : InfReal} : (a : InfReal) < x <-> x.L a => {?hidden_proof}

  \lemma <_U {a : Rat} {x : InfReal} : x < a <-> x.U a => {?hidden_proof}

  \lemma <_+ {a b c d : InfReal} (p : a < c) (q : b < d) : a + b < c + d => {?hidden_proof}
}


\lemma inf-real_<_LowerReal {x y : InfReal} : x < y <-> x LowerRealAbMonoid.< y => {?hidden_proof}