\import Algebra.Field
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Int
\import Arith.Rat
\import Arith.Real.LowerReal
\import Arith.Real.UpperReal
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta

\record InfReal \extends LowerReal, ExUpperReal {
  | LU-disjoint {q : Rat} : L q -> U q -> Empty
  | LU-located {q r : Rat} : q < r -> L q || U r
  | LU-focus-bound (B : Rat) {eps : Rat} : eps > 0 -> L B || Given (a : L) (U (a + eps))
  | LU-located => \lam {q} {r} q<r => (\case LU-focus-bound q {r - q} (RatField.pos_>0 q<r) \with {
    | byLeft p => byLeft p
    | byRight (s, Ls, Us+r-q) => \case LinearOrder.trichotomy q s \with {
      | less q<s => byLeft (L-closed Ls q<s)
      | equals q=s => byLeft (transportInv L q=s Ls)
      | greater s<q => byRight $ U-closed Us+r-q $ transport (_ <) (equation : q + (r - q) = r) (<_+-left (r - q) s<q)
    }
  })
  | L-inh => \case LU-focus-bound 1 {1} idp \with {
    | byLeft p => inP (1, p)
    | byRight p => inP (p.1, p.2)
  }
| LU-focus-bound => LU-focus-bound-impl

\protected \default LU-focus-bound-impl (B : Rat) {eps : Rat} (eps>0 : eps > 0) : L B || Given (a : L) (U (a + eps)) => \case L-inh, LU-located {\this} {B} {B + 1} linarith \with {
  | _, byLeft LB => byLeft LB
  | inP (q, Lq), byRight Ur => 
    \let | m r q => (r - q) * finv 3
         | LU-less {q} {r} (Lq : L q) (Ur : U r) : q < r => \case LinearOrder.dec<_<= q r \with {
           | inl q<r => q<r
           | inr r<=q => absurd $ LU-disjoint Lq (U_<= Ur r<=q)
         }
         | r => B + 1
    \in \case focus-iter (ratio 3 2) rat_<=-dec (\lam q r => \Sigma (L q) (U r))
    (\lam q r (Lq, Ur) => (\case LU-located (linarith (usingOnly (LU-less Lq Ur))) \with {  | byLeft Lq+m => inP (q + m r q, r, (Lq+m, Ur), linarith)
    | byRight Ur-m => inP (q, r - m r q, (Lq, Ur-m), linarith)})) (iabs $ rat_ceiling $ finv eps * (r - q)) q r (Lq, Ur)
   \with {
          | inP (q', r', (Lq', Ur'), p) => byRight (q', Lq',  U-closed Ur'  (  \have | r-q>0 {q} {r} (Lq : L q) (Ur : U r) : 0 < r - q => linarith (usingOnly (LU-less Lq Ur))
                  | pr>0 => RatField.<_*_positive_positive (RatField.finv>0 eps>0) (r-q>0 Lq Ur)        | c>0 => fromInt_<.conv $ pr>0 <∘l rat_ceiling>=id
                  | s : (r' - q') * (finv eps * (r - q)) < r - q =>
                    <_*_positive-right (r-q>0 Lq' Ur') (rat_ceiling>=id <∘r fromInt_<= (=_<= $ inv $ iabs.ofPos $ LinearOrder.<_<= c>0) <∘r pow>id _) <∘l p
                  | t => transport (_ <) (pmap (_ *) RatField.finv_* *> inv *-assoc *> pmap (* _) (finv-right $ RatField.>_/= $ r-q>0 Lq Ur) *> ide-left *> RatField.finv_finv) 
                        (RatField.<_rotate-right pr>0 s)  \in linarith (usingOnly t)))
        }
}

\lemma LU-less {q r : Rat} (Lq : L q) (Ur : U r) : q < r => {?hidden_proof}
}
\where {
  \use \coerce fromRat (x : Rat) : InfReal \cowith
    | LowerReal => LowerReal.fromRat x
    | ExUpperReal => ExUpperReal.fromRat x
    | LU-disjoint => {?hidden_proof}
    | LU-focus-bound => {?hidden_proof}

  \lemma pow>id (n : Nat) : Monoid.pow (ratio 3 2) n > n => {?hidden_proof}

  \lemma focus-iter (rat : Rat) (rat>=0 : 0 <= rat) (P : Rat -> Rat -> \Prop) (f : \Pi (q r : Rat) -> P q r -> ∃ (q' r' : P) ((r' - q') * rat <= r - q)) (n : Nat) 
  (q r : Rat) (Pqr : P q r) : ∃ (q' r' : P) ((r' - q') * Monoid.pow rat n <= r - q) => {?hidden_proof}

  \lemma real-ext {x y : InfReal} (p : \Pi {a : Rat} -> x.L a <-> y.L a) : x = y => {?hidden_proof}

  \lemma real-lower-ext {x y : InfReal} (p : x = {LowerReal} y) : x = y => {?hidden_proof}
}


\instance InfRealAbMonoid : LinearlyBiorderedAbMonoid InfReal 
  | zro => InfReal.fromRat 0
  | + => +
  | zro-left => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | < => <
  | <-irreflexive => {?hidden_proof}
  | <-transitive => {?hidden_proof}
  | meet => meet
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | join => join
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  | <-comparison => {?hidden_proof}
  | <-connectedness => {?hidden_proof}
  | <=_+ => {?hidden_proof}
  | meet_+-left => {?hidden_proof}
  | join_+-left => {?hidden_proof}
\where {
  \sfunc \infixl 6 + (x y : InfReal) : InfReal \cowith
    | LowerReal => x LowerRealAbMonoid.+ y
    | ExUpperReal => x ExUpperReal.+ y
    | LU-disjoint => {?hidden_proof}
    | LU-focus-bound => {?hidden_proof}

  \lemma +-lower {x y : InfReal} : x + y = {LowerReal} x LowerRealAbMonoid.+ y => {?hidden_proof}

  \lemma +-rat {x y : Rat} : InfReal.fromRat x + InfReal.fromRat y = InfReal.fromRat (x RatField.+ y) => {?hidden_proof}

  \lemma +_L {x y : InfReal} {a : Rat} : InfReal.L {x + y} a <-> ∃ (b : x.L) (c : y.L) (a RatField.< b RatField.+ c) => {?hidden_proof}

  \lemma +_L_<= {x y : InfReal} {a b : Rat} (b<x : x.L b) {c : Rat} (c<y : y.L c) (a<=b+c : a RatField.<= b RatField.+ c) : InfReal.L {x + y} a => {?hidden_proof}

  \lemma +-upper {x y : InfReal} : x + y = x ExUpperReal.+ y => {?hidden_proof}

  \lemma +_U {x y : InfReal} {a : Rat} : InfReal.U {x + y} a <-> ∃ (b : x.U) (c : y.U) (b RatField.+ c RatField.< a) => {?hidden_proof}

  \lemma +_U_<= {x y : InfReal} {a b : Rat} (x<b : x.U b) {c : Rat} (y<c : y.U c) (b+c<=a : b RatField.+ c RatField.<= a) : InfReal.U {x + y} a => {?hidden_proof}

  \type \infix 4 < (x y : InfReal) => ∃ (a : Rat) (x.U a) (y.L a)

  \lemma <=_L {x y : InfReal} : Not (y < x) <-> ∀ {a : x.L} (y.L a) => {?hidden_proof}

  \lemma <=_U {x y : InfReal} : Not (y < x) <-> ∀ {b : y.U} (x.U b) => {?hidden_proof}

  \sfunc meet (x y : InfReal) : InfReal \cowith
    | LowerReal => LowerRealAbMonoid.meet x y
    | ExUpperReal => ExUpperReal.meet x y
    | LU-disjoint => {?hidden_proof}
    | LU-located => {?hidden_proof}

  \lemma meet-lower {x y : InfReal} : meet x y = {LowerReal} LowerRealAbMonoid.meet x y => {?hidden_proof}

  \lemma meet_L {x y : InfReal} {a : Rat} : InfReal.L {meet x y} a <-> (\Sigma (x.L a) (y.L a)) => {?hidden_proof}

  \lemma meet_U {x y : InfReal} {a : Rat} : InfReal.U {meet x y} a <-> x.U a || y.U a => {?hidden_proof}

  \sfunc join (x y : InfReal) : InfReal \cowith
    | LowerReal => LowerRealAbMonoid.join x y
    | ExUpperReal => ExUpperReal.join x y
    | LU-disjoint => {?hidden_proof}
    | LU-located => {?hidden_proof}

  \lemma join-lower {x y : InfReal} : join x y = {LowerReal} LowerRealAbMonoid.join x y => {?hidden_proof}

  \lemma join_L {x y : InfReal} {a : Rat} : InfReal.L {join x y} a <-> x.L a || y.L a => {?hidden_proof}

  \lemma join_U {x y : InfReal} {a : Rat} : InfReal.U {join x y} a <-> (\Sigma (x.U a) (y.U a)) => {?hidden_proof}

  \lemma zro<ide : InfReal.fromRat 0 < InfReal.fromRat 1 => {?hidden_proof}

  \lemma <_L {a : Rat} {x : InfReal} : (a : InfReal) < x <-> x.L a => {?hidden_proof}

  \lemma <_U {a : Rat} {x : InfReal} : x < a <-> x.U a => {?hidden_proof}

  \lemma <_+ {a b c d : InfReal} (p : a < c) (q : b < d) : a + b < c + d => {?hidden_proof}
}


\lemma inf-real_<_LowerReal {x y : InfReal} : x < y <-> x LowerRealAbMonoid.< y => {?hidden_proof}