\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Equiv
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.Unique
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Order.Elem
\import Paths
\import Paths.Meta
\import Set
\import Set.Subset
\import Topology.Elem
\import Topology.MetricSpace
\import Topology.NormedAbGroup.Real
\import Topology.TopSpace
\open IntervalSubset

\func IntervalSubset  => \Sigma (U : Set Real) (a b : Real) (a < b) (\Pi {x : Real} -> a <= x -> x <= b -> U x)
  \where {
    \func left (S : IntervalSubset) : Elem S.1 => (S.2, S.5 <=-refl (<=-less S.4))

    \func right (S : IntervalSubset) : Elem S.1 => (S.3, S.5 (<=-less S.4) <=-refl)

    \func inside (S : IntervalSubset) : Set Real => \lam x => \Sigma (S.2 <= x) (x <= S.3)
  }


\lemma IVT-monotone {S : IntervalSubset} (f : Elem S.1 -> Real) (fm : IsStrictlyMonotone f) (fc : IsCont f) (y : Real) (fa<=y : f (left S) <= y) 
(y<=fb : y <= f (right S)) : Contr (\Sigma (x : Elem S.1) (f x = y)) => {?hidden_proof}
  \where {
    \func point (fm : IsStrictlyMonotone f) : Real \cowith
      | L => \lam q => ∃ (x : Real) (x.L q) (p1 : S.2 <= x) (p2 : x <= S.3) (f (x, S.5 p1 p2) <= y)
      | L-inh => {?hidden_proof}
      | L-closed => {?hidden_proof}
      | L-rounded => {?hidden_proof}
      | U => \lam r => ∃ (x : Real) (x.U r) (p1 : S.2 <= x) (p2 : x <= S.3) (y <= f (x, S.5 p1 p2))
      | U-inh => {?hidden_proof}
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}
      | LU-disjoint => {?hidden_proof}
      | LU-located => {?hidden_proof}

    \lemma point>=left (fm : IsStrictlyMonotone f) : S.2 <= point fm => {?hidden_proof}

    \lemma point<=right (fm : IsStrictlyMonotone f) : point fm <= S.3 => {?hidden_proof}

    \lemma point<-char (fm : IsStrictlyMonotone f) {x : Real} : x < point fm <-> ∃ (x' : Real) (x < x') (p : S.2 <= x') (q : x' <= S.3) (f (x', S.5 p q) <= y) => {?hidden_proof}

    \lemma point>-char (fm : IsStrictlyMonotone f) {x : Real} : point fm < x <-> ∃ (x' : Real) (x' < x) (p : S.2 <= x') (q : x' <= S.3) (y <= f (x', S.5 p q)) => {?hidden_proof}

    \func elem (fm : IsStrictlyMonotone f) : Elem S.1 => (point fm, S.5 (point>=left fm) (point<=right fm))

    \lemma point<-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<=x : S.2 <= x) (x<b : x < S.3) (fc : IsContAt f (x, S.5 a<=x (<=-less x<b))) 
    (fx<y : f (x, S.5 a<=x (<=-less x<b)) < y) : x < point fm => {?hidden_proof}

    \lemma point>-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<x : S.2 < x) (x<=b : x <= S.3) (fc : IsContAt f (x, S.5 (<=-less a<x) x<=b)) 
    (fx<y : y < f (x, S.5 (<=-less a<x) x<=b)) : point fm < x => {?hidden_proof}

    \lemma point>=-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<=x : S.2 <= x) (x<=b : x <= S.3) (fc : IsContAt f (x, S.5 a<=x x<=b)) (p<=x : point fm <= x) : y <= f (x, S.5 a<=x x<=b) 
      => {?hidden_proof}

    \lemma point<=-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<=x : S.2 <= x) (x<=b : x <= S.3) (fc : IsContAt f (x, S.5 a<=x x<=b)) (x<=p : x <= point fm) : f (x, S.5 a<=x x<=b) <= y 
      => {?hidden_proof}

    \lemma image (fm : IsStrictlyMonotone f) (fc : IsContAt f (elem fm)) : f (elem fm) = y => {?hidden_proof}
  }


\lemma monotone-inverse {U V : Set Real} (f : Elem U -> Real) (fm : IsStrictlyMonotone f) (fc : IsCont f) (fV : \Pi (x : Elem U) -> V (f x))
  (fU : ∀ {v : V} ∃ (a b : Real) (p : a < b) (q : (\Pi {x : Real} -> a <= x -> x <= b -> U x)) (f (a, q <=-refl (<=-less p)) <= v) 
  (v <= f (b, q (<=-less p) <=-refl))) : Equiv {Elem U} {Elem V} (\lam u => (f u, fV u)) => {?hidden_proof}

\lemma real-cont_<-inv {f : Real -> Real} {x y : Real} (fc : IsContAt f x) (fx<fy : f x < f y) : x < y || y < x => {?hidden_proof}

\lemma real-cont_<-inv-mono {f : Real -> Real} {x y : Real} (fm : y < x -> f y <= f x) (fc : IsContAt f x) (fx<fy : f x < f y) : x < y => {?hidden_proof}