\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Semiring
\import Arith.Rat
\import Arith.Real
\import Arith.Real.Field
\import Equiv
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.Unique
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Order.Elem
\import Paths
\import Paths.Meta
\import Set
\import Set.Subset
\import Topology.Elem
\import Topology.MetricSpace
\import Topology.NormedAbGroup.Real
\import Topology.TopSpace
\open IntervalSubset

\func IntervalSubset  => \Sigma (U : Set Real) (a b : Real) (a < b) (\Pi {x : Real} -> a <= x -> x <= b -> U x)
  \where {
    \func left (S : IntervalSubset) : Elem S.1 => (S.2, S.5 <=-refl (<=-less S.4))

    \func right (S : IntervalSubset) : Elem S.1 => (S.3, S.5 (<=-less S.4) <=-refl)

    \func inside (S : IntervalSubset) : Set Real => \lam x => \Sigma (S.2 <= x) (x <= S.3)
  }


\lemma IVT-monotone {S : IntervalSubset} (f : Elem S.1 -> Real) (fm : IsStrictlyMonotone f) (fc : IsCont f) (y : Real) (fa<=y : f (left S) <= y) 
(y<=fb : y <= f (right S)) : Contr (\Sigma (x : Elem S.1) (f x = y)) => {?hidden_proof}
  \where {
    \func point (fm : IsStrictlyMonotone f) : Real \cowith
      | L => \lam q => ∃ (x : Real) (x.L q) (p1 : S.2 <= x) (p2 : x <= S.3) (f (x, S.5 p1 p2) <= y)
      | L-inh => \case S.2.L-inh \with {
        | inP (q, q<a) => inP (q, inP (S.2, q<a, <=-refl, <=-less S.4, fa<=y))
      }
    | L-closed => \lam inP (x, q<x, a<=x, x<=b, fx<=y) q'<q => inP (x, x.L-closed q<x q'<q, a<=x, x<=b, fx<=y)
    | L-rounded => \lam inP (x, q<x, a<=x, x<=b, fx<=y) => (\case x.L-rounded q<x \with {
      | inP (r, r<x, q<r) => inP (r, inP (x, r<x, a<=x, x<=b, fx<=y), q<r)
    })
    | U => \lam r => ∃ (x : Real) (x.U r) (p1 : S.2 <= x) (p2 : x <= S.3) (y <= f (x, S.5 p1 p2))
    | U-inh => \case S.3.U-inh \with {
      | inP (r, b<r) => inP (r, inP (S.3, b<r, <=-less S.4, <=-refl, y<=fb))
    }
    | U-closed => \lam inP (x, x<q, a<=x, x<=b, y<=fx) q<q' => inP (x, x.U-closed x<q q<q', a<=x, x<=b, y<=fx)
    | U-rounded => \lam inP (x, x<q, a<=x, x<=b, y<=fx) => (\case x.U-rounded x<q \with {
      | inP (r, x<r, r<q) => inP (r, inP (x, x<r, a<=x, x<=b, y<=fx), r<q)
    })
    | LU-disjoint => \lam {q} inP (x1, q<x1, _, _, fx1<=y) inP (x2, x2<q, _, _, y<=fx2) => fx1<=y <=∘ y<=fx2 $ fm $ real_<-rat-char.2 $ inP (q, x2<q, q<x1)
    | LU-located => \lam {q} {r} q<r => (
      \let | q1 => (2 * q + r) * ratio 1 3
           | r1 => (q + 2 * r) * ratio 1 3
           | q<q1 : Real.fromRat q < q1 => real_<_L.2 linarith
           | r1<r : Real.fromRat r1 < r => real_<_L.2 linarith
           | q1<r1 : Real.fromRat q1 < r1 => real_<_L.2 linarith
      \in \case real-located {S.2} q1<r1, real-located {S.3} q1<r1 \with {
            | byLeft q1<a, _ => byLeft $ inP (S.2, real_<_L.1 $ q<q1 <∘ q1<a, <=-refl, <=-less S.4, fa<=y)
            | _, byRight b<r1 => byRight $ inP (S.3, real_<_U.1 $ b<r1 <∘ r1<r, <=-less S.4, <=-refl, y<=fb)
            | byRight a<r1, byLeft q1<b => 
              \let | q2 => Real.fromRat q1 ∨ S.2
                   | r2 => Real.fromRat r1 ∧ S.3
                   | q2<=b => <=-less (<_join-univ q1<b S.4)
                   | a<=r2 => <=-less (<_meet-univ a<r1 S.4)
                   | q2<r2 => <_meet-univ (<_join-univ q1<r1 a<r1) (<_join-univ q1<b S.4)
              \in \case real-located {y} (fm {(q2, S.5 join-right q2<=b)} {(r2, S.5 a<=r2 meet-right)} q2<r2) \with {
                    | byLeft fq2<y => byLeft $ inP (q2, real_<_L.1 $ q<q1 <∘l RealAbGroup.join-left, join-right, q2<=b, <=-less fq2<y)
                    | byRight y<fr2 => byRight $ inP (r2, real_<_U.1 $ meet-left <∘r r1<r, a<=r2, meet-right, <=-less y<fr2)
                  }
          })

    \lemma point>=left (fm : IsStrictlyMonotone f) : S.2 <= point fm => {?hidden_proof}

    \lemma point<=right (fm : IsStrictlyMonotone f) : point fm <= S.3 => {?hidden_proof}

    \lemma point<-char (fm : IsStrictlyMonotone f) {x : Real} : x < point fm <-> ∃ (x' : Real) (x < x') (p : S.2 <= x') (q : x' <= S.3) (f (x', S.5 p q) <= y) => {?hidden_proof}

    \lemma point>-char (fm : IsStrictlyMonotone f) {x : Real} : point fm < x <-> ∃ (x' : Real) (x' < x) (p : S.2 <= x') (q : x' <= S.3) (y <= f (x', S.5 p q)) => {?hidden_proof}

    \func elem (fm : IsStrictlyMonotone f) : Elem S.1 => (point fm, S.5 (point>=left fm) (point<=right fm))

    \lemma point<-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<=x : S.2 <= x) (x<b : x < S.3) (fc : IsContAt f (x, S.5 a<=x (<=-less x<b))) 
    (fx<y : f (x, S.5 a<=x (<=-less x<b)) < y) : x < point fm => {?hidden_proof}

    \lemma point>-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<x : S.2 < x) (x<=b : x <= S.3) (fc : IsContAt f (x, S.5 (<=-less a<x) x<=b)) 
    (fx<y : y < f (x, S.5 (<=-less a<x) x<=b)) : point fm < x => {?hidden_proof}

    \lemma point>=-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<=x : S.2 <= x) (x<=b : x <= S.3) (fc : IsContAt f (x, S.5 a<=x x<=b)) (p<=x : point fm <= x) : y <= f (x, S.5 a<=x x<=b) 
      => {?hidden_proof}

    \lemma point<=-cont-char (fm : IsStrictlyMonotone f) {x : Real} (a<=x : S.2 <= x) (x<=b : x <= S.3) (fc : IsContAt f (x, S.5 a<=x x<=b)) (x<=p : x <= point fm) : f (x, S.5 a<=x x<=b) <= y 
      => {?hidden_proof}

    \lemma image (fm : IsStrictlyMonotone f) (fc : IsContAt f (elem fm)) : f (elem fm) = y => {?hidden_proof}
  }


\lemma monotone-inverse {U V : Set Real} (f : Elem U -> Real) (fm : IsStrictlyMonotone f) (fc : IsCont f) (fV : \Pi (x : Elem U) -> V (f x))
  (fU : ∀ {v : V} ∃ (a b : Real) (p : a < b) (q : (\Pi {x : Real} -> a <= x -> x <= b -> U x)) (f (a, q <=-refl (<=-less p)) <= v) 
  (v <= f (b, q (<=-less p) <=-refl))) : Equiv {Elem U} {Elem V} (\lam u => (f u, fV u)) => {?hidden_proof}

\lemma real-cont_<-inv {f : Real -> Real} {x y : Real} (fc : IsContAt f x) (fx<fy : f x < f y) : x < y || y < x => {?hidden_proof}

\lemma real-cont_<-inv-mono {f : Real -> Real} {x y : Real} (fm : y < x -> f y <= f x) (fc : IsContAt f x) (fx<fy : f x < f y) : x < y => {?hidden_proof}