\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Ordered
\import Algebra.StrictlyOrdered
\import Algebra.Pointed
\import Arith.Int
\import Arith.Nat
\import Arith.Rat
\import Data.Or
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.LinearOrder
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths
\import Paths.Meta
\import Set

\record ExUpperReal (U : Rat -> \Prop) {
  | U-closed {q q' : Rat} : U q -> q < q' -> U q'
  | U-rounded {q : Rat} : U q -> ∃ (r : U) (r < q)

  \lemma U_<= {q r : Rat} (Uq : U q) (p : q RatField.<= r) : U r => {?hidden_proof}

  \func IsBounded : \Prop => ∃ U
}
  \where {
    \use \coerce fromRat (x : Rat) : ExUpperReal \cowith
      | U => x <
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}

    \lemma fromRat-inj {x y : Rat} (p : fromRat x = fromRat y) : x = y => {?hidden_proof}

    \sfunc \infixl 6 + (x y : ExUpperReal) : ExUpperReal \cowith
      | U => \lam a => ∃ (b : x.U) (c : y.U) (b RatField.+ c RatField.< a)
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}

    \lemma +_U {x y : ExUpperReal} {a : Rat} : UpperReal.U {x + y} a <-> ∃ (b : x.U) (c : y.U) (b RatField.+ c RatField.< a) => {?hidden_proof}

    \lemma +_U_<= {x y : ExUpperReal} {a : Rat} : UpperReal.U {x + y} a <-> ∃ (b : x.U) (c : y.U) (b RatField.+ c RatField.<= a) => {?hidden_proof}

    \lemma +-rat {x y : Rat} : fromRat x + fromRat y = fromRat (x RatField.+ y) => {?hidden_proof}

    \type \infix 4 <= (x y : ExUpperReal) => ∀ {b : y.U} (x.U b)

    \lemma <=_+-char {x y z : ExUpperReal} {a b : Rat} (x<=y+z : x <= y + z) (y<a : y.U a) (z<b : z.U b) : x.U (a RatField.+ b) => {?hidden_proof}

    \lemma <=-rat {a b : Rat} : a RatField.<= b <-> a <= b => {?hidden_proof}

    \protected \lemma <_<= {x : ExUpperReal} {q : Rat} (x<q : x.U q) : x <= q => {?hidden_proof}

    \sfunc meet (x y : ExUpperReal) : ExUpperReal \cowith
      | U => \lam a => x.U a || y.U a
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}

    \lemma meet_U {x y : ExUpperReal} {a : Rat} : UpperReal.U {meet x y} a <-> x.U a || y.U a => {?hidden_proof}

    \sfunc join (x y : ExUpperReal) : ExUpperReal \cowith
      | U => \lam a => \Sigma (x.U a) (y.U a)
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}

    \lemma join_U {x y : ExUpperReal} {a : Rat} : UpperReal.U {join x y} a <-> (\Sigma (x.U a) (y.U a)) => {?hidden_proof}

    \lemma join-bounded {x y : ExUpperReal} (xb : x.IsBounded) (yb : y.IsBounded) : (join x y).IsBounded => {?hidden_proof}

    \sfunc \infixl 7 * (x y : ExUpperReal) : ExUpperReal \cowith
      | U => \lam a => ∃ (b : x.U) (0 RatField.< b) (c : y.U) (0 RatField.< c) (b RatField.* c RatField.< a)
      | U-closed => {?hidden_proof}
      | U-rounded => {?hidden_proof}

    \lemma *_U {x y : ExUpperReal} {a : Rat} : UpperReal.U {x * y} a <-> ∃ (b : x.U) (0 RatField.< b) (c : y.U) (0 RatField.< c) (b RatField.* c RatField.< a) => {?hidden_proof}

    \lemma *_U_<= {x y : ExUpperReal} {a : Rat} : UpperReal.U {x * y} a <-> ∃ (b : x.U) (0 RatField.< b) (c : y.U) (0 RatField.< c) (b RatField.* c RatField.<= a) => {?hidden_proof}

    \lemma *_U_< {x y : ExUpperReal} {a : Rat} : UpperReal.U {x * y} a <-> ∃ (b : Rat) (x <= b) (0 RatField.<= b) (c : Rat) (y <= c) (0 RatField.<= c) (b RatField.* c < a) 
      => {?hidden_proof}

    \lemma *-rat {x y : Rat} (x>=0 : 0 RatField.<= x) (y>=0 : 0 RatField.<= y) : fromRat x * fromRat y = fromRat (x RatField.* y) => {?hidden_proof}
  }


\instance ExUpperRealPointed : Pointed ExUpperReal 
  | ide => ExUpperReal.fromRat 1

\lemma real_meet_U {a b : Rat} {x : ExUpperReal} (x<a : x.U a) (x<b : x.U b) : x.U (a ∧ b) => {?hidden_proof}

\instance ExUpperRealAbMonoid : BiorderedLatticeAbMonoid ExUpperReal 
  | zro => ExUpperReal.fromRat 0
  | + => +
  | zro-left => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | <= => <=
  | <=-refl => {?hidden_proof}
  | <=-transitive => {?hidden_proof}
  | <=-antisymmetric => {?hidden_proof}
  | <=_+ => {?hidden_proof}
  | < => <
  | <-irreflexive => {?hidden_proof}
  | <-transitive => {?hidden_proof}
  | <-transitive-right => {?hidden_proof}
  | <-transitive-left => {?hidden_proof}
  | <=-less => {?hidden_proof}
  | meet => meet
  | meet-left => {?hidden_proof}
  | meet-right => {?hidden_proof}
  | meet-univ => {?hidden_proof}
  | join => join
  | join-left => {?hidden_proof}
  | join-right => {?hidden_proof}
  | join-univ => {?hidden_proof}
  | <_meet-univ => {?hidden_proof}
  | <_join-univ => {?hidden_proof}
  | meet_+-left => {?hidden_proof}
  | join_+-left => {?hidden_proof}
  \where {
    \open ExUpperReal

    \type \infix 4 < (x y : ExUpperReal) => ∃ (q : x.U) (q ExUpperReal.<= y)

    \lemma <-rat {x : ExUpperReal} {y : Rat} : x < y <-> x.U y => {?hidden_proof}

    \lemma zro<ide : fromRat 0 < fromRat 1 => {?hidden_proof}

    \lemma <_+ {x y x' y' : ExUpperReal} (x<x' : x < x') (y<y' : y < y') : x + y < x' + y' => {?hidden_proof}

    \lemma <_+-left {x y : ExUpperReal} (x<y : x < y) {z : Rat} : x + z < y + z => {?hidden_proof}

    \lemma <_+-right {x : Rat} {y z : ExUpperReal} (y<z : y < z) : x + y < x + z => {?hidden_proof}

    \lemma <=_+-cancel-left {x y z : ExUpperReal} (xb : x.IsBounded) {q : Rat} (q<=x : q <= x) (p : x + y <= x + z) : y <= z => {?hidden_proof}
      \where {
        \lemma step {eps : Rat} (eps>0 : 0 RatField.< eps) {a : Rat} (x<a : x.U a) {b : Rat} (z<b : z.U b) : x.U (a - eps) || y.U (b RatField.+ eps) => {?hidden_proof}

        \lemma steps {eps : Rat} (eps>0 : 0 RatField.< eps) {a : Rat} (x<a : x.U a) {b : Rat} (z<b : z.U b) (n : Nat) : x.U (a - eps RatField.* n) || y.U (b RatField.+ eps) 
          => {?hidden_proof}
      }


    \lemma <=_+-cancel-right {x y z : ExUpperReal} (zb : z.IsBounded) {q : Rat} (q<=z : q <= z) (p : x + z <= y + z) : x <= y => {?hidden_proof}

    \lemma *n_U {n : Nat} (n/=0 : n /= 0) {x : ExUpperReal} {q : Rat} : (n ExUpperRealAbMonoid.*n x).U q <-> ∃ (r : x.U) (n RatField.* r RatField.<= q) => {?hidden_proof}

    \lemma *n_finv {n : Nat} (n/=0 : n /= 0) {x : ExUpperReal} {q : Rat} : (n ExUpperRealAbMonoid.*n x).U q <-> x.U (RatField.finv n RatField.* q) => {?hidden_proof}
  }


\lemma rat-upperReal : AddMonoidHom RatField ExUpperRealAbMonoid ExUpperReal.fromRat => {?hidden_proof}

\instance ExUpperRealSemigroup : CSemigroup ExUpperReal 
  | * => *
  | *-assoc => {?hidden_proof}
  | *-comm => {?hidden_proof}
  \where {
    \open ExUpperReal

    \protected \lemma ide-left_<= {x : ExUpperReal} : x <= fromRat 1 * x => {?hidden_proof}

    \protected \lemma ide-left {x : ExUpperReal} (x>=0 : 0 <= x) : fromRat 1 * x = x => {?hidden_proof}

    \protected \lemma ide-right {x : ExUpperReal} (x>=0 : 0 <= x) : x * fromRat 1 = x => {?hidden_proof}

    \lemma <=_* {x x' y y' : ExUpperReal} (x<=x' : x <= x') (y<=y' : y <= y') : x * y <= x' * y' => {?hidden_proof}

    \lemma *_join {x y : ExUpperReal} : x * y = join x 0 * join y 0 => {?hidden_proof}

    \lemma <_* {x x' y y' : ExUpperReal} (x>=0 : 0 <= x) (y>=0 : 0 <= y) (x<x' : x < x') (y<y' : y < y') : x * y < x' * y' => {?hidden_proof}

    \lemma <_*_U-left {x : ExUpperReal} {y z : Rat} (x<y : x.U y) (y>0 : 0 RatField.< y) (z>0 : 0 RatField.< z) : (x * z).U (y RatField.* z) => {?hidden_proof}

    \lemma <_*_U-right {x : Rat} (x>0 : 0 RatField.< x) {y : ExUpperReal} {z : Rat} (z>0 : 0 RatField.< z) (y<z : y.U z) : (x * y).U (x RatField.* z) => {?hidden_proof}

    \lemma <_*-left {x y : ExUpperReal} (x<y : x < y) (y>0 : 0 < y) {z : Rat} (z>0 : 0 RatField.< z) : x * z < y * z => {?hidden_proof}

    \lemma <_*-right {x : Rat} (x>0 : 0 RatField.< x) {y z : ExUpperReal} (y<z : y < z) (z>0 : 0 < z) : x * y < x * z => {?hidden_proof}

    \lemma <_*-left' {x y : ExUpperReal} (x<y : x < y) (x>=0 : 0 <= x) {z : Rat} (z>0 : 0 RatField.< z) : x * z < y * z => {?hidden_proof}

    \lemma <_*-right' {x : Rat} (x>0 : 0 RatField.< x) {y z : ExUpperReal} (y<z : y < z) (y>=0 : 0 <= y) : x * y < x * z => {?hidden_proof}

    \lemma *_>=0 {x y : ExUpperReal} : 0 <= x * y => {?hidden_proof}

    \protected \lemma ldistr_<= {x y z : ExUpperReal} : x * (y + z) <= x * y + x * z => {?hidden_proof}

    \protected \lemma rdistr_<= {x y z : ExUpperReal} : (x + y) * z <= x * z + y * z => {?hidden_proof}

    \protected \lemma ldistr {x y z : ExUpperReal} (y>=0 : 0 <= y) (z>=0 : 0 <= z) : x * (y + z) = x * y + x * z => {?hidden_proof}

    \protected \lemma rdistr {x y z : ExUpperReal} (x>=0 : 0 <= x) (y>=0 : 0 <= y) : (x + y) * z = x * z + y * z => {?hidden_proof}

    \protected \lemma zro_*-left {x : ExUpperReal} (xb : x.IsBounded) : 0 * x = 0 => {?hidden_proof}

    \protected \lemma zro_*-right {x : ExUpperReal} (xb : x.IsBounded) : x * 0 = 0 => {?hidden_proof}

    \lemma *n_*_<= {n : Nat} {x : ExUpperReal} (x>=0 : 0 <= x) : n AddMonoid.*n x <= n * x => {?hidden_proof}

    \lemma *n_* {n : Nat} {x : ExUpperReal} (x>=0 : 0 <= x) (xb : x.IsBounded) : n AddMonoid.*n x = n * x => {?hidden_proof}

    \lemma <_*-positive {x y : ExUpperReal} (x>0 : 0 < x) (y>0 : 0 < y) : 0 < x * y => {?hidden_proof}

    \open ExUpperRealAbMonoid

    \sfunc div-lb {a : Rat} {b : ExUpperReal} (a>0 : 0 < a) (b>0 : 0 < b) : \Sigma (c : ExUpperReal) (0 < c) (a * c <= b) 
    => (ExUpperReal.fromRat (RatField.finv a) * b, <_*-positive (<-rat.2 $ RatField.finv>0 $ <-rat.1 a>0) b>0,
          \have a>0 => <-rat.1 a>0  \in =_<= $ inv ExUpperRealSemigroup.*-assoc *> pmap (* b) 
            (ExUpperReal.*-rat (<=-less a>0) (<=-less $ RatField.finv>0 a>0) *> pmap ExUpperReal.fromRat (RatField.finv-right $ RatField.>_/= a>0)) *> 
            ExUpperRealSemigroup.ide-left (<=-less b>0)
    )

    \lemma div-lb-rat {a : Rat} {b : ExUpperReal} (a>0 : 0 < a) (b>0 : 0 < b) : ∃ (c : Rat) (0 RatField.< c) (a * c <= b) => {?hidden_proof}

    \lemma finv_<=-rotate-right {a : Rat} (a>0 : 0 RatField.< a) {b c : ExUpperReal} (p : RatField.finv a * b <= c) : b <= a * c => {?hidden_proof}

    \lemma finv_<-rotate-right {a : Rat} (a>0 : 0 RatField.< a) {b c : ExUpperReal} (p : RatField.finv a * b < c) : b < a * c => {?hidden_proof}

    \lemma finv_<-rotate-left {a : Rat} (a>0 : 0 RatField.< a) {b c : ExUpperReal} (c>0 : 0 < c) (p : b < a * c) : RatField.finv a * b < c => {?hidden_proof}

    \func pow (x : ExUpperReal) (n : Nat) : ExUpperReal \elim n
      | 0 => 1
      | suc n => pow x n * x

    \lemma rat-pow {x : Rat} (x>=0 : 0 RatField.<= x) {n : Nat} : pow x n = ExUpperReal.fromRat (RatField.pow x n) => {?hidden_proof}

    \lemma pow_<= {x y : ExUpperReal} (x<=y : x <= y) {n : Nat} : pow x n <= pow y n => {?hidden_proof}

    \lemma pow_>=0 {x : ExUpperReal} {n : Nat} : 0 <= pow x n => {?hidden_proof}

    \lemma square_<= {x : ExUpperReal} {q : Rat} (q>=0 : 0 RatField.<= q) (xx<=qq : x * x <= q RatField.* q) : x <= q => {?hidden_proof}

    \lemma square<=1 {x : ExUpperReal} (xx<=1 : x * x <= 1) : x <= 1 => {?hidden_proof}

    \lemma square-bound-div {x : ExUpperReal} (xb : x.IsBounded) {q : Rat} (q>=0 : 0 RatField.<= q) (xx<=qx : x * x <= q * x) : x <= q => {?hidden_proof}
      \where {
        \lemma step {e : Rat} (e>=0 : 0 RatField.<= e) (x<=q+e : x <= q RatField.+ e) : x <= q RatField.+ e RatField.* ratio 1 2 => {?hidden_proof}

        \lemma aux {e : Rat} (e>=0 : 0 RatField.<= e) (x<=q+e : x <= q RatField.+ e) (n : Nat) : x <= q RatField.+ e RatField.* RatField.pow (ratio 1 2) n => {?hidden_proof}
      }


    \lemma *n-bounded {n : Nat} {x : ExUpperReal} (xb : x.IsBounded) : (n ExUpperRealAbMonoid.*n x).IsBounded => {?hidden_proof}
  }


\record UpperReal \extends ExUpperReal {
  | U-inh : ∃ U

  \lemma natBounded : ∃ (n : Nat) (U n) => {?hidden_proof}

  \lemma U-inh_>0 : ∃ (q : U) (0 < q) => {?hidden_proof}

  \type IsLocated : \Prop => \Pi {a b : Rat} -> a < b -> ∀ {c : U} (a < c) || U b
}
  \where {
    \use \coerce fromRat (x : Rat) : UpperReal \cowith
      | ExUpperReal => ExUpperReal.fromRat x
      | U-inh => {?hidden_proof}

    \lemma ex-ext {x y : UpperReal} (p : x = {ExUpperReal} y) : x = y => {?hidden_proof}
  }


\instance UpperRealSemigroup : CSemigroup UpperReal 
  | * => *
  | *-assoc => {?hidden_proof}
  | *-comm => {?hidden_proof}
  \where {
    \sfunc \infixl 7 * (x y : UpperReal) : UpperReal \cowith
      | ExUpperReal => \eval x ExUpperReal.* y
      | U-inh => {?hidden_proof}

    \lemma *_U {x y : UpperReal} {a : Rat} : UpperReal.U {x * y} a <-> ∃ (b : x.U) (0 RatField.< b) (c : y.U) (0 RatField.< c) (b RatField.* c RatField.< a) => {?hidden_proof}

    \lemma *-ex {x y : UpperReal} : x * y = x ExUpperReal.* y => {?hidden_proof}
  }
