\import Algebra.Monoid
\import Arith.Int
\import Arith.Nat
\import Arith.Rat
\import Arith.Real.Root
\import Arith.Real.UpperReal
\import Data.Bool
\import Function.Meta
\import Logic
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.Lattice
\import Order.PartialOrder
\import Order.StrictOrder
\import Paths

\instance ExUpperRealLattice : CompleteLattice ExUpperReal 
  | Order.Lattice.Lattice => ExUpperRealAbMonoid
  | Meet {J : \Set} (g : J -> ExUpperReal) : ExUpperReal 
    | U => \lam q => ∃ (j : J) ((g j).U q)
    | U-closed => \lam inP (j, gj<q) q<q' => inP (j, U-closed gj<q q<q')
    | U-rounded => \lam inP (j, gj<q) => (\case U-rounded gj<q \with {
      | inP (r, gj<r, r<q) => inP (r, inP (j, gj<r), r<q)
    })
  | Meet-cond => {?hidden_proof}
  | Meet-univ => {?hidden_proof}
  | Join {J : \Set} (g : J -> ExUpperReal) : ExUpperReal 
    | U => \lam q => ∃ (r : < q) ∀ (j : J) ((g j).U r)
    | U-closed => \lam inP (r, r<q, c) q<q' => inP (r, r<q <∘ q<q', c)
    | U-rounded => \lam {q} inP (r, r<q, c) => inP (RatField.mid r q, inP (r, RatField.mid>left r<q, c), RatField.mid<right r<q)
  | Join-cond => {?hidden_proof}
  | Join-univ => {?hidden_proof}
  \where {
    \lemma *n_Join {n : Nat} (n/=0 : n /= 0) {J : \Set} {g : J -> ExUpperReal} : n AddMonoid.*n Join g = Join (\lam j => n AddMonoid.*n g j) => {?hidden_proof}

    \lemma *n_Join' {n : Nat} {J : \Set} (j : ∃ J) {g : J -> ExUpperReal} : n AddMonoid.*n Join g = Join (\lam j => n AddMonoid.*n g j) => {?hidden_proof}

    \lemma +_Join {J : \Set} {g : J -> ExUpperReal} : Join g + Join g = Join (\lam j => g j + g j) => {?hidden_proof}

    \lemma *n_join {n : Nat} {x y : ExUpperReal} : n AddMonoid.*n (x ∨ y) = n AddMonoid.*n x ∨ n AddMonoid.*n y => {?hidden_proof}

    \lemma +_join {x y : ExUpperReal} : (x ∨ y) + (x ∨ y) = (x + x) ∨ (y + y) => {?hidden_proof}

    \lemma Join-square {J : \Set} (j : ∃ J) {g : J -> ExUpperReal} : Join g * Join g = Join (\lam j => g j * g j) => {?hidden_proof}

    \lemma join-square {x y : ExUpperReal} : (x ∨ y) * (x ∨ y) = x * x ∨ y * y => {?hidden_proof}
  }
