\import Algebra.Domain.Euclidean
\import Algebra.Domain.GCD
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Algebra.Ring.Local
\import Data.Or
\import Equiv
\import Function.Meta ($)
\import Logic
\import Meta
\import Paths
\import Paths.Meta
\import Set
\open Monoid (Inv)

\class Field \extends LocalCRing, GCDDomain {
  | #0 => \lam x => Inv x
  | #0-+ => LocalRing.sumInv=>eitherInv
  | #0-zro => \lam (j : Inv zro) => zro/=ide (inv zro_*-right *> j.inv-left)
  | #0-*-left => Inv.cfactor-left
  | zro#ide => Inv.lmake ide ide-left
  | #0-* => \lam xj yj => Inv.product xj yj
  | isGCDDomain => \lam x y x#0 y#0 =>
  inP (\new GCD {  | res => 1  | res|val1 => \new Monoid.LDiv {    | inv => x    | inv-right => ide-left  }  | res|val2 => \new Monoid.LDiv {    | inv => y
      | inv-right => ide-left  }  | res-univ => \lam g g|x g|y => \new Monoid.LDiv {    | inv => Monoid.LDiv.inv {g|x} * Inv.inv {x#0}
      | inv-right => inv *-assoc *> pmap (* _) Monoid.LDiv.inv-right *> Inv.inv-right  }})
}

\class DiscreteField \extends Field, EuclideanDomain {
  | finv : E -> E
  | finv_zro : finv 0 = 0
  | finv-right {x : E} (x/=0 : x /= 0) : x * finv x = 1
  \field eitherZeroOrInv (x : E) : (x = 0) || Inv x
  | isEuclidean => inP (\new EuclideanRingData {  | euclideanMap => \lam x => 0  | divMod => \lam x y => (\case decideEq y 0 \with {    | yes _ => (0, x)
      | no _ => (finv y * x, 0)  })  | isDivMod => \lam x y => mcases  | isEuclideanMap => \lam x y y/=0 => mcases {1}})
  | finv => finv-impl
  | finv_zro => finv_zroImpl
  | finv-right => id_finvImpl
  | eitherZeroOrInv => \lam x => (\case decideEq x 0 \with {
    | yes x=0 => byLeft x=0
    | no x/=0 => byRight (Inv.rmake (finv x) (finv-right x/=0))
  })
  | locality => \lam x => (\case eitherZeroOrInv x \with {
    | byLeft x=0 => byRight $ Inv.lmake ide (equation.semiring {x=0})
    | byRight xInv => byLeft xInv
  })
  | decideEq => \lam x y => (\case eitherZeroOrInv (x - y) \with {
    | byLeft x-y=0 => yes (fromZero x-y=0)
    | byRight x-y-isInv => no (\lam x=y => #-irreflexive (rewrite x=y in x-y-isInv))
  })
  | nonZeroApart => \lam {x} x/=0 => (\case eitherZeroOrInv x \with {
    | byLeft x=0 => absurd (x/=0 x=0)
    | byRight x#0 => x#0
  })

  \protected \default finv-impl x => \case aux zro/=ide x (eitherZeroOrInv x) \with {
    | inl _ => 0
    | inr j : Inv => j.inv
  }

  \protected \default finv_zroImpl : finv-impl 0 = 0 => unfold finv-impl mcases

  \protected \default id_finvImpl {x} x/=0 : x * finv-impl x = 1 => unfold finv-impl mcases

  \lemma finv-left {x : E} (x/=0 : x /= 0) : finv x * x = 1 => {?hidden_proof}

  \lemma finv-Inv {x : E} (x/=0 : x /= 0) : Inv (finv x) x => {?hidden_proof}

  \lemma nonZero-Inv {x : E} (x/=0 : x /= 0) : Inv x (finv x) => {?hidden_proof}

  \lemma finv/=0 {x : E} (x/=0 : x /= 0) : finv x /= 0 => {?hidden_proof}

  \lemma finv_ide : finv ide = ide => {?hidden_proof}

  \lemma finv_* {x y : E} : finv (x * y) = finv y * finv x => {?hidden_proof}

  \lemma finv_pow {x : E} {n : Nat} : finv (pow x n) = pow (finv x) n => {?hidden_proof}

  \lemma finv_finv {x : E} : finv (finv x) = x => {?hidden_proof}

  \lemma zeroDimensional : IsZeroDimensional => {?hidden_proof}

  \lemma decideZeroOrInv (x : E) : (x = 0) `Or` Inv x => {?hidden_proof}

  \lemma finv-diff {x : E} (xi : x /= 0) (x+1i : x + 1 /= 0) : finv x - finv (x + 1) = finv (x * (x + 1)) => {?hidden_proof}

  \lemma finv-square {x : E} (xs : IsSquare x) : IsSquare (finv x) => {?hidden_proof}
}
  \where {
    \lemma aux {R : CRing} (p : R.zro /= R.ide) (x : R) (q : (x = 0) || Inv x) :
      \level ((x = 0) `Or` Inv x) (Or.levelProp (\lam x=0 (j : Inv x) => p $ inv R.zro_*-left *> pmap (* _) (inv x=0) *> j.inv-right)) => {?hidden_proof}

    \func backwards (f : RingHom) (e : Equiv f) (D : DiscreteField {  | Ring => f.Cod}) : DiscreteField {
      | Ring => f.Dom
    } \cowith
      | *-comm => {?hidden_proof}
      | zro/=ide => {?hidden_proof}
      | eitherZeroOrInv => {?hidden_proof}

    \func forward {f : RingHom} (e : Equiv f) (D : DiscreteField {  | Ring => f.Dom}) : DiscreteField {
      | Ring => f.Cod
    } => backwards (\new (RingHom f.Cod f.Dom e.ret) {  | func-+ => e.isInj $ e.f_ret _ *> inv (f.func-+ *> pmap2 + (e.f_ret _) (e.f_ret _))
      | func-ide => e.isInj $ e.f_ret _ *> inv f.func-ide  | func-* => e.isInj $ e.f_ret _ *> inv (f.func-* *> pmap2 * (e.f_ret _) (e.f_ret _))}) 
    (symQEquiv e) D
  }
