\import Algebra.Group
\import Algebra.Monoid
\import Algebra.Pointed
\import Data.Array
\import Function.Meta ($)
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set
\import Set.SetHom
\import Set.Fin

\record FinSuppFunc \extends SetHom {
  \override Cod : AddPointed
  | fSupp : ∃ (s : Array Dom) ∀ i ((\Pi (j : Fin s.len) -> s j /= i) -> func i = 0)
}

\instance FinSuppFuncDec (M : DecSet) (R : AddPointed) {D : DecSet R} : DecSet (FinSuppFunc M R) 
  | decideEq => {?hidden_proof}

\instance FinSuppFuncAddPointed {A : BaseSet} {B : AddPointed} : AddPointed (FinSuppFunc A B) 
  | zro => \new FinSuppFunc {
    | func => \lam _ => 0
    | fSupp => inP (nil, \lam _ _ => idp)
  }

\instance FinSuppFuncAddMonoid {A : BaseSet} {B : AddMonoid} : AddMonoid (FinSuppFunc A B) 
  | AddPointed => FinSuppFuncAddPointed
  | + => \lam f g => \new FinSuppFunc {
    | func => \lam a => f a + g a
    | fSupp => \case fSupp {f}, fSupp {g} \with {
      | inP (s, c), inP (s', c') => inP (s ++ s',  \lam a d =>
        pmap2 + (c a (\lam j => rewrite ++.++_index-left in d (++.index-left j))) (c' a (\lam j => rewrite ++.++_index-right in d (++.index-right j))) *> zro-left
      )
    }
  }
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}

\instance FinSuppFuncAbMonoid {A : BaseSet} {B : AbMonoid} : AbMonoid (FinSuppFunc A B) 
  | AddMonoid => FinSuppFuncAddMonoid
  | +-comm => {?hidden_proof}

\instance FinSuppFuncAddGroup {A : BaseSet} {B : AddGroup} : AddGroup (FinSuppFunc A B) 
  | AddMonoid => FinSuppFuncAddMonoid
  | negative => \lam f => \new FinSuppFunc {
    | func => \lam a => negative (f a)
    | fSupp => TruncP.map (fSupp {f}) (\lam c => (c.1, \lam a d => pmap negative (c.2 a d) *> B.negative_zro))
  }
  | negative-left => {?hidden_proof}
  | negative-right => {?hidden_proof}

\instance FinSuppFuncAbGroup {A : BaseSet} {B : AbGroup} : AbGroup (FinSuppFunc A B) 
  | AddGroup => FinSuppFuncAddGroup
  | +-comm => {?hidden_proof}