\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Arith.Int ()
\import Data.Array
\import Data.Fin
\import Data.Or
\import Equiv
\import Function.Meta ($)
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin

\class Group \extends CancelMonoid {
  | inverse : E -> E
  | inverse-left {x : E} : inverse x * x = ide
  | inverse-right {x : E} : x * inverse x = ide
  | inverse-left => make-inverse-left ide-right inverse inverse-right
  | inverse-right => make-inverse-left {Semigroup.op} ide-left inverse inverse-left
  | ide-left => make-ide-left ide-right inverse inverse-right inverse-left
  | ide-right => make-ide-left {Semigroup.op} ide-left inverse inverse-left inverse-right
  | cancel_*-left => \lam x {y} {z} p =>
  qed (y ==< inv ide-left >== ide * y ==< pmap (* y) (inv inverse-left) >== (inverse x * x) * y ==< *-assoc >== inverse x * (x * y) ==< pmap (inverse x *) p 
    >== inverse x * (x * z) ==< inv *-assoc >== (inverse x * x) * z ==< pmap (* z) inverse-left >== ide * z ==< ide-left >== z)
  | cancel_*-right => \lam z {x} {y} p => qed (x ==< inv ide-right >== x * ide ==< pmap (x *) (inv inverse-right) >== x * (z * inverse z) ==< inv *-assoc >== (x * z) * inverse z ==< pmap 
    (* inverse z) p >== (y * z) * inverse z ==< *-assoc >== y * (z * inverse z) ==< pmap (y *) inverse-right >== y * ide ==< ide-right >== y)

  \func ipow (a : E) (x : Int) : E \elim x
    | pos n => pow a n
    | neg n => pow (inverse a) n

  \lemma ipow_+ {a : E} {x y : Int} : ipow a (x + y) = ipow a x * ipow a y => {?hidden_proof}
    \where {
      \open Arith.Int.IntRing (+, +-comm)

      \lemma ipow_- {a : E} {n m : Nat} : ipow a (n Nat.- m) = pow a n * pow (inverse a) m => {?hidden_proof}
    }


  \lemma ipow_negaitve {a : E} {x : Int} : ipow a (negative x) = inverse (ipow a x) => {?hidden_proof}
    \where {
      \open Arith.Int.IntRing (negative)
    }


  \lemma ipow_* {a : E} {x y : Int} : ipow a (x * y) = ipow (ipow a x) y => {?hidden_proof}
    \where {
      \open Arith.Int.IntRing (*)
    }


  \lemma ipow_ide {x : Int} : ipow ide x = ide => {?hidden_proof}

  \lemma inverse-isInv {x : E} : inverse (inverse x) = x => {?hidden_proof}

  \lemma inverse_ide : inverse ide = ide => {?hidden_proof}

  \lemma inverse_* {x y : E} : inverse (x * y) = inverse y * inverse x => {?hidden_proof}

  \lemma inverse_pow {x : E} {n : Nat} : inverse (pow x n) = pow (inverse x) n => {?hidden_proof}

  \lemma makeInv (a : E) : Inv a (inverse a) => {?hidden_proof}

  \protected \func op : Group \cowith
    | Monoid => Monoid.op
    | inverse => inverse
    | inverse-left => {?hidden_proof}
    | inverse-right => {?hidden_proof}

  \lemma check-for-inv {x y : E} (p : x * y = ide) : y = inverse x => {?hidden_proof}

  \lemma equality-check {g h : E} (p : inverse g * h = ide) : g = h => {?hidden_proof}

  \lemma equality-corrolary (g h : E) (p : g = h) : inverse g * h = ide => {?hidden_proof}
}
  \where {
    \open Monoid (Inv)

    \lemma inverse-equality {X : \Set} (G H : Group X) (z : G.ide = H.ide) (m : \Pi {x y : G} -> x G.* y = x H.* y) (e : G) : G.inverse e = H.inverse e => {?hidden_proof}

    \func equals (G H : Group) (p : G = {Monoid} H) : G = H => (exts Group) {
      | Monoid => p
      | inverse => inverse-equality
    }
      \where {
        \lemma inverse-equality (e : G) : coe (p @ __) (inverse e) right = inverse (coe (p @ __) e right) => {?hidden_proof}
      }


    \lemma make-inverse-left {M : Semigroup} {ide : M} (ide-right : \Pi {x : M} -> x * ide = x) (inverse : M -> M) (inverse-right : \Pi {x : M} -> x * inverse x = ide) {x : M} : inverse x * x = ide 
      => {?hidden_proof}

    \lemma make-ide-left {M : Semigroup} {ide : M} (ide-right : \Pi {x : M} -> * x ide = x) (inverse : M -> M) (inverse-right : \Pi {x : M} -> x * inverse x = ide) 
    (inverse-left : \Pi {x : M} -> inverse x * x = ide) {x : M} : * ide x = x => {?hidden_proof}

    \func translate-is-Equiv {G : Group} (h : G) : QEquiv (h *) \cowith
      | ret => inverse h *
      | ret_f => \lam _ => rewrite (inv G.*-assoc, G.inverse-left, G.ide-left) idp
      | f_sec => \lam _ => rewrite (inv G.*-assoc, G.inverse-right, G.ide-left) idp

\class Dec \extends Group, DecSet
  }


\func \infixl 7 / {G : Group} (x y : G) => x * inverse y

\func conjugate {E : Group} (g h : E) => g * h * inverse g

\lemma conjugate-via-id {G : Group} {g : G} : conjugate ide g = g => {?hidden_proof}

\class AddGroup \extends AddMonoid {
  | negative : E -> E
  | negative-left {x : E} : negative x + x = zro
  | negative-right {x : E} : x + negative x = zro

  \lemma cancel-left (x : E) {y z : E} (p : x + y = x + z) : y = z => {?hidden_proof}

  \lemma cancel-right (z : E) {x y : E} (p : x + z = y + z) : x = y => {?hidden_proof}

  \lemma negative-isInv {x : E} : negative (negative x) = x => {?hidden_proof}

  \lemma negative_+ {x y : E} : negative (x + y) = negative y - x => {?hidden_proof}

  \lemma negative_- {x y : E} : negative (x - y) = y - x => {?hidden_proof}

  \lemma negative_zro : negative zro = zro => {?hidden_proof}

  \lemma minus_zro {x : E} : x - zro = x => {?hidden_proof}

  \lemma fromZero {x y : E} (x-y=0 : x - y = zro) : x = y => {?hidden_proof}

  \lemma toZero {x y : E} (x=y : x = y) : x - y = zro => {?hidden_proof}

  \lemma *n_negative {n : Nat} {a : E} : n *n negative a = negative (n *n a) => {?hidden_proof}

  \func \infixl 7 *i (x : Int) (a : E) : E \elim x
    | pos n => n *n a
    | neg n => n *n negative a

  \protected \lemma *i_ipow {x : Int} {a : E} : x *i a = \this.ipow a x => {?hidden_proof}

  \lemma *i-assoc {x y : Int} {a : E} : (x * y) *i a = x *i (y *i a) => {?hidden_proof}
    \where {
      \open Arith.Int.IntRing (*, *-comm)
    }


  \lemma *i-rdistr {x y : Int} {a : E} : (x Arith.Int.IntRing.+ y) *i a = x *i a + y *i a => {?hidden_proof}

  \lemma diff_+ {x y z : E} : (z - y) + (y - x) = z - x => {?hidden_proof}
}
  \where {
    \use \coerce fromGroup (G : Group) => \new (AddGroup G.E G.ide G.* G.ide-left G.ide-right G.*-assoc G.inverse G.inverse-left G.inverse-right)

    \use \coerce toGroup (G : AddGroup) => \new (Group G.E G.zro G.+ G.+-assoc G.zro-left G.zro-right G.negative G.negative-left G.negative-right)

    \lemma negative-equality {X : \Set} (A B : AddGroup X) (z : A.zro = B.zro) (m : \Pi {x y : A} -> x A.+ y = x B.+ y) (e : A) : A.negative e = B.negative e => {?hidden_proof}

\class With# \extends AddGroup, Set# {
      | \fix 8 #0 : E -> \Prop
      | #0-zro : Not (#0 zro)
      | #0-negative {x : E} : #0 x -> #0 (negative x)
      | #0-+ {x y : E} : #0 (x + y) -> #0 (#0 x || y)
      | #0-tight {x : E} : Not (#0 x) -> x = zro
      | # => \lam x y => #0 (x - y)
      | #-irreflexive => \lam x-x#0 => #0-zro (transport #0 negative-right x-x#0)
      | #-symmetric => \lam x-y#0 => transport #0 (negative_+ *> pmap (+ negative _) negative-isInv) (#0-negative x-y#0)
      | #-comparison => \lam x y z x-z#0 => #0-+ (transport #0 (inv diff_+) x-z#0)
      | tightness => \lam x-y/#0 => fromZero (#0-tight x-y/#0)

      \lemma apartNonZero {x : E} (x#0 : #0 x) : x /= zro => {?hidden_proof}

      \lemma #0-negative-inv {x : E} (p : #0 (negative x)) : #0 x => {?hidden_proof}

      \lemma #0-+-left {x y : E} (x#0 : #0 x) : #0 (x + y) || #0 y => {?hidden_proof}

      \lemma #0-+-right {x y : E} (y#0 : #0 y) : #0 (x + y) || #0 x => {?hidden_proof}

      \lemma #0-BigSum {l : Array E} (p : #0 (BigSum l)) : ∃ (j : Fin l.len) (#0 (l j)) => {?hidden_proof}

      \lemma #0-BigSum-conv {l : Array E} {i : Fin l.len} (p : #0 (l i)) : #0 (BigSum l) || (\Sigma (j : Fin l.len) (j /= i) (#0 (l j))) => {?hidden_proof}
    }

\class Dec \extends With#, DecSet {
      | nonZeroApart {x : E} (x/=0 : x /= zro) : #0 x
      | #0-negative => \lam x#0 => nonZeroApart (\lam -x=0 => #0-zro (transport #0 (inv negative-isInv *> pmap negative -x=0 *> negative_zro) x#0))
      | #0-+ => \lam {x} {y} x+y#0 => (\case decideEq y zro \with {
        | yes y=0 => byLeft (transport #0 (pmap (x +) y=0 *> zro-right) x+y#0)
        | no y/=0 => byRight (nonZeroApart y/=0)
      })
      | #0-tight => \lam {x} x/#0 => (\case decideEq x zro \with {
        | yes x=0 => x=0
        | no x/=0 => absurd (x/#0 (nonZeroApart x/=0))
      })
      | nonEqualApart => \lam p => nonZeroApart (\lam x-y=0 => p (fromZero x-y=0))
      | #0 => #0
      | #0-zro => #0-zro
      | nonZeroApart => notEqualApartImpl

      \protected \default #0 x : \Prop => x /= zro

      \protected \default #0-zro (zro/=0 : #0 zro) : Empty => zro/=0 idp

      \protected \default notEqualApartImpl {x} x#0 : #0 x => x#0

      \lemma decide#0 (a : E) : \level (Or (a = 0) (With#.#0 a)) (Or.levelProp (\lam p q => apartNonZero q p)) => {?hidden_proof}
    }
  }


\func \infixl 6 - {G : AddGroup} (x y : G) => x + negative y

\class CGroup \extends Group, CancelCMonoid {
  | inverse-right => *-comm *> inverse-left

  \lemma ipow_*-comm {a b : E} {x : Int} : ipow (a * b) x = ipow a x * ipow b x => {?hidden_proof}

  \lemma BigProd_inverse {l : Array E} : inverse (BigProd l) = BigProd (map inverse l) => {?hidden_proof}

  \lemma BigProd_ipow {k : Int} {l : Array E} : BigProd (\lam i => ipow (l i) k) = ipow (BigProd l) k => {?hidden_proof}
}

\class AbGroup \extends AddGroup, AbMonoid {
  | negative-right => +-comm *> negative-left

  \lemma *n-ldistr_- {n : Nat} {a b : E} : n *n (a - b) = n *n a - n *n b => {?hidden_proof}

  \lemma *i-ldistr {a b : E} {x : Int} : x *i (a + b) = x *i a + x *i b => {?hidden_proof}

  \lemma BigSum_negative {l : Array E} : negative (BigSum l) = BigSum (map negative l) => {?hidden_proof}

  \lemma sum-cancel-left {x y z : E} : x + z - (x + y) = z - y => {?hidden_proof}

  \lemma sum-cancel-right {x y z : E} : z + x - (y + x) = z - y => {?hidden_proof}

  \lemma diff-cancel-left {x y z : E} : x - z - (x - y) = y - z => {?hidden_proof}

  \lemma negative_+-comm {x y : E} : negative (x + y) = negative x - y => {?hidden_proof}

  \lemma diff_sum {x y z : E} : x - (y + z) = x - y - z => {?hidden_proof}

  \lemma diff_diff {x y z : E} : x - (y - z) = x - y + z => {?hidden_proof}
}
  \where {
    \use \coerce fromCGroup (G : CGroup) => \new (AbGroup G.E G.ide G.* G.ide-left G.ide-right G.*-assoc G.inverse G.inverse-left G.*-comm)

    \use \coerce toCGroup (G : AbGroup) => \new (CGroup G.E G.zro G.+ G.+-assoc G.zro-left G.zro-right G.negative G.negative-left G.+-comm)

    \func equals (A B : AbGroup) (p : A = {AddGroup} B) : A = B 
      => path (\lam i => \new AbGroup {  | AddGroup => p @ i  | +-comm => prop-dpi (\Pi {x y : p @ __} -> x + y = y + x) A.+-comm B.+-comm @ i})
  }


\class FinGroup \extends Group, Group.Dec, FinSet