\import Algebra.Field
\import Algebra.Group
\import Algebra.Group.GroupCategory
\import Algebra.Group.GroupHom
\import Algebra.Monoid
\import Algebra.Monoid.MonoidCategory
\import Algebra.Monoid.MonoidHom
\import Algebra.Pointed
\import Algebra.Pointed.PointedHom
\import Algebra.Ring
\import Algebra.Ring.RingCategory
\import Algebra.Ring.RingHom
\import Algebra.Semiring
\import Category
\import Category.Functor
\import Function.Meta($)
\import Logic
\import Meta
\import Order.Lattice
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set.SetCategory
\open SetColimit

\instance MonoidLatticeColimit {D : BottomJoinSemilattice} (F : Functor D MonoidCat) : Monoid (SetColimit (Comp MonoidCat.forget F)) 
  | ide => in~ (D.bottom, ide)
  | * => *
  | ide-left => {?hidden_proof}
  | ide-right => {?hidden_proof}
  | *-assoc => {?hidden_proof}
  \where {
    \lemma Func-app {j1 j2 j3 : D} {f : Hom j1 j2} {g : Hom j2 j3} {a : F j1} : F.Func (g ∘ f) a = F.Func g (F.Func f a) => {?hidden_proof}

    \lemma poset-app {j j' : D} {f g : j <= j'} {a : F j} : F.Func f a = F.Func g a => {?hidden_proof}

    \lemma poset-id {j : D} {p : j <= j} {a : F j} : F.Func p a = a => {?hidden_proof}

    \func inMap {F : Functor D MonoidCat} (d : D) : MonoidHom (F d) (MonoidLatticeColimit F) \cowith
      | func => \lam a => in~ (d, a)
      | func-ide => {?hidden_proof}
      | func-* => {?hidden_proof}

    \lemma inMap-coh {d d' : D} (p : d <= d') : inMap d = inMap d' ∘ F.Func p => {?hidden_proof}
  }


\instance AddMonoidLatticeColimit {D : BottomJoinSemilattice} (F : Functor D AddMonoidCat) : AddMonoid (SetColimit (Comp AddMonoidCat.forget F)) 
  | zro => in~ (D.bottom, zro)
  | + => +
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  \where {
    \lemma Func-app {j1 j2 j3 : D} {f : Hom j1 j2} {g : Hom j2 j3} {a : F j1} : F.Func (g ∘ f) a = F.Func g (F.Func f a) => {?hidden_proof}

    \lemma poset-app {j j' : D} {f g : j <= j'} {a : F j} : F.Func f a = F.Func g a => {?hidden_proof}

    \lemma poset-id {j : D} {p : j <= j} {a : F j} : F.Func p a = a => {?hidden_proof}

    \func inMap {F : Functor D AddMonoidCat} (d : D) : AddMonoidHom (F d) (AddMonoidLatticeColimit F) \cowith
      | func => \lam a => in~ (d, a)
      | func-zro => {?hidden_proof}
      | func-+ => {?hidden_proof}

    \lemma inMap-coh {d d' : D} (p : d <= d') : inMap d = inMap d' ∘ F.Func p => {?hidden_proof}
  }


\instance AddGroupLatticeColimit {D : BottomJoinSemilattice} (F : Functor D AddGroupCat) : AddGroup (SetColimit (Comp AddGroupCat.forget F)) 
  | AddMonoid => AddMonoidLatticeColimit (Comp AddGroupCat.forgetToAddMonoid F)
  | negative => negative
  | negative-left => {?hidden_proof}
  | negative-right => {?hidden_proof}
  \where {
    \func inMap {F : Functor D AddGroupCat} (d : D) : AddGroupHom (F d) (AddGroupLatticeColimit F) \cowith
      | func => \lam a => in~ (d, a)
      | func-zro => {?hidden_proof}
      | func-+ => {?hidden_proof}

    \lemma inMap-coh {d d' : D} (p : d <= d') : inMap d = inMap d' ∘ F.Func p => {?hidden_proof}
  }


\instance AbGroupLatticeColimit {D : BottomJoinSemilattice} (F : Functor D AbGroupCat) : AbGroup (SetColimit (Comp AbGroupCat.forget F)) 
  | AddGroup => AddGroupLatticeColimit (Comp AbGroupCat.forgetToAddGroup F)
  | +-comm => {?hidden_proof}
  \where {
    \func inMap {F : Functor D AbGroupCat} (d : D) : AddGroupHom (F d) (AddGroupLatticeColimit F) \cowith
      | func => \lam a => in~ (d, a)
      | func-zro => {?hidden_proof}
      | func-+ => {?hidden_proof}

    \lemma inMap-coh {d d' : D} (p : d <= d') : inMap d = inMap d' ∘ F.Func p => {?hidden_proof}
  }


\instance RingLatticeColimit {D : BottomJoinSemilattice} (F : Functor D RingCat) : Ring (SetColimit (Comp RingCat.forget F)) 
  | AbGroup => AbGroupLatticeColimit (Comp RingCat.forgetToAbGroup F)
  | Monoid => MonoidLatticeColimit (Comp RingCat.forgetToMonoid F)
  | ldistr => {?hidden_proof}
  | rdistr => {?hidden_proof}
  \where {
    \lemma Func-app {j1 j2 j3 : D} {f : Hom j1 j2} {g : Hom j2 j3} {a : F j1} : F.Func (g ∘ f) a = F.Func g (F.Func f a) => {?hidden_proof}

    \lemma poset-app {j j' : D} {f g : j <= j'} {a : F j} : F.Func f a = F.Func g a => {?hidden_proof}

    \func inMap (d : D) : RingHom (F d) (RingLatticeColimit F) \cowith
      | func => \lam a => in~ (d, a)
      | func-zro => {?hidden_proof}
      | func-+ => {?hidden_proof}
      | func-ide => {?hidden_proof}
      | func-* => {?hidden_proof}

    \lemma inMap-coh {d d' : D} (p : d <= d') : inMap d = inMap d' ∘ F.Func p => {?hidden_proof}
  }


\instance CRingLatticeColimit {D : BottomJoinSemilattice} (F : Functor D CRingCat) : CRing (SetColimit (Comp CRingCat.forget F)) 
  | Ring => RingLatticeColimit (Comp CRingCat.forgetToRing F)
  | *-comm => {?hidden_proof}

\func DiscreteFieldLatticeColimit {D : BottomJoinSemilattice} (F : Functor D CRingCat) (p : \Pi (d : D) -> DiscreteField {  | CRing => F d}) :
  DiscreteField (SetColimit (Comp CRingCat.forget F)) \cowith
  | CRing => CRingLatticeColimit F
  | zro/=ide => {?hidden_proof}
  | eitherZeroOrInv => {?hidden_proof}