\import Algebra.Group
\import Algebra.Group.Product
\import Algebra.Meta
\import Algebra.Module.LinearMap
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Algebra.Semiring
\import Arith.Nat
\import Category.Functor
\import Data.Array
\import Data.Array.EPerm
\import Data.Array.Split
\import Data.Fin(unfsuc)
\import Equiv
\import Equiv.Univalence(Equiv-to-=)
\import Function(IsInj, IsSurj)
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\import Set.Fin.Instances
\open AddMonoid
\open AbMonoid

\class LModule \extends AbGroup {
  | R : Ring
  | \infixl 7 *c : R -> E -> E
  | *c-assoc {r r' : R} {a : E} : r * r' *c a = r *c (r' *c a)
  | *c-ldistr {r : R} {a b : E} : r *c (a + b) = r *c a + r *c b
  | *c-rdistr {r s : R} {a : E} : (r R.+ s) *c a = r *c a + s *c a
  | ide_*c {a : E} : 1 *c a = a
}
  \where {
    \func count {R : Semiring} {J : DecSet} (l : Array (\Sigma R J)) (j : J) : R => R.BigSum (map __.1 $ keep (\lam s => decideEq j s.2) l)

    \lemma count_zro {R : Semiring} {J : DecSet} {l : Array (\Sigma R J)} (j : J) (p : \Pi (k : Fin l.len) -> j /= (l k).2) : count {R} l j = 0 => {?hidden_proof}

    \lemma count-unique {R : Semiring} {J : DecSet} {l : Array J} {c : Array R l.len} (inj : IsInj l) (k : Fin l.len) : count (\lam j => (c j, l j)) (l k) = c k => {?hidden_proof}

    \type IsZeroSum {R : Semiring} {J : \Set} (l : Array (\Sigma R J)) : \Prop 
      => ∃ (l' : Array (\Sigma (Array R) J)) (EPerm l (Big ++ nil $ map (\lam s => map (__, s.2) s.1) l')) (\Pi (j : Fin l'.len) -> R.BigSum (l' j).1 = 0)
      \where {
        \lemma aux {l : Array (\Sigma (Array R) J)} : Big ++ nil (map (\lam s => map (__, s.2) s.1) l) = Big ++ nil 
          (mkArray (\lam i => map (__, (remove (\lam s => decideEq (DArray.len {s.1}) 0) l i).2) (remove (\lam s => decideEq (DArray.len {s.1}) 0) l i).1)) => {?hidden_proof}

        \lemma nonEmpty {l : Array (\Sigma R J)} (zs : IsZeroSum l) :
        ∃ (l' : Array (\Sigma (c : Array R) J (c.len /= 0))) (EPerm l (Big ++ nil $ map (\lam s => map (__, s.2) s.1) l')) 
          (\Pi (j : Fin l'.len) -> R.BigSum (l' j).1 = 0) => {?hidden_proof}
      }


    \type \infix 4 Z~ {R : Ring} {J : \Set} (l1 l2 : Array (\Sigma R J)) : \Prop => IsZeroSum (map (\lam s => (R.negative s.1, s.2)) l2 ++ l1)

    \lemma count_IsZeroSum {R : Semiring} {J : DecSet} {l : Array (\Sigma R J)} (p : \Pi (j : Fin (DArray.len {nub $ map __.2 l})) -> count l (nub (map __.2 l) j) = 0) : IsZeroSum l 
      => {?hidden_proof}

    \lemma IsZeroSum_count {R : Semiring} {J : DecSet} {l : Array (\Sigma R J)} (p : IsZeroSum l) (j : J) : count l j = 0 => {?hidden_proof}
      \where {
        \lemma count_EPerm {l l' : Array (\Sigma R J)} (p : EPerm l l') {j : J} : count l j = count l' j => {?hidden_proof}

        \lemma count_++ {l l' : Array (\Sigma R J)} {j : J} : count (l ++ l') j = count l j + count l' j => {?hidden_proof}

        \lemma count_Big++ {ls : Array (Array (\Sigma R J))} {j : J} : count (Big ++ nil ls) j = BigSum (\lam i => count (ls i) j) => {?hidden_proof}
      }


    \open IsIndependentSet

    basisSet-split {R : Ring} {U V : LModule R} {J : \Set} {u : J -> U} (ub : U.IsBasisSet u) (v : J -> V) (x : U) :
      \Sigma (y : V) (∃ (c : Array (\Sigma R J)) (x = sum u c) (y = sum v c)) 
    => \case TruncP.rec-set (ub.2 x) (\lam s => sum v s.1) (\lam s s' => ~_= v $ =_~ ub.1 $ inv s.2 *> s'.2) \with {
      | (y, t) => (y, TruncP.map t (\lam s => (s.1.1, s.1.2, inv s.2)))
    }

    \func pullback (f : RingHom) (M : LModule f.Cod) : LModule f.Dom \cowith
      | AbGroup => M
      | *c => \lam a x => f a *c x
      | *c-assoc => {?hidden_proof}
      | *c-ldistr => {?hidden_proof}
      | *c-rdistr => {?hidden_proof}
      | ide_*c => {?hidden_proof}

    \lemma generated-fin-comp (f : RingHom) {M : LModule f.Cod} {I J : FinSet} {a : I -> f.Cod} {b : J -> M} (Cg : (homLModule f).IsGeneratedFin a) (Mg : M.IsGeneratedFin b) :
      LModule.IsGeneratedFin {pullback f M} (\lam (p : \Sigma J I) => a p.2 *c b p.1) => {?hidden_proof}

    \lemma generated-pullback (f : RingHom) {M : LModule f.Cod} (Cg : (homLModule f).IsFinitelyGenerated) (Mg : M.IsFinitelyGenerated) : (pullback f M).IsFinitelyGenerated => {?hidden_proof}

    \lemma generated-comp {R S T : Ring} (f : RingHom R S) (g : RingHom S T) (fg : (homLModule f).IsFinitelyGenerated) (gg : (homLModule g).IsFinitelyGenerated) :
      (homLModule (g RingHom.∘ f)).IsFinitelyGenerated => {?hidden_proof}
  }


\instance ProductLModule (R : Ring) (A B : LModule R) : LModule R 
  | AbGroup => ProductAbGroup A B
  | *c => \lam r p => (r *c p.1, r *c p.2)
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  \where {
    \func in1 {R : Ring} (A B : LModule R) : LinearMap A (ProductLModule R A B) \cowith
      | func => \lam a => (a, 0)
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}
      \where {
        \lemma aux {r : R} {a : A} {b : B} : r LModule.*c {ProductLModule R A B} (a, b) = (r *c a, r *c b) => {?hidden_proof}
      }


    \func in2 {R : Ring} (A B : LModule R) : LinearMap B (ProductLModule R A B) \cowith
      | func => \lam b => (0, b)
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}
      \where {
        \lemma aux {r : R} {a : A} {b : B} : r LModule.*c {ProductLModule R A B} (a, b) = (r *c a, r *c b) => {?hidden_proof}
      }


    \func proj1 {R : Ring} (A B : LModule R) : LinearMap (ProductLModule R A B) A \cowith
      | func => \lam (a, b) => a
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func proj2 {R : Ring} (A B : LModule R) : LinearMap (ProductLModule R A B) B \cowith
      | func => \lam (a, b) => b
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func coprod-map {R : Ring} {A B C : LModule R} (i : LinearMap A C) (j : LinearMap B C) : LinearMap (ProductLModule R A B) C \cowith
      | func => \lam (a, b) => i a C.+ j b
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func prod-map {R : Ring} {A B C : LModule R} (a : LinearMap C A) (b : LinearMap C B) : LinearMap C (ProductLModule R A B) \cowith
      | func => \lam c => (a c, b c)
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}
  }


\func RingLModule (R : Ring) : LModule R R \cowith
  | AbGroup => R
  | *c => *
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  \where {
    \func *_hom-left {R : CRing} {x : R} : LinearMap (RingLModule R) (RingLModule R) \cowith
      | func => \lam y => x * y
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func *_hom-right {R : Ring} {x : R} : LinearMap (RingLModule R) (RingLModule R) \cowith
      | func => \lam y => y * x
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \lemma basis {R : Ring} : LModule.IsBasis {RingLModule R} (1 :: nil) => {?hidden_proof}
  }


\instance ArrayLModule {R : Ring} (n : Nat) (M : LModule R) : LModule R (Array M n) 
  | zro => \lam _ => 0
  | + => \lam f g j => f j + g j
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | negative => \lam f j => negative (f j)
  | negative-left => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | *c => \lam r f j => r *c f j
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  \where {
    \lemma skip_*c {R : CRing} {n : Nat} {r : R} {l : Array R (suc n)} {k : Fin (suc n)} :
      skip (r *c {ArrayLModule _ (RingLModule R)} l) k = r *c {ArrayLModule _ (RingLModule R)} skip l k => {?hidden_proof}

    \lemma skip_+ {R : CRing} {n : Nat} {l l' : Array R (suc n)} {k : Fin (suc n)} :
      skip (l + {ArrayLModule _ (RingLModule R)} l') k = skip l k + {ArrayLModule _ (RingLModule R)} skip l' k => {?hidden_proof}

    \lemma BigSum-index {R : Ring} {n : Nat} {M : LModule R} {l : Array (Array M n)} {i : Fin n} :
      AddMonoid.BigSum {ArrayLModule n M} l i = M.BigSum (map {Array M n} (__ i) l) => {?hidden_proof}
  }


\func homLModule (f : RingHom) : LModule f.Dom \cowith
  | AbGroup => f.Cod
  | *c => \lam x y => f x * y
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}