\import Algebra.Group
\import Algebra.Group.Product
\import Algebra.Meta
\import Algebra.Module.LinearMap
\import Algebra.Monoid
\import Algebra.Pointed
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Algebra.Semiring
\import Arith.Nat
\import Category.Functor
\import Data.Array
\import Data.Array.EPerm
\import Data.Array.Split
\import Data.Fin (unfsuc)
\import Equiv
\import Equiv.Univalence (Equiv-to-=)
\import Function (IsInj, IsSurj)
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\import Set.Fin.Instances
\open AddMonoid
\open AbMonoid

\class LModule \extends AbGroup (R : Ring) {
  | \infixl 7 *c : R -> E -> E
  | *c-assoc {r r' : R} {a : E} : r * r' *c a = r *c (r' *c a)
  | *c-ldistr {r : R} {a b : E} : r *c (a + b) = r *c a + r *c b
  | *c-rdistr {r s : R} {a : E} : (r R.+ s) *c a = r *c a + s *c a
  | ide_*c {a : E} : 1 *c a = a

  \lemma cancel {r : R} {a b : E} (i : Monoid.Inv r) (s : r *c a = r *c b) : a = b => {?hidden_proof}

  \lemma *c_zro-left {a : E} : 0 *c a = 0 => {?hidden_proof}

  \lemma *c_zro-right {r : R} : r *c 0 = 0 => {?hidden_proof}

  \lemma *c_negative-left {r : R} {a : E} : R.negative r *c a = negative (r *c a) => {?hidden_proof}

  \lemma *c_negative-right {r : R} {a : E} : r *c negative a = negative (r *c a) => {?hidden_proof}

  \lemma *c-ldistr_- {r : R} {a b : E} : r *c (a - b) = r *c a - r *c b => {?hidden_proof}

  \lemma *c-rdistr_- {r s : R} {a : E} : (r - s) *c a = r *c a - s *c a => {?hidden_proof}

  \lemma neg_ide_*c {a : E} : -1 *c a = negative a => {?hidden_proof}

  \lemma natCoef_*c {n : Nat} {a : E} : natCoef n *c a = n *n a => {?hidden_proof}

  \lemma *c_BigSum-rdistr {l : Array R} {a : E} : R.BigSum l *c a = BigSum (\lam i => l i *c a) => {?hidden_proof}

  \lemma *c_BigSum-ldistr {r : R} {l : Array E} : r *c BigSum l = BigSum (\lam i => r *c l i) => {?hidden_proof}

  \lemma *c_FinSum-rdistr {J : FinSet} {f : J -> R} {a : E} : R.FinSum f *c a = FinSum (\lam j => f j *c a) => {?hidden_proof}

  \lemma *c_FinSum-ldistr {r : R} {J : FinSet} {f : J -> E} : r *c FinSum f = FinSum (\lam j => r *c f j) => {?hidden_proof}

  \func IsDependent (l : Array E) : \Prop => ∃ (c : Array R l.len) (BigSum (\lam j => c j *c l j) = 0) (j : Fin l.len) (c j /= 0)

  \func IsIndependent (l : Array E) : \Prop => \Pi (c : Array R l.len) -> BigSum (\lam j => c j *c l j) = 0 -> \Pi (j : Fin l.len) -> c j = 0

  \type IsGenerated (l : Array E) : \Prop => \Pi (x : E) -> ∃ (c : Array R l.len) (x = BigSum (\lam i => c i *c l i))

  \type IsBasis (l : Array E) : \Prop => \Sigma (IsIndependent l) (IsGenerated l)

  \lemma independent-subset {l : Array E} (li : IsIndependent l) {k : Nat} (p : k <= l.len) : IsIndependent (\lam j => l (fin-inc_<= p j)) => {?hidden_proof}

  \lemma independent-nonZero {l : Array E} (lb : IsIndependent l) {j : Fin l.len} (p : l j = 0) : 0 = {R} 1 => {?hidden_proof}

  \type IsIndependentSet {J : \Set} (g : J -> E) : \Prop => \Pi (c : Array (\Sigma R J)) -> sum g c = 0 -> IsZeroSum c
    \where {
      \func sum (g : J -> E) (c : Array (\Sigma R J)) => BigSum (\lam j => (c j).1 *c g (c j).2)

      \lemma sum-ldistr (g : J -> E) {r : R} {c : Array (\Sigma R J)} : r *c sum g c = sum g (map (\lam s => (r * s.1, s.2)) c) => {?hidden_proof}

      \lemma sum_++ (g : J -> E) {c d : Array (\Sigma R J)} : sum g (c ++ d) = sum g c + sum g d => {?hidden_proof}

      \lemma sum_Big++ (g : J -> E) {l : Array (Array (\Sigma R J))} : sum g (Big ++ nil l) = BigSum (map (sum g) l) => {?hidden_proof}

      \lemma sum_negative (g : J -> E) {c : Array (\Sigma R J)} : negative (sum g c) = sum g (map (\lam s => (R.negative s.1, s.2)) c) => {?hidden_proof}

      \lemma sum_EPerm (g : J -> E) {l l' : Array (\Sigma R J)} (p : EPerm l l') : sum g l = sum g l' => {?hidden_proof}

      \lemma =_~ (gi : IsIndependentSet g) {c d : Array (\Sigma R J)} (p : sum g c = sum g d) : c Z~ d => {?hidden_proof}

      \lemma IsZeroSum_= (g : J -> E) {c : Array (\Sigma R J)} (p : IsZeroSum c) : sum g c = 0 => {?hidden_proof}

      \lemma ~_= (g : J -> E) {c d : Array (\Sigma R J)} (p : c Z~ d) : sum g c = sum g d => {?hidden_proof}
    }


  \lemma IsIndependentSet-right-inj {J K : \Set} {f : J -> K} (inj : IsInj f) {g : K -> E} (gi : IsIndependentSet g) : IsIndependentSet (\lam j => g (f j)) => {?hidden_proof}

  \type IsIndependentDec {J : \Set} (g : J -> E) : \Prop => \Pi (l : Array J) (c : Array R l.len) -> IsInj l -> BigSum (\lam j => c j *c g (l j)) = 0 -> \Pi (j : Fin c.len) -> c j = 0

  \lemma IsIndependentSet<->IsIndependentDec {J : DecSet} {g : J -> E} : IsIndependentSet g <-> IsIndependentDec g => {?hidden_proof}

  \lemma IsIndependent<->IsIndependentSet {l : Array E} : IsIndependent l <-> IsIndependentSet l => {?hidden_proof}
    \where {
      \lemma sum_BigSum {l : Array E} {c : Array (\Sigma R (Fin l.len))} : sum l c = BigSum (\lam j => count c j *c l j) => {?hidden_proof}
    }


  \lemma IsIndependentSet-fin {J : FinSet} {g : J -> E} : IsIndependentSet g <-> (\Pi (c : J -> R) -> FinSum (\lam j => c j *c g j) = 0 -> \Pi (j : J) -> c j = 0) => {?hidden_proof}

  \type IsGeneratingSet {J : \Set} (g : J -> E) : \Prop => \Pi (x : E) -> ∃ (c : Array (\Sigma R J)) (x = IsIndependentSet.sum g c)

  \lemma IsGeneratingSet-fin {J : \Set} {g : J -> E} : IsGeneratingSet g <-> (\Pi (x : E) -> ∃ (K : FinSet) (c : (K -> \Sigma R J)) (x = FinSum (\lam k => (c k).1 *c g (c k).2))) => {?hidden_proof}

  \lemma IsGeneratingSet-surj {J K : \Set} {f : J -> K} (surj : IsSurj f) {g : K -> E} (gi : IsGeneratingSet g) : IsGeneratingSet (\lam j => g (f j)) => {?hidden_proof}

  \lemma IsBasisSet-equiv {J K : \Set} (e : Equiv {J} {K}) {g : K -> E} (gb : IsBasisSet g) : IsBasisSet (\lam j => g (e j)) => {?hidden_proof}

  \lemma IsGenerated<->IsGeneratingSet {l : Array E} : IsGenerated l <-> IsGeneratingSet l => {?hidden_proof}

  \type IsBasisSet {J : \Set} (g : J -> E) : \Prop => \Sigma (IsIndependentSet g) (IsGeneratingSet g)

  \lemma IsBasis<->IsBasisSet {l : Array E} : IsBasis l <-> IsBasisSet l => {?hidden_proof}

  \lemma independent-split-unique {l : Array E} (li : IsIndependent l) {c d : Array R l.len} (p : BigSum (\lam j => c j *c l j) = BigSum (\lam j => d j *c l j)) (j : Fin l.len) : c j = d j 
    => {?hidden_proof}

  \lemma basis-split-pair {l : Array E} (lb : IsBasis l) (x : E) : \level (\Sigma (c : Array R l.len) (x = BigSum (\lam j => c j *c l j))) (basis-split-unique lb.1 x) => {?hidden_proof}
    \where {
      \lemma basis-split-unique {l : Array E} (li : IsIndependent l) (x : E) : isProp (\Sigma (c : Array R l.len) (x = BigSum (\lam j => c j *c l j))) => {?hidden_proof}
    }


  \sfunc basis-split {l : Array E} (lb : IsBasis l) (x : E) : Array R l.len => (basis-split-pair lb x).1

  \lemma basis-split-char {l : Array E} {lb : IsBasis l} {x : E} : x = BigSum (\lam j => basis-split lb x j *c l j) => {?hidden_proof}

  \lemma basis-split-unique {l : Array E} (lb : IsBasis l) {x : E} (d : Array R l.len) (p : x = BigSum (\lam j => d j *c l j)) (j : Fin l.len) : basis-split lb x j = d j => {?hidden_proof}

  \lemma basis_split_basis {l : Array E} {lb : IsBasis l} {j k : Fin l.len} : basis-split lb (l j) k = (\case decideEq j k \with {  | yes _ => 1  | no _ => 0}) => {?hidden_proof}

  \lemma basis_split_= {l : Array E} {lb : IsBasis l} {j : Fin l.len} : basis-split lb (l j) j = 1 => {?hidden_proof}

  \lemma basis_split_/= {l : Array E} {lb : IsBasis l} {j k : Fin l.len} (j/=k : j /= k) : basis-split lb (l j) k = 0 => {?hidden_proof}

  \type IsGeneratedFin {J : FinSet} (f : J -> E) : \Prop => \Pi (x : E) -> ∃ (c : (J -> R)) (x = FinSum (\lam j => c j *c f j))

  \protected \func IsFinitelyGenerated : \Prop => ∃ (l : Array E) (IsGenerated l)

  \lemma basisSet_basis (J : FinSet) {g : J -> E} (gb : IsBasisSet g) : ∃ (l : Array E J.finCard) (IsBasis l) => {?hidden_proof}

  \lemma free-char : ∃ (l : Array E) (IsBasis l) <-> ∃ (J : FinSet) (g : (J -> E)) (IsBasisSet g) => {?hidden_proof}

  \lemma generated-array-fin {l : Array E} (g : IsGenerated l) : IsGeneratedFin l => {?hidden_proof}

  \lemma generated-fin-array {J : FinSet} {f : J -> E} (g : IsGeneratedFin f) : IsFinitelyGenerated => {?hidden_proof}

  \func IsFaithful : \Prop => \Pi (r : R) -> (\Pi (m : E) -> r *c m = 0) -> r = 0
}
  \where {
    \func count {R : Semiring} {J : DecSet} (l : Array (\Sigma R J)) (j : J) : R => R.BigSum (map __.1 $ keep (\lam s => decideEq j s.2) l)

    \lemma count_zro {R : Semiring} {J : DecSet} {l : Array (\Sigma R J)} (j : J) (p : \Pi (k : Fin l.len) -> j /= (l k).2) : count {R} l j = 0 => {?hidden_proof}

    \lemma count-unique {R : Semiring} {J : DecSet} {l : Array J} {c : Array R l.len} (inj : IsInj l) (k : Fin l.len) : count (\lam j => (c j, l j)) (l k) = c k => {?hidden_proof}

    \type IsZeroSum {R : Semiring} {J : \Set} (l : Array (\Sigma R J)) : \Prop 
      => ∃ (l' : Array (\Sigma (Array R) J)) (EPerm l (Big ++ nil $ map (\lam s => map (__, s.2) s.1) l')) (\Pi (j : Fin l'.len) -> R.BigSum (l' j).1 = 0)
      \where {
        \lemma aux {l : Array (\Sigma (Array R) J)} : Big ++ nil (map (\lam s => map (__, s.2) s.1) l) = Big ++ nil 
          (mkArray (\lam i => map (__, (remove (\lam s => decideEq (DArray.len {s.1}) 0) l i).2) (remove (\lam s => decideEq (DArray.len {s.1}) 0) l i).1)) => {?hidden_proof}

        \lemma nonEmpty {l : Array (\Sigma R J)} (zs : IsZeroSum l) :
        ∃ (l' : Array (\Sigma (c : Array R) J (c.len /= 0))) (EPerm l (Big ++ nil $ map (\lam s => map (__, s.2) s.1) l')) 
          (\Pi (j : Fin l'.len) -> R.BigSum (l' j).1 = 0) => {?hidden_proof}
      }


    \type \infix 4 Z~ {R : Ring} {J : \Set} (l1 l2 : Array (\Sigma R J)) : \Prop => IsZeroSum (map (\lam s => (R.negative s.1, s.2)) l2 ++ l1)

    \lemma count_IsZeroSum {R : Semiring} {J : DecSet} {l : Array (\Sigma R J)} (p : \Pi (j : Fin (DArray.len {nub $ map __.2 l})) -> count l (nub (map __.2 l) j) = 0) : IsZeroSum l 
      => {?hidden_proof}

    \lemma IsZeroSum_count {R : Semiring} {J : DecSet} {l : Array (\Sigma R J)} (p : IsZeroSum l) (j : J) : count l j = 0 => {?hidden_proof}
      \where {
        \lemma count_EPerm {l l' : Array (\Sigma R J)} (p : EPerm l l') {j : J} : count l j = count l' j => {?hidden_proof}

        \lemma count_++ {l l' : Array (\Sigma R J)} {j : J} : count (l ++ l') j = count l j + count l' j => {?hidden_proof}

        \lemma count_Big++ {ls : Array (Array (\Sigma R J))} {j : J} : count (Big ++ nil ls) j = BigSum (\lam i => count (ls i) j) => {?hidden_proof}
      }


    \open IsIndependentSet

    \sfunc basisSet-split {R : Ring} {U V : LModule R} {J : \Set} {u : J -> U} (ub : U.IsBasisSet u) (v : J -> V) (x : U) :
      \Sigma (y : V) (∃ (c : Array (\Sigma R J)) (x = sum u c) (y = sum v c)) 
    => \case TruncP.rec-set (ub.2 x) (\lam s => sum v s.1) (\lam s s' => ~_= v $ =_~ ub.1 $ inv s.2 *> s'.2) \with {
      | (y, t) => (y, TruncP.map t (\lam s => (s.1.1, s.1.2, inv s.2)))
    }

    \func pullback (f : RingHom) (M : LModule f.Cod) : LModule f.Dom \cowith
      | AbGroup => M
      | *c => \lam a x => f a *c x
      | *c-assoc => {?hidden_proof}
      | *c-ldistr => {?hidden_proof}
      | *c-rdistr => {?hidden_proof}
      | ide_*c => {?hidden_proof}

    \lemma generated-fin-comp (f : RingHom) {M : LModule f.Cod} {I J : FinSet} {a : I -> f.Cod} {b : J -> M} (Cg : (homLModule f).IsGeneratedFin a) (Mg : M.IsGeneratedFin b) :
      LModule.IsGeneratedFin {pullback f M} (\lam (p : \Sigma J I) => a p.2 *c b p.1) => {?hidden_proof}

    \lemma generated-pullback (f : RingHom) {M : LModule f.Cod} (Cg : (homLModule f).IsFinitelyGenerated) (Mg : M.IsFinitelyGenerated) : (pullback f M).IsFinitelyGenerated => {?hidden_proof}

    \lemma generated-comp {R S T : Ring} (f : RingHom R S) (g : RingHom S T) (fg : (homLModule f).IsFinitelyGenerated) (gg : (homLModule g).IsFinitelyGenerated) :
      (homLModule (g RingHom.∘ f)).IsFinitelyGenerated => {?hidden_proof}
  }


\instance ProductLModule (R : Ring) (A B : LModule R) : LModule R 
  | AbGroup => ProductAbGroup A B
  | *c => \lam r p => (r *c p.1, r *c p.2)
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  \where {
    \func in1 {R : Ring} (A B : LModule R) : LinearMap A (ProductLModule R A B) \cowith
      | func => \lam a => (a, 0)
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}
      \where {
        \lemma aux {r : R} {a : A} {b : B} : r LModule.*c {ProductLModule R A B} (a, b) = (r *c a, r *c b) => {?hidden_proof}
      }


    \func in2 {R : Ring} (A B : LModule R) : LinearMap B (ProductLModule R A B) \cowith
      | func => \lam b => (0, b)
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}
      \where {
        \lemma aux {r : R} {a : A} {b : B} : r LModule.*c {ProductLModule R A B} (a, b) = (r *c a, r *c b) => {?hidden_proof}
      }


    \func proj1 {R : Ring} (A B : LModule R) : LinearMap (ProductLModule R A B) A \cowith
      | func => \lam (a, b) => a
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func proj2 {R : Ring} (A B : LModule R) : LinearMap (ProductLModule R A B) B \cowith
      | func => \lam (a, b) => b
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func coprod-map {R : Ring} {A B C : LModule R} (i : LinearMap A C) (j : LinearMap B C) : LinearMap (ProductLModule R A B) C \cowith
      | func => \lam (a, b) => i a C.+ j b
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func prod-map {R : Ring} {A B C : LModule R} (a : LinearMap C A) (b : LinearMap C B) : LinearMap C (ProductLModule R A B) \cowith
      | func => \lam c => (a c, b c)
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}
  }


\func RingLModule (R : Ring) : LModule R R \cowith
  | AbGroup => R
  | *c => *
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  \where {
    \func *_hom-left {R : CRing} {x : R} : LinearMap (RingLModule R) (RingLModule R) \cowith
      | func => \lam y => x * y
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \func *_hom-right {R : Ring} {x : R} : LinearMap (RingLModule R) (RingLModule R) \cowith
      | func => \lam y => y * x
      | func-+ => {?hidden_proof}
      | func-*c => {?hidden_proof}

    \lemma basis {R : Ring} : LModule.IsBasis {RingLModule R} (1 :: nil) => {?hidden_proof}
  }


\instance ArrayLModule {R : Ring} (n : Nat) (M : LModule R) : LModule R (Array M n) 
  | zro => \lam _ => 0
  | + => \lam f g j => f j + g j
  | zro-left => {?hidden_proof}
  | zro-right => {?hidden_proof}
  | +-assoc => {?hidden_proof}
  | negative => \lam f j => negative (f j)
  | negative-left => {?hidden_proof}
  | +-comm => {?hidden_proof}
  | *c => \lam r f j => r *c f j
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}
  \where {
    \lemma skip_*c {R : CRing} {n : Nat} {r : R} {l : Array R (suc n)} {k : Fin (suc n)} :
      skip (r *c {ArrayLModule _ (RingLModule R)} l) k = r *c {ArrayLModule _ (RingLModule R)} skip l k => {?hidden_proof}

    \lemma skip_+ {R : CRing} {n : Nat} {l l' : Array R (suc n)} {k : Fin (suc n)} :
      skip (l + {ArrayLModule _ (RingLModule R)} l') k = skip l k + {ArrayLModule _ (RingLModule R)} skip l' k => {?hidden_proof}

    \lemma BigSum-index {R : Ring} {n : Nat} {M : LModule R} {l : Array (Array M n)} {i : Fin n} :
      AddMonoid.BigSum {ArrayLModule n M} l i = M.BigSum (map {Array M n} (__ i) l) => {?hidden_proof}
  }


\func homLModule (f : RingHom) : LModule f.Dom \cowith
  | AbGroup => f.Cod
  | *c => \lam x y => f x * y
  | *c-assoc => {?hidden_proof}
  | *c-ldistr => {?hidden_proof}
  | *c-rdistr => {?hidden_proof}
  | ide_*c => {?hidden_proof}