\import Algebra.Meta
\import Algebra.Pointed
\import Arith.Nat
\import Data.Array
\import Data.Array.EPerm
\import Data.Array.Perm
\import Data.Fin (fsuc, fsuc/=)
\import Data.Or
\import Equiv
\import Equiv.Sigma
\import Equiv.Univalence
\import Function
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\import Set.Fin.Instances
\import Set.Fin.Pigeonhole

\class Semigroup \extends BaseSet {
  | \infixl 7 * : E -> E -> E
  | *-assoc {x y z : E} : (x * y) * z = x * (y * z)

  \func IsSquare (x : E) => ∃ (y : E) (y * y = x)

  \protected \func op : Semigroup E \cowith
    | * => \lam x y => y * x
    | *-assoc => {?hidden_proof}
}

\class Monoid \extends Pointed, Semigroup {
  | ide-left {x : E} : ide * x = x
  | ide-right {x : E} : x * ide = x

  \func pow (a : E) (n : Nat) : E \elim n
    | 0 => ide
    | suc n => pow a n * a

  \lemma pow_+ {a : E} {n m : Nat} : pow a (n + m) = pow a n * pow a m => {?hidden_proof}

  \lemma pow_* {a : E} {n m : Nat} : pow a (n Nat.* m) = pow (pow a n) m => {?hidden_proof}

  \lemma pow-comm1 {a b : E} (p : a * b = b * a) {n : Nat} : pow a n * b = b * pow a n => {?hidden_proof}

  \lemma pow-comm2 {a b : E} (p : a * b = b * a) {n m : Nat} : pow a n * pow b m = pow b m * pow a n => {?hidden_proof}

  \lemma pow-comm {a b : E} (p : a * b = b * a) {n : Nat} : pow (a * b) n = pow a n * pow b n => {?hidden_proof}

  \lemma pow_ide {n : Nat} : pow ide n = ide => {?hidden_proof}

  \lemma pow-left {a : E} {n : Nat} : a * pow a n = pow a n * a => {?hidden_proof}

  \func BigProd (l : Array E) => Big * ide l

  \lemma BigProd-ext {n : Nat} {l l' : Array E n} (p : \Pi (i : Fin n) -> l i = l' i) : BigProd l = BigProd l' => {?hidden_proof}

  \lemma BigProd_ide {l : Array E} (p : \Pi (j : Fin l.len) -> l j = ide) : BigProd l = ide => {?hidden_proof}

  \lemma BigProd-unique {l : Array E} (i : Fin l.len) (p : \Pi (j : Fin l.len) -> i /= j -> l j = 1) : BigProd l = l i => {?hidden_proof}

  \lemma BigProd_++ {l l' : Array E} : BigProd (l ++ l') = BigProd l * BigProd l' => {?hidden_proof}

  \lemma BigProd_suc {n : Nat} {l : Array E (suc n)} : BigProd l = BigProd (\new (Array E n (\lam i => l i))) * l n => {?hidden_proof}

  \lemma BigProd_replicate {x : E} {n : Nat} : BigProd (replicate n x) = pow x n => {?hidden_proof}

  \lemma BigProd_replicate1 {n : Nat} : BigProd (replicate n ide) = ide => {?hidden_proof}

  \protected \func op : Monoid E \cowith
    | ide => ide
    | * => \lam x y => y * x
    | ide-left => {?hidden_proof}
    | ide-right => {?hidden_proof}
    | *-assoc => {?hidden_proof}
}
  \where {
    \protected \func equals {M N : Monoid} (p : M = {\Set} N) (q :   \let f x => coe (p @) x right  \in \Pi (x y : M) -> f (x * y) = f x * f y) : M = N => exts (p, ide-equality, q)
      \where {
        \lemma ide-equality : coe (p @) ide right = ide => {?hidden_proof}
      }


\record DivBase {M : Monoid} (\coerce val : M) (elem : M) (inv : M)

\record LDiv \extends DivBase {
      | inv-right : val * inv = elem
    }
      \where {
        \func make {M : Monoid} {a b : M} (c : M) (p : a * c = b) : LDiv a b => \new LDiv {
          | inv => c
          | inv-right => p
        }

        \lemma product {M : CMonoid} {x y z w : M} (x|y : LDiv x y) (z|w : LDiv z w) : LDiv (x * z) (y * w) (z|w.inv * x|y.inv) => {?hidden_proof}

        \lemma product-left {M : Monoid} (x : M) {y z : M} (y|z : LDiv y z) : LDiv (x * y) (x * z) y|z.inv => {?hidden_proof}

        \lemma product-right {M : CMonoid} (z : M) {x y : M} (x|y : LDiv x y) : LDiv (x * z) (y * z) x|y.inv => {?hidden_proof}

        \lemma factor-left {M : Monoid} {x y z : M} (x|y : LDiv x y) : LDiv x (y * z) (x|y.inv * z) => {?hidden_proof}

        \lemma factor-right {M : CMonoid} {x y z : M} (x|z : LDiv x z) : LDiv x (y * z) (x|z.inv * y) => {?hidden_proof}

        \lemma cancel-left {M : CancelMonoid} (x : M) {y z : M} (x*y|x*z : LDiv (x * y) (x * z)) : LDiv y z x*y|x*z.inv => {?hidden_proof}

        \lemma cancel-right {M : CancelCMonoid} {x y : M} (z : M) (x*z|y*z : LDiv (x * z) (y * z)) : LDiv x y x*z|y*z.inv => {?hidden_proof}

        \lemma trans {M : Monoid} {x y z : M} (x|y : LDiv x y) (y|z : LDiv y z) : LDiv x z (x|y.inv * y|z.inv) => {?hidden_proof}

        \lemma ide-div {M : Monoid} {x : M} : LDiv ide x x => {?hidden_proof}

        \lemma id-div {M : Monoid} {x : M} : LDiv x x ide => {?hidden_proof}

        \lemma swap {M : CMonoid} (l : LDiv {M}) : LDiv l.inv l.elem l.val => {?hidden_proof}

        \lemma idempt {M : Monoid} (l : LDiv {M}) (p : l * l = l) : l * l.elem = l.elem => {?hidden_proof}

        \use \lemma cancelProp {M : Monoid} (x : M) (q : \Pi {a b : M} -> x * a = x * b -> a = b) (y : M) : isProp (LDiv x y) => {?hidden_proof}

        \lemma fromTruncP {M : Monoid} {x y : M} (q : \Pi {a b : M} -> x * a = x * b -> a = b) (t : TruncP (LDiv x y)) : \level (LDiv x y) (cancelProp x q y) => {?hidden_proof}

        \use \level levelProp {M : CancelMonoid} (x y : M) : isProp (LDiv x y) => cancelProp x (M.cancel_*-left x) y
      }


\record RDiv \extends DivBase {
      | inv-left : inv * val = elem
    }
      \where {
        \lemma product-right {M : Monoid} (x y z : M) (x|y : RDiv x y) : RDiv (x * z) (y * z) x|y.inv => {?hidden_proof}

        \lemma cancel-right {M : CancelMonoid} (x y z : M) (x*z|y*z : RDiv (x * z) (y * z)) : RDiv x y x*z|y*z.inv => {?hidden_proof}

        \lemma trans {M : Monoid} (x y z : M) (x|y : RDiv x y) (y|z : RDiv y z) : RDiv x z (y|z.inv * x|y.inv) => {?hidden_proof}

        \lemma levelProp {M : CancelMonoid} (x y : M) : isProp (RDiv x y) => {?hidden_proof}
      }


\record LInv \extends RDiv {
      | elem => ide
    }
      \where {
        \lemma cancel {M : Monoid} {x y z : M} (j : LInv x) (p : x * y = x * z) : y = z => {?hidden_proof}
      }


\record RInv \extends LDiv {
      | elem => ide
    }
      \where {
        \lemma cancel {M : Monoid} {x y z : M} (j : RInv z) (p : x * z = y * z) : x = y => {?hidden_proof}
      }


\record Inv \extends LInv, RInv {
      \protected \func reverse : Inv DivBase.inv val \cowith
        | inv-left => {?hidden_proof}
        | inv-right => {?hidden_proof}
    }
      \where {
        \use \lemma inv-isUnique {M : Monoid} (j j' : Inv {M}) (p : j.val = j'.val) : j.inv = j'.inv => {?hidden_proof}

        \use \level levelProp {M : Monoid} {x : M} (j j' : Inv x) : j = j' => 
          \have p => inv-isUnique j j' idp
          \in path
                (\lam i => \new (Inv x (p @ i) (prop-dpi ((p @ __) * x = ide) j.inv-left j'.inv-left @ i) (prop-dpi (x * (p @ __) = ide) j.inv-right j'.inv-right @ i)))

        \lemma ide-isInv {M : Monoid} : Inv {M} ide => {?hidden_proof}

        \lemma product {M : Monoid} (i j : Inv {M}) : Inv (i * j) => {?hidden_proof}
          \where {
            \func func : Inv (i * j) \cowith
              | inv => j.inv * i.inv
              | inv-left => {?hidden_proof}
              | inv-right => {?hidden_proof}

            \lemma lem {M : Monoid} (i j : Inv {M}) : (j.inv * i.inv) * (i * j) = ide => {?hidden_proof}
          }


        \lemma prod {M : Monoid} (i j : Inv {M}) : Inv (i * j) (j.inv * i.inv) => {?hidden_proof}

        \lemma factor-right {M : Monoid} {x y : M} (i : LInv x) (j : Inv (x * y)) : Inv y => {?hidden_proof}

        \lemma factor-left {M : Monoid} {x y : M} (i : RInv y) (j : Inv (x * y)) : Inv x => {?hidden_proof}

        \lemma lmake {M : CMonoid} {x : M} (y : M) (p : y * x = ide) : Inv x y => {?hidden_proof}

        \lemma rmake {M : CMonoid} {x : M} (y : M) (p : x * y = ide) : Inv x y => {?hidden_proof}

        \lemma ldiv {M : CMonoid} {x : M} (d : LDiv x ide) : Inv x d.inv => {?hidden_proof}

        \lemma rdiv {M : CMonoid} {x : M} (d : RDiv x ide) : Inv x d.inv => {?hidden_proof}

        \lemma cfactor-right {M : CMonoid} {x y : M} (i : Inv (x * y)) : Inv y => {?hidden_proof}

        \lemma cfactor-left {M : CMonoid} {x y : M} (i : Inv (x * y)) : Inv x => {?hidden_proof}
      }

  }


\func associates {M : Monoid} (x y : M) => \Sigma (u : Monoid.Inv {M}) (x = u * y)
  \where {
    \use \level levelProp {M : CancelMonoid} (x y : M) (t t' : associates x y) : t = t' => 
      \have eq => cancel_*-right y (inv t.2 *> t'.2)
      \in ext (ext (eq, Monoid.Inv.inv-isUnique t.1 t'.1 eq))
  }


\func associates-sym {M : Monoid} {x y : M} (a : associates x y) : associates y x 
  => (Monoid.Inv.reverse {a.1}, inv $ pmap (_ *) a.2 *> inv *-assoc *> pmap (* y) a.1.inv-left *> ide-left)

\class AddMonoid \extends AddPointed {
  | \infixl 6 + : E -> E -> E
  | zro-left {x : E} : zro + x = x
  | zro-right {x : E} : x + zro = x
  | +-assoc {x y z : E} : (x + y) + z = x + (y + z)

  \lemma negative-unique {x z : E} (y : E) (p : x + y = zro) (q : y + z = zro) : x = z => {?hidden_proof}

  \func \infixl 7 *n (n : Nat) (a : E) : E \elim n
    | 0 => zro
    | suc n => n *n a + a

  \protected \lemma *n_pow {n : Nat} {a : E} : n *n a = \this.pow a n => {?hidden_proof}

  \lemma *n-rdistr {n m : Nat} {a : E} : (n Nat.+ m) *n a = n *n a + m *n a => {?hidden_proof}

  \lemma *n-assoc {n m : Nat} {a : E} : (n Nat.* m) *n a = n *n (m *n a) => {?hidden_proof}

  \func BigSum (l : Array E) => Big + zro l

  \lemma BigSum-ext {n : Nat} {l l' : Array E n} (p : \Pi (i : Fin n) -> l i = l' i) : BigSum l = BigSum l' => {?hidden_proof}

  \lemma BigSum_++ {l l' : Array E} : BigSum (l ++ l') = BigSum l + BigSum l' => {?hidden_proof}

  \lemma BigSum_Big++ {ls : Array (Array E)} : BigSum (Big ++ nil ls) = BigSum (map BigSum ls) => {?hidden_proof}

  \lemma BigSum_++' {l : Array E} {n : Nat} {l' : Array E n} : BigSum (l ++' l') = BigSum l + BigSum l' => {?hidden_proof}

  \lemma BigSum-split {n m : Nat} {l : Array E (n Nat.+ m)} : BigSum l = BigSum (\lam (i : Fin n) => l (fin-inc i)) + BigSum (\lam (j : Fin m) => l (fin-raise j)) => {?hidden_proof}

  \lemma BigSum_suc {n : Nat} {l : Array E (suc n)} : BigSum l = BigSum (\new (Array E n (\lam i => l i))) + l n => {?hidden_proof}

  \lemma BigSum_suc-nat {n : Nat} {f : Nat -> E} : BigSum (\new (Array E (suc n) (f __))) = BigSum (\new (Array E n (f __))) + f n => {?hidden_proof}

  \lemma BigSum_zro {l : Array E} (p : \Pi (j : Fin l.len) -> l j = zro) : BigSum l = zro => {?hidden_proof}

  \lemma BigSum-unique {l : Array E} (i : Fin l.len) (p : \Pi (j : Fin l.len) -> i /= j -> l j = 0) : BigSum l = l i => {?hidden_proof}

  \lemma BigSum-unique2 {l : Array E} {i j : Fin l.len} (i<j : i NatOrder.< j) (p : \Pi (k : Fin l.len) -> k /= i -> k /= j -> l k = 0) : BigSum l = l i + l j => {?hidden_proof}

  \lemma BigSum-pred {P : E -> \Prop} (P0 : P 0) (P+ : \Pi {x y : E} -> P x -> P y -> P (x + y)) {l : Array E} (p : \Pi (j : Fin l.len) -> P (l j)) : P (BigSum l) => {?hidden_proof}

  \lemma BigSum_replicate0 {n : Nat} : BigSum (replicate n zro) = 0 => {?hidden_proof}

  \lemma BigSum-subset {l l' : Array E} (p : l.len <= l'.len) (q1 : \Pi (j : Fin l.len) -> l j = l' (toFin j $ fin_< j <∘l p)) 
  (q2 : \Pi (j : Fin l'.len) -> l.len <= j -> l' j = 0) : BigSum l = BigSum l' => {?hidden_proof}

  \lemma fit_BigSum {n : Nat} {l : Array E} (p : \Pi (j : Fin l.len) -> n <= j -> l j = 0) : BigSum (fit 0 {n} l) = BigSum l => {?hidden_proof}

  \lemma fit-transpose {n m : Nat} (l : Array (Array E m) n) : BigSum (\lam j => fit zro (l j) j) = BigSum (\lam k => fit zro (l __ k) k) => {?hidden_proof}

  \protected \func op : AddMonoid E \cowith
    | zro => 0
    | + => \lam a b => b + a
    | zro-left => {?hidden_proof}
    | zro-right => {?hidden_proof}
    | +-assoc => {?hidden_proof}
}
  \where {
    \use \coerce fromMonoid (M : Monoid) => \new (AddMonoid M.E M.ide M.* M.ide-left M.ide-right M.*-assoc)

    \use \coerce toMonoid (M : AddMonoid) => \new (Monoid M.E M.zro M.+ M.+-assoc M.zro-left M.zro-right)
  }


\class CSemigroup \extends Semigroup {
  | *-comm {x y : E} : x * y = y * x
}

\class CMonoid \extends Monoid, CSemigroup {
  | ide-left => *-comm *> ide-right
  | ide-right => *-comm *> ide-left

  \lemma divInv {x y : E} (cancel : \Pi {a b : E} -> x * a = x * b -> a = b) (xy|x : LDiv (x * y) x) : Inv y => {?hidden_proof}

  \lemma pow_*-comm {a b : E} {n : Nat} : pow (a * b) n = pow a n * pow b n => {?hidden_proof}

  \func DivChain : \Prop => \Pi (a : Nat -> E) -> (\Pi (i : Nat) -> TruncP (LDiv (a (suc i)) (a i))) -> ∃ (j : Nat) (LDiv (a j) (a (suc j)))

  \lemma BigProd_* {n : Nat} {l l' : Array E n} : BigProd (\lam i => l i * l' i) = BigProd l * BigProd l' => {?hidden_proof}

  \lemma BigProd_pow {k : Nat} {l : Array E} : BigProd (\lam i => pow (l i) k) = pow (BigProd l) k => {?hidden_proof}

  \lemma BigProd_EPerm {l l' : Array E} (e : EPerm l l') : BigProd l = BigProd l' => {?hidden_proof}

  \lemma BigProd_Perm {n : Nat} {l l' : Array E n} (p : Perm l l') : BigProd l = BigProd l' => {?hidden_proof}

  \sfunc FinProd {A : FinSet} (x : A -> E) : E => aux.1
    \where {
      \lemma aux : \Sigma (r : E) (∃ (e : Equiv {Fin A.finCard} {A}) (BigProd (\lam j => x (e j)) = r)) => {?hidden_proof}
        \where {
          \lemma aux (e e' : Equiv {Fin A.finCard} {A}) : BigProd (\lam j => x (e j)) = BigProd (\lam j => x (e' j)) => {?hidden_proof}
        }

    }


  \lemma FinProd_char {A : FinSet} (x : A -> E) : ∃ (e : Equiv {Fin A.finCard} {A}) (FinProd {_} {A} x = BigProd (\lam j => x (e j))) => {?hidden_proof}

  \lemma FinProd_char2 {A : FinSet} {x : A -> E} (e : Equiv {Fin A.finCard} {A}) : FinProd x = BigProd (\lam j => x (e j)) => {?hidden_proof}

  \lemma FinProd-const {A : FinSet} {x : E} : FinProd {_} {A} (\lam _ => x) = BigProd (\new (Array E A.finCard (\lam j => x))) => {?hidden_proof}

  \func LDiv_BigProd {l : Array E} (j : Fin l.len) : LDiv (l j) (BigProd l) \elim l, j
    | a :: l, 0 => LDiv.factor-left LDiv.id-div
    | a :: l, suc j => LDiv.trans (LDiv_BigProd j) (LDiv.factor-right LDiv.id-div)

  \func LDiv_BigProd-coord {n : Nat} {l l' : Array E n} (p : \Pi (j : Fin n) -> LDiv (l j) (l' j)) : LDiv (BigProd l) (BigProd l') \elim n, l, l'
    | 0, nil, nil => LDiv.ide-div
    | suc n, a :: l, a' :: l' => LDiv.product (p 0) $ LDiv_BigProd-coord (\lam j => p (suc j))

  \lemma LDiv_BigProd_TruncP {n : Nat} {l l' : Array E n} (p : \Pi (j : Fin n) -> TruncP (LDiv (l j) (l' j))) : TruncP (LDiv (BigProd l) (BigProd l')) => {?hidden_proof}

  \func IsRegularElem (a : E) => \Pi {x y : E} -> a * x = a * y -> x = y

  \lemma LDiv_IsRegular {a b : E} (d : LDiv a b) (c : IsRegularElem b) : IsRegularElem a => {?hidden_proof}
}
  \where {
    \open Monoid
  }


\class AbMonoid \extends AddMonoid {
  | +-comm {x y : E} : x + y = y + x
  | zro-left => +-comm *> zro-right
  | zro-right => +-comm *> zro-left

  \lemma *n-ldistr {n : Nat} {a b : E} : n *n (a + b) = n *n a + n *n b => {?hidden_proof}

  \lemma BigSum_+ {n : Nat} {l l' : Array E n} : BigSum (\lam i => l i + l' i) = BigSum l + BigSum l' => {?hidden_proof}

  \lemma BigSum-transpose {m n : Nat} (f : Fin m -> Fin n -> E) : BigSum (\lam i => BigSum (f i)) = BigSum (\lam j => BigSum (f __ j)) => {?hidden_proof}

  \lemma BigSum-double-dep {n : Nat} (m : Fin n -> Nat) (y : \Sigma (i : Fin n) (Fin (m i)) -> E) :
    BigSum (\lam i => BigSum (\lam j => y (i, j))) = BigSum (\lam k => y (SigmaFin.aux.f k)) => {?hidden_proof}

  \lemma BigSum_Or {n m : Nat} (x : Or (Fin n) (Fin m) -> E) : BigSum (\lam j => x (OrFin.aux j)) = BigSum (\lam j => x (inl j)) + BigSum (\lam j => x (inr j)) => {?hidden_proof}

  \lemma BigSum_EPerm {l l' : Array E} (e : EPerm l l') : BigSum l = BigSum l' => {?hidden_proof}

  \lemma BigSum_Perm {n : Nat} {l l' : Array E n} (p : Perm l l') : BigSum l = BigSum l' => {?hidden_proof}

  \sfunc FinSum {A : FinSet} (x : A -> E) : E => aux.1
    \where {
      \lemma aux : \Sigma (r : E) (∃ (e : Equiv {Fin A.finCard} {A}) (BigSum (\lam j => x (e j)) = r)) => {?hidden_proof}
        \where {
          \lemma aux (e e' : Equiv {Fin A.finCard} {A}) : BigSum (\lam j => x (e j)) = BigSum (\lam j => x (e' j)) => {?hidden_proof}
        }

    }


  \lemma FinSum_char {A : FinSet} (x : A -> E) : ∃ (e : Equiv {Fin A.finCard} {A}) (FinSum {_} {A} x = BigSum (\lam j => x (e j))) => {?hidden_proof}

  \lemma FinSum_char2 {A : FinSet} {x : A -> E} (e : Equiv {Fin A.finCard} {A}) : FinSum x = BigSum (\lam j => x (e j)) => {?hidden_proof}

  \lemma FinSum_zro {J : FinSet} {x : J -> E} (p : \Pi (j : J) -> x j = 0) : FinSum x = 0 => {?hidden_proof}

  \lemma FinSum_+ {J : FinSet} {x : J -> E} {y : J -> E} : FinSum (\lam j => x j + y j) = FinSum x + FinSum y => {?hidden_proof}

  \lemma FinSum-const {A : FinSet} {x : E} : FinSum {_} {A} (\lam _ => x) = BigSum (\new (Array E A.finCard (\lam j => x))) => {?hidden_proof}

  \lemma FinSum-double-dep {A : FinSet} (B : A -> FinSet) {x : \Sigma (a : A) (B a) -> E} : FinSum (\lam a => FinSum (\lam b => x (a, b))) = FinSum {_} {SigmaFin A B} x => {?hidden_proof}

  \lemma FinSum-double {A B : FinSet} {x : A -> B -> E} : FinSum (\lam a => FinSum (\lam b => x a b)) = FinSum (\lam (p : \Sigma A B) => x p.1 p.2) => {?hidden_proof}

  \lemma FinSum=BigSum {n : Nat} {x : Fin n -> E} : FinSum x = BigSum x => {?hidden_proof}

  \lemma FinSum_Equiv {A B : FinSet} (e : Equiv {A} {B}) {x : B -> E} : FinSum x = FinSum (\lam a => x (e a)) => {?hidden_proof}

  \lemma FinSum_Equiv2 {A B : FinSet} (e : Equiv {A} {B}) {x : A -> E} {y : B -> E} (p : \Pi (a : A) -> x a = y (e a)) : FinSum x = FinSum y => {?hidden_proof}

  \lemma FinSum-inj {A B : FinSet} (f : A -> B) (inj : IsInj f) {x : B -> E} (p : \Pi (b : B) -> (\Pi (a : A) -> f a /= b) -> x b = 0) :
    FinSum x = FinSum (\lam a => x (f a)) => {?hidden_proof}

  \lemma FinSum_Or {A B : FinSet} {x : Or A B -> E} : FinSum x = FinSum (\lam a => x (inl a)) + FinSum (\lam b => x (inr b)) => {?hidden_proof}

  \lemma FinSum-unique {J : FinSet} {a : J -> E} (j : J) (p : \Pi (j' : J) -> j' /= j -> a j' = 0) : FinSum a = a j => {?hidden_proof}

  \lemma FinSum-unique2 {J : FinSet} {i j : J} (i/=j : i /= j) {x : J -> E} (p : \Pi (k : J) -> k /= i -> k /= j -> x k = 0) : FinSum x = x i + x j => {?hidden_proof}

  \lemma FinSum-pred {P : E -> \Prop} (P0 : P 0) (P+ : \Pi {x y : E} -> P x -> P y -> P (x + y)) {J : FinSet} {a : J -> E} (p : \Pi (j : J) -> P (a j)) : P (AbMonoid.FinSum a) 
    => {?hidden_proof}
}
  \where {
    \use \coerce fromCMonoid (M : CMonoid) => \new (AbMonoid M.E M.ide M.* M.ide-left M.ide-right M.*-assoc M.*-comm)

    \use \coerce toCMonoid (M : AbMonoid) => \new (CMonoid M.E M.zro M.+ M.+-assoc M.zro-left M.zro-right M.+-comm)
  }


\class CancelMonoid \extends Monoid {
  | cancel_*-left (x : E) {y z : E} (p : x * y = x * z) : y = z
  | cancel_*-right (z : E) {x y : E} (p : x * z = y * z) : x = y
}

\class CancelCMonoid \extends CancelMonoid, CMonoid {
  | cancel_*-right => \lam z {x} {y} x*z=y*z => cancel_*-left z (*-comm *> x*z=y*z *> *-comm)

  \lemma divInv {x y : E} (xy|x : Monoid.LDiv (x * y) x) : Monoid.Inv y => {?hidden_proof}
}