\import Algebra.Meta
\import Algebra.Pointed
\import Arith.Nat
\import Data.Array
\import Data.Array.EPerm
\import Data.Array.Perm
\import Data.Fin(fsuc, fsuc/=)
\import Data.Or
\import Equiv
\import Equiv.Sigma
\import Equiv.Univalence
\import Function
\import Function.Meta
\import Logic.Unique
\import Logic
\import Logic.Classical
\import Logic.Meta
\import Meta
\import Order.Biordered
\import Order.LinearOrder
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Set
\import Set.Fin
\import Set.Fin.Instances
\import Set.Fin.Pigeonhole

\class Semigroup \extends BaseSet {
  | \infixl 7 * : E -> E -> E
  | *-assoc {x y z : E} : (x * y) * z = x * (y * z)
}

\class Monoid \extends Pointed, Semigroup {
  | ide-left {x : E} : ide * x = x
  | ide-right {x : E} : x * ide = x
}
  \where {
    \func equals {M N : Monoid} (p : M = {\Set} N) (q :   \let f x => coe (p @) x right  \in \Pi (x y : M) -> f (x * y) = f x * f y) : M = N => exts (p, ide-equality, q)
      \where {
        \lemma ide-equality : coe (p @) ide right = ide => {?hidden_proof}
      }


\class DivBase {
      | M : Monoid
      | val : M
      | elem : M
      | inv : M
    }

\class LDiv \extends DivBase {
      | inv-right : val * inv = elem
    }
      \where {
        \func make {M : Monoid} {a b : M} (c : M) (p : a * c = b) : LDiv a b => \new LDiv {
          | inv => c
          | inv-right => p
        }

        \lemma product {M : CMonoid} {x y z w : M} (x|y : LDiv x y) (z|w : LDiv z w) : LDiv (x * z) (y * w) (z|w.inv * x|y.inv) => {?hidden_proof}

        \lemma product-left {M : Monoid} (x : M) {y z : M} (y|z : LDiv y z) : LDiv (x * y) (x * z) y|z.inv => {?hidden_proof}

        \lemma product-right {M : CMonoid} (z : M) {x y : M} (x|y : LDiv x y) : LDiv (x * z) (y * z) x|y.inv => {?hidden_proof}

        \lemma factor-left {M : Monoid} {x y z : M} (x|y : LDiv x y) : LDiv x (y * z) (x|y.inv * z) => {?hidden_proof}

        \lemma factor-right {M : CMonoid} {x y z : M} (x|z : LDiv x z) : LDiv x (y * z) (x|z.inv * y) => {?hidden_proof}

        \lemma cancel-left {M : CancelMonoid} (x : M) {y z : M} (x*y|x*z : LDiv (x * y) (x * z)) : LDiv y z x*y|x*z.inv => {?hidden_proof}

        \lemma cancel-right {M : CancelCMonoid} {x y : M} (z : M) (x*z|y*z : LDiv (x * z) (y * z)) : LDiv x y x*z|y*z.inv => {?hidden_proof}

        \lemma trans {M : Monoid} {x y z : M} (x|y : LDiv x y) (y|z : LDiv y z) : LDiv x z (x|y.inv * y|z.inv) => {?hidden_proof}

        \lemma ide-div {M : Monoid} {x : M} : LDiv ide x x => {?hidden_proof}

        \lemma id-div {M : Monoid} {x : M} : LDiv x x ide => {?hidden_proof}

        \lemma swap {M : CMonoid} (l : LDiv {M}) : LDiv l.inv l.elem l.val => {?hidden_proof}

        \lemma idempt {M : Monoid} (l : LDiv {M}) (p : l * l = l) : l * l.elem = l.elem => {?hidden_proof}

        \lemma cancelProp {M : Monoid} (x : M) (q : \Pi {a b : M} -> x * a = x * b -> a = b) (y : M) : isProp (LDiv x y) => {?hidden_proof}

        \lemma fromTruncP {M : Monoid} {x y : M} (q : \Pi {a b : M} -> x * a = x * b -> a = b) (t : TruncP (LDiv x y)) : \level (LDiv x y) (cancelProp x q y) => {?hidden_proof}

        \use \level levelProp {M : CancelMonoid} (x y : M) : isProp (LDiv x y) => cancelProp x (M.cancel_*-left x) y
      }


\class RDiv \extends DivBase {
      | inv-left : inv * val = elem
    }
      \where {
        \lemma product-right {M : Monoid} (x y z : M) (x|y : RDiv x y) : RDiv (x * z) (y * z) x|y.inv => {?hidden_proof}

        \lemma cancel-right {M : CancelMonoid} (x y z : M) (x*z|y*z : RDiv (x * z) (y * z)) : RDiv x y x*z|y*z.inv => {?hidden_proof}

        \lemma trans {M : Monoid} (x y z : M) (x|y : RDiv x y) (y|z : RDiv y z) : RDiv x z (y|z.inv * x|y.inv) => {?hidden_proof}

        \lemma levelProp {M : CancelMonoid} (x y : M) : isProp (RDiv x y) => {?hidden_proof}
      }


\class LInv \extends RDiv {
      | elem => ide
    }
      \where {
        \lemma cancel {M : Monoid} {x y z : M} (j : LInv x) (p : x * y = x * z) : y = z => {?hidden_proof}
      }


\class RInv \extends LDiv {
      | elem => ide
    }
      \where {
        \lemma cancel {M : Monoid} {x y z : M} (j : RInv z) (p : x * z = y * z) : x = y => {?hidden_proof}
      }


\class Inv \extends LInv, RInv
      \where {
        \lemma inv-isUnique {M : Monoid} (j j' : Inv {M}) (p : j.val = j'.val) : j.inv = j'.inv => {?hidden_proof}

        \use \level levelProp {M : Monoid} {x : M} (j j' : Inv x) : j = j' => 
          \have p => inv-isUnique j j' idp
          \in path
                (\lam i => \new (Inv x (p @ i) (prop-dpi ((p @ __) * x = ide) j.inv-left j'.inv-left @ i) (prop-dpi (x * (p @ __) = ide) j.inv-right j'.inv-right @ i)))

        \lemma ide-isInv {M : Monoid} : Inv {M} ide => {?hidden_proof}

        \lemma product {M : Monoid} (i j : Inv {M}) : Inv (i * j) => {?hidden_proof}
          \where {
            \func func : Inv (i * j) \cowith
              | inv => j.inv * i.inv
              | inv-left => {?hidden_proof}
              | inv-right => {?hidden_proof}

            \lemma lem {M : Monoid} (i j : Inv {M}) : (j.inv * i.inv) * (i * j) = ide => {?hidden_proof}
          }


        \lemma prod {M : Monoid} (i j : Inv {M}) : Inv (i * j) (j.inv * i.inv) => {?hidden_proof}

        \lemma factor-right {M : Monoid} {x y : M} (i : LInv x) (j : Inv (x * y)) : Inv y => {?hidden_proof}

        \lemma factor-left {M : Monoid} {x y : M} (i : RInv y) (j : Inv (x * y)) : Inv x => {?hidden_proof}

        \lemma lmake {M : CMonoid} {x : M} (y : M) (p : y * x = ide) : Inv x y => {?hidden_proof}

        \lemma rmake {M : CMonoid} {x : M} (y : M) (p : x * y = ide) : Inv x y => {?hidden_proof}

        \lemma ldiv {M : CMonoid} {x : M} (d : LDiv x ide) : Inv x d.inv => {?hidden_proof}

        \lemma rdiv {M : CMonoid} {x : M} (d : RDiv x ide) : Inv x d.inv => {?hidden_proof}

        \lemma cfactor-right {M : CMonoid} {x y : M} (i : Inv (x * y)) : Inv y => {?hidden_proof}

        \lemma cfactor-left {M : CMonoid} {x y : M} (i : Inv (x * y)) : Inv x => {?hidden_proof}
      }

  }


\func associates {M : Monoid} (x y : M) => \Sigma (u : Monoid.Inv {M}) (x = u * y)
  \where {
    \use \level levelProp {M : CancelMonoid} (x y : M) (t t' : associates x y) : t = t' => 
      \have eq => cancel_*-right y (inv t.2 *> t'.2)
      \in ext (ext (eq, Monoid.Inv.inv-isUnique t.1 t'.1 eq))
  }


\func associates-sym {M : Monoid} {x y : M} (a : associates x y) : associates y x 
  => (Monoid.Inv.reverse {a.1}, inv $ pmap (_ *) a.2 *> inv *-assoc *> pmap (* y) a.1.inv-left *> ide-left)

\class AddMonoid \extends AddPointed {
  | \infixl 6 + : E -> E -> E
  | zro-left {x : E} : zro + x = x
  | zro-right {x : E} : x + zro = x
  | +-assoc {x y z : E} : (x + y) + z = x + (y + z)
}
  \where {
    \use \coerce fromMonoid (M : Monoid) => \new (AddMonoid M.E M.ide M.* M.ide-left M.ide-right M.*-assoc)

    \use \coerce toMonoid (M : AddMonoid) => \new (Monoid M.E M.zro M.+ M.+-assoc M.zro-left M.zro-right)
  }


\class CSemigroup \extends Semigroup {
  | *-comm {x y : E} : x * y = y * x
}

\class CMonoid \extends Monoid, CSemigroup {
  | ide-left => *-comm *> ide-right
  | ide-right => *-comm *> ide-left
}
  \where {
    \open Monoid
  }


\class AbMonoid \extends AddMonoid {
  | +-comm {x y : E} : x + y = y + x
  | zro-left => +-comm *> zro-right
  | zro-right => +-comm *> zro-left
}
  \where {
    \use \coerce fromCMonoid (M : CMonoid) => \new (AbMonoid M.E M.ide M.* M.ide-left M.ide-right M.*-assoc M.*-comm)

    \use \coerce toCMonoid (M : AbMonoid) => \new (CMonoid M.E M.zro M.+ M.+-assoc M.zro-left M.zro-right M.+-comm)
  }


\class CancelMonoid \extends Monoid {
  | cancel_*-left (x : E) {y z : E} (p : x * y = x * z) : y = z
  | cancel_*-right (z : E) {x y : E} (p : x * z = y * z) : x = y
}

\class CancelCMonoid \extends CancelMonoid, CMonoid {
  | cancel_*-right => \lam z {x} {y} x*z=y*z => cancel_*-left z (*-comm *> x*z=y*z *> *-comm)
}