\import Algebra.Algebra
\import Algebra.Group
\import Algebra.Group.GroupHom
\import Algebra.Module
\import Algebra.Monoid
\import Algebra.Ring
\import Algebra.Ring.RingHom
\import Arith.Int
\import Arith.Nat
\import Arith.Rat
\import Function.Meta
\import Logic
\import Logic.Meta
\import Logic.Unique
\import Paths
\import Paths.Meta
\import Relation.Equivalence

\class DivisibleGroup \extends AbGroup {
  | isDivisible (a : E) {n : Nat} : n /= 0 -> ∃ (b : E) (n *n b = a)
}

\class TorsionFreeGroup \extends AbGroup {
  | noTorsion {a : E} {n : Nat} : n /= 0 -> n *n a = 0 -> a = 0
}

\class QModule \extends DivisibleGroup, TorsionFreeGroup
  \where {
    \func fromRatModule (M : LModule RatField) : QModule \cowith
      | AbGroup => M
      | isDivisible => {?hidden_proof}
      | noTorsion => {?hidden_proof}
  }


\lemma func-*q {A B : QModule} {f : AddGroupHom A B} {q : Rat} {a : A} : f (q A.*q a) = q B.*q f a => {?hidden_proof}

\class QPseudoAlgebra \extends QModule, PseudoRing
  \where {
    \func fromRatAlgebra (R : PseudoAlgebra RatField) : QPseudoAlgebra \cowith
      | QModule => QModule.fromRatModule R
      | PseudoRing => R
  }


\class QAlgebra \extends QPseudoAlgebra, Ring
  \where {
    \func fromRatAlgebra (R : AAlgebra RatField) : QAlgebra \cowith
      | QModule => QModule.fromRatModule R
      | Ring => R
  }


\instance RatQAlgebra : QAlgebra Rat 
  | Ring => RatField
  | QModule => QModule.fromRatModule ringAlgebra