\import Algebra.Domain.Bezout
\import Algebra.Group
\import Algebra.Meta
\import Algebra.Monoid
\import Algebra.Monoid.GCD
\import Algebra.Ring.Ideal
\import Algebra.Semiring
\import Arith.Nat
\import Equiv
\import Function.Meta ($)
\import Logic
\import Logic.Meta
\import Meta
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\import Set.Fin

\class PseudoRing \extends PseudoSemiring, AbGroup {
  | zro_*-left => \lam {x} =>
    AddGroup.cancel-left (zro * x) (qed (zro * x + zro * x ==< inv rdistr >== (zro + zro) * x ==< pmap (* x) zro-left >== zro * x ==< inv zro-right >== zro * x + zro))
  | zro_*-right => \lam {x} =>
    AddGroup.cancel-left (x * zro) (qed (x * zro + x * zro ==< inv ldistr >== x * (zro + zro) ==< pmap (x *) zro-left >== x * zro ==< inv zro-right >== x * zro + zro))

  \lemma negative_*-left {x y : E} : negative x * y = negative (x * y) => {?hidden_proof}

  \lemma negative_*-right {x y : E} : x * negative y = negative (x * y) => {?hidden_proof}

  \lemma negative_* {x y : E} : negative x * negative y = x * y => {?hidden_proof}

  \lemma ldistr_- {x y z : E} : x * (y - z) = x * y - x * z => {?hidden_proof}

  \lemma rdistr_- {x y z : E} : (x - y) * z = x * z - y * z => {?hidden_proof}

  \lemma *_sum_diff {x y : E} (p : x * y = y * x) : (x + y) * (x - y) = x * x - y * y => {?hidden_proof}

  \lemma *_diff_sum {x y : E} (p : x * y = y * x) : (x - y) * (x + y) = x * x - y * y => {?hidden_proof}

  \protected \func op : PseudoRing \cowith
    | AbGroup => \this
    | PseudoSemiring => PseudoSemiring.op
}

\class Ring \extends PseudoRing, Semiring {
  \func intCoef (x : Int) : E 
    | pos n => natCoef n
    | neg suc _ \as n => negative (natCoef n)

  \lemma intCoef_neg (n : Nat) : intCoef (neg n) = negative (natCoef n) => {?hidden_proof}

  \lemma negative_ide-left {x : E} : negative ide * x = negative x => {?hidden_proof}

  \lemma negative_ide-right {x : E} : x * negative ide = negative x => {?hidden_proof}

  \lemma negative_inv (j : Monoid.Inv {\this}) : Monoid.Inv (negative j) (negative j.inv) => {?hidden_proof}

  \lemma geometric-partial-sum {n : Nat} {x : E} : (1 - x) * BigSum (\new (Array E n (\lam j => pow x j))) = 1 - pow x n => {?hidden_proof}

  \func IsNilpotent (x : E) => ∃ (n : Nat) (pow x n = 0)

  \lemma pow_-1_+2 {n : Nat} : pow -1 (n Nat.+ 2) = pow -1 n => {?hidden_proof}

  \lemma pow_-1_even {n : Nat} : pow -1 (n Nat.* 2) = 1 => {?hidden_proof}

  \lemma pow_-1_mod2 {n : Nat} : pow -1 n = pow -1 (n Nat.mod 2) => {?hidden_proof}

  \lemma idempotent_LDiv {a b : E} (q : b * b = b) (d : Monoid.LDiv b a) : a = b * a => {?hidden_proof}

  \type IsConnected  => \Pi (a : E) -> a * a = a -> (a = 0) || (a = 1)

  \func IsVonNeumannRegular  => \Pi (a : E) -> ∃ (b : E) (a = a * b * a)

  \protected \func op : Ring \cowith
    | AbGroup => \this
    | Semiring => Semiring.op
}
  \where {
\class With# \extends Ring, AddGroup.With# {
      | #0-*-left {x y : E} : #0 (x * y) -> #0 x
      | #0-*-right {x y : E} : #0 (x * y) -> #0 y
      | #0-negative => \lam {x} x#0 => #0-*-left (transport #0 (inv (negative_* *> ide-right)) x#0)

      \lemma #0-FinSum {J : FinSet} {x : J -> E} (p : #0 (FinSum x)) : ∃ (j : J) (#0 (x j)) => {?hidden_proof}

      \lemma #0-FinSum-conv {J : FinSet} {x : J -> E} {i : J} (xi#0 : #0 (x i)) : #0 (FinSum x) || (\Sigma (j : J) (j /= i) (#0 (x j))) => {?hidden_proof}
    }

\class Dec \extends AddGroup.Dec, With# {
      | #0-*-left => \lam {x} {y} x*y#0 => (\case decideEq x zro \with {
        | yes x=0 => absurd (#0-zro (transport #0 (pmap (* y) x=0 *> zro_*-left) x*y#0))
        | no x/=0 => nonZeroApart x/=0
      })
      | #0-*-right => \lam {x} {y} x*y#0 => (\case decideEq y zro \with {
        | yes y=0 => absurd (#0-zro (transport #0 (pmap (x *) y=0 *> zro_*-right) x*y#0))
        | no y/=0 => nonZeroApart y/=0
      })
    }
  }


\class NonZeroRing \extends Ring, NonZeroSemiring

\class PseudoCRing \extends PseudoRing, PseudoCSemiring

\class CRing \extends Ring, PseudoCRing, CSemiring {
  \func IsBezout  => \Pi (a b : E) -> ∃ (s t : E) (LDiv (s * a + t * b) a) (LDiv (s * a + t * b) b)

  \func IsStrictBezout  => \Pi (a b : E) -> ∃ (s t u v : E) (a * u = b * v) (s * u + t * v = 1)

  \lemma bezout_finitelyGenerated_principal : IsBezout <-> (\Pi {I : Ideal \this} -> I.IsFinitelyGenerated -> I.IsPrincipal) => {?hidden_proof}

  \func bezoutGCD {a b s t : E} (p : LDiv (s * a + t * b) a) (q : LDiv (s * a + t * b) b) : GCD a b (s * a + t * b) \cowith
    | res|val1 => p
    | res|val2 => q
    | res-univ => \lam g (g|x : LDiv g a) (g|y : LDiv g b) => \new LDiv {
      | inv => s * g|x.inv + t * g|y.inv
      | inv-right => qed
      (g * (s * g|x.inv + t * g|y.inv) ==< ldistr >== g * (s * g|x.inv) + g * (t * g|y.inv) ==< inv (pmap2 + *-assoc *-assoc) >== (g * s) * g|x.inv + (g * t) * 
        g|y.inv ==< pmap2 (__ * g|x.inv + __ * g|y.inv) *-comm *-comm >== (s * g) * g|x.inv + (t * g) * g|y.inv ==< pmap2 + *-assoc *-assoc >== s * 
        (g * g|x.inv) + t * (g * g|y.inv) ==< pmap2 (s * __ + t * __) g|x.inv-right g|y.inv-right >== s * a + t * b)
    }

  \type Dim<= (k : Nat) => \Pi (x : Array E (suc k)) -> ∃ (a : Array E (suc k)) (m : Array Nat (suc k)) (fold x a m = 0)
    \where {
      \func fold {k : Nat} (xs as : Array E k) (ms : Array Nat k) : E \elim k, xs, as, ms
        | 0, nil, nil, nil => 1
        | suc k, x :: xs, a :: as, m :: ms => pow x m * (fold xs as ms - x * a)
    }


  \type IsZeroDimensional  => \Pi (a : E) -> ∃ (b : E) (n : Nat) (pow a n = pow a (suc n) * b)

  \lemma finite-zeroDimensional (c : FinSet E) : IsZeroDimensional => {?hidden_proof}
}
  \where {
    \open Monoid (LDiv, Inv)

\class With# \extends CRing, Ring.With# {
      | #0-*-right => \lam x*y#0 => #0-*-left (transport #0 *-comm x*y#0)
    }

\class Dec \extends Ring.Dec, With# {
      \lemma divQuotient_dec0 (a : DivQuotient \this) : Set.Dec (a = in~ 0) => {?hidden_proof}
    }
  }


\class NonZeroCRing \extends CRing, NonZeroRing